### ISSUE TITLE
Transmisje na żywo ze sport.tvp

### ISSUE THREAD

**Issue by Kamil-H** [ramicspa/kodi#10]
Niestety, ale mam problem z odtwarzaniem transmisji na żywo z serwisu sport.tvp.pl. We wtyczce wyświetla się poprawnie cała lista streamów i pokrywa się ona z tymi na stronie, ale niestety nie da się ich uruchomić.
Zamieszczam log z pliku kodi.log:

> 18:20:21 T:8904  NOTICE: DVDPlayer: Opening:
18:20:21 T:8904 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:20:21 T:5552  NOTICE: Creating InputStream
18:20:21 T:5552   ERROR: CDVDPlayer::OpenInputStream - error opening []
18:20:21 T:5552  NOTICE: CDVDPlayer::OnExit()
18:20:21 T:8904   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.LivePolishTV/?ex_link=&mode=play_sporttvp&foldername=17%3A50%3A+%5BCOLOR+blue%5DPi%C5%82ka+no%C5%BCna+%28M%29%3A+Grupa+A%3A+Irak+%E2%80%93+Dania+%28bez+komentarza%29%5B%2FCOLOR%5D]
18:20:21 T:8904  NOTICE: CDVDPlayer::CloseFile()
18:20:21 T:8904  NOTICE: DVDPlayer: waiting for threads to exit
18:20:21 T:8904  NOTICE: DVDPlayer: finished waiting
18:20:21 T:8904  NOTICE: CDVDPlayer::CloseFile()
18:20:21 T:8904  NOTICE: DVDPlayer: waiting for threads to exit
18:20:21 T:8904  NOTICE: DVDPlayer: finished waiting

W związku ze zbliżającymi się Igrzyskami w Rio, fajnie byłoby gdyby działały streamy na żywo ;)

**Comment by ramicspa** [comment]
Dzieki za info, naprawione, zrób update.

**Comment by Kamil-H** [comment]
Wow, naprawdę szybka reakcja! Dziękuję za update.

**Comment by DamianKurek** [comment]
Podobny problem

`14:13:15 719.617126 T:1786770496  NOTICE: -->Python Interpreter Initialized<--
14:13:22 726.508301 T:1786770496  NOTICE: play_sporttvp
14:13:40 744.107910 T:1967026176  NOTICE: DVDPlayer: Opening:
14:13:40 744.108276 T:1967026176 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:13:40 744.120239 T:1495262272  NOTICE: Thread DVDPlayer start, auto delete: false
14:13:40 744.121155 T:1495262272  NOTICE: Creating InputStream
14:13:40 744.144287 T:1495262272   ERROR: Error on dvdnav_open
14:13:40 744.144714 T:1495262272   ERROR: CDVDPlayer::OpenInputStream - error opening []
14:13:40 744.145081 T:1495262272  NOTICE: CDVDPlayer::OnExit()
14:13:40 744.147156 T:1967026176   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.LivePolishTV/?ex_link=&mode=play_sporttvp&foldername=13%3A25%3A+%5BCOLOR+blue%5DWio%C5%9Blarstwo%3A+M+i+K%5B%2FCOLOR%5D]
14:13:40 744.148682 T:1967026176  NOTICE: CDVDPlayer::CloseFile()
14:13:40 744.149048 T:1967026176  NOTICE: DVDPlayer: waiting for threads to exit
14:13:40 744.151306 T:1967026176  NOTICE: DVDPlayer: finished waiting
14:13:40 744.151855 T:1967026176  NOTICE: CDVDPlayer::CloseFile()
14:13:40 744.152161 T:1967026176  NOTICE: DVDPlayer: waiting for threads to exit
14:13:40 744.152405 T:1967026176  NOTICE: DVDPlayer: finished waiting
14:13:40 744.349243 T:1956639808  NOTICE: Found 1 Lists of Devices
14:13:40 744.349854 T:1956639808  NOTICE: Enumerated PI devices:
14:13:40 744.356934 T:1956639808  NOTICE:     Device 1
14:13:40 744.357605 T:1956639808  NOTICE:         m_deviceName      : HDMI
14:13:40 744.358032 T:1956639808  NOTICE:         m_displayName     : HDMI
14:13:40 744.358276 T:1956639808  NOTICE:         m_displayNameExtra:
14:13:40 744.358582 T:1956639808  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
14:13:40 744.358826 T:1956639808  NOTICE:         m_channels        : FL,FR
14:13:40 744.359131 T:1956639808  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
14:13:40 744.359436 T:1956639808  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
14:13:40 744.359741 T:1956639808  NOTICE:     Device 2
14:13:40 744.366699 T:1956639808  NOTICE:         m_deviceName      : Analogue
14:13:40 744.367065 T:1956639808  NOTICE:         m_displayName     : Analogue
14:13:40 744.367310 T:1956639808  NOTICE:         m_displayNameExtra:
14:13:40 744.367676 T:1956639808  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:13:40 744.367981 T:1956639808  NOTICE:         m_channels        : FL,FR
14:13:40 744.368225 T:1956639808  NOTICE:         m_sampleRates     : 48000
14:13:40 744.368530 T:1956639808  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
14:13:40 744.368774 T:1956639808  NOTICE:     Device 3
14:13:40 744.369202 T:1956639808  NOTICE:         m_deviceName      : Both
14:13:40 744.369446 T:1956639808  NOTICE:         m_displayName     : HDMI and Analogue
14:13:40 744.369751 T:1956639808  NOTICE:         m_displayNameExtra:
14:13:40 744.376892 T:1956639808  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:13:40 744.377258 T:1956639808  NOTICE:         m_channels        : FL,FR
14:13:40 744.377502 T:1956639808  NOTICE:         m_sampleRates     : 48000
14:13:40 744.377808 T:1956639808  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
14:13:46 749.913635 T:1522529344  NOTICE: Thread BackgroundLoader start, auto delete: false
`

**Comment by ramicspa** [comment]
Hej
Powinno dzialac. Zrob update wtyczki. Ostatnia wersja to 1.7.10
Pozdrawiam

**Comment by noirrak** [comment]
@ramicspa 
Z tego co widzę, to na http://sport.tvp.pl/rio jest większa lista kanałów live. Da się to naprawić? :)

btw. Dobra robota, świetna wtyczka!

**Comment by ramicspa** [comment]
Faktycznie nie wszystkie sa nadawana bezposrednio na sport.tvp. Transmisje oraz video dodałem do wtyczki tvp.pl

**Comment by noirrak** [comment]
@ramicspa, coś nie mogę znaleźć. Po przejściu do "TVP.pl" co dalej? :)

**Comment by ramicspa** [comment]
W repo sa zawsze aktualizacje ... trzeba w kodim tylko wymusic reczne odswiezenie repozytoriow. Domyslnie robi to raz na dobe.
LivePolishTv addon tez dostalo update dla rio ma wiecej streamow live niz dostepne sa na stronie sport.tvp.pl/rio

**Comment by noirrak** [comment]
Robiłem force, ale nie znajdowało nic nowego.

Jeszcze raz dzieki!

**Comment by noirrak** [comment]
@ramicspa, jakiś kontakt do ciebie? - mail by wystarczył ;)

**Comment by ramicspa** [comment]
jak jest jakis problem z wtyczka lepiej zostaw wiadomosc na githubie a reszte na maila ramicspa at gmail dot com
