### ISSUE TITLE
audycje tok fm

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#100]
Tym razem propozycja do zrobienia wtyczki z audycji ze strony http://audycje.tokfm.pl/. 
Byłoby coś z tego?

**Comment by xxcriticxx** [comment]
@ramicspa pora na radio plugin

**Comment by noirrak** [comment]
Jakiś czas temu zablokowali możliwość słuchania podcastów (za free). No chyba, że się uda wyciągnąć ze strony.

**Comment by rafciu27** [comment]
Niektóre są za free jak np sport, ale faktycznie dużo materiałów należy do płatnej strefy premium. Ok do zamknięcia.
