### ISSUE TITLE
Problem z większością serwisów (cda,alltube) na tv z androidem

### ISSUE THREAD

**Issue by karolpoz817** [ramicspa/kodi#102]
Witam. Mam problem z wtyczkami wideo takimi jak np. cda, gdy probuje włączyć to wyświetla się komunikat "dodatek jest niekompatybilny lub oznaczony jako uszkodzony w repozytorium. Niespełnione zależnosci. Proszę skontaktować sie z autorem. Posiadam telewizor z systemem android 5.1.1, mogłby mi ktoś z tym pomóc? Dzięki wielkie z góry. :) a tutaj screen: https://zapodaj.net/fe3cc7470f078.jpg.html

**Comment by ramicspa** [comment]
witam, wyglada na to ze nie masz zainstalowanego pluginu: "script.common.plugin.cache", ktory normalnie wystepuje standardowo.
zeby sprawdzic czy jest wejdz w: dodatki->moje dodatki->serwise (czy jakos tak)
mozna go pobrac np z http://mirrors.kodi.tv/addons/jarvis/script.common.plugin.cache/

**Comment by adaski8** [comment]
Kodi 16 ma kolega . Na 5.1 andka niech kolega zainstaluje 17 kodiego

**Comment by karolpoz817** [comment]
okej, pomogło zainstalowanie tego pluginu. Dzięki wielkie! :)
