### ISSUE TITLE
efilmy - błąd przy wyszukiwaniu

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#103]
Jak w temacie:
`10:46:21 T:140506482857728  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23
10:46:23 T:140506482857728  NOTICE: Previous line repeats 1 times.
10:46:23 T:140506482857728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/home/tomasz/.kodi/addons/plugin.video.efilmy/main.py", line 302, in <module>
                                                ListSearch(ex_link)
                                              File "/home/tomasz/.kodi/addons/plugin.video.efilmy/main.py", line 154, in ListSearch
                                                filmy,seriale = ef.search(ex_link)
                                              File "/home/tomasz/.kodi/addons/plugin.video.efilmy/resources/lib/efilmy.py", line 211, in search
                                                for s in suggestions:
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
10:46:23 T:140507936945920  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
10:46:23 T:140508345913728   ERROR: GetDirectory - Error getting plugin://plugin.video.efilmy/?ex_link=teoria%2bwielkiego%2bpodrywu&foldername=teoria%20wielkiego%20podrywu&mode=ListSearch&page=0
10:46:23 T:140508345913728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.efilmy/?ex_link=teoria%2bwielkiego%2bpodrywu&foldername=teoria%20wielkiego%20podrywu&mode=ListSearch&page=0) failed
10:46:24 T:140506482857728  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23`

Drugi problem to wersje językowe. Wybieram serial Teoria Wielkiego podrywu
Na stronie w sezonie 10 epizodzie 5 (http://www.efilmy.tv/serial,495,Teoria-wielkiego-podrywu-The-Big-Bang-Theory-2007-2011,sezon-10,odcinek-5.html) mam wersję z dubbingiem jak i wersję z napisami. We wtyczce zaś mam tylko z napisami, nie ma możliwości wyboru wersji językowej.

**Comment by ramicspa** [comment]
sporo sie pozmieniali na stronie ... trzeba znaczaco wtyczke przerobic.
niebawem bede mial wiecej czasu to sie pojawia aktualizacje ...

**Comment by tomasiek** [comment]
Ok. W takim razie czekamy...

**Comment by ramicspa** [comment]
info na temat wersji jezykowej powinno sie pojawic obok hostu.
blad przy szukaniu usuniety
wersja 1.9
