### ISSUE TITLE
download

### ISSUE THREAD

**Issue by soprano800** [ramicspa/kodi#107]
Czy jest możliwe dodanie do jakiejś wtyczki np alltube możliwości ściągania zawartości aby można ją było obejrzeć offline jak to ma miejsce np we wtyczce exodus.

**Comment by ramicspa** [comment]
jest mozliwe.

**Comment by soprano800** [comment]
a czy jest jakaś szansa na aktualizacje w powyższej kwestii w najbliższym czasie?

**Comment by ramicspa** [comment]
tak, niebawem bede robil update wytczki i postaram sie wrzucic taka opcje ... do alltube ?

**Comment by soprano800** [comment]
z racji tego że najczęściej właśnie z niej korzystam, ale myślę że taka opcja mogła by trafić również do innych wtyczek. ostatnio cinemaHD się pojawiła i tam taka opcja też by mogła być dodana. oczywiście nie wszystko na raz tylko w miarę twoich update'ów. 

ps. odwalasz kawał dobrej roboty z tymi wtyczkami. z początku używałem innego polskiego repo, ale wtyczka która tam była bardzo często nie działała, ale odkąd znalazłem twoje repo to jestem jego fanem

**Comment by soprano800** [comment]
próbuje testować tą funkcję download zaimplementowaną do alltube ale chyba jednak nie działa. przy źródłach takich openload czy vidto wyskakuje błąd "problem. może inny link będzie działał? utrresolver error: file not found." a przy cda da się nawet wybrać rozdzielczość a potem wyskakuje małe okienko "preparing download" i nic się nie dzieje. katalog docelowy w ustawieniach mam dodany więc nie wiem o co może chodzić.

**Comment by ramicspa** [comment]
nie kazdy host pozwala na download. poza tym idea wtyczek jest streaming. sa inne i duzo lepsze metody na pobieranie materialow z sieci.

**Comment by tomasiek** [comment]
dla cda polecam skryptozakładkę (działa na cda.pl, na zalukaj, na freedisc,, tvp.pl, vod.pl, vshare.io) - wyświetla linka do pobrania, czasem (w przypadku zalukaj) wymaga 2 kliknięć.
http://pastebin.com/GnsndVTS

**Comment by Janasek** [comment]
przeglądarka sama wypluwa linki bez skryptu

Narzędzia dla programistów/
zakładka network
klikasz f5 i wszystko jak na tacy,ale dzięki za skrypt.....
