### ISSUE TITLE
LivePolishTV - tworzenie listy m3u z wizja.tv + mały problem z przewodnikiem PART2

### ISSUE THREAD

**Issue by ddavidek256** [ramicspa/kodi#108]
Koledzy czy jest w tej chwili możliwość tworzenia listy m3u z yoy.tv posiadając bądź nie konto premium.  Czy jest szansa na modyfikacje wtyczki livepolish tv aby obsługiwała inne serwisy.  Potrzebuje zrobić sobie listę pod ss iptv w TV. DZIĘKI za pomoc. 
Sorki jeśli nie ten dział ale w tamtym nikt nie odpowiada wiec pewnie nie czytają.

**Comment by ramicspa** [comment]
hej, jesli mozesz wejsc na strone yoy i uruchomic jakis strumien to i wtyczka bedzie w stanie to zrobic - lacznie z utworzeniem list m3u - jesli nie to nie. 
Mozna dodac nowe serwisy do wtyczki, jak znasz cos ciekawego to podaj linka.

**Comment by ebot2007** [comment]
http://www.typertv.com.pl/ :)

**Comment by ebot2007** [comment]
tutaj jeszcze cos ze sportu dalo by sie wyciagnac http://livelooker.com/pl/ 
dzieki.

**Comment by ebot2007** [comment]
Witam 
Tv-online.fm nie dziala jak trzeba , strona natomiast ok
dzieki

**Comment by kashkash18** [comment]
Po aktualizacji wtyczki , sporo serwisów wywala błąd na Androidzie

**Comment by ramicspa** [comment]
ciagle jakies problemy z androidem ... ehhh ...

**Comment by tomasiek** [comment]
No niestety - Android jako okrojony linux na pewno nie jest super środowiskiem. Ale jest b. powszechny a należy też zauważyć że tvboxy od naszych przyjaciół z chin mają cenę ~ 100 zł więc są coraz bardziej popularne...

**Comment by ebot2007** [comment]
Na andku LivePolishTV  jest offline ??
pozdro

**Comment by ebot2007** [comment]
witam ,tele-wizja niedziala choc stronka tak.

**Comment by ebot2007** [comment]
Witam ponownie looknij in tez padlo .

**Comment by ramicspa** [comment]
hej, dzieki za info, dzis lub jutro bedzie update co naprawi problemy.

**Comment by ebot2007** [comment]
Dziala :) dziekowac

**Comment by ramicspa** [comment]
hehe ... a dlaczego mialoby nie dzialac? - jak stronka dziala.
psa-tv i polon - padly - blogspot zamknal ich stronki - wywale je z listy przy nastepnej aktualizacji

**Comment by ebot2007** [comment]
lecz z tego co widze tylko na 17 , 16.1 nie odpala :) dzieki

**Comment by Algirion** [comment]
Dalej jest błąd i listy nie można zrobić. Kiedyś działało. Chyba wtyczka padła już bo więcej nie działa niż działa :(

**Comment by ExXxtr3me** [comment]
Is there some wy to create a m3u list from yoy.tv if you have a premium account? Can´t find an option put in my username and password for yoy.
