### ISSUE TITLE
cda.pl brak podziału na katalogi

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#109]
Witam! Wyglada ze po ostatniej aktualizacji cda.pl zniknął cały podział na katalogi: 2016, 2015, starsze itp.

Teraz jak otwieram cda.pl wchodzę w "Root" ( w którym prędzej był podział na katalogi,który dodam ze był super i na bierząco aktualizowany) pokałuje sie tylko o to taka zakładka: Aktualizacja. 

Wiadomo co sie stało?

Pozdrawiam

**Comment by krriss** [comment]
Aktualnie pokazuje w "Root" - Aktualizacja bazy danych...

Czyli domyślam sie ze coś działacie? 

Pozdrawiam

**Comment by ramicspa** [comment]
baza naprawiona ... aktualizacja dostepna wtyczki dostepna w repo

**Comment by krriss** [comment]
Poszło, super dzięki! :)

Pozdrawiam
