### ISSUE TITLE
Repository.ramic

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#11]
Coś jest nie tak z tą wtyczką , np: cda.pl , kiedy ją zainstaluje w kodi i nie wpiszę swoich danych do mojego CDA , wszystko sie odtwarza ok , lecz jak wpiszę login i hasło to już niczego nie mogę obejrzeć , ani u siebie swoich filmów ani tych ogólno dostępnych które przed zalogowaniem normalnie się odtwarzały , bardzo proszę o jakieś sugestie jak rozwiązać ten problem

**Comment by ramicspa** [comment]
Hej dzieki za info, sprawdze ten problem ale nie spotkalem sie  znim na androidzie/linux/win. Czy po logowaniu pojawia sie 'Moje cda.pl' ?
Przeslij moze log z kodi na http://pastebin.com/

**Comment by Seico** [comment]
Wszystko się pojawia , filmy na moim koncie sie pojawiają ale nic nie może się odtworzyć , ani ma moim koncie ani w ogólnodostępnych , sprawdzałem na windzie i na androidzie i jest to samo wszędzie jak się nie zaloguje to wszystko śmiga ok a jak tylko wpisze dane do logowania to już nic nie moge odtworzyć

Jakiś mały tutorial jak wyciągnąć log z kodi , nigdy tego nie robiłem i dlatego nie wiem jak to zrobić , może ta prośba troche śmieszyć ale tak jest

**Comment by ramicspa** [comment]
na windows C:\Users\<user>\AppData\Roaming\Kodi\kodi.log

**Comment by Seico** [comment]
Proszę bardzo :http://pastebin.com/fmmWacR2

Otwierałem film "Atak na posterunek"

**Comment by ramicspa** [comment]
Nie udało mi się powtórzyć tego problemu u siebie wiec może masz problem z kontem - jak się zalogujesz przez strone to wszystko sie odtwarza? Zrobiłem modyfikacje wtyczki (wersja 1.7.4) która powinna ci pomóc. Jeśli nie to prześlij log ponwnie: gdy odtwarza i nie.

**Comment by Seico** [comment]
Jest wszystko na razie ok , dzięki bardzo , mam jeszcze pytanko , czy dałbyś radę jeszcze stworzyć wtyczkę i dodac do repo z tej stronki : http://segos.es

**Comment by xxcriticxx** [comment]
nowe serwisy seansik.nl i kinex.tv (clone alltube.tv)

**Comment by ramicspa** [comment]
Ok fajnize ze dziala.
Dzieki za linki - na pewno da sie cos znich zrobic :)

**Comment by Seico** [comment]
Fajnie żeby wypaliło z tymi linkami moimi i xxcriticxx bo posiadam dość pokaźną kolekcje filmów i może jak to zrobisz ujrzą światło dzienne :)

**Comment by ramicspa** [comment]
segos.es to fajna stronka z dobra jakosca video i audio. wrzucilem wtyczke do repo - przetestujcie.

**Comment by Seico** [comment]
Po testach zauważyłem ze pojawia się z danego tytułu film który jest pierwszy w kolejce a są pozycje z kilkoma linkami , czy dało by radę zrobić aby był wybór linku , gdyż są linki z lepsza jakością (np. audio) pod tym samym filmem

**Comment by ramicspa** [comment]
Faktycznie, zdarzaja sie filmy z wieloma linkami. naprawione (wersja 1.1)

**Comment by Seico** [comment]
No i tu już jest problem
Przy wyborze linku z http://greevid.com lub cda.pl film się już nie odpala.Film który odpalałem to "33" , inne też nie startują
Tu masz log : http://pastebin.com/fmmWacR2
Jak już to naprawisz to fajnie by było aby oprócz jakości audio przy linku mogłaby się pokazać jakość wideo

**Comment by ramicspa** [comment]
ano byl maly problem z greevid ... w ogole nie powinien sie tam pojawic. juz naprawione. co do innych szczegolnie cda to trzeba (teraz) sprobowac ponownie uruchomic video - serwery sa przeiciazone i jak slaby jest ping to wyrzuca.

**Comment by xxcriticxx** [comment]
cda should die!

**Comment by Seico** [comment]
ok teraz jest ok :) dodasz jeszcze tą jakość wideo obok audio ? :)

**Comment by xxcriticxx** [comment]
ja widze tylko ver 1.0. gdzie jest 1.1?

**Comment by Seico** [comment]
xxcriticxx ręcznie zaktualizuj repo

**Comment by xxcriticxx** [comment]
ok mam 1.2 thx

**Comment by xxcriticxx** [comment]
33 z openload mi sie nie otwiera

**Comment by Seico** [comment]
U mnie jest ok , może zrestartuj kodi :)

**Comment by xxcriticxx** [comment]
uzywajac search no go

![capture](https://cloud.githubusercontent.com/assets/15007183/17652110/7e33a094-6242-11e6-9a7b-f8f12749279e.PNG)

**Comment by xxcriticxx** [comment]
savages jest pokazane 720p naciskasz wyskakuje tylko 480p. na stronie jest tylko jeden link do cda

**Comment by Seico** [comment]
no to na cda.pl jest normalne sam mam tak u siebie na cda.pl , pokazuje że film ma 1080p a jak wchodzę w tą rozdzielczość to wyskakuje że nie może znaleść wideo błąd "404"

**Comment by Seico** [comment]
Twój dostawca netu lub zapora ci nie blokuje strony  openload.co ? bo u mnie wszystko śmiga jak ta lala :)

**Comment by Seico** [comment]
**xxcriticxx** mam ten film "savages' ale nie odrazu mogę całą swoją kolekcje tam wrzucić , trzeba trochę poczekać , ale napewno się pojawi :)

**Comment by xxcriticxx** [comment]
@Seico oglondalem tylko jak testowalem to go wybralem

**Comment by xxcriticxx** [comment]
@Seico 33 ze strony mi dziala bez problemu ale w kodi no go

**Comment by Seico** [comment]
**@xxcriticxx** to ja nie wiem , tak ja pisałem u mnie śmiga bez problemu , może coś w kodi masz uwalone - może urlresolver ? a sprawdź czy link skopiowany ze strony pójdzie ci w kodi

**Comment by xxcriticxx** [comment]
@Seico jak?

**Comment by Seico** [comment]
Zainstaluj w Kodi url tester PRO lub albo i Url tester Tool

**Comment by xxcriticxx** [comment]
@Seico dziekuje za pomoc do nastepnego razu

**Comment by Seico** [comment]
**ramicspa** jest szansa że dodasz jeszcze tą jakość wideo obok audio ? :)

**Comment by xxcriticxx** [comment]
a dzisaj 33 z openload dziala bez problemu!

**Comment by ramicspa** [comment]
@Seico 
jakosc video pojawi sie przy nastepnym update. 
kolejna wytczka bedzie do iwatchonline

**Comment by xxcriticxx** [comment]
News: Iwatchonline alternative domain www.Iwatchonline.lol

**Comment by ramicspa** [comment]
wtyczka do Iwatchonline wrzucona do repo

**Comment by Seico** [comment]
Extra , jesteś wielki :) dzięki bardzo, będziemy testować , tak na szybko sprawdziłemi film z PL ruszył ok , a czy jest też możliwość aby dodać funkcje wpisywania tytułu po polsku aby znajdował film z angielskim odpowiednikiem ?
Miało być też update segos :)?

**Comment by xxcriticxx** [comment]
@ramicspa thx za plugin

@Seico teraz uploaduj chlopak
