### ISSUE TITLE
Live iptv

### ISSUE THREAD

**Issue by jzbond65** [ramicspa/kodi#110]
Hej Czy mozesz dodac funkcje save do  twojego addona bo szybko giną te m3u za 2 dni ipsatpro juz nie było wiem ze linki mają krótka żywotność
Ale jak się już coś znajdzie to szkoda ze znika więc please dodaj opcję save jak można pozdrowienia ze Szwecji i dzięki za dobrą robotę JZ

**Comment by ramicspa** [comment]
dobry pomysl, niebawem bedzie update wtyczki

**Comment by ramicspa** [comment]
opcja dostepna z menu contekstowego

**Comment by Cinek77** [comment]
Witam. Tv Online w LivePolishTv przestala dzialac.

**Comment by jzbond65** [comment]
Hej Wszysto śmiga ok na iptvsatlinks tylko na drugej liście iptvlinkss nieda sie savnąc😪
Jak jeszcze o coś można prosić to live ip check zebe sprawdzić 3 piersze na liście czy linki żyją😊
No i może jakiś internal search *.pl 
Jeszcze raz wiekie dzieki Jz

**Comment by ramicspa** [comment]
obydwie sie zapisuja ... z druga trzeba poprawic nazwe pliku (nie moze chyba byc '[' ']'). 
przy nastepnym poprawie generowanie nazwy zgodnej z std plikow.
3 linki mozna sprawdzic ... tylko kiedy - przed zapisem?? 
search jest (nazywa sie filt i jest wbudowany w kodi - dostepny z panelu bocznego)

**Comment by jzbond65** [comment]
Hej
Chcę tylko ping -nąc listę czy coś żyje dzisiaj było
Kilka pustych nieraz 3 pierwsze mogą być nieaktualne więc może random ping?
