### ISSUE TITLE
bajki - nie odtwarza

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#111]
Odtwarzanie bajek nie działa...
Dowolna ze stron z pluginu bajki -> spis alfabetyczny -> (przykładowo) Agent Specjalny Oso

`16:57:08 T:18446744072324363752   ERROR: Error loading addon settings to special://profile/addon_data/script.module.urlresolver/settings.xml
16:57:09 T:18446744072324363752   ERROR: Previous line repeats 1 times.
16:57:09 T:18446744072324363752  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23
16:57:11 T:18446744072288055312  NOTICE: DVDPlayer: Opening:
16:57:11 T:18446744072288055312 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:57:11 T:18446744072293346568  NOTICE: Creating InputStream
16:57:11 T:18446744072293346568   ERROR: virtual bool XFILE::CFileCache::Open(const CURL&) - failed to open source <>
16:57:11 T:18446744072293346568   ERROR: CDVDPlayer::OpenInputStream - error opening []
16:57:11 T:18446744072293346568  NOTICE: CDVDPlayer::OnExit()
16:57:11 T:18446744072288055312   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=Z%C5%82ote+Wi%C3%B3rko&page=1&ex_link=http%3A%2F%2Fbajkipopolsku.com%2Fzlote-wiorko&mode=getLinks]
16:57:11 T:18446744072288055312  NOTICE: CDVDPlayer::CloseFile()
16:57:11 T:18446744072288055312  NOTICE: DVDPlayer: waiting for threads to exit
16:57:11 T:18446744072288055312  NOTICE: DVDPlayer: finished waiting
16:57:11 T:18446744072288055312  NOTICE: CDVDPlayer::CloseFile()
16:57:11 T:18446744072288055312  NOTICE: DVDPlayer: waiting for threads to exit
16:57:11 T:18446744072288055312  NOTICE: DVDPlayer: finished waiting
`
Kilka dni temu działało (nie pamiętam dokładnie kiedy)

**Comment by ramicspa** [comment]
pewnie cos zmienili na stronie ... bedzie update pewnie jutro

**Comment by tomasiek** [comment]
Się lekko przypomnę... dzieciaki męczą...

**Comment by ramicspa** [comment]
to nie problem z wtyczka ale urlresolverem - nie oblsuguje hosta.

**Comment by tomasiek** [comment]
Cóż... Dailymotion w 100% wypełnia moje potrzeby co do bajek - a bardziej moich dzieci.
