### ISSUE TITLE
Ekstraklasa

### ISSUE THREAD

**Issue by hekelezeme** [ramicspa/kodi#112]
Witam, na windowsie z kodi 16.1 po wejściu we wtyczkę ekstraklasa w sekcji live mam pusto, jaka może być przyczyna ?

**Comment by ramicspa** [comment]
wejdz w opcje wtyczki i zaznacz proxy powinno pomoc

**Comment by rafciu27** [comment]
A tak przy okazji LechTV coś szwankuje. U mnie na każdej platformie filmy nie działają.

**Comment by ramicspa** [comment]
wtyczka wymaga aktualizacji .... pojawi sie niebawem ...

**Comment by ramicspa** [comment]
sprawdzalem lechTV i nie widze problemu ... moze jakies wyjasnienie w czym jest problem?

**Comment by rafciu27** [comment]
U mnie na każdej platformie w zakładce nowe, włącza się może co 5 film. Reszta to nieudane odtwarzanie.
