### ISSUE TITLE
efilmy.tv

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#115]
poprawka potrzebna

**Comment by ramicspa** [comment]
chyba jakis problem jest z serwisem bo przez strone nic nie leci

**Comment by xxcriticxx** [comment]
wymagaja rejestracji

Rejestracja jest całkowicie darmowa i zajmuje tylko kilka sekund.

**Comment by xxcriticxx** [comment]
@ramicspa strona dziala jest tylko 15 sec timer potem play i wszystko dziala na stronie bez rejestracji

**Comment by ramicspa** [comment]
ok, resolver dla streaminto padl - dlatego nie gralo, trzeba napisac od zera.

**Comment by ramicspa** [comment]
poszedl update, powinno wszystko dzialac

**Comment by xxcriticxx** [comment]
@ramicspa zrobilem update do 1.10 ale dalej mam subkategorie puste

**Comment by ramicspa** [comment]
hmm, trzeba wiec precyzowac w czym jest problem bo do kategori filmow nawet nie zagladalem.
'poprawka potrzebna' to troche malo

**Comment by xxcriticxx** [comment]
@ramicspa nastepnym razem napisze wiecej

**Comment by ramicspa** [comment]
patrzylem na wtyczke czy cos jest nie tak i nic nie znalazlem
filmy w kategoriach sie pojawiaja, streamy odgrywane sa jak trzeba
Jak nie ma problemu zamknijmy temat
