### ISSUE TITLE
alltube - nie działa

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#117]
Jak w temacie:
http://pastebin.com/3162bXH5
Nie działa na:
android 5.1 spmc 16.5.2, na kodi 17 beta 6 (czysta instalacja)
linux (arch x64) kodi 16.1 (czysta instalacja - pierwsze zainstalowanie wtyczki)
(ostatnio w ogóle coraz częściej błędy przy otwieraniu wtyczek - na moje oko coś z "kodowaniem")

**Comment by ramicspa** [comment]
tak z alltubem jest problem, nie zawsze testuje na wszystkich platformach - a nie zawsze ten sam kod dziala. Zaraz bedzie update

**Comment by gosiaiunia1** [comment]
Po aktualizacji padlo calkowicie. Nie otwiera sie. Ani na KODI iSPMC to samo

**Comment by ramicspa** [comment]
moze doprecyzuj co znaczy "padlo calkowicie" oraz "nie otwiera sie" - czy wtyczka pokazuje blad? jesli tak -warto zalczyc, jaka wersja kodi? - podac numer, platforma?
testowalem alltuba na wszystkich platformach z  16.1 i nie znalazlem problemu.

**Comment by gosiaiunia1** [comment]
Nie kompatybilne z kodi

**Comment by ramicspa** [comment]
na stronie glownej repo jest informacja - warto sie z nia zapoznac.

**Comment by gosiaiunia1** [comment]
Czyli mamy rozumiec ze dla zabawy alltube nie jest kompatybilne z KODI. Szkoda fajny plugin byl

**Comment by gosiaiunia1** [comment]
Na czystym kodi 16.1 jest to samo. Nie kompatybilne

**Comment by tomasiek** [comment]
Hm.. czy jest sens "niekompatybilności" na innych niż domyślny skin? Przecież on jest kompletnie nieużywalny i ma mało opcji dostosowania.... Na tv boxie nie korzystam z wielu opcji menu i w mimic mam własne menu zrobione... Confluence wymaga za wiele chodzenia po menu żeby dojść do ulubionych rzeczy...

**Comment by VanWolf** [comment]
Zapytanie czy doczekamy sie aktualizacji wtyczki aby dzialala z innymi skorkami czy tak ma to juz zostac?
Prosze o odp.

**Comment by ramicspa** [comment]
bedzie aktualizacja i na innych skorkach tez bedzie dzialac ale nie wszystkich.

**Comment by VanWolf** [comment]
Dziekuje za odp, i trzymam kciuki.
