### ISSUE TITLE
Dailymotion Channels 

### ISSUE THREAD

**Issue by bubuleur** [ramicspa/kodi#119]
Hello
I come to you to give my contribution a addons Dailymotion that works very well I translated your addon in french if you made me sign
Otherwise I would like to know how to remove the popup that tells me to add default channels at the start of the addon
Thanking you

**Comment by ramicspa** [comment]
Hi, Your contribution with a french addon translation is very welcome. The easiest way would be to make a pull request or you can just send me a file: 'string.po' via email or pastebin.com
The pop-up window with default channels appears only when a channel list is empty so simply add at least one channel. Making this optional doesn't make a sense cause that's a main feature of this addon.

**Comment by bubuleur** [comment]
Hello, thanks for your reply I refine the translation and I'll send it
Just to find out how can you add channels by defects in the addon
Thank you for your information

**Comment by bubuleur** [comment]
Hello,
I refine my translation
How do you send it by email?
I use your repository and I would like to know how long the translation will be set up
cordially
Thank you

**Comment by ramicspa** [comment]
Hi, you can send via email. you can find it in addon.xml. I'll let you know when updated version is available on repository, quite soon I guess.

**Comment by bubuleur** [comment]
File sent to your email
Kind regards
Thank you

**Comment by ramicspa** [comment]
i have not got it yet. send it one more time to ramicspa@gmail.com

**Comment by bubuleur** [comment]
File sent
Thanks

**Comment by ramicspa** [comment]
got it. thx

**Comment by bubuleur** [comment]
Nothing however I have not change the date of translation in the strings file

**Comment by ramicspa** [comment]
no problem, the repo has been updated. check it out and let know if everything is ok.

**Comment by bubuleur** [comment]
Everything works it is good thanks for your speed if you ever another translation to do on this addon made me sign
Kind regards

**Comment by bubuleur** [comment]
Hello
Coming back to you for a translation error that I made on the file addon.xml
Need to replace the old two lines by
<summary lang="fr">Canaux utilisateur pour Dailymotion</summary>
<description lang="fr">Cette addon permet de parcourir le contenu des chaînes créées par les utilisateurs de Dailymotion.</description>
Thanking you
Sorry for this inconvenience

**Comment by bubuleur** [comment]
Up please thanks you

**Comment by bubuleur** [comment]
Hello
Coming back to you to see if you have made changes to the depot with the last translation I sent you on email
Thanking you

**Comment by ramicspa** [comment]
Looks like I forgot to make an upload with the latest translation. In a few days, a new version should be available

**Comment by bubuleur** [comment]
Ok thank you for your reply
Have a good day

**Comment by ramicspa** [comment]
updated version has been uploaded to repo.

**Comment by tomasiek** [comment]
Właśnie zacząłem się bawić ta wtyczką... I przyszło mi na myśl (dotyczy to nie tylko tego dodatku, ale taż innych) - czy jest możliwość żeby kolejny film na liście odtwarzał się automatycznie?
