### ISSUE TITLE
cda-online.pl

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#12]
poprawka jakas bendzie?

**Comment by ramicspa** [comment]
cos jest nie tak? ... zajrzyj do opcji pluginu

**Comment by xxcriticxx** [comment]
captcha hyba na main page

zaraz zajrze

**Comment by xxcriticxx** [comment]
aha proxy potrzebuje zeby ogladac

dziwne bo na stronie dziala bez proxy raczeaj mysle ze cos nie tak stym captcha z CloudFlare 

![capture](https://cloud.githubusercontent.com/assets/15007183/17681862/1d819bc8-6316-11e6-9ca2-467649faafb0.PNG)

**Comment by ramicspa** [comment]
jak sie laczysz z ip poza krajem to niestety tak sie dzieje - a proxy pomaga. jak juz wszystko ci smiga to zamykamy ten problem ...

**Comment by xxcriticxx** [comment]
tak jestem poza krajem. ale na stronie mi wszystko dziala bez proxy. musze tylko przejsc captcha. czyli w kodi tez powino smigac
