### ISSUE TITLE
cda.pl opcje widoku, autoview

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#121]
Jak zawsze moja ulubiona wtyczka i kolejna "uwaga"
W opcjach widoku dla cda.pl mamy ograniczenie którego nie mamy w innych twoich wtyczkach. Mamy możliwość wyboru tylko kilku podstawowych (miniatura-szeroki-lista-lista szeroka). Owszem - w opcjach wtyczki mamy "autoview"... ale to nie działa idealnie - na niektórych skórkach nie wszystkie opcje działają. W innych wtyczkach (filmy.to, cinemahd) nie ma tego typu ograniczenia - jest możliwość wybrania wielu opcji wyglądu. Pozwoliłoby to na "fajne" ujednolicenie wyglądu pomiędzy poszczególnymi twoimi dodatkami.

**Comment by tomasiek** [comment]
To podniosę ponownie temat. W innych wtyczkach nie ma tego ograniczenia, występuje ono chyba tylko w cda.pl. W Kodi 17 RC2 na wtyczce Mimic (a jakże...) zmiana autoview w ustawieniach dodatku nic nie powoduje...
Pojawiły się zaś parametry filmu (pisałem o tym tutaj: https://github.com/ramicspa/kodi/issues/92) - na kodi 17 rc2 (na andku) ze skórką mimic z githuba autora skórki. Pozostało więc tylko to jedno ustawienie widoku :)

**Comment by ramicspa** [comment]
za prare dni planuje update wiec zobacze co z tym autoview.
aktualnie znalazlem problem tez ze stronicowaniem filmow premium.
K17 ma automatyczne dopasywanie view do typu mediow (movie/tvshow/folder) - sprawdze jak tam to dziala.

**Comment by tomasiek** [comment]
O tym dopasowywaniu do typu w k17 to wiem. W cinemahd działa to prawidłowo,
po wejściu w filmy można wybrać dowolny układ. W cda jest to zablokowane.

12.01.2017 5:46 PM "ramicspa" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
Podniosę - mówiłes o najbliższych aktualizacjach wtyczek - może warto wywalić to ograniczenie?

**Comment by tomasiek** [comment]
Super. Dzięki....
