### ISSUE TITLE
Prośba o przystosowanie wtyczek do skina 

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#122]
Proszę o przystosowanie wtyczek do skina
Confluence - hwy 2016 fixed by husham

Skin do pobrania z http://repo.husham.com

Bardzo mi zależy na tym skinie ponieważ można wyciągnąć 25 skrótów do wideo, muzyki itp.

W standardowej skinie jest tylko 5 skrótów
Kodi 16.1 na tv box z androidem Kit Kat skin Confluence - hwy 2016 …

Wyskakuje takie  komunikat 
![screenshot_2016-12-22-00-01-02](https://cloud.githubusercontent.com/assets/20740632/21409449/9a774fbe-c7da-11e6-9ebf-2e03f8b0f09c.png)
![screenshot_2016-12-22-00-03-52](https://cloud.githubusercontent.com/assets/20740632/21409448/9a758d1e-c7da-11e6-80f0-bba101cdf864.png)

Ramic masz dużo wtyczek i standardowa skin ma za mało skrótów  aby obsłużyć twoje repo 

Dzięki za włożoną prace w repo i wtyczki

**Comment by marcintomanek** [comment]
Ramic, twoja wtyczka jest jedą z najlepszych wtyczek w polskim Kodi, ale twoja robota bedzie bez sensu, bo ludziom chodzi o łatwą konfigurację Kodi. Dzisiaj z Aoena przełaczyłem się na oryginalną skórę i pokazałem żonie, że tak to teraz będzie. Powiedziała mi, że mam jej nie tłumaczyć, bo to nie dla niejn no i wywaliłem teoje repo a szkoda bo robisz fajną robotę. Ramic będziesz robił coś dla nikogo....szkoda twojej pracy.

**Comment by marcintomanek** [comment]
Wszyscy jesteśmy Ci wdzięczni za wykonaną robotę, ale bez twojej wtyczki to już nie jest to Kodi jakim było. Szkoda, bo ja nigdy nie kupowałem wizarda od polskich "wizardzistów", a wylądowałem w jednym koszu z nimi. Pozdrawiam Ramic i daj znać co dalej, bo lepiej olać oryginalny skin i mieć dalej inne wtyczki, a szkoda twojej pracy.

**Comment by marcintomanek** [comment]
Im wcześniej przywrócisz twoje wtyczki do funkcjonalności tym lepiej dla twojej pracy. Ci którzy sprzedają wizardy, już napisali swoje wtyczki pod swoje płatne wizardy i za chwię twoja praca będzie całkowicie bez sensu, ale pomyśl o tych co nie chcą kupować wizardów. Zostali z reką w nocniku. Nikt nie używa oryginalnego skina, jak choć trochę poznał Kodi, będziesz robił pracę w powietrze.

**Comment by tomasiek** [comment]
Panowie. Temat został już omówiony tutaj
https://github.com/ramicspa/kodi/issues/118 , nie ma sensu kruszyć kopii.
Przy czym skórka o której jest mowa w.1 poście raczej do oficjalnych nie
należy, więc rozumiejąc tok postępowania ramicspa nie spodziewałbym się za
wiele....

22.12.2016 1:46 AM "marcintomanek" <notifications@github.com> napisał(a):

**Comment by kashkash18** [comment]
Nie mów że oryginalnego skina nikt nie używa. Używają a co za tym idzie nie mają problemów i nie płaczą tutaj. Wg mnie powinni tak zostać , bo nie ma nic gorszego jak kradzież ciężkiej pracy.

**Comment by tomasiek** [comment]
@kashkash18 tutaj https://github.com/ramicspa/kodi/issues/118 już o tym rozmawialiśmy. Oryginalny skin jest nieużywalny przy obsłudze na telewizorze z pilota. Są zaś OFICJALNE skórki które działają świetnie - jak np. aeon, mimic, mające dużo opcji dostosowania. Nie mają one nic wspólnego z "kradzieżą" - są oficjalnie dostępne przez repo kodi.

**Comment by kashkash18** [comment]
Na TV z Andkiem po zainstalowaniu Kodiego z Sklepu Play działa obsługa pilota na podstawowym skinie

**Comment by kashkash18** [comment]
No ja właśnie mam TV z Andkiem i używam podstawowego skina i też nie narzekam.

**Comment by tomasiek** [comment]
Działa. ale wygoda tego jest mocno dyskusyjna

22.12.2016 12:11 PM "kashkash18" <notifications@github.com> napisał(a):

**Comment by kashkash18** [comment]
Ale działa nie mam problemu z dodatkami Ramica

**Comment by Algirion** [comment]
Wtyczki działają na zwykłym ale bez przesady... nie chce mi się tego ustawiać samemu wszystkiego. Są wizardy i to setki ich dostępnych więc po cholerę ta blokada?
No chyba że sam Pan Ramic zaraz zrobi swojego Wizarda i może na tym to polega...?

**Comment by kashkash18** [comment]
Skoro Ci się nie chce to nie płacz , bo to tylko Twoje zwykłe lenistwo

**Comment by tomasiek** [comment]
A nawet jak zrobi własnego wizarda? Jakością pracy pokazał że robi dobre wtyczki... Więc i wizarda może być dobry... Chociaż ja tam wolę czyste kodi

**Comment by Algirion** [comment]
No może i moje lenistwo. Mam swoje kodi i ustawione pod siebie zrobione na Confluence ale jednak też chciałem wypróbować inne skórki czy wizardy i tu zonk.
Pewnie że tak, jestem leniwy i nie chce mi się siedzieć kilka dni by to ustawiać wszystko tak, jak jest w jakimś Wizardzie. Są setki przygotowanych wizardów po to by móc z nich korzystać i co w tym złego?
