### ISSUE TITLE
Nowy dodatek na Swieta!

### ISSUE THREAD

**Issue by ramicspa** [ramicspa/kodi#124]
Jakby ktos mial jakis problem z uruchomieniem jakies wtyczki, to 'kolega' zrobil kompilacje paru moich wtyczek. On sprzedaje ja w sowim buildzie oraz do innych buildow wiec na swieta taki maly prezent.

**Comment by tomasiek** [comment]
Nie no świetny _prezent_ . Wtyczka o wiele bardziej profesjonalna od twojej, lepszy podział - czytelny i w ogóle, na pewno o wiele szybciej będą poprawki i w ogóle lepiej. Jaja jak berety...

Na wszelki wypadek - tak to była ironia.
Dobry ruch - jak się nie da po dobroci to walić młotkiem... :)

ps. czy ja dobrze widzę że pojawia się _Kodi 17 required_ w changelog'ach?

**Comment by ramicspa** [comment]
Mi tez sie bardzo podoba, nigdy nie chcialo mi sie wrzucac wszystkiego w jedna wtyczke a tu patrz taki prezent na swieta. Mam nadzieje ze bedzie tez robil updaty. 

Tak, kodi17 jest juz za rogiem i dobrze bo coraz wiecej serwisow wymaga szyfrowanych polaczen ktorych K16 starsze nie obsluguja.

**Comment by lotos53** [comment]
A tak z ciekawości. Kto jest autorem wtyczki?

**Comment by anonimusek** [comment]
tak mlotkiem .. :) ja bym chetnie chcial to zobaczyc w realnym swiecie ale jak widac wiekszosc z was to tylko za monitorem sie umie chowac bo taka wasza polityka panowie a raczej paniusie bo do prawdziwych facetow z jajami wam daleko za duzo filmow o hakerach ogladacie i w glowach sie wam troche poje****** .. 

kazdy kij ma dwa konce..

**Comment by ebot2007** [comment]
No to nie ladnie brak slow nic wiecej ...

**Comment by Mandic11** [comment]
i dobrze robi :D te buildy platne to zbieranina smiecia calego i wygladaja jak przeladowana swiatelkami choinka.... w zyciu bym im nie dal za to 1e nie mowie o wiecej, najlepiej jakby Ramic zrobil platny dostep do wtyczek i z glowy, a ten kto chce i tak bedzie sobie korzystal z wtyczek Ramica lub sobie sam przerobi, jak sa tacy zdolni to niech tez to sobie robia i dodaja do buildow, choc pewnie tego nie potrafia dlatego tak placza i sie rzucaja..... dla mnie to zlodziejstwo i zarabianie na czyjejs pracy, zeby jeszcze to za free dawali ale branie kasy za jego prace to dno totalne.... tak dalej Ramic!!!! :D

**Comment by anonimusek** [comment]
Co za bzdury..

Bulidy a przynajmniej alientv były za free.. ale gdy ktoś sprzedaje bulid za 40 funtów to sorry dlaczego bulid ma być darmowy? 5 euro za bulid to śmiech na sali.. zrób własny zobaczysz jak to wygląda.. ja się nie będę wypowiadał na temat innych bulidow ale mogę na temat alientv nic nie jest przeladowane jest poprostu dostosowane do użytkownika.. 

I odrazu widać że nie miałeś np alientv bo inaczej byś to opisywał.. a kasę bierze się za pomoc techniczna bardziej niż za sam bulid.. a że nie jesteś w temacie i nie wiesz jak to wygląda to już twój problem..

**Comment by DiagSystem** [comment]
Skoro ktoś robi wtyczki za Free to dlaczego ktoś za free nie może zrobić bulid ? Tylko kasę żąda Wiemy że często duża część wtyczek nie działa i za każdą aktualizację ma ktoś płacić Ludzie jak ktoś daje wtyczki za free to niech ktoś na tym nie zarabia
