### ISSUE TITLE
Ramic Twoje ego leży Kwiczy i wolą o pomoc

### ISSUE THREAD

**Issue by vTneilA** [ramicspa/kodi#125]
Chłopcze.. daj już sobie spokój udostępnisz dream vision które nie należy do Ciebie.. bawisz się w jakieś gierki.. jeśli masz ochotę to daj namiar a chętnie cie odwiedzę pójdziemy na piwo wyjaśnisz mi w czy leży Twoj problem.. może czujesz jakieś zagrożenie z mojej strony a może coś innego.  

Tak czy siak robisz się śmieszny..

Wtyczki są darmowe lady o tym wie.. wiele ludzi umie instalować wtyczki i robić skroty.. 

Ale jeszcze więcej ludzi tego nie potrafi.. i dlatego pobieraja bulid..

I żeby było jasne bulid mógłby być za free tak jak twoje wtyczki.. lecz zawsze się znajdzie w polskim społeczeństwie jakiś cwaniak który będzie sprzedawać ten bulid.. a są tacy płacą za bulid 5euro a sprzedają go za 15 innym.. parodia.. z Bulidem przychodzi pomoc techniczna itd.. widzisz to co ty teraz przerabiasz z blokowanie swoich wtyczek ja przerabialem w marcu tego roku gdy bulid był jeszcze za free i inni "cwaniaczki" sprzedawali go za nie mała kasę.. ale ty tego nie potrafisz zrozumieć... masz problem ze sobą i swoim ego.. taka jest niestety prawda.  

Dzięki za udostępnianie i robienie reklamy.. i popraw adres w tekście.. ;) 

Więc żyj i daj żyć.. jak to się mówi..

**Comment by anonimusek** [comment]
Aha dodam jeszcze że żaden z serwisów nie należy do Ciebie.. ! 

Przed tobą był mr know który ma alltube od zawsze dopiero później byłeś ty i twój alltube co nie czyni Cie złodziejem oczywiście..

Ale tego też nie potrafisz pojąć.. idź dalej tym torem.. w dream vision będą wszystkie dodatki które ty masz dostępne na każdą skórkę a twoje repo pójdzie w niepamięć..

A jak ktoś wcześniej napisał odnosnie wyglądu.. co za różnica jaki wygląd skoro ani tak skrótu przycina się do głównego menu.. robione pod bulid i tak ma być..

**Comment by gzenio22** [comment]
Racja ta blokada na inne skory to błąd bo sorry ale oryginalna skora kodi nie oferuje nic w kodi 16 a już tym bardziej w nowym 17 scie gdzie ten skin to jedno wielkie bagno 2 sprawa nie każdy ma czas i ochotę od podstaw układać pod siebie kodi dla tego szuka gotowców a Pan Michał blokując wtyczki na inne skory sam strzela sobie w kolano. Szanuje Pana za to co pan potrafi i co zrobił do tej pory ale jednak blokada wtyczek na skórach innych niz Confluence to milowy krok w tył

**Comment by kashkash18** [comment]
Ooooo widzę tu wielkie ból dupy hahaha

**Comment by marcintomanek** [comment]
Dupek z tego Ramica, trochę wiedzy i te wszystkie wtyczki można przepisać. 15 minut roboty. A co do Dream Vision, to każdy może zrobić swoje Vision, ale czy umie. Alien i MM rozpowszechnili wtyczkę Ramica i teraz ją zabiją, ja już ją sam zabiłem a nie mam wizzarda od Aliena. To co zrobił Ramic jest tak żenujące, przy ilości wtyczek dostępnych na świecie, że jego robota mi już koło dupy lata

**Comment by marcintomanek** [comment]
Repo powinno się nazywać KODREMIC, albo NOWOCZESNAREMIC

**Comment by marcintomanek** [comment]
anonimusek . Jesteś w związku partnerskim z Ramiciem? że mu tak lody robisz?

**Comment by marcintomanek** [comment]
Ramic za to co zrobił jest przegrany na całym świecie wtyczek do Kodiego, nikt tak nie postapił a wtyczek jest setki. Co mu odbiło?

**Comment by kashkash18** [comment]
Marcintomanek widzę że żona nadal wkurwiona iż Ramic nic nie zmienił odnośnie skinu hehehe

**Comment by marcintomanek** [comment]
Już go wy...waliłem i napisałem swojw wtyczki

**Comment by marcintomanek** [comment]
dzień roboty i wszystko chodzi. Nikt nie jest wkurwiony.

**Comment by kashkash18** [comment]
Brawo Ty , tylko po co to bluzganie ??

**Comment by marcintomanek** [comment]
Bo Wtyczki do Kodiego mają być dostępne, bo takie ma być Kodi, cały świat to rozumie, Ramic jest chyba jedyny na świecie, który sie cipi

**Comment by marcintomanek** [comment]
Pokaż mi inną wtyczkę, która robi takie jaja na świecie?

**Comment by kashkash18** [comment]
No przecież jest dostępna , a to że będzie działać na oryginalnym skinie to tylko jego sprawa. Napisałeś sobie sam wtyczki więc nie ma co się rzucać , najważniejsze że Ci działa i że sam będziesz robił sobie update

**Comment by marcintomanek** [comment]
Chłopak już jest przegrany w świecie Kodiego. A kto bluzgał Aliena, to też jest jakaś robota.

**Comment by kashkash18** [comment]
Przegrany w świecie Kodiego bo jego wtyczki działają na oryginalnym skinie ?? Proszę Cie

**Comment by marcintomanek** [comment]
Przegramy? Ilu was jest?......Tak przegracie. Już przegraliście, bo tego nikt nie będzie instalować, bo promil ludzi używa oryginalnego skina i tam wtyczek nie instalują, tylko filmy sciągnięte odtwarzają, albo zdjęcia z wakacji. Jak to WY jesteście to, tak już przegraliście

**Comment by marcintomanek** [comment]
żenada, pokarz mi jednego, kto takie coś wymyślił jak RAMIC?

**Comment by kashkash18** [comment]
Widać że czytanie ze zrozumieniem jest problemem. A ten promil o którym mówisz jest zadowolony bo nie ma problemów

**Comment by marcintomanek** [comment]
No, ok jeżeli mądre jest przełączanie skinów dla jednej wtyczki to gratujuje rozumu. A czytanie ze zrozumieniem to pozostawym. POKAŻ MI JEDNE REPO NA ŚWIECIE KTÓRE ROBI TAKIE CYRKI?

**Comment by marcintomanek** [comment]
z czym problemów?......coś piepszysz

**Comment by marcintomanek** [comment]
Połowa Europy wykasowała Ramica, gościu robi repo sam dla siebie, GTRATULACJE. To tak samo jak pisać piosenki i chować do szuflady

**Comment by kashkash18** [comment]
Ale po co mam Ci to pokazywać ?? Ramic jest twórcą wtyczek i to on decyduje jak mają wyglądać i na jakich zasadach mają działać. Za obecną sytuację możesz podziękować "oburzonym złodzieją". Nikt nie każe Ci używać tych wtyczek , ale też nikt nie blokuje Ci do nich dostępu. Ustalił nowe zasady i tylko od Ciebie zależy czy się do nich dostosujesz. Ty poszedłeś inną drogą i sam sobie wtyczki napisałeś, ważne że Ci działają. Będziesz robił sobie Update i nadal będą działać na Twoim ulubionym Skinie

**Comment by kashkash18** [comment]
Połowa Europy hehehe Pokaż mi takie dane

**Comment by anonimusek** [comment]
Hahaha z mojego punktu widzenia to ramic ma problem ze swoim ego.. chyba chce zaistnieć w świecie.. 

Prosił grzecznie techmaniaka żeby nagrał film o jego repo.. a później zablokował mu dostęp do wtyczek kodem który robił fresh start każdemu co posiadam MM..

alientv był jako pierwszy to jest jedyny fakt.. później pojawił się dopiero MM i ramic.. nigdzie nie było napisane że nie można było korzystac z wtyczek ramica.. więc autorzy bulidow skorzystali z tych wtyczek.. Po jakimś czasie wtyczki zostały usunięte z bulidow.. powstała nowa wtyczka Dream Vision która teraz jest przerobiona przez ramica i jest w jego repo wtyczka nie należy do niego.. więc teraz mi powiedz kto tu jest złodziejem?

**Comment by kashkash18** [comment]
Upakowanie kilku wtyczek Ramica do jednego pudełka i nazwanie jej Dream Vision jest wg Ciebie OK ??

**Comment by tomasiek** [comment]
Kompletnie nie rozumiem tej irytacji... Skoro i tak nikt nie używa repo ramicspa, skoro wtyczki można napisać w 15 minut, skoro wtyczka ma być dostępna to jest. O co ten nerw? Dostaliśmy prezent na święta... Świetna wtyczka, wiele serwisów, dzialająca...A patrząc na ton wypowiedzi co niektórych to mogą dostać... wylewu.

**Comment by Algirion** [comment]
Czytam powyższe komentarze i jakieś jaja to są! Z tego co czytałem to gdy inni używali kodi z buildem i z jego wtyczkami to im cały katalog czyściło! Niektórym podobno nawet katalog użytkownika Windows leciał. 
Taka osoba jak ramic powinna w ogóle mieć zabroniony dostęp do tworzenia czegokolwiek i tego udostępniania jeśli zwykły Kowalski dostaje po dupie!
Jak mu się nie podobają buildy to jego sprawa ale nie powinien mieszać w to innych. 
Przecież są setki innych buildów na świecie dostępne za darmo jak i za opłatą ale sorry, te darmowe, które widziałem z ArezWizard są tragiczne a sprawdziłem ostatnio po tej akcji chyba z 15 czy 20 najpopularniejszych. Od miesięcy nikt się nimi nie zajmował więc respect dla tych polaków, którym się w ogóle chce przygotować coś takiego dla innych.

**Comment by anonimusek** [comment]
Ale kto mówi o uzyskaniu wtyczek ramica.. tylko ramic może być taki głupi i osoby czytający i idące jego torem.. tak jak pisałem mr know miał alltube gdy ramic zrobił osobna wtyczkę do alltube to nikt mu nie zarzuca tego że mu coś zabrał.. 

Ludzie te serwisy nie należą do ramica !!!!!!!!!!! On robi tylko wtyczki i skoro je blokuje na skin inne to rzeczą normalna jest ze pojawi się ktoś inny kto zrobi te same wtyczki.. i wcale nie jest to rywalizacja czy złośliwośc jest to poprostu kolej rzeczy.. a każdy wie że wtyczki ramica są jednak fajne i to trzeba mu przyznać..

**Comment by tomasiek** [comment]
Pytanie tylko czy ramicspa wziął kod z repozytorium mrknow czy napisał sam swój własny. Bo to o to się rozchodzi a nie o to czy zrobił wtyczkę do serwisu do którego ktoś inny już zrobił....Bo patrząc na kod z dodatku dream vision to jednak widać kod ramica... 
Dajmy sobie spokój... Święta idą...

**Comment by anonimusek** [comment]
Co za różnica jaki kod skoro efekt jest ten sam? Ramic nie chce się dzielić to spoko ma takie jazdy jakie ma więc ok.. w dream vision będą w takim razie wszystkie przydatne wtyczki dostępne dla każdego w http://repo.alientv.pro bo już zmęczony jesteś tym idiotycznym tematem.. 

Bo to jest więcej niż żenada.. jak można wpisać kod we wtyczkę który formatuja dyski C tylko dlatego bo ktoś używam bulidu? Jaja jakieś.. palce połapać i tyle by miał z pisania tych kodów.. 

Kwestia czasu i ramic już nie będzie taka prywatna osoba..  i każdy się dowie co zrobił w świecie kodi oraz kim jest gdzie mieszka i gdzie pracuje.. a osoby które miały wyczyszczone komputery wtedy będą mogły wrzucić swoje 5gr.. a z tego co wiem bylo ich sporo i straciły wiele ważnych rzeczy prywatnych i firmowych.. 

Więc co jest gorsze zrobienie wtyczki na wzór ramic który nie chce się dzielić czy robienie pozłości każdemu i czyszczenie komputerów..?

**Comment by Algirion** [comment]
Jeżeli wtyczka z alientv.pro jest faktycznie darmowa i dostępna teraz dla każdego z buildem nie ważne jakim to widać kto tu faktycznie walczy o ludzi i chce ich dobra a kto ma jakiś kompleks Boga.
Dzięki :)

**Comment by Mandic11** [comment]
Ramic to ma was gleboko w d... raczej, sa swieta i sie bawi zamiast jak wy kwiczec tu w kolko, chyba was zabolalo :D

**Comment by anonimusek** [comment]
To chyba ramica zabolalo skoro robi co robi.. dla mnie sprawa jest jasna.. i chciałem się tym podzielić ktokolwiek umie czytać ze zrozumieniem to zrozumie..

**Comment by kashkash18** [comment]
Ramic zabrał tylko swoje coście mu zajechali. Tyle w temacie

**Comment by ramicspa** [comment]
hmm sporo postow, nie czytalem zapoznam sie moze nieco pozniej. Wesolych Swiat dla wszystkich i moze nieco wiecej zyczliwosci a mniej agresji.

**Comment by kashkash18** [comment]
Zdrowych i wesołych :)

**Comment by anonimusek** [comment]
Ja uważam trochę inaczej i złodziejstwem bym tego nie nazwał.. tak czy siak mnie to lata.. wtyczka jest free cieszy mnie to i mam nadzieję że jak najwięcej osób z niej będzie korzystać bo z ramica wtyczek się nie da..! 

Również życzę wesołych świąt i trochę oglady..

**Comment by Algirion** [comment]
Kwestia tego, że te zwady są najbardziej nie na rękę zwykłym osobom chcącym używać wtyczek. Ja dzisiaj jeszcze trochę bawiłem się w buildy z AresWizard no i jedna fajne, drugie gorsze ale bez wtyczek ramic będzie lipa i nie ma po co instalować takiego builda. Jeżeli ta dream vision będzie działać to chociaż coś.
Dogadajcie się między sobą wszyscy bo to idzie za daleko.
Wesołych Świąt wszystkim! Naprawdę mniej agresji. W końcu mamy dziś Wigilię.

**Comment by Seico** [comment]
Ja zadam tylko jedno pytanie :
Czy ktos kogokolwiek zmuszał aby instalował wtyczki wtyczki "Ramica" ? - wydaje mi się że nikt
Jeżeli są umiesczane w jakim kolwiek buildzie to znaczy że nie ma lepszych w Polsce wtyczek niż robi to "Ramic" , a jeżeli ktoś w jakiś sposób chce na tym zarobić to sorry , na to nie ma zgody :(
Sam jestem pomysłodawcą 3 wtyczek , jedna okazała się niewypałem , bo znaleźli się "życzliwi" którym przeszkadza oglądanie filmów w wysokiej jakości , dlatego jedna ze wtyczek jest bardzo zabezpieczona aby nie przeszkadzało tym "życzliwym" i filmy które tam są były zawsze dostępne.
Nikt nigdy nie dał zgody na to aby na wtyczkach "Ramic" można było jeszcze zarabiać. 
Jak komuś to nie pasuje to poproszę "Ramica" i za jego zgodą jednym kliknięciem myszki skończy się oglądanie filmów w jakości która by zadowoliła wszystkich - wybór należy do Was

W tym dniu Życzę Wszystkim Zdrowych , Spokojnych i Wesołych Świąt - mam nadzieje że ostudziłem co poniektórym emocje

**Comment by anonimusek** [comment]
Seico.. bulidy były zanim się pojawił ramic.. a info nie było nigdzie żeby ich nie używać.. wtyczek w bulidzie jest ok 100 z czego ok 7 od ramic.. tak było już ich nie ma.. więc w czym problem? Ludzie nauczcię się rozmawiać z innymi a wy zabieracię się do tego nie od tej strony której trzeba.. jestem już zmęczony tym tematem.. 

Bez wątpienia ramic robi najlepsze wtyczki ale nie jest jedynym który to potrafi jest mnóstwo osób które robią to lepiej ale poprostu nie mają na to czasu a raczej wolę ten czas poświęcić na coś porzyteczniejszego niż robienie free wtyczek a później ich blokowanie.. 

Mój punk widzenia jest odmienny niż ramica.. ale mam dobre chęci od samego początku i nie płacze z powodu wrzucenia wtyczki dream vision w repo ramic.. a nawet się cieszę.. ;) 

Istnieje sensowne rozwiązanie tego sporu ale nie będę pisał o tym na Forum ramic ma mój Email może też się sam odezwać.. oczywiście nic z tego ani tak nie będzie bo ramic należy do osób które koniecznie muszą dominować i musi być po jego myśli.. i jeśli on na jakiś pomysł nie wpadnie to nikt inny nie może.. a blokowaniem wszystkiego co się da to tylko próbuje nagłośnic temat swojego repo tak jak to prosił techmaniaka o nagranie filmu promującego jego repo.. a blokuje te wtyczki po co? Skoro ich już nie ma w żadnym bulidzie poza gladiatorem? Właśnie po to bo lubi afery.. 

A odnośnie sprzedawania czyjejś pracy w bulidach to napisze tyle że bulid alientv wtyczka Alien Wizard oraz dream vision oraz wszystko co z tym związane łącznie z grupą licząca 1400 osób która była już założona w tamtym roku włożyłem w to więcej pracy niż ramic we wszystkie swoje wtyczki a jeśli ktoś sądzi inaczej to życzę i sugeruje mu zrobić coś podobnego i przekonać sie samemu.. odnośnie wtyczkę niestety nie jestem tak uzdolniony jak ramic ale jestem pewien że sklepanie dream vision kosztowało więcej czasu niż ramica jego wtyczki.. 


Taka moja opinia na ten temat..

**Comment by Seico** [comment]
**anonimusek** - no widzisz , a jakbyś wiredział ile czasu "Ramic" spędził nad tworzeniem mojego pomysłu wtyczki i ile musiał znosić moich kaprysów żeby wtyczka miała wygląd i była bezpieczna taka jak jest (choć posiada jeszcze teraz małe mankamenty) to byś inaczej do tego tematu podszedł , ja bardzo dużo czasu i pieniędzy poświęciłem aby zgromadzić to co teraz posiadam i jak by nie "Ramic" to bym mógł to stracić w ciągu paru godzin , a kolega "Ramic" pomógł mi (Choć  nie musiał- mógł moją prośbę olać) i teraz filmy które posiadam są dostępne w dobrej jakości i bezpieczne.
Wydaje mi się że Twoja bolączka polega na tym że ktoś Tobie przeszkodził w tym aby jeszcze na tym zarobić - ale mogę się mylić - jeżeli tak jest to przekonaj mnie że się  mylę

**Comment by Mandic11** [comment]
tez mi sie wydaje, ze najwiecej placza ci ktorzy na tym zarobic nie moga
i pewnie sie pelno skarg posypalo im teraz czemu nie dziala....
pro sprawa z tym usowaniem all w kodi:D specjalnie testowalem (qrde pomysl masakra gratulacjje za to:D, masakra pomysl :D)

**Comment by tomasiek** [comment]
Nie rozumiem tego problemu z usuwaniem. Z tego co wywnioskowałem to wtyczki
ramica usuwały na innych niż oryginalny build zawartość profilu kodi. No i?
Czyżby wszyscy superspece od wizardów, zwłaszcza ci którzy tu jęczą, brali
kasę za pomoc techniczną a nawet nie testowali wtyczek? Czyli skasowali a
potem radź sobie sam, bo mi się nie chce testować? Przecież to normalne że
wtyczka może nie działać, może działać szkodliwie itp itd. Kupując builda
płacę autorowi (ale nie autorowi wtyczki) za to żeby działało wszystko, za
ta słynna pomoc techniczną.... A tu kurcze jakiś ramicspa ośmiela się do
swojej wtyczki wrzucić małego szpiega u tych którzy na nim zarabiają...
Poza tym... Pomoc techniczna? Wydaje mi się że ramicspa świadczy jedną z
lepszych z jakimi miałem do czynienia. Wysłuchuje uwag, wprowadza
poprawki... Tłumaczy problemy.
Ramicspa - tak trzymaj. Inne wtyczki chowają się przy twoich ze względu na
swoją modułowość.

24.12.2016 10:57 PM "Mandic11" <notifications@github.com> napisał(a):

**Comment by anonimusek** [comment]
@tomasiek

Nie do końca jest tak jak to opisujesz.. 

Wtyczki są sprawdzane tzn były.. nikt już nie potrzebuje ramica wtyczek przynajmniej w moim przypadku mam osobne wtyczki do tych samych serwisów.. i nie płacze tylko prowadzę rozmowę.. 

Popatrz na to z tej strony.. skoro Alien Wizard jest juz w sieci od lutego a ramic pojawił się dopiero później.. ja jego wtyczki wrzuciłem do bulidu dopiero w październiku bodajże a 12 listopada jakoś tak bez żadnej informacji wtyczki dostały update i dopiero wtedy zaczęły sprawiać problem.. 

Od października do listopada nie ma sporo czasu więc też nie tak sporo osób posiadało te wtyczki.. w kolejnych dniach wtyczki dostawało inny kod który nie czyścić kodi tylko cały system Windows.. więc moim zdaniem to lekka przesada mnie to nie szkodzi bo ja na tym nic nie tracę i potrafię odzyskać wszystko.. ale jak to wytłumaczyć emeryta czy osoba niepełnosprawnym które całe dnie spędzają przed kodi a tu nagle dostają kopa że nie mają nic na swoim kompie? 

Ramic dowiedział że że są bulidy chociaż dziwi mnie ze wcześniej o tym nie wiedział.. napisał z tego co się dowiedziałem tylko do jednej osoby a do alientv już nie poprostu sobie wrzucił kod i niech się dzieje co chce.. 

Pff no cóż za spryt.. ale karma zawsze wraca.. 

Nie ma co ciągnąć tego tematu bo różne osoby mają różny punkt widzenia..

Wtyczek ramica nie powinno być w bulidzie jeśli sobie tego on nie życzy i ich tam nie ma.. no poza gladiatorem.. ale też nie chcę słyszeć że ktoś zarabia na jego wtyczkach bo tak nie jest.. piszę poraz setny bulidy były jak jeszcze ramica nie było i co za tym idzie działały bez jego wtyczek..

**Comment by tomasiek** [comment]
Czyli podsumowując twoje rozumowanie.  Buildy były i działały bez ramica, bo były zanim powstało jego repozytorium, teraz też działają bez... Więc w czym problem? Skoro te wtyczki są do niczego bo macie lepsze? Kurcze.. masz merca a chcesz jeździć maluchem?

**Comment by Seico** [comment]
Mercedes ma już duży przebieg , "Ramic" mam prośbę zamknij ten temat bez dna , bo trzeba by było rozpisywać się za tych co są według nich ok i tych co są według Nas ok , @tomasiek , widocznie maluch ma mniejszy przebieg , szkoda czasu , niech lecą na tych wtyczkach co mieli przed Twojej pracy , uwierz mi za moment bę

**Comment by tomasiek** [comment]
@seico to z tym maluchem to była przenośnia. Oni rzekomo mają mercedesa. Ale to beczka ze sporym przebiegiem, łatana po raz 1000x w RPA....My/Ramic zaś mamy autko małe, ciasne, z silnikiem w tyle, chłodzone powietrzem.. czyli malucha... ale czy to na pewno jest maluch? A może to małe 911… :) eot.

**Comment by DiagSystem** [comment]
Wczoraj mieliśmy sylwester A ja kuźwa stawiałem na nowo system Bo mi kuźwa po odpaleniu Kodi wyjebało wszystko z systemu Tak się nie robi zwykłym użytkownikom darmowych nakładek. Nie kupuje płatnej bo w darmowe sam dokładam sobie co mi potrzeba prócz tego co dali za free w darmowej nakładce. I za to od was otrzymałem prezent Wyczyszczony windows i zabawa z postawieniem na nowo systemu . Dobrze ze już w nowych wersjach usuneliście  Kod , który kasuje nie tylko Kodi ale i cały system

**Comment by marcintomanek** [comment]
Art. 269b kk (dotyczący tzw. narzędzi hakerskich, a omówiony szczegółowo w NetWorld 5/2004) jednoznacznie pozwala na karanie osób parających się tworzeniem wirusów - zakazuje bowiem tworzenia, a nawet pozyskiwania programów przystosowanych do osiągania destrukcyjnych skutków w postaci usuwania danych z systemu komputerowego lub paraliżowania jego pracy.

**Comment by marcintomanek** [comment]
Art. 269b kk (dotyczący tzw. narzędzi hakerskich, a omówiony szczegółowo w NetWorld 5/2004) jednoznacznie pozwala na karanie osób parających się tworzeniem wirusów - zakazuje bowiem tworzenia, a nawet pozyskiwania programów przystosowanych do osiągania destrukcyjnych skutków w postaci usuwania danych z systemu komputerowego lub paraliżowania jego pracy.

**Comment by marcintomanek** [comment]
Ramc......szykuj sie na pozew

**Comment by marcintomanek** [comment]
ale sie najbołeś........

**Comment by kashkash18** [comment]
Jaki Ty jesteś śmieszny :) Jak to jest że wtyczki Ramica piszesz w 15 min a danych z dysku nie potrafisz odzyskać hahaha Kozak w necie , pizda w świecie . Tyle w temacie

**Comment by marcintomanek** [comment]
kashkash18 spierdalaj cipo, dane odzyskam, ale zapłacisz mi za czas, do pierdla z wami jebane kodziarstow, Ryja twpjego nie widziałem, to nie wiem czy jesteś śmieszny

**Comment by skorpion454** [comment]
Moim zdaniem, repo jest prywatne i jezeli pisal wczesniej ze bedzie tylko dzialac na oficjalnej skin to jego sprawa, ale nie zgadzam sie z tym zeby usuwac folder USER z windows to juz nie jest ochrona, mozna to zalatwic w sposob ktory nie zagraza uzytkownikowi, sam tego nie doswiadczylem ale to tylko dlatego ze wiem jak tego nie doswiadczyc ale sa ludzie ktorzy maja problem nawet z zainstalowaniem kodi a co dopiero mowic o odzyskaniu straconych danych.

**Comment by Algirion** [comment]
Niby tak. Właściciel ma prawo zrobić z nimi co chce ale albo jestem głupi albo to jest trochę pomylone bo wtyczki są prywatne ale są tutaj powszechnie dostępne i autor chce by z nich korzystano a z drugiej strony wywala system lub katalog kodi to o co chodzi w tym wszystkim?
Teraz te wtyczki są nawet w superrepo a to jest zaprzeczenie prywatności bo superrepo ma wszystkie repa i wtyczki niemal dostępne w kodi i używa się tego na całym świecie i chyba tylko sam autor mógł je tam umieścić.
Niech ktoś mi to wytłumaczy w takim razie...

**Comment by onicram** [comment]
Witam.
Drodzy zwolennicy i przeciwnicy Ramica i buildow.
Czytam od dwóch tygodni to co tutaj wypisujecie w tym temacie i w innych dotyczących sporu.

To nie jest pierwszy spór Ramica ze mu coś ukradli.
Każdy kto dostał od niego email z zaproszeniem i adresem dostępu do tego repo o tym wie.

Przez tą wojenkę miedzy Ramicem a twórcami buildow cierpią zwyczajni użytkownicy.
Wiadomo też że każdy wypowiadający się tutaj ma swoje zdanie i pogląd na to wszystko.
Ja szanuje wasze zdania i proszę Was o uszanowanie mojego.

A moje zdanie jest takie.
Skoro dostałem zaproszenie i pozwolenie na darmowe korzystanie z tego repo i znajdujących się w nich wtyczek chcę by one były bezpieczne dla mojego systemu i sprzętu.
Nie ważne w czym tego używam.
Zapewne tego samego chce każdy korzystający z tego repozytorium.

Według mnie że jest to kawał dobrej (świetnej) roboty Ramica i zaliczam to repo do najlepszych repozytoriów na świecie.
Wątpię by ktoś się ze mną nie zgodził.

@skorpion454  moim zdaniem rozwiązuje to spór o to czy repo jest prywatne czy publiczne.
Skoro Ramic sam zaprosił do korzystania z niego to nie może ono być prywatne.
Nie wspominał tam też że będzie działało tylko na oficjalnym skinie.

Tutaj kawałeczek tego emeila z zaproszenie do do korzystania z Repozytorium i wtyczek Ramica
http://screenshot.sh/oeY0Gl2ZqwIu0

Pozdrawiam Was wszystkich.

**Comment by ramicspa** [comment]
nie wsyzstko tu czytalem ale troche tu wulgaryzmow polecialo, jak sie juz pozalili to zamykamy temat.
