### ISSUE TITLE
changelog i linki w readme

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#127]
Czy jest możliwość żeby w readme na githubie kliknięcie na datę aktualizacji wtyczki prowadziło do changeloga danej wtyczki?

**Comment by ramicspa** [comment]
tak

**Comment by tomasiek** [comment]
Super. Zanim aktualizuje, zawsze sprawdzam changelog. Wiem że to niewiele i tak daje, bo możesz wpisać tam cokolwiek, jednak odruch to odruch.
