### ISSUE TITLE
efilmy nie działa na wtyczce mimic

### ISSUE THREAD

**Issue by DarDo1** [ramicspa/kodi#128]
Jak w temacie wtyczka nie działa na wtyczce mimic. Da się co z tym zrobić. pozostałe wtyczki działają super.

**Comment by tomasiek** [comment]
Trzeba czekać na update :). jest rozwiązanie, ale ramicspa nie wyraził zgody na jego upublicznianie.

**Comment by tomasiek** [comment]
I już po problemie.

**Comment by DarDo1** [comment]
Nie można wejść w dział filmy. Reszta działa

**Comment by tomasiek** [comment]
Może to jakaś tymczasowa przypadłość... U mnie działa :)

**Comment by DarDo1** [comment]
Faktycznie tymczasowa. Już działa.
