### ISSUE TITLE
Zalukaj com

### ISSUE THREAD

**Issue by KML73** [ramicspa/kodi#129]
Czy jest możliwość naprawy wtyczki zalukaj ?

**Comment by ramicspa** [comment]
jak sie napiszesz w czym problem to bedzie latwiej poprawic

**Comment by tomasiek** [comment]
Wczoraj przez jakieś 2-3 godziny nie działało, ale na stronie też był
problem. Teraz jest już ok.

06.01.2017 3:16 PM "ramicspa" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
ok, warto wiec najpierw sprawdzic czy strona dziala
