### ISSUE TITLE
nowe serwisy 

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#13]
lobu.pl

psa-tv.blogspot.com

**Comment by ramicspa** [comment]
dobre serwisy ... cos z tego wyjdzie

**Comment by ramicspa** [comment]
z lobu jest chyba cos nie tak ... nie udalo mi sie tam znalesc nic dzialajacego

**Comment by xxcriticxx** [comment]
dziwne przez strone dziala super

**Comment by xxcriticxx** [comment]
zostaly jeszcze nowe serwisy seansik.nl i kinex.tv (clone alltube.tv)

**Comment by ramicspa** [comment]
Seansik jest juz w repo.
Co do lobu to podaj jakiegos dzialajacego linka ze strony bo mi zaden co
probowalem nie dzialal ... ciagle msg "flie not found"

**Comment by xxcriticxx** [comment]
wszystko gra z flashx.tv


http://lobu.pl/new-player/player-gosc.php?host=www.flashx.tv&type=embed&id=0vtqjf28s4gf
http://lobu.pl/new-player/player-gosc.php?host=www.flashx.tv&type=embed&id=1tvfyboras6x

**Comment by Seico** [comment]
**xxcriticxx** kinex.tv (clone alltube.tv) jest w Repo Alakamba

**Comment by xxcriticxx** [comment]
tak otym wiem

**Comment by ramicspa** [comment]
to nie ma sensu duplikowac pluginu

**Comment by xxcriticxx** [comment]
ok

**Comment by xxcriticxx** [comment]
alltube tez jest w kilku wtyczkach i jakos niema problemu

**Comment by xxcriticxx** [comment]
http://zobaczmyto.tv

**Comment by xxcriticxx** [comment]
https://looknij.in/filmy-online/

**Comment by ramicspa** [comment]
dzieki za linki, troche tych serwisow znalazles ... jak mi sie jakis spodoba to dorobie plugin, chyba ze jest jakis konretky powod ze jestes zainteresowany ich zasobami w kodi? duza czesc ston nie ma dobrej jakosci zasobow albo sortowania po jakosci i w takich przypadkach sa raczej bezuzyteczne

**Comment by xxcriticxx** [comment]
za duzo wolnego czasu

**Comment by ramicspa** [comment]
Hehe to zacznij pisac samemu pluginy. To nie takie trudne.  Jest pelno
tutoriali

**Comment by ebot2007** [comment]
wiatm .
na poczatek dzieki za twoja prace jaka wkladasz . 
mam pytanko czy dalo by cos wyciagnac z tej stronki dziala dobrze wiec moze jakies czary mary http://delta-live.pro/ 
pozdrawiam

**Comment by ebot2007** [comment]
Jestem tez zainteresowany pluginem na wylacznosc oczywiscie za oplata , czekam na jakies info , jeszcze raz pozdrawiam

**Comment by ramicspa** [comment]
@ebot2007 
Hej, da sie wyciagnac cos z tej strony ale to nic specjalnego - jest bardzo duzo tego typu klonow (i-hqtv.com albo telewizja-live.com) i zwykle ich zywotonosc jest dosc krotka jak zrodla nie sa aktualizowane. Poza tym stronki te zwykle nie maja swoich zrodel a kozystaja z innych serwisow ktore same dostarczaja zrodla - one tylko zeruja na reklamach.
Jest jakis szczegolny powod dlaczego chcesz miec to na wylacznosc? moze lepiej podzielic sie ze wszystkimi ?

**Comment by ebot2007** [comment]
Dziekuje za odpowiedz, co do tej stronki http://delta-live.pro/ to pewnie masz racjie. plugin na wylacznosc nie jest az tak mi potrzebny moge oczywiscie dzielic sie ze wszystkimi . :)
tylko nie chodzilo mi o zrobienie pluginu do http://delta-live.pro/  tylko do tej stronki http://www.liveonlinetv247.info/tvchannels.php kanaly ang jezyczne. 
pozdrawiam.

**Comment by ramicspa** [comment]
to wrzuce delta-live do livepolishtv pluginu ... a faktyczkie anglojezyczne lepiej jest umiescic w odrebnym dodatku. pozdrawiam

**Comment by ebot2007** [comment]
Dziekuje bardzo i czekam na info do ang kanalow . :)

**Comment by ramicspa** [comment]
nowa wtyczka live IPTV jest dostepna w repo z kanalami z poza kraju

**Comment by ebot2007** [comment]
Witam, dziekuje dziala naprawde dobrze lecz jest maly problem po wlaczeniu kanalu pojawia sie sygnal lecz jest ramka na srodku ekranu. kiedy robie ok kanal sie wylacza.

**Comment by ramicspa** [comment]
Faktycznie, juz naprawione. iptvsatlinks dzialac beda lepiej jak sobie zainstalujesz plugin.video.f4mTester. (BTW to bylo wtego powodem tej ramki). Bez tego pluginu tez powinno smiagac ale czasem strumien moze sam z siebie sie wylaczyc.

**Comment by xxcriticxx** [comment]
umnie kanaly dzialaja z 10 sec i wraca do listy serwerow

**Comment by ebot2007** [comment]
zalezy jaki server wybierzesz  , jak dla mnie super , dzieki wielkie

**Comment by ramicspa** [comment]
jak wywala streama to zainstalujcie f4mTester: https://github.com/Shani-08/ShaniXBMCWork2/tree/master/zips/plugin.video.f4mTester
najlpiej przez Shani repository, by wtyczka byla zawsze aktualna

**Comment by noirrak** [comment]
Dorzucam: http://i-hqtv.com/

**Comment by Marcino2404** [comment]
Hej. Nie działa Wtyczka Segos. Moglbys to sprawdzic ?
Oraz czy da sie zrobic z tej stronki wtyczke ? http://www.livefootballol.me/

**Comment by ramicspa** [comment]
w czym problem z segos?

**Comment by Seico** [comment]
Gołębie :)

**Comment by Marcino2404** [comment]
Przy probie otwarcia linku z filmem wyskakuje taki komunikat.

https://zapodaj.net/72a64d386edec.png.html

**Comment by Seico** [comment]
Jaką masz wersje Kodi?  Na 17 wystepują w roli głównej "Gołębie" :) , wiec trzeba chyba czekać na aktualizacje

**Comment by Marcino2404** [comment]
Wersja 16.1. Teraz juz działa ok.

**Comment by Seico** [comment]
A u mnie dalej są "Gołębie" - no to tego juz nie rozumiem :(

**Comment by xxcriticxx** [comment]
u mnie dalej pigeon

**Comment by ebot2007** [comment]
Witam, segos dziala .:) pozdrawiam

**Comment by Marcino2404** [comment]
A u mnie dzis znow golebie :( Jeden Film otworzyl sie dobrze, a reszta tylko golebie.

https://zapodaj.net/35e5d755c1baf.png.html

**Comment by ramicspa** [comment]
Ponowne otwarcie powinno usunąć gołębi problem

**Comment by Marcino2404** [comment]
Wydaje mi sie ze problem z golebiami wystepuje na tych filmach wstawionych no openload.co
Jesli jest odnosnik do CDA to otwiera sie dobrze.

**Comment by Seico** [comment]
U mnie nadal filmy z openload.co otwierają się z miłymi głodnymi ptaszkami :)

**Comment by ebot2007** [comment]
Witam ponownie , takie pytanko dalo by rade zrobic wtyczke do zalukaj tv , mr know probowal lecz nie dziala 
p;ozdrawiam

**Comment by ebot2007** [comment]
moze dalo by rade wyciagnac cos z tego jest dlugo juz wiec moze szybko nie zniknie

http://www.typertv.com.pl/

**Comment by xxcriticxx** [comment]
typertv byl dead rok temu

**Comment by ebot2007** [comment]
rok temu ale od kilku miesiecy smiga az milo

**Comment by xxcriticxx** [comment]
http://tele-wizja.com

**Comment by ramicspa** [comment]
juz dawno dodany do livepolishtv ;)

**Comment by Cinek77** [comment]
Hej. Mam pytanie i prosbe. Czy moglbys sprawdzic czy z tej stronki da sie zrobic wtyczke ?
http://filmland.pl/

Pozdrawiam.

**Comment by xxcriticxx** [comment]
@Cinek77 strona sie nie nadaje tak zwany szajs

**Comment by kashkash18** [comment]
A czy jesteś w stanie dodać tele-wizja PVR Live TV by utworzyć m3u ??

**Comment by ramicspa** [comment]
musze sprawdzic czy link sie nie zmienia. jesli nie to mozne wygenerowac m3u - pojawi sie opcja we wtyczke. Jak stabilne zrodla to wygodnie uzywac PVR :)

**Comment by kashkash18** [comment]
I jak za Tele-wizja , da się wrzucić do PVR m3u ??

**Comment by kashkash18** [comment]
I jeszcze jedno pytanie , da się z tej strony zrobić coś sensownego ??

**Comment by ramicspa** [comment]
Tele-wizja dodana do listy mozliwych m3u ... zapomialem przy poprzednim updatecie.
serwis squidtv tylko udostepnia linki z innych serwisow ... obawiam sie ze moga byc duze problemy ze znalezieniem dzialajacego zrodelka. Lepiej by znalesc serwis ktory sam udostepnia streamy a kopiuje z innych serwisow.

**Comment by kashkash18** [comment]
Tele-wizja w PVR śmiga aż miło :)

**Comment by ramicspa** [comment]
hmm ... dobrze ze smiaga ... ale jeszcze trzeba zmienic nazwy kanalow by mozna wykorzystac dobrodziejstwa epg

**Comment by kashkash18** [comment]
Było by spoko :)

**Comment by xxcriticxx** [comment]
@kashkash18 na jakim os pvr nagrywasz?

**Comment by ramicspa** [comment]
pvr dziala na kazdym .... 
zrobilem update - utworz ponownie liste - nazwy kanalow powinny juz byc zgodne z epg

**Comment by xxcriticxx** [comment]
jest mozliwosc dodania lokacji z networku?

**Comment by ramicspa** [comment]
co masz na mysli? lokalizacja na podstawie IP ?

**Comment by xxcriticxx** [comment]
android ma tylko 16 gb co mam nato nagrac

**Comment by ramicspa** [comment]
pvr pozwala nagrywac, ale nie jest to koniecznie.
otworz livepolishtv, wybierz ostatnia opcje '-> aktywuj PRV live TV'
wybierz tele-wizja jako zrodlo.
utworz liste m3u (poczekaj az skonczy)
nastepnie uaktalij/aktywuj PVR
jako efekt dostaniesz: menu telewizja z lista knalow i aktualnym programem epg. Dziala to dobrze jesli linki nie ulegaja zmianie ... inaczej trzeba wygenrowac je ponownie

![image](https://cloud.githubusercontent.com/assets/12544737/19284201/340cd464-8ff5-11e6-99d0-6db13d802a10.png)

**Comment by Cinek77** [comment]
A moze moglbys dodac Gold TV do LivePolishTV ?

**Comment by xxcriticxx** [comment]
myslalem ze nagrywacje uzywajac pvr

**Comment by ramicspa** [comment]
GoldTV ma swoja wtyczke dla kodi ... a zrodelka sa platne.

**Comment by kashkash18** [comment]
Po aktualizacji wtyczki , przy próbie utworzenia m3u wywala błąd

**Comment by Cinek77** [comment]
To moze z tego cos da sie zrobic ?
http://www.darmowevod.pl/seriale.html
http://www.drhtv.com.pl/index.html

**Comment by xxcriticxx** [comment]
darmowe = przekierowanie do innych stron

**Comment by ramicspa** [comment]
jak wywala blad zapodaj loga przez pastebin.com ... mi dziala dobrze wiec nie wiem gdzie problem

**Comment by ebot2007** [comment]
Witam , u mnie dziala dobrze , pozdro

**Comment by xxcriticxx** [comment]
na windowsie dziala 

problem jest z androidem

**Comment by kashkash18** [comment]
05:34:45 T:18446744073016703280  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'service'}
05:34:45 T:18446744072988920112  NOTICE: virtual void EPG::CEpgContainer::Start(bool) - EPG thread started
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Comedy Central'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'TVN24'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Discovery Channel Pl'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Comedy Central'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Polsat HD'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Filmbox HD'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'HBO'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Filmbox HD'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'CanaŁ+'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'TVP 1'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'TVP2 HD'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Natgeochanell HD'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'HBO'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Polsat 2'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'CanaŁ+'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'CanaŁ+'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'HBO'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'TVN Pl'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'Filmbox HD'
05:34:45 T:18446744072930457904 WARNING: EPG - bool EPG::CEpg::UpdateFromScraper(time_t, time_t) - channel not found, can't update
05:34:45 T:18446744072930457904   ERROR: EPG - bool EPG::CEpg::Update(time_t, time_t, int, bool) - failed to update table 'TVP HD'
05:34:45 T:18446744073018022192  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'service'}
05:34:45 T:18446744073018022192  NOTICE: [SPECTO]: ->----------                originaltitle: None
05:34:46 T:18446744072930457904  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
05:34:56 T:18446744073045801264 WARNING: Attempt to use invalid handle -1
05:34:59 T:18446744073044232496 WARNING: Previous line repeats 2 times.
05:34:59 T:18446744073044232496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.LivePolishTV/lib/telewizja.py', 128, 42, "    fix={o.get('title'):o.get('title') for o in out}\n"))
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.LivePolishTV/addon.py", line 618, in <module>
                                                build_m3u()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.LivePolishTV/addon.py", line 237, in build_m3u
                                                import telewizja
                                            SyntaxError: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.LivePolishTV/lib/telewizja.py', 128, 42, "    fix={o.get('title'):o.get('title') for o in out}\n"))
                                            -->End of Python script error report<--

**Comment by kashkash18** [comment]
Dzieje się tak na fonie z Andkiem 6.0.1 i TV z Andkiem 5.1

**Comment by ramicspa** [comment]
log pomogl ... update poprawiajacy blad juz jest dostepny

**Comment by kashkash18** [comment]
Teraz wszystko jest OK

**Comment by xxcriticxx** [comment]
http://filmy.to/ maybe?

**Comment by xxcriticxx** [comment]
`http://polon-tv.blogspot.com/` or `http://tvp1-online.blogspot.com/`

**Comment by ramicspa** [comment]
thx, cos sie z tego da zrobic

**Comment by xxcriticxx** [comment]
serialosy.pl

**Comment by ebot2007** [comment]
Prosze o sprawdzenie http://www.typertv.com.pl/ naprawde chodzi dobrze .

**Comment by Cinek77** [comment]
Witaj ramicspa.
Znajomy prosił bym zapytał czy dalbyś rade zrobic coś z tym aby nie trzeba było ciągle parować openload z kodi aby coś obejżeć czy w segosie czy w alltube?

**Comment by xxcriticxx** [comment]
wizjada is back!

http://telewizjada.bid/

**Comment by ramicspa** [comment]
to nie ta telewizjada co kiedys ale trzeba lubic to co sie ma. update juz poszedl.

**Comment by ramicspa** [comment]
typertv tez sie niebawem pojawi, dzieki za info o fajnych serwisach :)

**Comment by xxcriticxx** [comment]
serialosy.pl bendzie cos stego?

**Comment by ramicspa** [comment]
pewnie tak ... jak znajdzie sie wolna chwila na napisanie

**Comment by xxcriticxx** [comment]
http://tele-miki.pl/index.html

**Comment by ramicspa** [comment]
tele-miki nic nie wnosi ... wszystkie zrodelka z tele-wizja.com
ystkie zrodelka z tele-wizja.com

**Comment by xxcriticxx** [comment]
@ramicspa niektore sa z private stream

**Comment by xxcriticxx** [comment]
wizjada dead 

Kanał w chwilowo nie dostępny, spróbuj później.

krasnoludek
30 października 2016 z 09:30
Permalink

uaktualnienie:
jak sobie założycie konto na delta media player to macie dostęp do cennika.
Subskrypcja delta media player jest płatna i wynosi:
Subscription for 30 days – EUR €6.49
Subscription for 30 days – USD $6.99
hmmm specjalnie tanio nie wychodzi. Dostęp na 2 urządzenia.
Jak ktoś ma doświadczenie w tym, jak to działa, to proszę o info.

Tomasz
30 października 2016 z 11:38
Permalink

Potwierdzam, po zakupie subskrypcji delta media Player wszystko działa jak należy

**Comment by xxcriticxx** [comment]
mozna hyba skasowac ten serwis

**Comment by ramicspa** [comment]
ja bym tam jej jeszcze nie kasowal ... czasem cos leci
![image](https://cloud.githubusercontent.com/assets/12544737/19836420/95d27aaa-9ea0-11e6-80c3-ec594b229e3d.png)

**Comment by xxcriticxx** [comment]
ale to jest z wizja a pisalem o (tele)wizjada :)

**Comment by ramicspa** [comment]
ok, ale 'ta', platna telewizjada nie jest w livepolishtv

**Comment by xxcriticxx** [comment]
byla za free teraz zmienili na platne

**Comment by ebot2007** [comment]
Witam a moze cos z tego http://zalukaj-online.com/
pozdrawiam

**Comment by xxcriticxx** [comment]
telewizjada.net zaczela dzialac ale player trzeba wykupic za $6.99

**Comment by Cinek77** [comment]
Ramicspa dzieki za dodanie http://tv-online.fm/
Pozdrawiam :)

**Comment by ramicspa** [comment]
nie ma problemu, tv-online.fm jest dobra stronka ... jak cos dobrego na wtyczke sie trafi daj znac.

**Comment by Cinek77** [comment]
Podsylam linka do TV http://amigostv.eu/tv
Na stronie fajnie to chodzi.
Moze bedzie przydatne w LivePolishTv ?

**Comment by Cinek77** [comment]
Hej.
Dzis znalazlem taka stronke http://zalukaj-filmy-cda.pl/
Moze nada sie do repo.

**Comment by clowni** [comment]
@ramicspa Pisalem wczesniej na temat wtyczki, ze Wizja TV uzywa portu 81 w adresie IP dla uzytkownikow premium, natomiast uzytkownicy standard sa na 80 i stad limit uzywania Wizja TV tylko 3h, gdzie czesto jest to mniej. Prosilem o ta poprawke.

Delta Media Player jest dostepny za free aktualnie. Moze go do wtyczki dodac, dosyc dobrze chodzi.

Natomiast inna sprawa tworze listy TV i ciagle mi nic nie chodzi na Kodi Jarvis 16.1, mam crona i ustawienia tak jak opisane i ciagle nie chca mi sie ladowac streamy. Co mozna poprawic ?
