### ISSUE TITLE
Tworzenie listy z wizja tv

### ISSUE THREAD

**Issue by sonictails** [ramicspa/kodi#131]
Po pierwsze, wielkie dzieki za wtyczke! Najlepsza jak do tej pory jezeli chodzi o PL tv. Maly problem - nie daje sie stworzyc listy z nadawcy wizja tv. process zawiesza sie i wyskakuje error. Czy dalo by sie to naprawic? Jeszcze raz dziekuje.

**Comment by ramicspa** [comment]
sprawdze jeszcze czy 'powolne' tworzenie listy (tak w przeciagu kilku minut) moze rozwiazac ten problem
