### ISSUE TITLE
serialosy.pl

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#135]
serialosy.pl padlo a stronka dziala ,dzieki

**Comment by tomasiek** [comment]
No nie działa:
`08:10:07 T:140060359915264  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
08:10:07 T:140060913510144 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.serialosypl/?foldername=%5BCOLOR+blue%5DSortowanie%3A%5B%2FCOLOR%5D+%5BB%5DBrak%5B%2FB%5D&params=%7B%7D&ex_link=&mode=filtr%3Asort
08:10:07 T:140060913510144   ERROR: InputStream: Error opening, plugin://plugin.video.serialosypl/?foldername=%5BCOLOR+blue%5DSortowanie%3A%5B%2FCOLOR%5D+%5BB%5DBrak%5B%2FB%5D&params=%7B%7D&ex_link=&mode=filtr%3Asort
08:10:09 T:140060359915264  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26`

**Comment by ramicspa** [comment]
poszedl update, powinno wszystko wrocic do normy
