### ISSUE TITLE
Alltube.tv - wybór języka nie działa do końca poprawnie

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#136]
Wchodzimy w alltube.tv, wybieramy język i tu albo **dubbing** albo **lektor** powoduje że nic się nie pokazuje (tzn. pusta lista), dopiero kliknięcie OK na pilocie powoduje wyszukiwanie. Z innymi opcjami (napisy, PL, EN) działa prawidłowo, lista filmów pojawia się od razu.

**Comment by ramicspa** [comment]
patrze na alltube i wybor jezyka - hmm no i wszystko dziala jak trzeba -  po wybraniu jezyka wyswietlany jest subset z filmow. Moze to problem ze skorka ?

**Comment by Cerber2000** [comment]
Witam
 Proszę o dodanie do wtyczki  zgrupowany wybór jezyka np lektor, dubbing, pl aby wszystke filmy wyświetlały się  a nie jak do tej pory trzeba wybierać lektor później dubbjing itd
