### ISSUE TITLE
Alltube.tv - niepełne wyszukiwanie

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#138]
Korzystając z opcji szukaj we wtyczce alltube.tv np. szukając filmu Masza i niedźwiedź, wpisuję frazę _masza_. W kodi otrzymuję 4 wyniki: 

- Masza Petraniuk,
- Masza Jatrowa, 
- Masza Bogucka-Bauman, 
- Masza i niedźwiedź. 

Na stronie zaś otrzymuję 5 wyników jakże innych:

- Radio Piter FM / Piter FM
- Zołuszka / Zolushka
- Pocałunek Putina / Putin's Kiss
- Masza i niedźwiedź / Masha i Medved
- Bajeczki Maszy / Mashiny skazki

Z jednej strony - twoje wyszukiwanie wychwytuje aktorów - a to duży plus. Z drugiej zaś, wyszukiwanie na stronie wychwyciło Bajeczki Maszy - a to duży plus. Czy jest możliwość znalezienia jakiegoś złotego środka? Albo dodania opcji (oczywiście z możliwością przełączania) pomiędzy wyszukiwaniem twoim a tym ze strony?

**Comment by ramicspa** [comment]
wtyczka kozysta z tego samego mechanizmu co strona, ... moze jakos format wynimow sie zmienil i cos nie jest filtrowane jak trzeba. pyrzy updatecie bedzie poprawka.

**Comment by tomasiek** [comment]
Na alltube na stronie nie udało mi się uzyskać tych samych wyników w żaden sposób.

**Comment by ramicspa** [comment]
dokladnie ze strony i wtyczki takie same wyniki:
![image](https://cloud.githubusercontent.com/assets/12544737/21903065/ace93eca-d8fe-11e6-8d37-93dc12555951.png)
kiedys nie bylo opcji aktorow wiec ich segreguje jako filmy.
Wyglda na to ze mozna szukac fimow/seriali po aktorach - wiec przy nastepnym update bedzie taka opcja

**Comment by tomasiek** [comment]
Tak - w szybkim podglądzie są dokładnie te same wyniki. Ale jak klikniesz enter po wpisaniu "masza", to przeniesie cię do listy wyników które podałem w pierwszym poście.
