### ISSUE TITLE
Wtyczki Ramica na sprzedaż...

### ISSUE THREAD

**Issue by Algirion** [ramicspa/kodi#142]
Jestem od niedawna na forum, w sumie od kiedy zaczęły się te jazdy z bildami bo to lepsze niż brazylijska telenowela ale pozwoliłem sobie założyć nowy temat jako że sytuacja jest nawet bardziej ciekawa.
Czytałem te bluzgi na forum odnośnie twórców bildów. Sam korzystałem z kilku naprzemiennie MM, AlienTV i Gladiator ale również z tych w AresWizard. Jestem zwolennikiem tego typu ułatwień ale jeszcze nie bijcie mnie za to, kwestia gustu łamane na lenistwa :p
Ogólnie blokada repozytorium jest na te polskie buildy. OK. Oni już nie używają Ramica - sprawa prosta ale teraz do rzeczy!
Mam rodzinkę w Stanach, dokładnie w Chicago i ostatnio gadka szmatka przez skype z wujem odnośnie tego, jak pizgało zimnem no i ten oczywiście wszystko wie bo ma polską tv. Przyśpieszając co i jak okazuje się że ma boxa z wtyczkami Ramica - zatkało mnie jak diabli! Kupił cudo za $250 kilka miesięcy temu wstecz a ogłoszenie wisiało w polskim spożywczaku. Box to istna tandeta, MXQ z android 4.
Nie ma tam żadnej nakładki, samo kodi, repo ramic i wtyczki, nic nawet nie wyciągnięte w ikonkach tylko dodane do ulubionych LivePolishTV i cała reszta. Pomyślałem, co za rozbój! Wuj zadowolony bo mu to działa i to wszystko co mu trzeba ale teraz zacząłem się zastanawiać że wszyscy tak jadą na tych autorach bildów, którzy jednak robią sporo i robią to fajnie i dzięki nim wiele amatorów może się wszystkeigo nauczyć a ktoś taki kto centralnie sprzedaje gówniany box z wtyczkami ramica robi na tym grubą kasę a ile w tym wkładu od siebie? Żeby nawet przeklętego skrutu nie wyjąć tylko dodać do ulubionych? Tamci chociaż się starają bo każdy kto jednak spojzał na ich wysiłek widzi, że jest to dobra i własna robota.
Pytałem wuja i mówił że tych ogłoszeń w prasie polskiej jest sporo ale nie wszystkie jakoś tak jednoznacznie mówią co tam się w nich znajduje. Po prostu polska telewizja, box z tym i wszystko w temacie.

Pewnie nie jeden śledzący temat myślał nad zrobieniem swojego bilda ale jednak sprawa nie jest taka łatwa bo jest z tym kupa roboty ale kupic kilka chinskich tanich boxów, wrzucić tam samo repo ramic i poprzyklejać ogłoszenia na dzielni to łatwizna.
Zaraz pewnie część tego forum będzie miało własny biznes plan ;)

**Comment by ramicspa** [comment]
od czasu do czasu jakas lewatywa przeczyszczajaca powinna skutecznie zniecheci geniuszy businessu.

**Comment by cronofx** [comment]
A propo  tzw platnych buildow na h...mi 1200 pluginow  z czego wieszosc to rubish osobiscie w kodi uzywam Ramic repo i wizji tv   a tych paserow co kase od ludzi biora za gotowe buildy powinni wykastrowac . P.s. Ramic masz racje rob im podgore jak sie da...nie beda sie k...dobrabiac na czyjejs pracy.Nie dajcie sie ludzie zfrajerzyc ( nie sponsorujcie paserow)

**Comment by tomasiek** [comment]
@ramicspa LOL. Przypominają mi się stare dobre czasy na forum Netscape/Mozilla....

**Comment by skorpion454** [comment]
Są dwie strony medalu tak zwani "BUILDERZY" którzy faktycznie biznes rozkręcili, ale są też ludzie którzy nie mają pojęcia o co w tym wszystkim chodzi i chodźby się paliło i tak będą kupować, bo nie wszyscy mają talent,  umiejętności a niekiedy i czas żeby to ogarnąć i jeśli ktoś im proponuje coś takiego to płacą i używają. Próbuje tutaj stanąć w obronie właśnie tych ludzi, 15min z youtube hmm, dla niektórych nawet i cały dzień nie wystarczy , ponieważ poprostu niektórzy nie chcą lub nie mają daru :) do takich rzeczy. Na koniec jeśli autor wtyczek nie chce żeby wtyczki były sprzedawane z buildami to jego decyzja powinna być uszanowana.

**Comment by Algirion** [comment]
Jak się tego trochę poszuka to od cholery takich ofert. Jak się okazuje to od zawsze działa. Zobaczcie nawet na Alledrogo gdzie box się sprzedaje tzw fully loaded bo to napędza sprzedaż a później sprzedawca ma końcowego użytkownika głęboko.

A teraz zapytam o to co pewnie nie jednemu przeszło przez myśl. Jeśli kupię kilka tanich boxów z Chin, zainstaluję wtyczki Ramica, zrobię skróty do wtyczek i sprzedam u siebie w robocie to stanę się wrogiem publicznym nr1 na forum czy jak? Nie bijcie ale chociaż mam jaja zadać pytanie o to, co pewnie połowa już tutaj kombinuje. 
Poszukam stosunkowo najlepszego boxa za dobre pieniądze, poswięce swój czas by to fajnie zrobić i jeśli chłopaki u mnie w robocie będą zadowolone to jestem ten zły czy nie? Wspominałem dzisiaj kilku typom o tym i oni by chcieli ale nie mają do tego głowy. Wiedzą, że wtyczki te są do pobrania i to nic nie kosztuje ale zadeklarowali się że mi sypną po 50 zyla jeśli im to ogarnę po odliczeniu wszystkich pozostałych kosztów. 
Teraz mam moralniaka z jednej strony ale w robocie są chętni mi sypnąć za ogarnięcie im tego więc jak to widzicie?

**Comment by Algirion** [comment]
@skorpion454
Właśnie o tym mówię. Dzisiaj na hali w robocie zebrała się kupka nas i tłumaczę im, że wszystko jest do ogarnięcia. Że na youtubie są filmiki jak to zrobić ale wszyscy zaproponowali mi, żebym im to zrobić i mam dylemat bo jednak jest to stosunkowo nie dużo roboty a kumple aż błagają by im w tym pomóc a i dodatkowy grosz na pampersy się przyda.

Autorzy tych buildow z tego co widziałem też informują, że i kodi i wszystkie wtyczki są za friko i można sobie to samemu ogarnąć więc ludzie są przecież świadomi ale zwyczajnie tak jest wygodniej.

**Comment by Algirion** [comment]
@ramicspa 
> od czasu do czasu jakas lewatywa przeczyszczajaca powinna skutecznie zniecheci geniuszy businessu.

Czyli nawet jeśli zrobię dla tych kilku osób taką skrzynkę to im też usuniesz wszystko? :(

**Comment by onicram** [comment]
Witam.
Drodzy zwolennicy i przeciwnicy Ramica i buildow.
Czytam od dwóch tygodni to co tutaj wypisujecie w tym temacie i w innych dotyczących sporu.

To nie jest pierwszy spór Ramica ze mu coś ukradli.
Każdy kto dostał od niego email z zaproszeniem i adresem dostępu do tego repo o tym wie.

Przez tą wojenkę miedzy Ramicem a twórcami buildow cierpią zwyczajni użytkownicy.
Wiadomo też że każdy wypowiadający się tutaj ma swoje zdanie i pogląd na to wszystko.
Ja szanuje wasze zdania i proszę Was o uszanowanie mojego.

A moje zdanie jest takie.
Skoro dostałem zaproszenie i pozwolenie na darmowe korzystanie z tego repo i znajdujących się w nich wtyczek chcę by one były bezpieczne dla mojego systemu i sprzętu.
Nie ważne w czym tego używam.
Zapewne tego samego chce każdy korzystający z tego repozytorium.

Według mnie że jest to kawał dobrej (świetnej) roboty Ramica i zaliczam to repo do najlepszych repozytoriów na świecie.
Wątpię by ktoś się ze mną nie zgodził.

@skorpion454  moim zdaniem rozwiązuje to spór o to czy repo jest prywatne czy publiczne.
Skoro Ramic sam zaprosił do korzystania z niego to nie może ono być prywatne.
Nie wspominał tam też że będzie działało tylko na oficjalnym skinie.

Tutaj kawałeczek tego emeila z zaproszenie do do korzystania z Repozytorium i wtyczek Ramica
http://screenshot.sh/oeY0Gl2ZqwIu0

Pozdrawiam Was wszystkich.

**Comment by Algirion** [comment]
Więc morał z tego taki że nie powinno być kasacji, formatów czy wyrzucania profili a wystarczy by Ramic dał okienko że nie działa z tą skórką i tyle. Byłby to koniec sporu.
Jednak krzywda została wyrządzona i tak wielu ludzi dostało od ramica po nosie i to zwykłych ludzi... 

Nie można też powiedzieć że jest ono prywatne, skoro tutaj każdy nawet bez rejestracji może wejść i je pobrać zgadza się?

**Comment by cronofx** [comment]
Prawda jest taka ze to Jego wtyczka i jezeli chce ja zabezpieczyc tak ze bedzie dzialac tylko na domyslnym skinie  no nic Ci dotego dostosuj sie albo usun repo.. jaki masz problem ja osobiscie  nie bede zadnych  buildow za pieniadze supportowal z dwoch powodow  1  zebrac wtyczki do kupy to nie to samo co ztowrzyc je wlasnorecznie od 0  , 2  Kodi to projekt open source  i skoro oni nie trzepia kasy na tym  ,To tym bardziej tworcy buildow nie powinni...a zreszta nie chce mi sie juz kontynuowac tego...kazdy ma swoj rozum

**Comment by Algirion** [comment]
Kodi samo z siebie zarabia i to dobrze na tym poprzez dotacje ale i przede wszystkim chodzi o rozgłos.
A co z buildami darmowymi takimi jak MM? Tam też były wtyczki Ramica...

**Comment by skorpion454** [comment]
zabezpieczyc tak, ale nie w taki sposob ze ludzie dane traca, ciekawe co bys ty zrobil jakby Ciebie to spotkalo, pomysl instalujesz jakis program na win10 ze swoja tapeta nie windowsowska a on ci usuwa dane bo tworca tak sobie wymyslil ze masz miec tapete tylko default windows i co w takim wypadku? A najgorsze jest to ze nie wiesz ze tak sobie tworca wymyslil. Tak sie stalo u wielu ludzi ktorzy nie mieli zielonego pojecia o konsekwencjach.
Pozdrawiam

**Comment by cronofx** [comment]
Nie wiem jade na urzadzeniach Nv Shield tv jak wiadomo sa na Andku ;-)   z reszta w Kodi mam wszedIe default theme lol

**Comment by kashkash18** [comment]
Wtyczki zostały zabezpieczone przez Ramica w taki sposób jaki uznał za stosowny. Gdyby nie "wielcy" twórcy gotowców problemu by nie było. Albo się godzicie na warunki albo nie. Nikt nie każe wam ich instalować . A to że komuś coś się wysypało , no cóż . Jak się bawisz granatem to wiedz iż może być boooom. Teraz problem mają twórcy gotowców bo spadła na nich cała gównoburza od ich klientów . I nagle od tego czasu pojawiło się tu sporo nowych ludzi .... Ciekawe

**Comment by skorpion454** [comment]
chyba nie rozumiesz sedna sprawy, nie chodzi o gotowce i o ich tworcow ale o nie swiadomych ludzi.
"Jak się bawisz granatem to wiedz iż może być boooom. " Nie kazdy wie ze bawi sie granatem :).
Pozdrawiam

**Comment by kashkash18** [comment]
Ja mam tylko nadzieję że wszystko zostanie tak jak jest. Bo jest bardzo dobrze

**Comment by onicram** [comment]
Ludu drogi, ludu kochany.
Otwórzcie sobie tego screana i przeczytajcie co w nim jest.
Ja sam się tutaj nie wprosiłem.
Zaprosił mnie sam Ramic bym korzystał z jego repo i wtyczek.
Nic nie wspominał o jakimś kodzie który będzie kasował systemy itd.
http://screenshot.sh/oeY0Gl2ZqwIu0


Ja korzystałem tylko z tego repo oraz dwóch innych polskich mr know i sd-xbmc na swojej nakładce którą zrobiłem nie na handel ale na swój własny użytek. Nie korzystałem z żadnego mm czy innego aliena.

Dzięki Bogu wywaliło mi tylko sam katalog Kodi a nie jak wielu innym system.

Ale powtórzę się  bo chyba nikt z was tego nie przeczytał.
Skoro dostałem zaproszenie i pozwolenie na darmowe korzystanie z tego repo i znajdujących się w nich wtyczek chcę by one były bezpieczne dla mojego systemu i sprzętu.
Nie ważne w czym tego używam.
Zapewne tego samego chce każdy korzystający z tego repozytorium.


kashkash18  problemy ma wielu zwyczajnych użytkowników,a nie twórcy gotowców.
A jeśli tego nie rozumiesz to być może ty masz problem z samym sobą



Według mnie jest to kawał dobrej (świetnej) roboty Ramica i zaliczam to repo do najlepszych repozytoriów na świecie.
Wątpię by ktoś się ze mną nie zgodził.

Ale na obecną chwilę przestaje z tego korzystać by nie dołączyć do grupy której wywaliło system.
Takich zwykłych użytkowników zapewne jest więcej.

Dobrej nocy wszystkim życzę

**Comment by kashkash18** [comment]
To nie używaj , i po kłopocie . Ja używam tego co Ty i problemów nie mam . Dziękuję to by było na tyle

**Comment by onicram** [comment]
A osiol dalej swoje

kashkash18 widze ze ty masz problem z glowa, jesli nie potrafisz zrozumiec co jest wyzej i tutaj napisane

Ja sam się tutaj nie wprosiłem.
Zaprosił mnie sam Ramic bym korzystał z jego repo i wtyczek.
Nic nie wspominał o jakimś kodzie który będzie kasował systemy itd.
http://screenshot.sh/oeY0Gl2ZqwIu0

**Comment by Cinek77** [comment]
Ha ha ha ha ha ha 

:D :D :D

**Comment by kashkash18** [comment]
Prosił nie prosił , zapewne kod pozostanie i dobrze

**Comment by onicram** [comment]
kashkash18 Stracą na tym tylko zwyczajni użytkownicy...

Ale co ty tam możesz wiedzieć.

**Comment by kashkash18** [comment]
Ale ja też jestem zwykłym użytkownikiem , sam poinstalowac sobie wtyczki i działa . Nie mam problemów ze znikającymi plikami czy folderami. Czyli da się tego normalnie używać

**Comment by onicram** [comment]
Ja korzystałem tylko z tego repo oraz dwóch innych polskich mr know i sd-xbmc na swojej nakładce którą zrobiłem nie na handel ale na swój własny użytek. Nie korzystałem z żadnego mm czy innego aliena.

Wiec czemu mi wywaliło katalog Kodi ???
kashkash18  wytlumacz mi to ???
Nigdy nie mialem doczynienia z platnymi nakladkami.
Zrobilem swoja na skorce xonfluence.
Jesli by wspolgrala z tym repozytorium bede mogl ja udostepnic kazdemu za free.

**Comment by kashkash18** [comment]
A ja mam wszystko postawione na czystym Kodim , do tego mam jeszcze sporo wtyczek zagranicznych . Nie mam problemów z czymkolwiek. Widać to jest klucz do tego by działało OK

**Comment by Cinek77** [comment]
kashkash18
Tylko ze na czystym Kodi ubogo to wyglada wizualnie
Chyba nie zaprzeczysz ?

**Comment by skorpion454** [comment]
@kashkash18 
Z tego co widzę to Tobie chodźby wywaliło to i tak byś pisał że jest ok ;)
Pozdrawiam

**Comment by kashkash18** [comment]
Oczywiście że tak , temat skórek też już był tu przerabiany. Ja tylko pokazałem Ci jak to może działać bez problemów.

**Comment by onicram** [comment]
kashkash18 moze pokazesz to i mnie ?

**Comment by kashkash18** [comment]
Nawet gdyby mi wywaliło to mam coś takiego jak backup ;)

**Comment by skorpion454** [comment]
Czyli jednak się boisz ;)

**Comment by kashkash18** [comment]
Onicram podaj maila to wyśle Ci linka do mojego backup Kodiego

**Comment by kashkash18** [comment]
W tych czasach to podstawa :) Przezorny zawsze ubezpieczony

**Comment by onicram** [comment]
No tak ubezpieczonym trzeba byc, nawet od statkow powietrznych :)

Kashkask18 
onicram1977@o2.pl

**Comment by kashkash18** [comment]
Obraz pod Windę czy Andka ??

**Comment by onicram** [comment]
Pod Windowsa.
Antka dopiero mam w planach :)

**Comment by kashkash18** [comment]
Poszło , przywróć na czystym Kodim 16.1

**Comment by onicram** [comment]
Dzieki.
Pobieram i zaraz sprawdze :)

**Comment by kashkash18** [comment]
Daj znać jak ściągniesz to zlikwiduje łącze.

**Comment by onicram** [comment]
Pobralo sie.

**Comment by kashkash18** [comment]
To jeszcze tylko daj znać jak przywrocisz

**Comment by onicram** [comment]
Przywrócone.
Prawie wszystkie te same dodatki co i u mnie.
Nie obraź się, ale to nie moja bajka.
Zbyt prosto i mało kolorowo jak dla mnie.
Ale jak to mówią jak się nie ma co się lubi, to się lubi co się ma :)
Ważne by chodziło.
Dobrej nocy.

**Comment by Algirion** [comment]
A ja w tym zamęcie wziąłem starego kompa. Postawiłem tam win10. Zainstalowałem darmowe MM, zainstalowałem repo, do tego livepolishtv i chodzi dobrze :)
Bawie sie bawie właczam i wyłączam a za ktoryms razem zwiecha. Chce wlączyć Kodi - brak skrótu na pulpicie, tapeta podstawowa, brak innych skrótów.
Wlaczam tą przeglądarke edge i nie chce sie włączyć. Wchodzę w panel sterowania chcę dodać nowego użytkownika i tez się nie da, okno tylko mrygnie. Restart kompa kilka razy i nic, przywrócenie systemu wyłączyłem bo dysk mały i się bałem że z win10 się zatka... Bida! Windows10 uwalony! Gratulacje autorowi repozytorium. Jeżeli kogoś to spotkało na systemie ktory uzywa na codzien to juz rozumiem wkurw.

**Comment by tomasiek** [comment]
To taki lekki offtopic. Ostatnio u znajomego (65+, komp do Onetu i do radia, nic więcej), też wywaliło profil windowsa 10. Po aktualizacji, normalnej, od MS. Oczywiście wszelkie dane na innej partycji, dodatkowy profil admina był stworzony, więc jakoś poszło. MS na swoim supporcie tłumaczył że nie wgrały się wszystkie łatki, a system i tak postanowił że je wgra.

**Comment by ramicspa** [comment]
jak juz kazdy wyrazil swoja opinie to moze zamkniemy temat bo i tak sie do niczego nie dojdzie.
Alien i inni geniusze businessu przestana wykradac wtyczki nimi handlowac. 
Fakt ze jest dostepne publiczne i nie wymaga hasla nie zmienia faktu ze zawartosc jest na uzytek prywatny. Jak sie komus cos tu niepodoba to nikt nie nikogo nie zmusza by tego uzywac.
