### ISSUE TITLE
Wypowiedz do sporu

### ISSUE THREAD

**Issue by onicram** [ramicspa/kodi#144]
Witam.
Drodzy zwolennicy i przeciwnicy Ramica i buildow.
Czytam od dwóch tygodni to co tutaj wypisujecie w tym temacie i w innych dotyczących sporu.

To nie jest pierwszy spór Ramica ze mu coś ukradli.
Każdy kto dostał od niego email z zaproszeniem i adresem dostępu do tego repo o tym wie.

Przez tą wojenkę miedzy Ramicem a twórcami buildow cierpią zwyczajni użytkownicy.
Wiadomo też że każdy wypowiadający się tutaj ma swoje zdanie i pogląd na to wszystko.
Ja szanuje wasze zdania i proszę Was o uszanowanie mojego.

A moje zdanie jest takie.
Skoro dostałem zaproszenie i pozwolenie na darmowe korzystanie z tego repo i znajdujących się w nich wtyczek chcę by one były bezpieczne dla mojego systemu i sprzętu.
Nie ważne w czym tego używam.
Zapewne tego samego chce każdy korzystający z tego repozytorium.

Według mnie że jest to kawał dobrej (świetnej) roboty Ramica i zaliczam to repo do najlepszych repozytoriów na świecie.
Wątpię by ktoś się ze mną nie zgodził.

@skorpion454  moim zdaniem rozwiązuje to spór o to czy repo jest prywatne czy publiczne.
Skoro Ramic sam zaprosił do korzystania z niego to nie może ono być prywatne.
Nie wspominał tam też że będzie działało tylko na oficjalnym skinie.

Tutaj kawałeczek tego emeila z zaproszenie do do korzystania z Repozytorium i wtyczek Ramica
http://screenshot.sh/oeY0Gl2ZqwIu0

Pozdrawiam Was wszystkich.

**Comment by Swir** [comment]
jak dla mnie Ramic chciał dać nauczkę co pobierali kasę za jego projekt... wcale mu się nie dziwię  chciał po dobroci  nic nie dało .....  więc pokazał swoją siłę i całkowicie go popieram!  jak dla mnie Ramic robi dobrą robotę i ludzie powinni ją uszanować..

**Comment by skorpion454** [comment]
No dał nauczkę ale nie im tylko użytkownikom tych właśnie buildow a nie samym builderom, no ale cóż zrobic

**Comment by Swir** [comment]
prosił o ich skasowanie...  ale każdy miał wywaloną lachę  na niego dlatego  wcale mu się nie dziwię

**Comment by skorpion454** [comment]
Nie wieże ze myślisz ze każdy kto kupił i używał build z tymi  wtyczkami wiedział o tym ze ma je usunąć. Nie ma co już i tak po sprawie

**Comment by Cinek77** [comment]
Panowie walkujecie znow to samo. Te wypowiedzi juz sa znane, a wy sie powtarzacie.
Odniescie sie do wypowiedzi onicrama.
Do zaproszenia przez ramica do korzystania z repo
Zerknijcie na screana
http://screenshot.sh/oeY0Gl2ZqwIu0

**Comment by skorpion454** [comment]
Odpowiedziałem na wszystko ;)

**Comment by Cinek77** [comment]
Nie widze tego. Chodzi o odniesienie sie do tego czy repo jest prywatne czy publiczne.
Ja uwazam tak jak onicram.
Skoro Ramic sam zaprosil sporo osob do uzytkowania to nie moze byc ono prywatnym.

onicram dobry wpis.
Tylko licz sie z tym ze tutaj raczej nikt z tym co napisales sie nie zgodzi.
Zgadzam sie tez ze przez ta wojenke cierpia zwyczajni uzytkownicy.

Na tym mkoncze moje wypowiedzi

**Comment by skorpion454** [comment]
Wedlug mnie jezeli jest udospnione publicznie to jest publiczne, druga sprawa jak juz pisalem wczesnie nawet jesli chcial cos z tym zrobic to jest wiele innych mozliwosci a nie  usuwanie user folder z systemu.

**Comment by vTneilA** [comment]
Panowie wypowiem sie jako autor AlienTV.. 

podzielam zdanie ramica chodz wczesniej tego nie robilem.. Jesli nie chce zeby jego wtyczki byly w bulidach ja to uszanyje i nie bedzie tych wtyczek w AlienTV i zreszta tak juz jest od jakiegos dobrego miesiaca.. Z tym ze ramic mial usunac kod ktory powodowal wywalanie calego profilu.. jak widac nie zrobil tego lub mu sie nie pali.. 

cala ta sprawa zaczyna a w sumie od samego poczatku jest smieszna i zdecydowanie niepotrzebna.. Wiele z was oraz uzytkownikow ramic repo czy nawet kodi uwaza ze osoby ktore robia bulidy bogaca sie na tym i jezdza conajmniej BMW 7 ;D otoz nie.. trzeba ladnie tez odprowadzic od tego co sie dostanie podatek 40% wiec z 5 euro zostaje naprawden nie wiele.. 

aha i odwieczne pytanie dlaczego bulidy sa platne? 

wlasnie dlatego ze zawsze jakis polak sie znajdzie ktory bedzie chcial sprzedac czyjas prace.. I juz to pisalem ramicowi wczesniej prywatnie i na forum chyba tez.. 

AlienTV na poczatku tamtego roku byl darnowy przez 2 miesiace.. Pozniej zaczely naplywac do mnie informacje ze osoby trzecie sprzedaja bulid a raczej instaluja go odpladnie za 20-40 funtow.. Wiec innym slowy poswiacaja 5 min na instalacje i kasuja dobra kase. . 

-nie prowadza grupy 
-nie udzielaja pomocy
-nie robia aktualizacji
etc...

Wiele osob potrafi instalowac wtyczki dodawac skroty tapety nawet szukac jakis list i ogarnia to kodi calkiem nie zle a przedewszystkim ma na to czas.. 

Inne osoby jak np moja zona nie ogarniaja tego wcale.. i nawet nie wiedza co zrobic jak wyskakuje okno przy odtwarzaniu filmu openload.co/pair :D i ogarniac nie beda...!!  dlatego pobieraja bulid.. a placi sie za niego zeby taka osoba ktora go sprzedaje dalej musiala tez za niego zaplacic.. bo dlaczego ktos ma sie bogacic na mojej pracy.. 

I jest to przykre ale nie da sie tego obejsc.. ja nie potrafie i ramic tez nie potrafi obejsc tego zeby jego wtyczki nie byly sprzedawane .. bo mozna robic bulid na podstawowej skorze przy uzyciu super favorites.. bedzie to biedny bo biedny ale tez prosty bulid a o to chyba tez chodzi.. 

dodam jeszcze tylko ze bulidy byly przed ramic repo i beda jak juz tego repo nie bedzie.. :) 

a dzialanie na szkode uzytkownika z wywaleniem profilu nie jest profesionalne a raczej zalosne i nie na miejscu.. jak ktos wczesniej wspomnial mozna to zrobic w inny sposob mniej szkodlywy.. ale ramic chce "LET HAVE SOME FUN"

ps
cdax i serialosy dzialaja.. ale niestety nie w tym repo.. :)

WALKA Z WIATRAKAMI.. :D

**Comment by Algirion** [comment]
No i chyba coś w tym jest i każdy kto ma własny rozum potrafi już lub chociaż się domyśla kto tu przegiął. W bildach wtyczek nie ma od dłuższego czasu ale ciągle pojawiają się wpisy że komuś coś wywaliło a ramic ma to w głębokim poważaniu. Ludzie sami doinstalowują te wtyczki i ramic ich karze za to więc lepiej albo niech zdejmie to pseudo zabezpieczenie albo niech wywali repo z github i niech ono faktycznie będzie prywatne.
@vTneilA piszesz ze mozna zrobić taki byle jaki bild i jak widać w USA ma to miejsce i bokiem ich obchodzi to wywalanie profili windows czy katalogów kodi.

**Comment by ramicspa** [comment]
@vTneilA 
jak juz sie wyzaliles to zamykam temat. I przypominam, nie handluj wtyczkami z tego repo.
