### ISSUE TITLE
cda.pl, katalog root, foldery użytkowników

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#145]
1. We wtyczce cda jest tajemniczy folder root... Ktoś coś? Na jakiej zasadzie wpadają tam filmy?
2. Czy jest możliwość żeby wyswietlał się folder (z zawartością oczywiscie) danego użytkownika np. Majtek2
Możnaby wtedy łatwiej obserwować to, co nas interesuje.

**Comment by ramicspa** [comment]
1. w rootcie sa wybrane linki ze stronki. 
2. najepiej sie zalogowac przez wtyczke na swoje konto - i sa obserwowani uzytkownicy

**Comment by tomasiek** [comment]
1. no to część nie działa :( Katalogi z gwiezdnymi wojnami np są niepełne.
2. o - fakt - nigdy tam nie zaglądałem :)
dzięki..
