### ISSUE TITLE
Kasowanie tematów jest śmieszne

### ISSUE THREAD

**Issue by marcintomanek** [ramicspa/kodi#147]
Kasowanie tematów nie pomoże w odpowiedzialności prawnej Ramic.....Pozdrawiam

**Comment by marcintomanek** [comment]
Kasuj, a ja zakładam nowe.....pasuje?

**Comment by ramicspa** [comment]
i tak to jest jak sie cos robi ale nie wie co ... 
tutaj masz swoj temat https://github.com/ramicspa/kodi/issues/133
nikt ci go nie skasowal, wiec sobie tam pisz, albo wydrukuj i powies na scianie.

**Comment by cronofx** [comment]
czwieku Polsat i Trudne sprawy sa dla Ciebie .. szkoda ze bana nie moge Ci dac ,bo Tylko K...a gmaila mi zasmiecasz...
