### ISSUE TITLE
Dotacje na AlienTV i MM legalne w UE

### ISSUE THREAD

**Issue by marcintomanek** [ramicspa/kodi#148]
Opinia prawnika.......konsultacja 10/01/2017  W Polsce osoba dotowana musi załozyć fundację, na którą są wpłacane pieniądze dotowane przez ludzi ( np. Owsiak) . W innmych krajacj UE takich wymagań nie ma, można dobrolonie dotować ludzi np. w Iralndii, bedąc członkiem UE. Dlatego i Alien i MM działa legalnie a Ramic złamał prawo stosując nielegalny kod i zaingerował w komputery ludzi, którzy nie byli świadomi, że po instalacji jego repo zostaną usuniete dane z komputera.

**Comment by cronofx** [comment]
Jak narazie to tylko Ty masz problem,zeby nie bylo.Ramic Repo tez mam na pc z win10 x64

**Comment by marcintomanek** [comment]
nie....posty zostały wykasowane, bo ?

**Comment by marcintomanek** [comment]
zniszył mi komputer.....i to sie bedzie ciągło

**Comment by marcintomanek** [comment]
spokojnie, spokojnie zobaczymy dalej.pozdrawiam cronofx. Widocznie tylko ja mam odwagę
