### ISSUE TITLE
Wizja.tv

### ISSUE THREAD

**Issue by MarcinM23** [ramicspa/kodi#149]
Hej tam. Uwielbiam tą wtyczkę. Najbardziej używam wizja.tv No ale zawszę dostaję informacje że brak jest premium i mam tylko 3 godziny oglądania. Ciekawy jestem jak to zmienić? Czy muszę wykupić Premium na stronie wizja.tv? Jak tak to gdzie wtedy mogę wpisać dane do logowanie do premium wizja.tv?

Jest może inny program który ma jeszcze więcej kanałów telewizyjnych?

**Comment by cronofx** [comment]
1.Tak premium musisz wykupic na stronie wizja.tv.
2 powinienes moc wpisac login i chaslo w ustawieniach wtyczki.3 Inne strony z polska tv  to  goldvod.tv i weeb.tv aczkolwiek najlepiej chodzi wizja

**Comment by cronofx** [comment]
Jednak nie ma mozliwosci  narazie do Wizji.tv ja uzywam mrknow.tv  tam dodatek do wizji ma mozliwosc wpisania loginu i chasla

**Comment by waldi22** [comment]
Też używam wizji tv od pół roku na wtyczce mrknow premium . Faktycznie premium chodzi stabilnie , bez problemu sporadycznie jakiś lekki delikatny bufor . Wszystkie kanały idą  w SD ale jakość jest bardzo dobra . Natomiast problemem jest rosnąca cena premium w lipcu 2016 90 dni premium kosztowało 39 pln , w tej chwili 90 dni premium to już 69 pln . To już że tak powiem  zaczyna robić się trochę  drogo jak na internetową tv , poza tym wszystko ok .Lecz jeżeli komuś bardzo zależy można wykupić i bez problema oglądać 24h/dobę ..
