### ISSUE TITLE
seansik.nl

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#15]
hyba jeszcze strona nie skonczona. duzo zeczy sie nie odpala w ogole

**Comment by ramicspa** [comment]
hmm to raczej problem urlresolver'a ... jak sie nie poprawi niebawem to zrobie jakiegos pathca

**Comment by xxcriticxx** [comment]
tak vshare urlresolver dead openload dziala

![capture](https://cloud.githubusercontent.com/assets/15007183/17809070/1001b9f0-65e2-11e6-84d5-626a341c878d.PNG)
