### ISSUE TITLE
cda.pl - dodatkowa opcja w menu kontekstowym filmu

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#150]
Nie wiem czy się da...
W cda mamy opcję możliwości wyboru jakości - albo automatycznie albo ręcznie. U siebie mam nastawione na 720p (większość z tego co oglądam to i tak bajki, a dzieciakom aż tak nie zależy na 1080p - wychodzę z założenia że mimo nielimiotwanego transferu i dość szybkiej sieci, nie ma sensu ciągnąć aż tylu danych - nawyk z lat młodzieńczych). Ale fajnie by było żeby pod prawym klawiszem po kliknięciu na film była możliwość ręcznego wybrania jakości. Czyli - domyślnie mam ustawione na 720. Klikam film i się otwiera od razu, bez konieczności wyboru jakości streamu. Ale chcę sobie obejrzeć np... SuperPrzyrodniczyFilm 2 w full HD żeby cieszyć się szczegółami - i teraz żeby obejrzeć go w 1080p muszę albo mieć ustawione na wybór ręczny, albo wchodzić w opcje, zmieniać ustawienia i dopiero odtwarzać. A tak, pod prawym klawiszem miałbym "Wybór jakości" lub "Zmiana jakości" i wyskakiwało by mi okienko ręcznego wyboru. Chyba jasno opisałem.

**Comment by ramicspa** [comment]
powinno dac rade

**Comment by tomasiek** [comment]
I działa jak zawsze super :)
