### ISSUE TITLE
sport :)

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#151]
Witam .
Ramic czy moglbys wyciagnac sport z tej stronki http://www.sport365.live/ jest niby wtyczka w zem tv ale ciagle maja jakies problemy . Moze dal bys rade , dzieki wielkie .

**Comment by ramicspa** [comment]
znajdziesz w livepolishtv

**Comment by Zigi1974** [comment]
nie wiem czemu ale mam to samo po paru minutach wylacza sie stream ,a moze tylko u mniemoze ktos sprawdzic dzieki

**Comment by rafciu27** [comment]
U mnie ok

**Comment by Zigi1974** [comment]
dzieki juz dziala wszystko.
