### ISSUE TITLE
cda.pl - foldery użytkowników

### ISSUE THREAD

**Issue by malcolmpl** [ramicspa/kodi#153]
Byłoby miło, gdybyś dodał do folderów użytkowników we wtyczce cda.pl tego gościa, ma całkiem ciekawą kolekcję i codziennie coś dorzuca: http://www.cda.pl/mbkasek
Ewentualnie możliwość własnoręcznej edycji też byłaby mile widziana.

**Comment by tomasiek** [comment]
Każdy może go dodać do obserwowanych w cda. Potem, po zalogowaniu się we wtyczce będzie on widoczny w "moim cda"
