### ISSUE TITLE
problem z alltube.tv

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#155]
widze ze dodali CloudFlare

naciskajac `Gatunek` , `Rok` ,`Jezyk` pod  `Filmy Filtr` wywala error

`http://paste.ubuntu.com/23804251/`

**Comment by ramicspa** [comment]
robie poprawke dla alltuba i przy gatunku/roku wszystko dziala jak trzeba. masz jeszcze ten problem ?

**Comment by xxcriticxx** [comment]
@ramicspa zaraz sprawdze

**Comment by xxcriticxx** [comment]
@ramicspa dalej jest problem z alltube.tv log: `http://paste.ubuntu.com/24002548/`

**Comment by xxcriticxx** [comment]
@tomasiek dalej mam error z simplecache i alltubem na kodi17

**Comment by tomasiek** [comment]
Robiłeś pełną aktualizacje wszystkich wtyczek?

18.02.2017 5:11 PM "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by xxcriticxx** [comment]
tak fresh install 5 min ago

**Comment by xxcriticxx** [comment]
@ramicspa jak bendzi czas to podaje nowy log `http://paste.ubuntu.com/24071464/`

**Comment by ramicspa** [comment]
dziwna sprawa bo mi nie wywala takiego bledu. uzywasz openelec?
czy na win/android tez ci wywala blad?

**Comment by xxcriticxx** [comment]
to bylo na win7 zaraz przetestuje na ubuntu i elec

**Comment by xxcriticxx** [comment]
ubuntu `http://paste.ubuntu.com/24072606/`

**Comment by xxcriticxx** [comment]
@ramicspa problem jest z common plugin cache nie startuje jak kodie sie wlancza. raczej nie idzie tego omnac az jakis fix wyjdzie.
