### ISSUE TITLE
Nasze-Kino

### ISSUE THREAD

**Issue by Janasek** [ramicspa/kodi#156]
Czy myślisz nad dodaniem opcji logowanie do Nasze-Kino
bo chyba przez to nie wyświetla pozycji.

**Comment by ramicspa** [comment]
faktycznie, trzeba byc zalogowanym by zobaczyc linki ... warto w ogole?

**Comment by Janasek** [comment]
Jeśli nie jest to dużo roboty to na pewno 

dziś chciałem to zrobić ale coś w snifrze nie mogłem sobie poradzić
z tego opisu [http://forum.kodi.tv/showthread.php?tid=99082](url)

**Comment by Janasek** [comment]
Rozwiązałem problem widzę już linki w Nasze-Kino

**Comment by ramicspa** [comment]
i znowu zmiana na stronie - juz nie trzeba byc zalogowanym - jak milo :)

**Comment by Janasek** [comment]
Chyba nadal coś nie tak u mnie nie działa nawet z loginem chyba zmienili http na https
