### ISSUE TITLE
Zalukaj

### ISSUE THREAD

**Issue by masterdzikus** [ramicspa/kodi#157]
Dlaczego nie pokazuje mi zalukaj w repo? Chcialbym zainstalowac. Sciagniecie osobnego wprowadza wiele bledow.

**Comment by ramicspa** [comment]
i wlasnie dlatego nie ma w repo zeby uniknac tych bledow. jak odpalisz na K17 to wtyczka pojawi sie w repozytorium.

**Comment by masterdzikus** [comment]
Dziekuje.
