### ISSUE TITLE
Prośba

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#16]
Wtyczka Iwatchonline - Czy jest możliwość aby dodać funkcje wpisywania tytułu po polsku aby znajdował film z angielskim odpowiednikiem ? W specto mrknow działa taka możliwość.

Wtyczka Segos - Czy jest też możliwość aby obok jakości audio przy linku pokazywała się  jakość wideo

**Comment by ramicspa** [comment]
**Iwatchonline** search engin na strone wyszukuje tylko takie tytuly jakie sa w ich bazie danych. Nie ma mozliwosci podania polskiego odpowiednika.
**Segos** dostalo sporo sporo nowych pozycji - fajny upload z twojej strony, a z mojej update wtyczki do 1.3 jest juz dostepny - Polcena pozycje sie pojawily oraz jakosc video

**Comment by Seico** [comment]
Dzięki bardzo :)
No szkoda że nie da sie z Iwatchonline

Czy samoaktualizujące się repo jest możliwe , bo cały czas muszę ręcznie aktualizować :)

**Comment by ramicspa** [comment]
repo kodi aktualizuje sie raz na dobe albo przy kazdym wlaczeniu kodi. pewnie w wersji 17 dodaja mozliwosc ustawienia.

jest mozliwosc dodania info z filmweba ... przy nastepnym update.

**Comment by Seico** [comment]
Jest na stronie segos.es w informacjach o filmie

**Comment by xxcriticxx** [comment]
+1 do auto update wtyczki/repo

**Comment by ramicspa** [comment]
informacje sa, ale trzeba otworzyc kolejna strone - a to moze znacznie wydluzyc czas ladowania listy.
Warto byloby troche zmienic format tej strony by te informacje o filmie byly jednej stronie.
W kazdym razie jest update wtyczki - info opcjonalne.

**Comment by Seico** [comment]
To nie moja strona , więc ja niczego nie zmienie , jak się pokaże właściciel na czacie to mu to zasugeruje, dzięki za info w pluginie :)

**Comment by Seico** [comment]
Stronka z info o filmie poprawiona , jest razem z filmem na jednej stronie(według twojej sugesti) , teraz mozesz poprawić  plugin

**Comment by Seico** [comment]
Dzięki za update , mały mankament , w filmach i bajkach pobiera wszystko ok , ale w ich polecanych już nie pobiera , mozesz to naprawić ?:)

**Comment by ramicspa** [comment]
zmiana na stronie nie jest do konca tym o co mi chodzilo. szybkosc wczytywania info o mediach wcale sie nie zwiekszyla. Polecan filmy maja ok 400 pozycji: segos.es/recomend_list.php - w tym wlasnie miejscu wszystkie info powinno byc zawarte jak jest np na tej (www.iwatchonline.cr/movies). Opisy filmow sa w podstronach (segos.es/filmy/view.php?id=+id) i ich otwieranie zajmuje duzo czasu bo trzeba na kazda zajrzec ... by wyciagnac info.
sprawdzam teraz rozwiazanie co mogloby znaczaco przyspieszyc ten proces.
