### ISSUE TITLE
CinemaHd - android, kodi 17 - częściowo nie działa...

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#160]
Na andku na kodi 17 RC 3 nie działają filmy w CinemaHD - filmy (nie listuje filmów):
`14:43:10.173 T:18446744072371292960  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23
14:45:04.144 T:18446744072290228864  NOTICE: Previous line repeats 1 times.
14:45:04.144 T:18446744072290228864   ERROR: GetDirectory - Error getting plugin://plugin.video.CinemaHD/?ex_link=.&foldername=Filmy%20HD&mode=walk&xfile=https%3A%2F%2Fdrive.google.com%2Fuc%3Fexport%3Ddownload%26id%3D0BxBgVaEbySmuVW0zblJpaE92VEU
14:45:04.147 T:18446744072290228864   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.CinemaHD/?ex_link=.&foldername=Filmy%20HD&mode=walk&xfile=https%3A%2F%2Fdrive.google.com%2Fuc%3Fexport%3Ddownload%26id%3D0BxBgVaEbySmuVW0zblJpaE92VEU) failed
14:45:08.430 T:18446744072290228864   ERROR: GetDirectory - Error getting plugin://plugin.video.CinemaHD/
14:45:08.433 T:18446744072290228864   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.CinemaHD/) failed
14:45:11.739 T:18446744072365836296  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23`

Na linuxie działa.
 Działają bajki, hdtv, serie hd2, seriale, serie hd 3+

**Comment by Seico** [comment]
U mnie wszystko na androidzie kodi 17 RC 3 jest ok , poszła wczoraj aktualizacja , zainstalowałeś ją ?

**Comment by tomasiek** [comment]
No właśnie po niej mi nie działa... Myślałem że to na routerze Adblock
blokuje, ale w tej samej sieci na linuksie działa.

17.01.2017 3:38 PM "Seico" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
Odinstalowałem i na nowo zainstalowałem.... Troszkę długo to trwało ale
poszło

17.01.2017 3:53 PM "Tomasz Woś" <tomasz.wos@gmail.com> napisał(a):

**Comment by Seico** [comment]
To może odinstaluj wtyczkę i zainstaluj ponownie , u mnie jest wszystko ok
