### ISSUE TITLE
Propozycja ugody

### ISSUE THREAD

**Issue by marcintomanek** [ramicspa/kodi#162]
Mam propozycję ugody miedzy Ramiciem , Alienem i MM. Jeżeli jesteście zainteresowani to piszcie.
Pozdrawiam. Marcin

**Comment by tomasiek** [comment]
Ale ugoda już chyba jest. Wtyczkę ramica nie ma w ich buildach...

18.01.2017 11:06 PM "marcintomanek" <notifications@github.com> napisał(a):

**Comment by cronofx** [comment]
I rownie dobrze mozna zamknac ten temat :-)
