### ISSUE TITLE
CinemaHd brak filmow

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#163]
witam , brak filmow w CinemaHd , odinstalowalem i na nowo zainstalowalem wtyczke i jest to samo , bajki ,seriale ok . To sama na win 10 i andek.

**Comment by ramicspa** [comment]
Kodi 17RC ma problem z ladowaniem duzej listy wiec go nie uzywaj.

**Comment by tomasiek** [comment]
hehe... a ja po tym: https://github.com/ramicspa/kodi/issues/124#issuecomment-269018853 przerzuciłem się na kodi 17rc... które śmiga aż miło... tylko na cinemahd jest problem.
@ramicspa czy wiesz coś czy będzie to naprawione w finalnej? Jeśli nie, to chyba trzeba będzie pomyśleć o jakimś "podziale" w cinemahd - np. takim: https://github.com/ramicspa/kodi/issues/104#issuecomment-273275041
ps. czasem pomaga kliknięcie ok na pilocie, jak już się pokaże "pusta lista" i lista się objawia...

**Comment by Zigi1974** [comment]
tak tylko ja uzywam 16.1 :)
