### ISSUE TITLE
Troszkę więcej kultury... nowy serwis?

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#164]
Dla rozluźnienia dość spiętej atmosfery.... proponuję nowy serwis...
ninateka.pl
Teatry telewizji, dużo polskiej klasyki, ostatnio polska sci-fi, troszkę dokumentu, troszkę koncertów.... Ciężko mi powiedzieć czy jest to gdzieś indziej dostępne... pewnie tak...

**Comment by tomasiek** [comment]
Super. Dzięki.

**Comment by frijerz** [comment]
Jestem za! A nawet dodalbym jeszcze jeden wyjatkowy serwis, w jakims stopniu nawiazujacy do ninateki: http://www.film-milicyjny.klubmord.com/klasyka-filmow-milicyjnych/
