### ISSUE TITLE
Czytać ze zrozumieniem..... coś chyba nie tak z wami

### ISSUE THREAD

**Issue by marcintomanek** [ramicspa/kodi#165]
Pierwszy komp, który wywaliło był mojego ojce. Była na darmowym MM. Sprawa poszła się walić, byłem wkurwiony i chciałem to wszystko prawnie załatwić. Udało mi się odzyskać dane z kompa mojego ojca i sprawę odpuściłem, ale na Policji byłem i swoje wiem. Tworzę swój bulid dla rodziny i moich znajomych i nie jestem neptykiem, tak jak niektórzy chcieli mi wmówić, że jestem sam zagrożeniem dla siebie i instaluje co mi popadnie. Mój bulid ma 1,4  pojemniości i nie ma tam nic niepotrzebnego, dane w trybie special ( o ile wiecie o co chodzi ). Teraz testuję Ramica i nic co wy ty wygadujecie nie zgadza się z rzeczywistością. Jesteście jedną kilką i nie wiem co macie za interes w tym co robicie, ale jest to droga do nikąd. Jeszcze raz powtarzam: nie mam Aliena, nie mam MM, Jestem obiektywny i dalej będę Was testować, aby nie wciskać ludzom kitu......Pozdrawiam

**Comment by marcintomanek** [comment]
Ramic może tematy zamykać. A ja otwierać Githab stanie się dla niego koszmarem

**Comment by rafciu27** [comment]
Jeszcze jakby ktoś się tym przejmował to może miałoby sens to co robisz. Ale wszyscy mają to w dupie.

**Comment by tomasiek** [comment]
Marcin, fajny chłopak ze Śląska jesteś, ja też zresztą, więc wytłumacz mi
kilka rzeczy.
1. Wywaliło ci system, to wiemy, przyznaliśmy w końcu rację że w pewnych
konfiguracjach może to się dziać, i że winny jest kod w kilku dodatkach
ramica. To po co ciągle ich używasz? Sparzyłeś się raz... I na siłę chcesz
po raz kolejny się sparzyć.
2. Napisałeś swoje wtyczki w 15 minut (to twoje słowa), więc po co dalej
używasz tych ramica?
3. Nie używasz mm ani aliena. Ok. Na części wtyczek jest juz komunikat, że
konfiguracja taka jest be i należy wyłączyć kodi. Ma się na to  2 minuty.
Ale nie jest to jeszcze we wszystkich wtyczkach. Z tego co widzę ramic
dodaje to systematycznie podczas aktualizacji do kolejnych wtyczek. Możliwe
też że używasz innego dodatku/wizarda który jest na czarnej liście Ramica.
Z tego co kojarzę jest tam 1x22, gladiator, i tvpis czy coś takiego...
4. Czy naprawdę sądzisz że wszyscy tutaj założyli spisek po to żeby kasować
ludziom, a zwłaszcza tobie, dane z kompa? Takie "kod-i" przeciwko
Marcinowi?. Michał to Mateusz K., Zigi to Zbigniew S., Cronox to Ryszard P.
a ja to Tomasz L.? Nie. Wiele osób korzysta z tego repo i tylko dwie
przyszły na githubie powiedzieć że padły jego ofiarą... Reszta nie ma z nim
problemu...
Ramic odwala kupę dobrej roboty z tymi wtyczkami i sam o tym wiesz bo tylko
dlatego chcesz ich w swoim buldzie używać. Porobił blokady. Już o tym
mówiliśmy... Jego repo, jego kod, jego zasady. Komu nie pasuje niech nie
używa.
5. Skoro tworzysz swego builda i coś ci na nim nie działa to proponuję
żebyś zaczerpnął świeżego powietrza (wiem, wiem że na Śląsku ostatnio z tym
ciężko), potem rzetelnie opisał swój problem. Podstawową konfigurację,
błędy jakie się pokazują w logach, wtyczki i ustawienia jakie masz. Wtedy,
jestem tego pewien, że jeśli odpuścisz sobie bluzgi, wyzywanie od c.p
ch..ów, na pewno ktoś ci pomoże. Może nawet sam ramic. Ale mając takie
podejście jak teraz bardziej widzę że większość doda cię do blokowanych
użytkowników.

Jak dla mnie do czasu aż nie opuścisz emocji i nie zaczniesz mówić
konkretnie koniec tematu. Żeby móc pomóc komuś, ten ktoś musi chcieć tej
pomocy. Eot


20.01.2017 11:31 PM "marcintomanek" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
Napisałem dość długi komentarz, tłumacząc to i owo... Ale go usunąłem bo Rafał ma rację. Nie karmy go, sam zniknie.

**Comment by Zigi1974** [comment]
marcintomanek@ 
tutaj masz link
https://pl.wikipedia.org/wiki/Zaburzenia_afektywne_dwubiegunowe
 poczytaj moze cos Tobie sie przyda a jak nie to po prostu nie pomozemy , pozdrawiam

**Comment by marcintomanek** [comment]
Dzięki, moja żona jest pielegniarką, chyba by coś widziała. tomasiek ma rację wystarczy pogadać. Ja nie jestem osobą, która wszystkich obraża. Wzieło się to na początku, jak byłem sfrustrowany. Wszydkich Was przepraszam za moje słownictwo i naprawdę chcę pogadać co się dzieje....sorry, że tu się dostałem, ale to dzieki temu, że przez ramica miałem problemy.....Wierzcie, ja naprawdę nie jestem hujem......tylko człoweikiem, który przez te repo niał wiele robory

**Comment by marcintomanek** [comment]
Wszyskich Was przepraszam i każdego z osoba. Ale dalej na miom wizardzie wywala wtyczki ramica. to jest czysty bulid i nie ma żadnych info o wyłaczeniu. Jestem na linuxie debianie. Pozdrawiam Was chłopcy i jeszcze raz przeprzaszam za moje pierwsze posty

**Comment by marcintomanek** [comment]
Zigi1974, Ciebie też  przepraszam, Spoko jesteś, ale zaburzenia afektywne? trochę nie na miejscu. Znam tę chorobę, bo moja żona pracuje z tkimi. Zigi pozdro
