### ISSUE TITLE
żle wróżyłem temu repo?

### ISSUE THREAD

**Issue by marcintomanek** [ramicspa/kodi#166]
Aktualizacja MR idzie w dobrym kierunku, za chwilę repo Ramic nie będzie niało co oferować, albo zmieni swój stosunek do wizardów, albo padnie......dalej mnie gnoicie?

**Comment by marcintomanek** [comment]
po aktualizacji MRK już nie ma wiele do pokazania

**Comment by marcintomanek** [comment]
dlaczego oni nie robią takich jaj jak ramic i istnieją wiele lat przed ramiciem?

**Comment by adame111** [comment]
nie rozumiem, co ty chcesz udowodnić?

**Comment by frijerz** [comment]
Nic pewnie, gada sam ze sobą :)

**Comment by Cerber2000** [comment]
Udostępnij za darmo swoje chętnie przetestuje 

Podaj link

**Comment by tomasiek** [comment]
DNFTT.

**Comment by Swir** [comment]
a ten znow swoje...uczepil sie jak rzep psiego ogona ....
