### ISSUE TITLE
segos i bajki

### ISSUE THREAD

**Issue by vajha** [ramicspa/kodi#167]
Witam, od pewnego czasu nie działają obie wtyczki. Nie ładują zawartości. Czy zostanie to naprawione?

**Comment by ramicspa** [comment]
Dzieki za info. dawno tam nie zagladalem. Niebawem bedzie to poprawione

**Comment by tomasiek** [comment]
Bajki to już od jakiegoś czasu nie działają poprawnie - raz po raz coś działa, ale nie wszystko - dobrym zamiennikiem okazuje się (przynajmniej dla mnie) cinemahd i dailymotion

**Comment by ramicspa** [comment]
jak admin wprowadza zmiany na stronie to parser sie gubi i nie moze nic znalesc. co jakis czas wiec potrzebna jest poprawka.

**Comment by DarDo1** [comment]
@vajha uprzedziłeś mnie właśnie siadałem dać info, że nie działa :-)
