### ISSUE TITLE
Problem z odtwarzaniem niektórych pozycji na Alltube

### ISSUE THREAD

**Issue by frankenfreez** [ramicspa/kodi#168]
Problem nie dotyczy wszystkich pozycji i wystąpił wczoraj. Nie działają wszystkie linki ze streamin, openload i vidzi ale i niektore z cba. Te same pozycje na tym samym urządzeniu  w przeglądarce działają bez problemu. System Lenovo tab2 A5.1.1 kodi 16.1 plugin 1.13 .

pytanie czy ktoś zauważył podobny probem ? 

postaram się załączyć loga jak się tylko go doszukam.

**Comment by frankenfreez** [comment]
log z akcji - próba odtworzenia niektórych pozycji z piewszej strony nowości filmowych. 

http://paste.ubuntu.com/23869523/

**Comment by Cerber2000** [comment]
U mnie też są problemy 

Zabezpieczyli filmy dodatkowym mechanizmem http://alltube.tv/jsverify.js

Ktoś znalazł rozwiązanie 

https://gitlab.com/iptvplayer-for-e2/iptvplayer-for-e2/commit/7cc90471eab3ea58f710d477a5189e650b5ae6e0


Czekam na Ramica aż aktualizuje wtyczkę

**Comment by frankenfreez** [comment]
thx Cerber2K 
..ciekawe czemu wybiórczo - część linków działa normalnie.

**Comment by frankenfreez** [comment]
..cba po aktualizacji przestało działać ... potrzebny log?

**Comment by ramicspa** [comment]
aktualizowalem wtyczke ... ale tego problemu nie znalazlem ... jak pojawi sie jakas pozycja co sie nie odtwarza to dajcie namiar
