### ISSUE TITLE
telewizja-live.com  znów nie działa

### ISSUE THREAD

**Issue by eko5** [ramicspa/kodi#169]
proszę o poprawkę wtyczki gdyż nie odtwarza strumieni , ani nie można wejść do wtyczki

**Comment by ramicspa** [comment]
przed koncem tygodnia bedzie update wtyczki - pare serwisow wymaga poprawki
zdaje size ze tez jest problem z PVR na K17

**Comment by tomasiek** [comment]
@ramicspa na kodi 17 jest o wiele lepiej pod względem buforowania (sprawdzane na tym samym sprzęcie), na tych samych kanałach itp itd. Jest problem z odświeżaniem listy - https://github.com/ramicspa/kodi/issues/154#issuecomment-274249955

**Comment by tomasiek** [comment]
To przy okazji mały pomysł. Mamy w ustawieniach kodi-telewizja, gdzie
możemy sobie wybrać które kanały mają być aktywne a które nie. Może dałoby
się zrobić tak, żeby podczas pobierania nowej listy m3u pobierać z stamtąd
listę kanałów aktywnych i tylko je odpytywać na serwerze?

26.01.2017 1:22 PM "ramicspa" <notifications@github.com> napisał(a):

**Comment by frijerz** [comment]
Tworzenie listy powoduje błąd LivePolishTV, czy tez tak macie?

**Comment by tomasiek** [comment]
@frijerz https://github.com/ramicspa/kodi/issues/154#issuecomment-275941180
