### ISSUE TITLE
Wyszukiwanie na Alltube.tv

### ISSUE THREAD

**Issue by adio2** [ramicspa/kodi#17]
Nie działa mi wyszukiwanie na Alltube.tv. Trzeba coś dodatkowo konfigurować? Na cda.pl wyszukiwanie działa.

**Comment by ramicspa** [comment]
dzieki za info. faktycznie szukanie sie popsulo. niebawem bedzie update

**Comment by ramicspa** [comment]
naprawione, wymus recznie update repozytoriow albo uruchom ponownie kodi

**Comment by adio2** [comment]
Dzięki, działa.
