### ISSUE TITLE
Ekstraklasa

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#171]
Witam. Będzie aktualizacja wtyczki przed rozpoczęciem rozgrywek? Skróty meczów ze strony estadios.pl nie działają oraz filmy ze strony Lech,tv - pojedyncze filmiki działają.

**Comment by ramicspa** [comment]
ok, dzieki za info, sprawdze co nie biega i poprawie co sie da.

**Comment by rafciu27** [comment]
Wielkie dzięki :)

**Comment by kashkash18** [comment]
FootballOrgin też padło

**Comment by rokibalboa** [comment]
Działa już ekstraklasa bo na kryptonie wczoraj o 18 wpodczas meczu Ruch-Cracowia niestety nie.

**Comment by rokibalboa** [comment]
Mogę prosić o jakąś informację czy wtyczka będzie działać czy szukać innych źródeł transmisji naszej ekstraklasy?

**Comment by kashkash18** [comment]
Wszystko działa , masz w opcjach wtyczki włączone Proxy ??

**Comment by rokibalboa** [comment]
Nie.Ma być włączone rozumiem?

**Comment by kashkash18** [comment]
Tak
