### ISSUE TITLE
LivePolishTv aktywacja PVR

### ISSUE THREAD

**Issue by locoslaw** [ramicspa/kodi#173]
Witaj Ramic, czy dałbyś rade do opcji aktywacja PVR Live TV dodać do pola dostawca serwis telewizja-live?

Byłbym wdzięczny.
Pozdrawiam.

**Comment by ramicspa** [comment]
Witam, pewnie ze da rade - poszedl update. 
Cos ostatnio te serwisy jakos wolno biegaja ...

**Comment by kashkash18** [comment]
Ramic a jest możliwość by w Sport365 zmienić czas ?? Bo pokazuje godziny rozpoczęcia transmisji o godzinę do tylu

**Comment by locoslaw** [comment]
Super! Dzięki, jesteś wielki :) Powiedz mi jeszcze proszę (bo nie umiem znaleźć) gdzie lub można znaleźć długość wyszukiwania strumienia bo kanały które nie są dostępne "uruchamia" w nieskończoność.

**Comment by locoslaw** [comment]
Jeszcze jedno pytanko. Niektóre streamy na telewizja-live wyłączają się do 3s od uruchomienia. Możesz coś z tym zrobić, czy to już jest niezależne od Ciebie?

**Comment by siwix86** [comment]
pojawia mi sie blad dodatku LivePolishTV na kodi... szukal szukal co zrobic i nie znalazl... prosze o pomoc :P
