### ISSUE TITLE
cda.pl  - kodi 16.1 błąd

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#175]
Na kodi 16.1 cda.pl nie działa

**Comment by tomasiek** [comment]
SOA - u mnie działa :) Na linuksie działa. Sprawdź czy działa przy wyłączonym pobieraniu danych z filmweb - u mnie czasem się wieszał. Patrząc na logi na routerze, to wina tkwiła po stronie długich czasów odpowiedzi z filmweb.

**Comment by ramicspa** [comment]
jak jest problem to ponownie wtyczke zainstaluj - czasem sie cos z bledem sciagnie.

**Comment by ramicspa** [comment]
powinno juz byc naprawione
