### ISSUE TITLE
LivePolishTv bug android kodi 16.1

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#176]
Witam

Wtyczka LivePolishTv wyrzuca z  telewizji po 2-3 s od uruchomienia 
W pvr iptv  da się oglądać streamy przez 2-3 minuty

Testowałem różne źródła:
telewizja-live
tele-wizja

Proszę o sprawdzenie czy to wina źródeł czy wtyczki 

Na kodi 17 android  nie można zainstalować wtyczki LivePolishTv v 2.1.6 wyskakuje błąd instalacji

**Comment by frijerz** [comment]
Nieprawda: wtyczka instaluje sie i dziala normalnie na kodi 17.

**Comment by krriss** [comment]
Mam podobny problem. Jeszcze dosłownie miesiąc temu mogłem oglądać prawie każdy program. Teraz albo wyrzuca po kilku minutach albo (w większości) programy nie działają. 

I tez moje pytanie brzmi czy to jest wina źródła czy wtyczki? 
Pozdrawiam
