### ISSUE TITLE
cda.pl od czasu aktualizacji nie dziala

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#177]
Witam! Tak jak w temacie cda przestało działać od memomentu ostatniej aktualizacji. Po odinstalowaniu nie da sie juz nawet ponownie zainstalować :(

**Comment by ramicspa** [comment]
niektore nazwy plikow mogly ulec zmianie. jak nie mozna ponownie zainstalowac to trzeba zrestartowac kodi - potem nie powinno byc problemow z ponowna instalacja

**Comment by krriss** [comment]
Dzięki za odpowiedz. Zrestartowałem kodi i udało mi sie zainstalować cda.pl lecz ponownie pokazuje ten sam error co był prędzej a wiec: cda.pl error check the log for more information

**Comment by souacz** [comment]
U mnie działa w Kodi 17 a w Kodi 16.1 nie

**Comment by krriss** [comment]
No u mnie wlasnie nie działa na na Kodi 17. Jakies jeszcze sugestie co zrobic? Dodam ze wszystkie inne addonsy od ramicspa działają bez problemu tylko cda.pl padło :( czekac na nowy update chyba juz tylko pozostało i liczyć ze wtedy na nowo ruszy

**Comment by tomasiek** [comment]
A może zerkniesz w loga kodi i go tu wkleisz? Na pewno ramic będzie miał
łatwiej...

06.02.2017 1:03 PM "krriss" <notifications@github.com> napisał(a):

**Comment by souacz** [comment]
A gdzie są przechowywane logi na Androidzie?

**Comment by tomasiek** [comment]
www.google.pl
http://kodi.wiki/view/Log_file/Advanced#Location

**Comment by souacz** [comment]
[http://pastebin.com/G1JLHhL0](url)

**Comment by krriss** [comment]
`
![image](https://cloud.githubusercontent.com/assets/23279310/22661226/89d6808a-ec9c-11e6-847b-c78563455970.jpg)
`

**Comment by krriss** [comment]
Witam! Zrobiłem zdjęcie loga: 

https://cloud.githubusercontent.com/assets/23279310/22661226/89d6808a-ec9c-11e6-847b-c78563455970.jpg

Coś wam to mówi? Dzięki

**Comment by souacz** [comment]
Zainstalowałem wersję 1.8.1, można przeglądać filmy, wyszukiwać etc. ale próba odtworzenia czegokolwiek wywala błąd.

**Comment by ramicspa** [comment]
Jest jakis problem z SPMC. pod koniec tygodnia bedzie update

**Comment by krriss** [comment]
Ok ramic czekamy na update 👍

**Comment by ramicspa** [comment]
poszedl update wtyczki - powinno juz dzialac SPMC.
tak na przyszlosc to wyczki beda testowane tylko na kodi - zadne inne forki kodiego nie beda brane pod uwage.

**Comment by krriss** [comment]
Działa!!! Dziękować Panu ;-) to były długie 2 tygodnie czekania ale warto było 👍

**Comment by ramicspa** [comment]
warto zawsze dodac wersje kodi oraz system operacyjny

**Comment by souacz** [comment]
Zaktualizowałem ale musiałem ręcznie, z zip-a bo przez repo pokazuje mi 1.8.2 jako najnowszą. I w Kodi 17 i w SPMC 16.5. Używam SPMC bo przy odtwarzaniu 1080p mam 55-60*C a w Kodi 80*C. MXQ PRO Plus

**Comment by ramicspa** [comment]
z repo lepiej aktualizaowac ... jak nie widac nowszej wersji w repo to trzeba wymusic odswierzenie (opcja dostepna z bocznego paska)

**Comment by tomasiek** [comment]
Co do spmc... To naprawdę dobry form, oficjalny niejako ze względu na developera... Działa o niebo lepiej na andku niż normalne kodi. Miejmy nadzieję że nie będzie większych problemów i twoje wtyczki będą działać na spmc...

**Comment by ramicspa** [comment]
domyslnie powinny dzialac, ale jest jakis bug w spmc przy parsowaniu kodu python

**Comment by tomasiek** [comment]
@ramicspa to może go zgłosisz koying'owi? Nikt inny go nie przedstawi tak jak ty...

**Comment by djvolt1942** [comment]
A dlaczego nie działają żadne filmy? Od kilku dni, wszystko się wczytuje ale nie ładuje żadnego filmu nawet po podłączeniu konta premium...

**Comment by ramicspa** [comment]
Dzięki za info. Nie zauważyłem. Będzie poprawka.

On Feb 25, 2017 19:39, "djvolt1942" <notifications@github.com> wrote:

A dlaczego nie działają żadne filmy? Od kilku dni, wszystko się wczytuje
ale nie ładuje żadnego filmu nawet po podłączeniu konta premium...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/177#issuecomment-282503327>, or mute
the thread

**Comment by tomasiek** [comment]
Też właśnie miałem pisać że nie działa...

25.02.2017 7:47 PM "ramicspa" <notifications@github.com> napisał(a):

> Dzięki za info. Nie zauważyłem. Będzie poprawka.
>

**Comment by djvolt1942** [comment]
Jakbyś mógł to popraw, a konto premium jest wymagane czy mozna korzystac bez konta premium i miec dostep do wszystkiego?

**Comment by ramicspa** [comment]
Poprawie za parę h jak tylko dojdę do kompa. Co do premium to nie potrzeba
mieć konta. Zasoby dostępne za darmo.

**Comment by djvolt1942** [comment]
A masz paypala? Souvenira bym podeslal :)

**Comment by ramicspa** [comment]
dzieki, wtyczki i repo sa darmowe, lepiej zrob dotacje na jakas organizacje chartytatywna.
poszedl upate wtyczki. wyglada na to ze zaczeli dodatkowo kodowac linki.
prosze pisac jak cos nie dziala bo nie mam mozliwosci sprawdzac wszystkiego.

**Comment by souacz** [comment]
wszystko już działa, dzięki @ramicspa
