### ISSUE TITLE
Buforowanie

### ISSUE THREAD

**Issue by afi21** [ramicspa/kodi#178]
Witam od kilku dni mam problem z odtworzeniem filmow. Po okolo 2 min filmu film sie zacina i nie chce sie buforowac. Net o szybkosci 100Mb/s komp tez dobry wiec w czym tkwi problem ??? na YT filmy w Full HD smigaja az milo buforuje do przodu a w Cinema HD cos sie zaczelo psuc z buforem...o co kaman???

**Comment by tomasiek** [comment]
Nie zauważyłem, chociaż to może indywidualnie zależeć od filmu. Ja z filmami z cinemahd hd robię tak, że odpalam, daje pauzę i idę zrobić herbatę... Po 5 minutach mam tyle zbuforowane że film idzie gładko.

**Comment by Janasek** [comment]
Może buffersize pomoże liczba **104857600=bits** w zależności od ramu można ustawiać buffer indywidualnie masz 4gb ramu to zrób 300/400 mb,czyli 404857600 zapisz plik jako **advancedsettings.xml** buffermode tez można podnosić nawet do 30,40 u mnie działa bez problemu na m8s,PiPO,MINIX

`<advancedsettings>
  <network>
    <buffermode>1</buffermode>
    <cachemembuffersize>52428800</cachemembuffersize>
  </network>
</advancedsettings>`
