### ISSUE TITLE
Propozycja - Sezony seriali jako foldery na odcinki

### ISSUE THREAD

**Issue by adio2** [ramicspa/kodi#18]
Można zrobić tak, aby po wybraniu serialu najpierw wyświetliła się lista dostępnych sezonów, a po kliknięciu w odpowiedni sezon dopiero odcinki z tego sezonu? Ułatwiłoby to oglądanie seriali które mają dużo sezonów, a dopiero zaczęło się je oglądać.

**Comment by adio2** [comment]
Głównie chodzi mi o wtyczkę alltube.tv

**Comment by ramicspa** [comment]
Wole miec wszystkie epizody w jednym widoku I uzyc opcji 'schowaj obejrzane'
W wersji 1.4 alltube jest opcja do grupowania epizodow po sezonach. Zrob update.

**Comment by adio2** [comment]
dzięki
