### ISSUE TITLE
A teraz coś z zupełnie innej beczki... Napisy

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#180]
Więc tak... Ramic robi najlepsze wtyczki o czym wszyscy wiemy. I dlatego podrzuce pomysł... Zrobienia wtyczki z cyklu tych które są...Ale nie działają. Wtyczki do obsługi napisów... Ale łączącej w sobie opensubtitles napisy24 i co jeszcze przyjdzie do głowy Ramicowi.
Dlaczego? Oficjalna opensubtitles raz działa raz nie. Napiprojekt, napisy24 nie działają... Zebranie tego razem było by czymś naprawdę ciekawym...
Nie mam pojęcia jak to technicznie ugryźć, ale już nie takie cuda tu widzieliśmy.

**Comment by rafciu27** [comment]
Napisy24 działają bez zarzutu, tylko trzeba się wcześniej zalogować. Co od open się nie wypowiem, ja osobiście się nie spotkałem aby nie działało, ale też używam od wielkiego dzwonu.

**Comment by tomasiek** [comment]
No u mnie na andku coś nie chcą działać. Ani jedno ani drugie. Skąd masz
ściągnięte napisy24…?

10.02.2017 11:46 PM "rafciu27" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
eh - adblock na routerze blokował....
