### ISSUE TITLE
Nie działa Tele-wizja ?

### ISSUE THREAD

**Issue by jorg35** [ramicspa/kodi#182]
Nie działa Tele-wizja w Kodi brak listy Proszę bardzo o naprawę.

**Comment by tomasiek** [comment]
Bo i strona nie działa. Na przyszłość sprawdzajmy przed zgłoszeniem błędu czy strona działa, ułatwi to pracę autorowi wtyczki.

**Comment by ramicspa** [comment]
stronka czasem strasznie wolno chodzi albo w ogole jest down. 
Niebawem bedzie update wtyczki bo wydze ze wymaga troche poprawy

**Comment by jorg35** [comment]
Strona działa tylko zmienili jej wygląd-https://images83.fotosik.pl/361/294b9966f2cde296.png
http://www.tele-wizja.com/ogolne.html

**Comment by kashkash18** [comment]
Po aktualizacji do ver. 2.1.7 na K17 Android TV wyskakuje czerwony napis Offline

**Comment by jorg35** [comment]
@ramicspa wielkie dzięki jest OK.

**Comment by kashkash18** [comment]
Dobra , dziś śmiga normalnie
