### ISSUE TITLE
efilmy.online

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#183]
@ramicspa niewidze tego w repo w kodi ver 16 czy dziala tylko z ver 17 kodi?

**Comment by ramicspa** [comment]
zgadza sie ... tylko k17. coraz wiecej serwisow wykorzystuje szyforowanie ktore nie jes obslugiwane w K16. coraz mniej wtyczek bedzie kompatybilnych z k16.

**Comment by xxcriticxx** [comment]
ok thx za info

**Comment by xxcriticxx** [comment]
na kodi 17 dziala super!
