### ISSUE TITLE
zalukaj.com

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#184]
plugin ver 1.2 niemoge zamontowac na kodi 17. naciskajac install nic sie nie dzieje niema zadnego blendu.

**Comment by ramicspa** [comment]
ja nie widze zadnego problemu ... ladnie sie instaluje nawet na swierzym kodim. jak nic nie wywala to i tak warto zajrzec do loga - tam zawsze jakas wskazowka bedzie.

**Comment by kashkash18** [comment]
Ja miałem ten problem gdy sklep Play zaktualizował mi Kodi. Po odinstalowaniu i ponownym postawieniu nie było problemu z instalacją

**Comment by ramicspa** [comment]
hmm ... to pewnie byla wazna aktualizacja kodi z wersji RC do finalnej  - i poszlo cos nie tak przy konvwersji wtyczke.

**Comment by kashkash18** [comment]
W moim przypadku była to aktualizacja z 16.1 na finalną 17

**Comment by tomasiek** [comment]
Czyli odpowiedź jest prosta - przy dużym skoku wersji odinstalować/usunąć profil kodi i na nowo stawiać... Może ramic dodałbyś jakis mechanizm kasujący profil przy aktualizacji :) LOL>?

**Comment by ramicspa** [comment]
sa dostepne wtyczki co robia takie rzeczy np: https://www.tvaddons.ag/indigo-kodi-jarvis/
dziala tez na k17

**Comment by tomasiek** [comment]
@ramicspa to był żart co do kasowania zawartości profilu :)

**Comment by ramicspa** [comment]
hehe ... nie prowokuj

**Comment by tomasiek** [comment]
@ramicspa instalacja tego indigo tylko przez fusion installer? Obawiam się instalowania różnych dziwnych rzeczy ze względu na potencjalną interakcję pomiędzy dodatkami...

**Comment by ramicspa** [comment]
z takich narzedzi to chyba tylko podglad loga z poziomu kodi wydaje sie uzyteczny  by szybko zdiagnozowac problem. - ktory zwykle przy instalacji wytczek jest brakiem zaleznosci lub blad w archiwum zip. reszta to malo uzyteczne bajery - choc czasem mozna spotkac jakies opcje o ktorych sie nie mialo pojecia ze istnieja.

**Comment by xxcriticxx** [comment]
@ramicspa bende w domu podam loga

**Comment by xxcriticxx** [comment]
log z zamontowania zalukaj `http://paste.ubuntu.com/24002668/`

**Comment by xxcriticxx** [comment]
odmontowanie i zamontowanie kodi na nowo pomoglo
