### ISSUE TITLE
Do czego ten kod?

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#187]
Witam, do czego ten kod w readme:
KOD: ASW2Q

**Comment by tomasiek** [comment]
Ramic nie trzymaj nas w niepewności... Powiedz że to kod na nieśmiertelność...

**Comment by ramicspa** [comment]
kod sie przydaje. nie wszystkim ale pewnie ktos sie znajdzie co by z niego skorzystal.

**Comment by tomasiek** [comment]
No to super... Wiem że nic nie wiem....
PS. Jak będą nagrody za kody to się piszę....

19.02.2017 8:10 AM "ramicspa" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
Ej... no zdradź o co chodzi...

**Comment by tomasiek** [comment]
Kod się zmienił a my dalej nie wiemy po co on...
