### ISSUE TITLE
filiser.tv - szukaj

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#188]
Oczywista oczywistość - brakuje funkcji szukaj. Poza tym wszystko działa (na andku 5.1+k17, na linie+k17).

**Comment by ramicspa** [comment]
thx za sprawdzenie wtyczki ... faktycznie jest tam tez opcja szukania ... pojawi sie przy updatecie

**Comment by kashkash18** [comment]
Ramic a ten kod do czegoś służy ASW2Q ??

**Comment by tomasiek** [comment]
Szukają na tym serwisie dość przyjemnie działa, więc , niecierpliwością czekam na jej dodanie.
@kashkash18 też się o to pytałem i obawiam się odpowiedzi...

**Comment by rafciu27** [comment]
Bardzo fajny serwis, wcześniej o nim nie słyszałem. Wtyczka działa jak należy, ale faktycznie brakuje tej opcji szukaj. Dobra robota 👏💪
