### ISSUE TITLE
Zapytanie

### ISSUE THREAD

**Issue by frijerz** [ramicspa/kodi#192]
Dzieki wielkie za ninateka!
Teraz zapytanie: co sie dzieje z tvn24? Nigdy to u mnie nie dzialalo, może daloby sie wskrzesic? A jesli nie to chyba usunać z repo?
No i na koniec propozycja: jest taki ciekawy - moim zdaniem - serwis z filmami "milicyjnymi", choc nie tylko. Nieduży, ale jest tam sporo ciekawych tytułów, ale tez klimat tych filmów jest niepowtarzalny. Może dałoby się zrobic wtyczkę do tego serwisu? Chodzi mi o www.film-milicyjny.klubmord.com/klasyka-filmow-milicyjnych/

**Comment by ramicspa** [comment]
ninateka tez mi sie bardzo podoba :)
co do tvn24 to wszystko smiga - a co jest jakis problem? nikt nie wspominal. bedzie i tak update bo pojawilo sie male usprawnienie.
flmy milcyjne tez dobra rzecz - bedzie wtyczka

**Comment by frijerz** [comment]
TVN24 od zawsze mi pokazuje komunikat: "Błąd dodatku TVN24", nawet nie wiem co tam jest :(  Może niech ktoś jeszcze to sprawdzi.
Cieszę się z filmów milicyjnych, nie wszystkie linki działają, ale może to się zmieni :)
Skoro jesteśmy przy polskich filmach to może warto się przyjrzeć tez stronie http://polskifilmserial.blogspot.com/ - coś dla miłośników polskiego kina :) 
A może zrobić to w jednej wtyczce, np. Polskie kino, a w nim dział: Filmy milicyjne ?

**Comment by ramicspa** [comment]
hmm to jest blog - i wiekszosc likow to youtubue a do tego wtyczki juz sa.
Dalej problem z TVN? bo u mnie nie ma zadnego bledu

**Comment by frijerz** [comment]
TVN24 teraz działa :)
No tak, na youtube jest duzo polskich filmów, jednak wiele z nich nie dziala (usuniete z powodu naruszenia praw autorskich - co dla mnie jest skandalem: placac podatki, abonament nie możemy ich ogladac, ale to inny temat)
Ale chyba nie ma wtyczki, ktora oferowalaby tylko polskie filmy? W dodatku z jakims sensownym  podzialem. Chyba ze czegos nie wiem? No i liczę na wtyczke z filmami z MOrd. Strona jest chyba nieakatywna, może warto sciagnać dostepne filmy, uaktualić i zachować je.
