### ISSUE TITLE
firstonetv.eu TELEWIZJA Prośba o dodanie 

### ISSUE THREAD

**Issue by eko5** [ramicspa/kodi#194]
Można by dodać podaną stronę do wtyczki ?? https://www.firstonetv.eu/Live/Poland

**Comment by kashkash18** [comment]
Ramic dało by się to dołączyć do LivePolishTv ??

**Comment by ramicspa** [comment]
da rade, patrzylem tam ale ...
- jest captcha
- zrodla sa kopia innych serwisow dostepnych we wtyczke

**Comment by kashkash18** [comment]
No to nie ma sensu
