### ISSUE TITLE
Serwis dla dorosłych

### ISSUE THREAD

**Issue by rokibalboa** [ramicspa/kodi#195]
Może dałoby się dodać serwis Showup.tv do repozytorium.Myślę że byłoby wielu zainteresowanych i wdzięcznych panów a może i pań.

**Comment by ramicspa** [comment]
Niby mozna by zrobic i wtyczke do tego serwisu ale ... repo powstalo bo malo bylo wtyczke ze zrodlami polskimi. Serwisow i wtyczke dla doroslych jest pelno wiec troche nie widze potrzeby dorabiac kolejny.

**Comment by frijerz** [comment]
Serwisow dla doroslych jest duzo, szczegolnie zachodnich filmow, ale trzeba przyznac, ze showup jest wyjątkowy
