### ISSUE TITLE
LivePolishTV a proxy do tvp.sport

### ISSUE THREAD

**Issue by lisek746** [ramicspa/kodi#196]
Proszę o pomoc.Czy w sport.tvp nie działa już opcja proxy?Dziś chciałem oglądnąć skoki i niestety nie dałem rady bo nie działa.Mieszkam w Anglii,a jeszcze nie tak dawno działała opcja proxy w tym serwisie.Jeśli dałbyś radę to proszę o naprawę.

**Comment by ramicspa** [comment]
wtyczka ta wykorzystuje proxy - bylo to stabilne przez dosc dlugi okres czasu - jak niedziala to znaczy ze usluga ta padla. Poszukam jakiegos nowego i bedzie aktualizacja.

**Comment by krriss** [comment]
Nie działa i to juz od okolo miesiąca ale myślałem ze jestem jedynym któremu nie działa wiec nic prędzej nie pisałem :-( 
A naprawdę super mi sie oglądało właśnie skoki czy tez piłkę nożna. Extra jakość i nigdy nie zacinało.

**Comment by lisek746** [comment]
Dzięki za szybką odpowiedź:)Fajnie jeśli się uda to naprawić bo tak jak pisał krriss usługa jest super dla tych co siedzą poza Polską.

**Comment by ramicspa** [comment]
sport.tvp powinien juz dzialac

**Comment by lisek746** [comment]
Dziękuję bardzo,działa jak cholera!Po prostu jesteś one of the best!

**Comment by lisek746** [comment]
Niestety tvp.sport znów nie działa a chciałem obejrzeć Radwańską.

**Comment by krriss** [comment]
A ja skoki i tez nie poszło niestety.
