### ISSUE TITLE
CDA.PL padło? 

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#197]
Witam jak wyżej w temacie: od 2 dni nie można odtworzyć żadnego filmu na cda.pl
Można wyszukać, wybrać jakość obrazu no i na tym sie kończy. Przy większości filmów po prostu nic sie nie dzieje a przy próbie otworzenia nie których filmów pokazuje standardowy komunikat: "please check the log..."
Ktoś ma ten sam problem?

**Comment by ramicspa** [comment]
jest juz dostapna aktualizacja wtyczki.
tak na przyszlosc jak cos padnie to nie czekaj 2 dni

**Comment by krriss** [comment]
Dzięki wielkie! 

Wysłane z iPada

Dnia 25.02.2017 o godz. 22:31 ramicspa <notifications@github.com> napisał(a):
