### ISSUE TITLE
cdapl

### ISSUE THREAD

**Issue by donald73** [ramicspa/kodi#2]
wersja 1.1 działa wersja 1.3 nie ładuje filmów można wybrać rozdzielczość a potem nic się nie dzieje

dzięki za świetną wtyczkę

**Comment by ramicspa** [comment]
Dzieki za info. nie bardzo wiem co sie stalo ale faktycznie cos jest nie
tak. Wieczorem poprawie kod.
Pozdrawiam

**Comment by donald73** [comment]
polecam się na przyszłość

**Comment by ramicspa** [comment]
Naprawione ... nowa wersja dostepna

**Comment by donald73** [comment]
jesteś wielki działa super  -(rasberry pi 2 kodi 16.0) po aktualizacji trzeba uruchomić ponownie system bo inaczej nie zadziała 
jeszcze raz dzięki jak będzie coś potrzeba służę pomocą
