### ISSUE TITLE
Openload.co przestał działać w kodi

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#20]
Nie startują filmy z openload.co , z tego co napisał mrknow , coś zmienili na stronie , możesz sprawdzić ?

**Comment by ramicspa** [comment]
zgadza sie ... cos zmienili i URLResolver sobie nie radzi. mysle ze najpozniej jutro pojawi sie update od eldorado jak sie beda chlopaki ociagac to trzeba bedzie skorzystac innych skryptow

**Comment by Seico** [comment]
mrknow.urlresolver - tam filmy z openload.co normalnie działają

**Comment by ramicspa** [comment]
wrzucilem update resolver'a - zrodla powinny juz smigac.

**Comment by Seico** [comment]
Długo nie pomogło , gołębie atakują z powrotem

**Comment by ramicspa** [comment]
hehe ale numer ... faktycznie
w takich sytuacjach docenia sie serwisy co oferuja wiele zrodel na wypadek jakby z jakims byly problemy ...
hmm a bywalo i tak ze przez pare miesiecy nic nie zmieniali i wszystko ladnie chodzilo
niebawem pojawi sie update

**Comment by Seico** [comment]
Jedna rzecz mnie zastanawia , jak się łączę w kodi poprzez ftp z openload , nigdy nie mam problemu z wystartowaniem filmu nie mówiąc już o jakiś golębiach , może w tym kierunku trzeba by było iść i skonfigurować urlresolvera
