### ISSUE TITLE
Alltube 

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#201]
Zauważyłem mały problem. Gdy wybierzemy określany gatunek filmu wyświetli nam się lista filmów, ale po przejściu na następną stronę wyświetlają się nadal te same tytuły. Mówiąc w skrócie jest dostęp tylko do pierwszej strony danego gatunku. Pozdrawiam ;)

**Comment by ramicspa** [comment]
faktycznie, bedzie poprawka
