### ISSUE TITLE
Ekstraklasa.tv problem z proxy

### ISSUE THREAD

**Issue by kamilinho1** [ramicspa/kodi#202]
Nie działają mecze na żywo w tym dodatku. To chyba wina proxy, bo po odznaczeniu tej opcji w ustawieniach i puszczeniu internetu przez jakiś dowolny vpn działa. Niestety VPNy są albo drogie albo słabe więc w ten sposób nie da się płynnie oglądać.

**Comment by rafciu27** [comment]
Potwierdzam

**Comment by rafciu27** [comment]
Jest szansa naprawić to w tym tygodniu?

**Comment by ramicspa** [comment]
zobacze co da sie zrobic

**Comment by rokibalboa** [comment]
Błąd dodatku.

**Comment by rafciu27** [comment]
Wielkie dzięki Ramic! :)

**Comment by rokibalboa** [comment]
Działa już na kodu 17 po wymuszenia aktualizacji,wielkie podziękiwania.😀👍
