### ISSUE TITLE
serialosy.pl problem 

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#205]
mam taki problem na serialosy.pl. co kolwiek otwieram jest tak jak na obrazku. nie wiem czy ktos ma jakies info jak to naprawic. setup kodi 17 na win7. 

![capture](https://cloud.githubusercontent.com/assets/15007183/23627475/ede5d16e-027e-11e7-9f15-8773c581ee62.PNG)

**Comment by ramicspa** [comment]
to problem z resolverem -  jaki host?

**Comment by xxcriticxx** [comment]
openload

**Comment by ramicspa** [comment]
uaktualnij URLResolver, zdaje sie ze ostatni numerek: 3.0.28

**Comment by xxcriticxx** [comment]
jestem na takiej ver urlresolvera czym wiecej czytam zdaje sie mi ze jest problem z script.module.requests byl jakis update do ver 2.12.4 1/16/2017.

**Comment by xxcriticxx** [comment]
kodi log `http://paste.ubuntu.com/24128310/`

**Comment by xxcriticxx** [comment]
format komputera nie pomaga dziwna sprawa

**Comment by ramicspa** [comment]
i jak ... naprawiony problem? w logu co podales widzialem ze resolver byl w starej wersji
`21:01:43.678 T:4068  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23`
format kompa chyba troche za duzo hehe

**Comment by xxcriticxx** [comment]
Nope problem jest dalej tylko na jedednej maszynie. Uptetowalem ten url resolver do najnowszej ver i nic nie pomogło. Myśle ze problem jest może z network karta ale to dopiero projekt na weekend.
