### ISSUE TITLE
Propozycja do wtyczki ekstraklasa

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#207]
Witam. Myślę, że ciekawym dodatkiem do wtyczki byłby materiały ze strony http://ekstraklasa.tv/
Jest szansa na dodanie? Pozdrawiam

**Comment by duri2** [comment]
To ja się podłączę, bo chciałem coś podobnego zaproponować. Wszystkie materiały z Ekstraklasa.tv to byłaby super opcja, ale jeśli nie, to może chociaż sam poniedziałkowy Magazyn Ekstraklasy (skoro jest np. CafeFutbol)

**Comment by kashkash18** [comment]
Ramic czy istnieje opcja by dodać http://ekstraklasa.tv/ oraz http://www.1liga.org

Było by to fajne dopełnienie do dodatku Ekstraklasa
