### ISSUE TITLE
CDA.pl - nie da się odtwarzać filmów premium

### ISSUE THREAD

**Issue by souacz** [ramicspa/kodi#209]
W 1.8.4 brak możliwości odtwarzania filmów premium mimo zalogowania i opłacenia pakietu. Po włączeniu filmu, komunikat o nieudanym odtwarzaniu pozycji. SPMC 16.5, zauważyłem dzisiaj. Na wtyczce od MrKnow działa.

**Comment by ramicspa** [comment]
na kodim nie widze zadnego problemu. jak bede mial okazje to przetestuje na spmc.

**Comment by souacz** [comment]
A na pewno odtwarzałeś film premium? Bo w dziale premium są wymieszane z darmowymi i bezpłatne działają. Wyszukaj np "krwawa Hrabina" i spróbuj odpalić. U mnie nie działa ani na Kodi 17 ani na SPMC 16.6. Na MrKnow działa. Jeszcze jedna uwaga, w Twoim dodatku w dziale premium na listach kategorii pokazuje się mniej filmów niż w MrKnow, dziwne... Np. wejdź w historyczne i tam "krwawa hrabina" nie znajdziesz a u MrKnow jest.

**Comment by ramicspa** [comment]
Zgadza się. Wtyczka z zasobow premium pokazuje tylko darmowe pozje.

**Comment by souacz** [comment]
Why ah why????

**Comment by ramicspa** [comment]
Bo taki filtr ustawiłem. Tylko darmowe pozycję. Płatne kiedyś działamy teraz chyba coś pozmieniało i padły.

**Comment by souacz** [comment]
Szkoda, no nic, trzeba będzie używać MrKnow bo tam działa.
