### ISSUE TITLE
KINO FREEDISC

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#21]
moze to?

http://freedisc.pl/seriale-online/najnowsze
http://freedisc.pl/bajki-online/najnowsze

**Comment by ramicspa** [comment]
bardzo podobne do http://vider.pl/ ... masz jakis pomysl na organizacje wtyczki - jak pogrupowac filmy? jaka jakosc itp ...?

**Comment by xxcriticxx** [comment]
zostawie to dla ciebie ty jestes specialista ja tu tylko sprzatam

**Comment by xxcriticxx** [comment]
@ramicspa jaki progres stym?

**Comment by ramicspa** [comment]
niebawem sie pojawi

**Comment by ramicspa** [comment]
wrzucilem do repo freedisc, chodzi bardzo wolno (moze teraz bo serwery sa przeciazone). Nie wiem jak tobie ale mi te linki nie dzialaja: (http://freedisc.pl/seriale-online/najnowsze oraz http://freedisc.pl/bajki-online/najnowsze) wiec przeglada sie zasoby po profilach userow.

**Comment by xxcriticxx** [comment]
faktycznie zdjeli ze strony te kino freedisco ale moze wrocic
