### ISSUE TITLE
Wizja.tv premium

### ISSUE THREAD

**Issue by farbenh** [ramicspa/kodi#211]
Witam, czy możliwe jest dodanie opcji Premium do wtyczki wizja.tv?

**Comment by rafciu27** [comment]
Jeśli Ci się śpieszy to MrKnow ma taką opcje w swojej wtyczce

**Comment by farbenh** [comment]
Nie śpieszy, chciałem tylko wiedzieć czy będzie taka opcja we wtyczce która jest w repo ramic?

**Comment by ramicspa** [comment]
tylko darmowe zrodla w livepolishtv
