### ISSUE TITLE
Cinema HD - pytanie o kod ?

### ISSUE THREAD

**Issue by zbyszek789** [ramicspa/kodi#212]
Hey , Mam problem z Cienma HD , dzialalo ok to dzisiaj a teraz pojawia sie pytanie o kod ze strony repo ?
nie widzialem tego wczesniej :(  Jakies propozycje ?;
dzieki sliczne

**Comment by xxcriticxx** [comment]
Informacja

Niektóre wtyczki z repozytorium wymagać bedą standardowych ustawień programu KODI do poprawnego działania.

KOD: ghvn

Zawartość repozytoium

**Comment by zbyszek789** [comment]
Dzięki Śliczne za pomoc - Działa

**Comment by tomasiek** [comment]
A więc tutaj ten kod się pojawia... Ale jakoś nie u mnie...

**Comment by zaqwa** [comment]
zmienił się kod ? ghvn rzestało działać :(

**Comment by tomasiek** [comment]
Tak zmienił się.
Zastosuj się do komunikatu.

28.04.2017 1:25 PM "zaqwa" <notifications@github.com> napisał(a):

**Comment by zaqwa** [comment]
juź mam: "nowa" 
:)

**Comment by danielson2014** [comment]
znowu kod nie działa.......jaki jest nowy??

**Comment by kashkash18** [comment]
Działa

**Comment by tomasiek** [comment]
Też sprawdzałem. Działa.

30.04.2017 8:28 AM "kashkash18" <notifications@github.com> napisał(a):

**Comment by flexfit1983** [comment]
Hi guys, 

Looks like they change code ghvn does not work for me , does anyone know the new one? 

Thanks

**Comment by flexfit1983** [comment]
Czesc,

KOD ghvn nie dziala , zna ktos nowy kod ? 

Dzieki

**Comment by kashkash18** [comment]
nowy

**Comment by tomasiek** [comment]
Go to the main page https://github.com/ramicspa/kodi , scroll to readme and
find "kod"

30.04.2017 11:24 AM "flexfit1983" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
Dawajmy im wędkę a nie rybę, ok?

30.04.2017 11:26 AM "kashkash18" <notifications@github.com> napisał(a):

**Comment by flexfit1983** [comment]
Czesc , 

Przy otwieraniu wiekszosci filmow w Cinema HD wyskakuje mi w prawym rogu komunikat "B Wiecej informacji na ten temat znajdziesz w pliku dziennika diagnostycznego" moze ktos napisac jak rozwiazac ten problem ? 

Dzieki 
J

**Comment by ramicspa** [comment]
Wymagany jest kodi w wersji 17. Inne wersje mogą powodować takie problemy

**Comment by flexfit1983** [comment]
@ramicspa

Rzeczywiscie spojrzalem teraz I mam kodi 16.1 
Moge zrobic update do 17 tak zeby nie tracic wszystkich ustawien nad ktorymi troszke siedzialem 🙂 ? Czy musze wgrac 17 I zaczac wszystko na nowo? 

Dzieki @ramicspa

**Comment by ramicspa** [comment]
Spróbuj może się uda ale lepiej na świeżym instalować bo sporo się
pozmieniało pomiędzy wersjami. Zrób backup.

**Comment by flexfit1983** [comment]
Nie wiem co robie zle ? Sciagnalem Kryptona i zrobilem przywracanie I nic tak jak byl nowy Tak pozostal I nic sie nie przywrocilo , sciagnalem Jarvisa -16.1 zrobilem przywracanie i wszystkie ustawienia wrocily , czy cos trzeba dodatkowo zrobic w Kryptonie zeby przywrocic ustawienia ? 

Dzieki

**Comment by ramicspa** [comment]
ustawienia czego? czesc wtyczek w tym skinow zmienila sie znaczaco pomiedzy wersjami 16.x a 17.x wiec moga nie dzialac. zrob swierza instalacje - przy okazji sie posprzata kodi ze zbednych smieci.

**Comment by flexfit1983** [comment]
Czesc , 

Czy w Cinema HD zmienil sie kod ? 
"nowy" nie loguje sie 

Dzieki

**Comment by tomasiek** [comment]
Zaczyna się... Tak. Kod się zmienił. Nowy kod jest na głównej stronie
repozytorium.

21.06.2017 4:06 AM "flexfit1983" <notifications@github.com> napisał(a):
