### ISSUE TITLE
Cdax.tv niedziałające odnośniki 

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#214]
Witam. We wtyczce Cdax.tv nie działają żadne linki do filmów. Tam gdzie widniała nazwa serweru na którym znajduje się film jest teraz pusty kwadrat.

**Comment by rokibalboa** [comment]
Potwierdzam od wczoraj u mnie to samo na wielu urządzeniach. Oprócz tego od dawna błąd wyszukiwarki.

**Comment by ramicspa** [comment]
Trochę pozmieniało na stronie. Dodatkowo dla ip z poza kraju jest captcha. Zobaczę czy da się to jakoś naprawić.

**Comment by ramicspa** [comment]
tak na szybko fix poszedl - widze ze ciagle cos na stronie zmieniaja - potrzebne beda czestrze poprawki do wtyczki

**Comment by driver00** [comment]
no chwała Ci, chłopie, za te aktualizacje i całą zabawę. jesteś wielki.
