### ISSUE TITLE
problemy z wtyczka cdax tv

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#215]
nie mozna otworzyc seriali i filmów po aktualizacji strony internetowej cdax tv czy jest mozliwosc naprawienia wtyczki pod kodi ?

**Comment by ramicspa** [comment]
Dzięki za info. Ja się da naprawić to będzie update

**Comment by rafciu27** [comment]
Po aktualizacji nie działają zakładki gatunek, rok i kraj

**Comment by driver00** [comment]
i nie ma wyszukiwarki 😖
