### ISSUE TITLE
Wizja TV

### ISSUE THREAD

**Issue by yngbld** [ramicspa/kodi#216]
Wizja tv nie dzala.

**Comment by rafciu27** [comment]
U mnie działa

**Comment by yngbld** [comment]
Na Kodi 17?

**Comment by rafciu27** [comment]
Fakt na 17 nie działa

**Comment by kodishu** [comment]
Pewnie się narażę niektórym, ale jaka Wizja TV? Nie widzę takiej wtyczki w repo
