### ISSUE TITLE
LivePolishTv lista pvr

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#217]
Witam 

nie twozy sie lista z 
nowatv.net
telemaniak.org
itvi pusto strona dziala
pozdrawiam

**Comment by ramicspa** [comment]
dzieki za info - sprawdze co tam sie dzieje i bedzie niebawem update wtyczki

**Comment by Zigi1974** [comment]
Nie ma za co , dodatkowo na obu nowatv.net
telemaniak.org po chwili ogladania wyskakuje komunikat " kanal dpstepny na stronie " i tylko plansza.

**Comment by hellboy2** [comment]
A dodałbyś więcej pozycji tv aby utworzyć listę m3u
