### ISSUE TITLE
Ekstraklasa TV

### ISSUE THREAD

**Issue by garbatyprostak** [ramicspa/kodi#218]
Witam, wyskakuje teraz kod do wtyczki (nie wiesz ile czasu zajęło mi zeby Cie znalezc, bo w sprawach kodi jestem leszczem:P) , i druga sprawa czy Twoje repo jest bezpieczne na buildach (darmowych) takich jak Pulse,Wookie etc ? Miałem MM, ale skasowalem po tych wszystkich przepychankach.
Można sie z Toba skontaktowac mailowo np? bo tu sie troche gubie.
Pozdrawiam

**Comment by ramicspa** [comment]
Witam,
Od czasu do czasu bedzie cos takiego wyskakiwalo - trzeba wiec zajrzec na ta stronke i wpisac nowy kod. Jesli chodzi o buildy to nic nie jest bezpieczne - uzytkownik nie ma kontroli nad tym co instaluje. Moje wtyczki nie lubia buildow.
