### ISSUE TITLE
cdax tv -hostingi

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#219]
widac już hostingi teraz czekamy tylko aż będziesz miał czas zęby mogły te hostingi działać na kodi pozdrawiamy fachowca

**Comment by ramicspa** [comment]
wczoraj dzialaly - dzis juz cos zmienili.

**Comment by krzysztof222** [comment]
miejmy nadzieje że za jakiś czas to naprawisz

**Comment by ramicspa** [comment]
poszedl update wtyczki

**Comment by rafciu27** [comment]
Działa lecz brak możliwości szukania oraz segregacji przez rok, gatunek i kraj ogranicza oglądanie materiałów do tylko świeżo dodanych i rankingu nowości.

**Comment by cronofx** [comment]
kurde nie wiem co u mnie z tym cdax ....na telefonie po 4g dziala jak przelacze na wifi to dupa nie idzie na zadnym uzadzeniu ... na strone wchodze filmy ze strony chodza...

**Comment by ramicspa** [comment]
szukanie poprawione i dodane do wtyczki. co do segregowania po roku/gatuku/kraju to powinno dzialac - ja nie widze u siebie zadnych problemow

**Comment by rafciu27** [comment]
Po aktualizacji wszystko działa jak należy! Wielkie dzięki :)

**Comment by tomasiek** [comment]
To przy okazji - brakuje miniaturek w wynikach wyszukiwania.

**Comment by tomasiek** [comment]
A i jeśli można - zerknij tutaj: https://github.com/ramicspa/kodi/issues/139#issuecomment-274249639 - bo to ciągle nie działa...

**Comment by ramicspa** [comment]
faktycznie, jest tam problem, bedzie poprawka

**Comment by krzysztof222** [comment]
rozumiem że wtyczka cdax już nie bedzie działac

**Comment by tomasiek** [comment]
https://github.com/ramicspa/kodi2/issues/3
