### ISSUE TITLE
Wtyczka Iwatchonline przestała działać

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#22]
Wtyczka Iwatchonline przestała działać - brak dostępu do jakichkolwiek filmów

**Comment by ramicspa** [comment]
ok, dzieki za info, wiem w czym problem i zrobie update jeszcze dzis.

**Comment by Seico** [comment]
Działa na windowsie , na androidzie nie działa

**Comment by ramicspa** [comment]
I nic sie na razie na to nie poradzi trzeba poczekac na nastepna wersje kodi.
zabezpieczenie cloudflare wymaga polaczenia ssl3 ktore nie jest obsługiwane we kazdej wesji python w kodi 16.1
Ale na kodi 16.1 z dystrybucji osmc I openelec wszystko dziala

**Comment by Seico** [comment]
Następna będzie 17 która nie chodzi na androidzie mniejszym niż 5.0

**Comment by Seico** [comment]
Na windowsie z kodi 16,1 też nie działa , działa tylko z kodi 17

**Comment by ramicspa** [comment]
Zgadza sie, mam to samo i jak na razie nie znalazlem rozwiazania

**Comment by Seico** [comment]
"cdaonline" też nie działa na kodi 16.1

**Comment by ramicspa** [comment]
Cdaonine powinno dzialac jak aktywujesz bramke proxy z opcjii pluginu.

**Comment by Seico** [comment]
Na androidzie z kodi 16,1 nie działa , nawet po zaznaczeniu proxy
