### ISSUE TITLE
Efilmy błędne tytuły filmów bug

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#220]
Witam

We wtyczce efilmy v 1.11  kodi 17 android  wyskakują błędne tytuły filmów 
inna nazwa inny film np
Top Filmów  tydzień 
Widmo zagłady wyświetla jako Transformers: Wiek Zagłady
Sinbad i zderzenie furii (2016) [Lektor PL] wyświetla jako Przełęcz ocalonych

Podobnie jest w Filmach

W miarę możliwości proszę o poprawienie buga 

Ramic dzięki za dodanie wielokrotnego wyboru jezyka w alltube oraz filiser przy następnych aktualizacjach proszę o dodanie tej opcji do pozostałych wtyczek

**Comment by ramicspa** [comment]
wielokrotny wybor jest dostepny tylko dla kodi17 - powoli bedzie sie pojawial w innych wtyczkach.
co do filmow to wtyczka wycia lika ze strony - jak tam jest zly link do filmu (nie ten tytul) to nic na to nie poradze.

**Comment by ramicspa** [comment]
u mnie listy pozycji na stronie i wtyczce sa identyczne. moze przez strone uzywasz jakis dodatkowych opcji sortowania -we wtycznie np nie ma opcji zmiany rosnaco/malajaco.

**Comment by Cerber2000** [comment]
![screenshot_2017-03-17-17-09-15-557_mobi mgeek tunnybrowser](https://cloud.githubusercontent.com/assets/20740632/24052154/bea53368-0b34-11e7-9859-867996797b36.png)
![screenshot_2017-03-17-17-09-15-557_mobi mgeek tunnybrowser](https://cloud.githubusercontent.com/assets/20740632/24052159/c482d628-0b34-11e7-86e5-62373fdf32e6.png)

**Comment by Cerber2000** [comment]
Ja mam tak

**Comment by Cerber2000** [comment]
A film Sully to leci coś takiego

![screenshot_2017-03-17-17-15-59-852_org xbmc kodi](https://cloud.githubusercontent.com/assets/20740632/24052417/aecee0e6-0b35-11e7-8dc4-59f7ee7f348f.png)

**Comment by Cerber2000** [comment]
![screenshot_2017-03-17-17-19-21-145_org xbmc kodi](https://cloud.githubusercontent.com/assets/20740632/24052473/e9ae68ee-0b35-11e7-9b82-95dec4cb9218.png)
![screenshot_2017-03-17-17-19-28-027_org xbmc kodi](https://cloud.githubusercontent.com/assets/20740632/24052477/edcff7ee-0b35-11e7-941f-8803998817fe.png)

**Comment by ramicspa** [comment]
wylacz opcje metadada dla filmow - bo nie znajduje ich poprawnie

**Comment by Cerber2000** [comment]
Ok po wyłączenie pokazuje prawidłowo tylko brak oceny filmów 

Dzięki za pomoc
