### ISSUE TITLE
http://szukajka.tv - czy można to wykorzystać?

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#222]
Witam.
Ostatnio na kompie korzystam z tego: http://szukajka.tv - świetna baza do wyszukiwania. Nie wiem gdzie, w jakiej wtyczce, a może stworzyć nową?
Działa naprawdę fajnie, znajduje szybko multum źródeł...

**Comment by kopernik1983** [comment]
Doszla do FanFilm Mr Know w ostatniej aktualizacji i sprawdza sie tam swietnie. Multum zrodel  i w czyms wlasnie takim ja bym ja widzial. raczej w paru polaczonych wtyczkach z filmami czy serialami.

**Comment by tomasiek** [comment]
O fakt - tam też jest - nota bene z fanfilm robi się całkiem fajny dodatek.
Parę połączonych wtyczek? To i tak bez sensu - bo szukajka.tv ściąga sama z wielu źródeł.
Może podrzucę 2 pomysły jak to widzę:
1. Uzupełnienie "szukaj" w innych wtyczkach. Jeżeli np. na cda nic nie znajdzie to dać opcję "Wyszukaj w innych" i to by prowadziło do szukajka.  
lub
2. Osobna wtyczka - służąca głównie do szukania, ale posiadająca foldery do np. filmweb ranking 500 (http://www.filmweb.pl/rankings/film/world, http://www.filmweb.pl/rankings/film/poland, http://www.filmweb.pl/rankings/film/premiere/world)
Nie wiem czy to nie będzie dubel fanfilm.
lub 
3. Najprosze i chyba najszybsze - po prostu wyszukiwanie filmów - jako osobna wtyczka tylko z tą funkcją (+ ewentualnie opcje w innych twoich wtyczkach żeby alternatywnie korzystały z szukajka.tv)

**Comment by xxcriticxx** [comment]
@tomasiek szukaj a znajdziesz :)

**Comment by tomasiek** [comment]
No szukałem ale nie znalazłem... Zresztą... Czy ktoś to zrobi lepiej niż
Michał?

31.03.2017 4:37 PM "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by kopernik1983** [comment]
Opcja druga chyba by mi bardziej odpowiadala z prostego wzgledu. zadko szukam po tytulach bo ich nie znam :) , raczej po gatunkach , czy krotkim opisie :) a czy bylby to dubel?? a czy wszystkie wtyczki z filmami czy serialami to nie duble?? w sumie i tak w nich prawie to samo z tym ze jedne dzialaja lepiej inne troche gorzej. takze jest wybór :)

**Comment by xxcriticxx** [comment]
@tomasiek to slabo szukasz :)

**Comment by tomasiek** [comment]
@xxcriticxx to zapodaj linka.

**Comment by xxcriticxx** [comment]
@tomasiek znowu bendzie off topic

**Comment by tomasiek** [comment]
To wykasujemy posty.

**Comment by xxcriticxx** [comment]
lol

**Comment by kopernik1983** [comment]
@tomasiek chciałeś i masz :)

**Comment by tomasiek** [comment]
Szczegóły? Bo nie widzę...

**Comment by kopernik1983** [comment]
jest w repo znaczy bedzie bo jeszcze u siebie nie widze ale jest w info

**Comment by tomasiek** [comment]
A już widzę!
Brawo Ramic, po raz kolejny wielkie dzięki...

**Comment by kopernik1983** [comment]
Brawo on :)
