### ISSUE TITLE
blad wtyczki filiser.tv

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#223]
po wejsciu w wtyczke wyskakuje napis (podaj kod z ze  strony repozytorium wtyczki) bardzo prosimy o naprawe

**Comment by kopernik1983** [comment]
zaden blad. tak ma byc. wprowadz kod i bedzie dzialac.  strony repozytorium etyczki chyba nie musze podawac??

**Comment by krzysztof222** [comment]
A jaki jest kod

06.04.2017 12:23 "kopernik1983" <notifications@github.com> napisał(a):

**Comment by kopernik1983** [comment]
ghvn chlopaki czytajcie troszke :) kod sie zmienia co jakis czas wiec zagladaj na https://github.com/ramicspa/kodi/blob/master/README.md

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/24754394/4a7d6c6a-1aa4-11e7-8e43-c55d0534684a.PNG)

**Comment by krzysztof222** [comment]
Dzięki zioneczku

06.04.2017 14:37 "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
@xxcriticxx nie podawaj im za każdym razem zrzutu z zaznaczonym kodem.. niech się nauczą choć trochę szukać. Ważne jest aby wchodzili na główną stronę, żeby potem nie było jak z marcintomanek :)
Ps.
Jak ktoś jest w stanie obsługiwać pilota skoro ma problem ze znalezieniem tego kodu....

**Comment by xxcriticxx** [comment]
@tomasiek tesknisz za marcinem?

**Comment by tomasiek** [comment]
Właśnie nie - a ostatnio coraz częściej widze pytanie o hasło którego się nie che ludziom odczytać... to irytujące... Ramic specjalnie je dał na główną stronę, żeby osoby te czytały informacje które tam są...

**Comment by xxcriticxx** [comment]
ok next subject
