### ISSUE TITLE
segos- logowanie

### ISSUE THREAD

**Issue by DarDo1** [ramicspa/kodi#224]
Witam,
w dodatku segos pojawiły się filmy dla zalogowanych i premium. Mimo rejestracji na koncie i wpisaniu loginu i hasła w dodatku nie odtwarza filmów przeznaczonych dla zalogowanych. Da się coś z tym zrobić?

**Comment by kopernik1983** [comment]
dzisiaj byla aktualizacja. losowo odpalilem kilka filmow i dzialaja wiec juz chyba po problemie

**Comment by rokibalboa** [comment]
Po założeniu konta i zalogowaniu wybieram film dla zalogowanych przeważnie 720p i nie łączy z żadnym serwisem.

**Comment by kopernik1983** [comment]
podaj jakis konkretny tytul bo sprawdzam jak leci i dziala np psy mafii , londyn w ogniu , 13 hours i dziala bez problemu

**Comment by rokibalboa** [comment]
Film Fances np.

**Comment by rokibalboa** [comment]
Głupio się przyznać ale przyznaję się do błędu w logowaniu stąd te problemy. Przepraszam już wszystko działa.

**Comment by kopernik1983** [comment]
:)
