### ISSUE TITLE
problem raptu w wtyczce http://filiser.tv

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#228]
po wejsciu  na hosting rapu wyskakuje bład dodatku

**Comment by ramicspa** [comment]
podaj jakias przykladowa pozycje ... bo mi raptu idzie bez problemu (np forrest gump)

**Comment by krzysztof222** [comment]
The originals 4x04

09.04.2017 23:46 "ramicspa" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
u mnie biega 
wtyczna na dniach dostanie update

**Comment by krzysztof222** [comment]
Ok dzięki za info

09.04.2017 23:52 "ramicspa" <notifications@github.com> napisał(a):

**Comment by Seico** [comment]
Wkodi 17,1 wszystko jest ok z raptu.com , a SPMC wywala błąd przy wybraniu filmu z tego hostu

**Comment by krzysztof222** [comment]
problem z rapu hause of cards 

> 

> 
![rapu](https://cloud.githubusercontent.com/assets/24533475/25312157/67c4db34-2812-11e7-8018-bbbc5806e152.png)
](url)

**Comment by ramicspa** [comment]
SPMC oparte jest na K16 wiec duzo rzeczy moze nie dzialac jak trzeba.
nie uzywaj forkow kodiego a wszystko bedzie dzialac ja trzeba.
