### ISSUE TITLE
jaki kod filmy.to i nasze-kino

### ISSUE THREAD

**Issue by gregoryyyy** [ramicspa/kodi#229]
Jak w tytule co za kod trzeba wpisać

**Comment by tomasiek** [comment]
Do znudzenia. Wejdź na główną stronę repo, jak byk masz tam kod podany.

11.04.2017 3:16 PM "gregoryyyy" <notifications@github.com> napisał(a):

**Comment by gregoryyyy** [comment]
można link?

**Comment by tomasiek** [comment]
No przecież wszedłeś tutaj, to i na głównej stronie musiałeś być. Lenistwo
na maksa
https://github.com/ramicspa/kodi

11.04.2017 3:20 PM "gregoryyyy" <notifications@github.com> napisał(a):

**Comment by xxcriticxx** [comment]
pora na wieksza strzalke

**Comment by tomasiek** [comment]
Sądzę że w niektórych przypadkach nawet to nie pomoże... I dla takich osób
są buildy :)

11.04.2017 3:55 PM "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by kopernik1983** [comment]
jak dla mnie to trzeba zakończyć chyba te podawanie bo ileż można. i w tematach zamkniętych jest wystarczy chcieć i zerknąć a nie wałkować w kółko to samo. a jak komuś się nie chce oczy w sufit.

**Comment by tomasiek** [comment]
Dokładnie. Kod ma swoją wadę (trzeba go podać), ale ma ważną zaletę dla Michała - wymusza na użytkownikach (którzy używają jego wtyczek w sposób kompletnie nieświadomy) wejścia na jego stronę, uświadomienia sobie że to, za co płacą tym cwaniakom, jest tak naprawdę za darmo. Daje szansę poznania innych dodatków i ich wykorzystania. Podając leniwcom kod na tacy - działamy na niekorzyść repo. Poza tym - nie rozumiem jak można odczytać informacje na kodi że należy wpisać kod znajdujący się na stronie, przepisać adres i zamiast odczytać informację - walić od razu w issue - new issue.

Poza tym - zastanawia mnie jedno. Korzystam głównie z wtyczek ramica, sporadycznie z fanfilm. Oglądam - w sumie 2-3 filmy w tygodniu + kilka bajek dla dzieciaków. I kod mi nie wyskoczył ani razu jeszcze...

**Comment by xxcriticxx** [comment]
to jaki jest ten kod jeszcze raz? :)

**Comment by Cinek77** [comment]
Wpisz 1234 lub ABC. Moze Ci zadziala :)
A na przyszosc to poczytaj troche tematow :)

**Comment by kopernik1983** [comment]
@tomasiek jak mniemam wyskoczy ci jak będziesz korzystał powiedzmy z jakiegoś bilda. mi na boxie też nie wyskakuje natomiast na kompie to juz inna sprawa. taka sama konfiguracja na jednym i drugim ( mimic ) z tym ze na kompie pewnie jakieś śmieci mi po powiedzmy takiej nakładce pozostały. w sumie na kompie malo korzystam służy mi za platforme testowa dodatków bo box az tak duzo pamici nie posiada a potrafi sie kodi rozrosnąć tymi miniaturkami do dość sporych rozmiarów.

**Comment by xxcriticxx** [comment]
@kopernik1983 ja oglondam na apple tv 1 1 ghz cpu i 256 mb ramu ten box ma 10 lat :+1:

**Comment by tomasiek** [comment]
No to wykrakałem. Dziś mi wyskoczył kod na cinemahd... I na segoes...

13.04.2017 11:17 PM "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by kopernik1983** [comment]
@xxcriticxx   chodziło mi bardziej o dysk niż ram. na kompie kodi ma już 2,4 giga takze sporo a wszystko przez to ze ciągnie sobie miniaturki i tym podobne pierdoły dlatego na kompie szukam i sprawdzam sobie wtyczki zanim trafią do boxa szkoda miejsca na smieci :) mozna to usuwac zeby odchudzic ale mi sie nie chce heheh:)

**Comment by xxcriticxx** [comment]
@kopernik1983 thx za info ale wszystko dziala na 16gb usb sticku hd zdech pare lat temu :)

**Comment by albertrafal** [comment]
Filmy.to KOD:nowy
