### ISSUE TITLE
Prośba dodania czeskiej telewizji

### ISSUE THREAD

**Issue by eko5** [ramicspa/kodi#23]
Tak jak w tytule czy miałbyś ochotę na dodanie czeskiej telewizji z tej strony http://streema.com/tv/country/Czech_Republic , po za tym na tej stronie znajdują się inne kanały z całej europy .

**Comment by ramicspa** [comment]
Mozna dodac czeska tv ale nie z tej strony co podales bo ona nie zawiera zrodel a tylko linki oficjalnych stron kanalow ktore nie zawsze a nawet dosc rzadko udostepniaja transnisje live.
na stronie czeskiej tv znalazlem 3 stacje co transmituja live.
podaj lepsze zrodlo I zobzczymy co da sie zrobic

**Comment by eko5** [comment]
Oto lepsze źródło http://tvtvtv.ru/index_eng.php?co=21

**Comment by ramicspa** [comment]
wrzucilem nowa wtyczke liveIPTV ... tam znajdziesz cos po czesku i nie tylko. niebawe z kolejnymi updatami inne zrodla sie tam tez pojawia.

**Comment by eko5** [comment]
super dzięki
