### ISSUE TITLE
live tv 

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#230]
Witam 
Mam pytanie odnosnie http://tele-wizja.com/ stronka dziala czy da rade dodac do wtyczki 
dziekuje

**Comment by ramicspa** [comment]
hmm serwis ten byl dostepny ... chyba przestal kiedys dzialac skoro zniknal z wtyczki - jak dobrze dziala to pojawi sie ponownie niebawem.

**Comment by Zigi1974** [comment]
dziekuje
