### ISSUE TITLE
Filmy Dokumentalne

### ISSUE THREAD

**Issue by garbatyprostak** [ramicspa/kodi#231]
Witam. Po wybraniu jakiegokolwiek filmu z listy wyskakuje bład  " Set either url, or host and media_id.
No other combination are valid" .Pozdro

**Comment by ramicspa** [comment]
dzieki za info - zobacze w czym problem

**Comment by ramicspa** [comment]
patrzyles jak sprawa wyglada na stronie ?

**Comment by garbatyprostak** [comment]
Nie mam pojecia na jakiej;) , korzystam tylko z Twojej uprzejmosci i Twoich wtyczek.

**Comment by tomasiek** [comment]
Filmydokumentalne.eu

**Comment by garbatyprostak** [comment]
pisze tylko o uzytkownikach premium itd, nie da sie ogladac bez tego.

**Comment by ramicspa** [comment]
ok, fajnie ze sprawdziles jak sprawa wygla z serwisem filmydokumentalne.eu. 
linki do zrodel sa platne - i niewiele na to poradze

**Comment by garbatyprostak** [comment]
Wielka szkoda bardzo fajny serwis . Do zamkniecia czyli ;)
