### ISSUE TITLE
Livepolishtv nie uruchamia sie

### ISSUE THREAD

**Issue by dziobek9** [ramicspa/kodi#232]
Witam, wtyczka się nie uruchamia i wyskakuje komunikat o nieaktualnym pluginie i repo a są aktualne

**Comment by kopernik1983** [comment]
nie potwierdzę u mnie wszystko chodzi bez zarzutu kodi 17.1 win 7 i box. podaj może więcej informacji  i spróbuj zaktualizować recznie

**Comment by xxcriticxx** [comment]
@dziobek9 podaj jakies logi

wszystko dziala tak jak @kopernik1983 pisal

**Comment by dziobek9** [comment]
https://pastebin.com/eSyCtCux trzymajcie logi

**Comment by xxcriticxx** [comment]
@dziobek9 ustaw sobie czas i timezone.  wyloncz pvr i poptestuj. jak to nie pomoglo to odmontowac wtyczke i zamontowac jeszcze raz. masz tam resztki starych wtyczek by pasowalo to posprzatac.

**Comment by ramicspa** [comment]
1. pobierz aktulana wersje repozytorium (wersja 1.3.0)
2. na kodim zainstaluj z zip (to repozytorium)
3. uaktualnij wtyczke przez repo
4. problem rozwiazany.

**Comment by JohnMorra** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/24629005/25066278/86eb73dc-2219-11e7-8eda-a2525e8ca07a.png)

takie cos wyskakuje

**Comment by tomasiek** [comment]
To wpisz kod ze strony głównej repozytorium.

15.04.2017 9:24 PM "JohnMorra" <notifications@github.com> napisał(a):

**Comment by xxcriticxx** [comment]
@tomasiek to nie z tego repo "**BROUGHT TO YOU BY ARES PROJECT**"

**Comment by JohnMorra** [comment]
to jeszcze mi prosze powiedziec jaki jest adres strony....

**Comment by tomasiek** [comment]
Ludzie... No przecież jesteś na tej stronie!!!!!! Wejdź na główną stronę
repo nie na isues ale na code...Czasem zastanawiam się jak co niektórzy
ogarniają myszkę i klawiaturę

15.04.2017 9:38 PM "JohnMorra" <notifications@github.com> napisał(a):

**Comment by dziobek9** [comment]
@ramicspa własnie nie raz tak probowałem i nie dawało rady :/ @xxcriticxx gdzie dokladnie się to ustawia?

**Comment by xxcriticxx** [comment]
@dziobek9 wykasuj całe kodi i nagraj odnowa masz resztki ruskich wtyczek

**Comment by dziobek9** [comment]
@xxcriticxx  zrobiłem kompletny reinstall ale nadal nie działa...Tak samo jak wtyczki od MrKnow..Filmy Online nawet sie nie uruchamia

**Comment by xxcriticxx** [comment]
@dziobek9 podaj nowy log zobaczymy co nowego masz

**Comment by dziobek9** [comment]
https://pastebin.com/JYqXwnMr

**Comment by ramicspa** [comment]
Większość wtyczek wymaga od kodi dostępu do internetu. Pewnie przez jego
brak nic nie działa.

**Comment by dziobek9** [comment]
Ale jak może nie mieć internetu jak exodus działa idealnie :D

**Comment by ramicspa** [comment]
To może sprawdź czy podobne problemy pojawiają się jak zainstalujesz na
innym urządzeniu niż pc z win 8.1

**Comment by xxcriticxx** [comment]
@kopernik1983 powiec nam gdzie ty to montujesz? W jakieś pracy? Widzę ip6 i port 8080 proxy masz? Pozatym zle montujesz wtyczki napewno za dużo na raz. I bym polecił Windows 7 a nie 8. Przedtem miałeś Windows 10 czemu zmieniłeś?

**Comment by dziobek9** [comment]
W domciu.. Tylko na tym kompie nie działa :/ na androidzie 6.0 i win 10 dzial

**Comment by xxcriticxx** [comment]
@dziobek9 Ok ale natej boxie jakieś cuda masz? Widzę ze jest problem z common cache i innymi zeczami. WiFi tobie nie przerywa ale network card nie pada? Może masz jakiś antivirus albo firewall wlonczone?

**Comment by xxcriticxx** [comment]
@dziobek9 znalazłem problem zmień usera z Michał na coś innego kodi nie lubi polskich znaków

**Comment by dziobek9** [comment]
Obczaje i napisze... Wesołych świąt!

**Comment by dziobek9** [comment]
Dzięki!  Działa!  Co prawda nie wiem jak zmienić ścieżkę do appdata ale utworzyłem nowego użytkownika i hula

**Comment by xxcriticxx** [comment]
@dziobek9 zuc 5zl na donacije dla @ramicspa za dobra robote!
