### ISSUE TITLE
Livepolishtv

### ISSUE THREAD

**Issue by hellboy2** [ramicspa/kodi#236]
Wtyczka nie działa

**Comment by pawlak1212** [comment]
U mnie też nie działa

**Comment by xtrerpl** [comment]
U mnie offline chcialem uaktualnic liste m3u i nic. 
W LivepolishTv zniknela sciezka dostepu do listy oraz brak mozliwosci aktualuzacji

**Comment by rafciu27** [comment]
U mnie działa i wcześniej też bo oglądałem ligę mistrzów przez sport365live

**Comment by xtrerpl** [comment]
Ja wywalilem calego androida zainstalowalem na nowo kodi i Polish Live TV jest offline brak PVR

**Comment by pawlak1212** [comment]
Już działa 😊
