### ISSUE TITLE
seagos premium

### ISSUE THREAD

**Issue by rokibalboa** [ramicspa/kodi#239]
Z serwisu mogą teraz korzystać posiadacze konta premium? Chciałem obejrzeć dwa tytuły ale w miejscu wyboru jakości jest tylko opcja premium.😞

**Comment by tomasiek** [comment]
A na stronie sprawdź jak jest. Niektóre filmy mają tylko linki premium

**Comment by rokibalboa** [comment]
Zauważyłem że nie wszystkie.

**Comment by tomasiek** [comment]
Podaj konkretny przykład. Nikt nie będzie zgadywał

**Comment by rokibalboa** [comment]
Dusigrosz,Siedem minut po północy.Sand Castle to pierwsze trzy tytuły z 10 ostatnio dodanych.Tylko dla posiadaczy kont premium.

**Comment by tomasiek** [comment]
Nie mam tam konta premium, więc nie sprawdzę - ale na stronie wszystkie 3 filmy mają dopisek:
> Wstawka Premium. Pozostały czas do zmiany dla wszystkich: 0d 6h 28m 6s

Rozumiem że masz tam konto premium, i we wtyczce mimo wszystko nie wyświetlają się linki? Jeśli tak - wrzuć tu logi (chowając ewentualnie login i hasło - je możesz przesłać ramicowi celem sprawdzenia). Jeśli nie masz tam konta premium, to chyba oczywiste że się nie wyświetlają...

ps. filmy dostępne do zalogowanych działają normalnie.
ps2 - dusigrosz (nota bene wczoraj oglądałem - fajny) i pozostałe dwa są na filmy.to - działają na 100%

**Comment by rokibalboa** [comment]
Ok.dzięki za odpowiedź.Nie mam konta premium na Segos i dlatego musiałem szukać danego tytułu na innych serwisach bo tam były dla mnie niedostępne.Rozumiem że niektóre linki są po prostu niedostępne dla tylko zalogowanych że  tak powiem w godzinach szczytu i po kilku godzinach można je jednak otworzyć.

**Comment by tomasiek** [comment]
A to już nie pytanie tutaj tylko do autorów serwisu seagos.

23.04.2017 12:16 PM "rokibalboa" <notifications@github.com> napisał(a):
