### ISSUE TITLE
Błąd przy instalowaniu pluginów

### ISSUE THREAD

**Issue by razjel** [ramicspa/kodi#24]
Gdy próbuję zainstalować dowolny z pluginów to Kodi loguje mi taki błąd:
```
15:02:07 T:5756   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
15:02:07 T:5756   ERROR: CCurlFile::Open failed with code 400 for https://raw.githubusercontent.com/ramicspa/kodi/master/plugin.video.cdapl/
15:02:07 T:5756   ERROR: XFILE::CHTTPDirectory::GetDirectory - Unable to get http directory (https://raw.githubusercontent.com/ramicspa/kodi/master/plugin.video.cdapl/)
15:02:07 T:5756   ERROR: XFILE::CDirectory::GetDirectory - Error getting https://raw.githubusercontent.com/ramicspa/kodi/master/plugin.video.cdapl/
15:02:07 T:5756   ERROR: CAddonInstallJob[plugin.video.cdapl]: could not read addon description of special://home/addons/plugin.video.cdapl
```

**Comment by xxcriticxx** [comment]
zamontuj respitory pierwszo potem z respitory wtyczki

**Comment by ramicspa** [comment]
@razjel 
Instalowanie pluginow bez repozytorium nie jest wskazane bo zaleznosci wtyczki nie zostana automatycznie zainstalowane i nie bedzie (poprawnie) dzialac. Udalo sie?

**Comment by razjel** [comment]
Próbowałem to zainstalować na komputerze rodziców i gdy szukałem w internecie to jedyny link jaki udało mi się znaleźć tłumaczący jak dodać to repozytorium, mówił o zainstalowaniu SuperRepo i tam znalezieniu go. Jak się okazało w SuperRepo jest jakaś stara niedziałająca wersja tego repozytrium, dlatego po licznych próbach udało i ręcznym dodawaniu repozytoriów udało mi się uzyskać tylko efekt z zaprezentowanym wyżej błędem. Teraz jak już wróciłem do domu to znalazłem stronę, gdzie jest umieszczone paczka z działającym repozytorium, dlatego problem został już rozwiązany.
