### ISSUE TITLE
plugin vectra - telewizja online dla abonentow

### ISSUE THREAD

**Issue by bart00777** [ramicspa/kodi#242]
czy ktoś jest w stanie naprawić tą wtyczkę plugin.video.vectra.tvonline ?
https://github.com/rafakob/plugin.video.vectra.tvonline
o kurcze chyba nie tutaj powinienem to pisać

**Comment by ramicspa** [comment]
moze spytaj sie vectry - powinni poszerzyc oferte dla uzytkownikow kodi
