### ISSUE TITLE
Jeden by wszystkimi rządzić....

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#246]
> Jeden, by wszystkimi rządzić, Jeden, by wszystkie odnaleźć,
Jeden, by wszystkie zgromadzić i w ciemności związać
W Krainie Mordor, gdzie zaległy cienie.

Mam genialny pomysł. Rozumiemy chyba wszyscy potrzebę istnienia kodu do wtyczek ramica. Dzisiaj kod się na nowo uaktywnił... musiałem go podać około 10 razy... rewelacja, prawda? Wielu z nas "jedzie" praktycznie tylko na wtyczkach ramica, to ich jedyne źródła... też chyba nie muszę mówić czemu. Czy nie można by było zrobić, żeby podczas zmiany kodu, po uruchomieniu "pierwszej" wtyczki z "pakietu ramicspa" byłaby prośba o kod, zaś przy uruchamianiu następnych już by się nie pytał? Żeby kolejne wtyczki pamiętały ten kod wpisany w pierwszej? Oczywiście do kolejnej zmiany kodu...
Czy to w ogóle możliwe... taka globalna autoryzacja...

**Comment by xxcriticxx** [comment]
@tomasiek tesciowa ma problem z kodem?

**Comment by ramicspa** [comment]
> Było nas trzech (w tym wypadku wielu). W każdym z nas inna krew. Ale jeden przyświecał nam cel. ....

**Comment by tomasiek** [comment]
Czyli co... 
> Znowu w życiu mi nie wyszło...

**Comment by tomasiek** [comment]
W sumie rozumiem takie podejście. Łatwiej by było januszom biznesu podrzucić spreparowane ustawienie dla wszystkich wtyczek niż kombinować dla każdego z osobna...

**Comment by manius123** [comment]
Ramic blagam cie zdejmij ten kod to jest poprostu masakra..... a ten gostek tech @#$#$!#!@# niech sie idzie walic z orangutanem.

**Comment by manius123** [comment]
wez dotacje jakas od userow za dostep do repository..... ja bym zaplacil zeby tego nie bylo i kazdy ma swoj kod ktory daje prawa do uzytku.

**Comment by tomasiek** [comment]
Znając naszych "cfaniaków" wykupili by 1 dostęp a następnie by dodali do swojego super buildu i sprzedawaliby to 10x drożej
Kod raczej będzie - kwestia płatności... to już niech się ramic wypowie, ale obserwując tego githuba od jakiegoś pół roku - to ciężko to widzę... byli już tacy co proponowali... i znikali dość szybko...

**Comment by manius123** [comment]
no to jak mowiles.... jeden globalny kod..... tak jakby activation code cos w tym stylu..... .. ja nie jestem cfaniakiem ... i doceniami ramic mr know i wiele innych developerow...... dzieki nim  polacy zagranica tak jak ja maja opcje na polska tv, i filmy.

**Comment by manius123** [comment]
ja uwazam ze ktokolwiek placi za build....tzn za darmowe reposytoria to kompletny naiwniak... no ale techmaniac to cos w stylu marcin p/ amber gold co nie ? Musze sie sam nauczyc jak robic wtyczki jest wiele stron z ktorych mozna darmowe feedy streamowac..... trzeba miec tylko czas zeby przysiasc i postukac w klawiature.

**Comment by manius123** [comment]
ramic..... daj nam znac..... te wpisywaniu za kazdym razem jak whodzisz w kazda wtyczke to mordega .... wiem ze techmaniac to kawal huja i nie jest ok to co on robi..... ale czemu cala reszta musi przez paru debilow cierpiec.

**Comment by koladka** [comment]
A ja powiem tak zdecyduj sie albo to jest free wtyczka albo  idz w strone platna i daj spokuj z ciskaniem sie do ludzi ! Ten kod to jakas paranoja powinien byc na jakiejs oficjalnej stronie;) Ja sie przestawilem na apki z iptv ktore sa zajebiste znaczy kreca od sztycha ;)

**Comment by tomasiek** [comment]
A na jakiej stronie masz ten kod jak nie na oficjalnej? Poza tym jak nie
chcesz korzystać, nie korzystaj. Masz full płatnych buildów.


30.04.2017 9:09 AM "koladka" <notifications@github.com> napisał(a):

A ja powiem tak zdecyduj sie albo to jest free wtyczka albo idz w strone
platna i daj spokuj z ciskaniem sie do ludzi ! Ten kod to jakas paranoja
powinien byc na jakiejs oficjalnej stronie;) Ja sie przestawilem na apki z
iptv ktore sa zajebiste znaczy kreca od sztycha ;)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/246#issuecomment-298215883>, or mute
the thread

**Comment by koladka** [comment]
Widziales strone Mr know  tak powinno to wygladac!;) Wiec tak odbierasz ludzi troche nie kulturalnie! Twoja wtyczka jest bardzo ladnie ulozona dla oka!  Nieodbieraj ludzi tak jakby wszyscy byli przeciwko tobie!;)  Robisz wspaniala robote,  dzieki ze odpisujesz tak szybko !

**Comment by tomasiek** [comment]
1. To nie autor wtyczek ci odpisuje, tylko ja. Użytkownik jak każdy inny, może ciut bardziej świadomy.
2. Na oficjalnej stronie jest wszystko co jest potrzebne, jest czytelne, nie ma zbędnych wodotrysków. Strona mrknow jak dla mnie niczego nie wnosi, i tak wszystko co ważne ma na githubie.
3. Co do kodu, kultury itp, to tego akurat autorowi nie można zarzucić. Kod jest konsekwencją tego, że ludzie kradną wtyczki, chcą za nie opłat, zaś ramic chce żeby były za free, kod jest konsekwencją dyskusji które się odbywały tutaj kilka miesięcy temu (z wyzwiskami, pozwami sądowymi). Więc żeby utrudnić życie cwaniakom, zaś użytkowników uświadomić że są robieni w wała, został wprowadzony kod. Dzięki temu wiele osób zostaje uświadomionych że płacą za coś, co mogą mieć za darmo i że tych rzeczy jest więcej.

**Comment by koladka** [comment]
Dzieki swietnie to ujoles i wytlumaczyles ;) Teraz juz wszystko jasne;)
Jeszcze raz dziekuje

30.04.2017 1:04 PM "tomasiek" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
@tomasiek dzieki wielkie za wyjasnienia podczas mojej nieobecnosci.

@koladka - tak z ciekawosci sie spytam ... w jakis sposob wtyczki z tego repo trafily do ciebie. z opisu wnioskuje ze raczej nie przez strone githuba

@manius123 jeden globalny kod nie jest planowany. ja tam bym sie cieszyl ze kazda wtyczka nie ma innego kodu ;)

**Comment by koladka** [comment]
Twoja wtyczka jest ogolnievdostepna w google na stronach addadons tv ;) Rowniez jest w full super reppo!;)

**Comment by tomasiek** [comment]
Widzę że ramicspa sprząta, to i ja zamknę.
