### ISSUE TITLE
iitv seriale 

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#249]
po wpisaniu nowego kodu przy wejsciu do wtyczki , prosi o kolejne wpisanie przy wejsciu do pod menu , poczym prosi o wpisanie kiedy wybieramy kolejny serial I tak dalej .
jednorazowe wpisanie kodu nie pomaga .
:)

**Comment by ramicspa** [comment]
fajnie ze zauwazyles - powazny bug ktory nie powienin sie pojawic. juz naprawione. niebawem wtyczka sie zaktualizuje
