### ISSUE TITLE
Yoy.tv

### ISSUE THREAD

**Issue by borys76** [ramicspa/kodi#25]
Witam 
Mozesz sprawdzic co pozmieniali na yoy.TV ?
Nie dziala na twojej wtyczce I Mr know 
Dzieki

**Comment by ramicspa** [comment]
wyglada na to ogladanie tylko dla premium ...

**Comment by borys76** [comment]
Na mrknow TV tez nie dziala nawet po wpisaniu premium

**Comment by borys76** [comment]
Wlasnie MrKnow dodal comment 
"Yoy.tv coś pozmieniał. Ukrywają adres IP serwera rtmp. Jeszcze nie potrafię go odkodować."

**Comment by borys76** [comment]
Na mrknow juz dziala z premium

**Comment by ramicspa** [comment]
tez naprawione, sprawdzam inne serwisy i wieczorem zrobie update

**Comment by borys76** [comment]
Super 
Dzieki

**Comment by tomasiek** [comment]
Nie chcę zakładać nowego tematu, a pytanie dotyczy yoy.tv.
jak ze stabilnością źródeł? Rozumiem że jak utworzę listę m3u (w ciągu tych magicznych 8 minut) to linki będą przez jakiś czas działać.. i tu pojawia się pytanie - czy z doświadczenia ktoś wie jak długo? Dzień/dwa? Czy jest możliwość żeby np. w opcjach tworzenia listy m3u ustawić harmonogram odświeżania - że np. codziennie o 13 ma odświeżać listę?
