### ISSUE TITLE
Filmy.to

### ISSUE THREAD

**Issue by cieniawa83** [ramicspa/kodi#251]
Nie aktualizują się seriale , 
Dla przykładu hell's kitchen polska sezon 6 jest tylko 6 odcinków brakuje 4

**Comment by rafciu27** [comment]
To sprawdź najpierw na stronie ile jest odcinków. Wszystko jest z wtyczką.

**Comment by xxcriticxx** [comment]
na stronie jest tylko 7 odcinkow
