### ISSUE TITLE
Problem z kodem do repozytorium cda.pl 1.9.0

### ISSUE THREAD

**Issue by cypekis11** [ramicspa/kodi#252]
Czesc,

w nowej wersji pojawila mi sie prosba o podanie hasla, ktore znajde na stronie repozytorium. Nie podano jednak strony i nie bardzo kumam o co chodzi. 
Kto pomoze?
Dzieki

**Comment by tomasiek** [comment]
Jak ja się cieszę że reforma edukacji wchodzi...
Wszedłeś na stronę repo i założyłeś temat... o tym że nie możesz znaleźć strony repo... daj cofnij w przeglądarce i będziesz na właściwym miejscu i poznasz **nowy** kod

**Comment by cypekis11** [comment]
Aha, no to fajnie, ze sie cieszysz i jestes taki wyedukowany. Nie bedziesz musial isc do gimnazjum, tylko wskoczysz od razu do 7 klasy. 
Wyobraz sobie, ze szukalem po tematach, lecz nie znalazlem watku, ktory mial w tytule 'cda.pl' oraz bylo w nim nadmienione o podawaniu hasla. 
Wiec zamiast cwaniakowac, pouczac i mowic ludziom co maja robic, moglbys napisac:
Haslo jest podane na stronie glownej i brzmi ono 'nowy'

**Comment by rafciu27** [comment]
Skasuj ten wątek jak już się dowiedziałeś bo ludzi denerwujesz.

**Comment by tomasiek** [comment]
@cypisek11 sorry poniosło mnie. Następnym razem (czyli za ok. tydzień, jak kod się zmieni) jak wyskoczy ci ten komunikat, napisz tutaj, a ktoś przyjedzie i wpisze go specjalnie dla ciebie...
Ps. Mam napisać że hasło jest podane na stronie głównej... Ale przecież właśnie to miałeś napisane w komunikacie który co wyskoczył... Więc nie sądzę żeby to cokolwiek pomogło.
