### ISSUE TITLE
Serialnet

### ISSUE THREAD

**Issue by cieniawa83** [ramicspa/kodi#253]
Można zrobić serialnet.pl ?

**Comment by tomasiek** [comment]
Troszkę słaba baza (przynajmniej w tym co patrzyłem) w porównaniu do już istniejących - brakuje całych sezonów seriali (3 których sprawdzałem), a są one dostępne w innych dodatkach ramica. W liście tych które "niby są" - wiele jest z komunikatem: Przepraszamy wybrany odcinek jest w tej chwili niedostępny.
Przykłady http://serialnet.pl/serial-online/1-1571/two-and-a-half-men - sezon 1 i różne odcinki
http://serialnet.pl/serial-online/1-1298/latajacy-cyrk-monty-pythona
czy w inne
W sumie nie udało mi się niczego odtworzyć.... poza kilkoma z pierwszej strony.
IMO - za słaba baza... niekompletna...

**Comment by ramicspa** [comment]
taka sama baza danych dostepna jest na innych serwisach ... i tam dziala
