### ISSUE TITLE
Alltube 

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#255]
Ramic, 

Probuje na wszystkie sposoby ale nie moge rozgrysc  
 alltube, 
Wtyczka wydaje sie pusta, 
Mozesz pomoc?

**Comment by wisiann** [comment]
Jeszcze jedo, 
Co sie stalo z Idigo,?
Wywala blad kiedy chce zaladowac twoja wtyczke?

**Comment by ramicspa** [comment]
cloudflare blokuje dostep do zasobow alltube z poza granic kraju ... poszedl update powinien troche naprawic
