### ISSUE TITLE
Alltube - różnica pomiędzy stroną w wtyczką... oraz niepożądane treści + błąd wyszukiwania (w tej i w innych)

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#256]
1. Na stronie alltube.tv wybieram filmy - nowe filmy i mam:
http://prntscr.com/f299im
We wtyczce (świeżo zainstalowana na kompie) mam zaś:
http://i.imgur.com/VwkKvP4.png
Zupełnie inne jak widać... + zwiastuny... poza tym we wtyczce mam też takie kwiatki:
http://i.imgur.com/hdmRd51.png - chodzi o panienki na rurkach... (sprawdzałem... może nie na rurkach, ale panienki).
Błąd po mojej stronie, jakiś bug? Różnica dość spora, ponadto te panienki + zwiastuny...
2. Występuje tu także błąd z innych wtyczek:
https://github.com/ramicspa/kodi/issues/237

**Comment by Cerber2000** [comment]
Strona alltube tv jako pierwsza wyświetla to po wyborze wersji jezykowej

http://alltube.tv/filmy-online/wersja[Lektor,Dubbing,PL]+

Wtyczka natomiast to 

http://alltube.tv/filmy-online/wersja[Lektor,Dubbing,PL]%20kategoria[]%20strona[2]%20strona[1]+

Czyli alltube ma jakby strone zerową a potem 1,2,3 itp a wtyczka wyświetla od 1 strony  

Trzeba na stronie przełączyć na strone 2 i wrócić do 1, aby zobaczyć różnicę


Dlatego jest różnca pomiędzy wtyczką a stroną w internecie 


Ps.Czy da radę dodać do wtyczki alltube.tv oceny filmów z filmweb.pl jakiś scraper czy coś podobnego

**Comment by ramicspa** [comment]
bug ten powinien zostac naprawiony z nastepna aktualizacja
