### ISSUE TITLE
Ramic repository password problem

### ISSUE THREAD

**Issue by monroe1** [ramicspa/kodi#257]
Hello, sorry this is in english.
I can read in Polish just terrible at writing in Polish.
The question, pytanie*.
The ramic repository is asking for a log in password to use the addon..livepolish.tv. alltube, ex.
I tried to reinstall and update all but it is still asking for the password.
What should I do or what do I need to do for the program addons to work?

**Comment by rafciu27** [comment]
Nowy

**Comment by tomasiek** [comment]
Next time, go to https://github.com/ramicspa/kodi , scroll down to readme
and find "kod"

30.04.2017 9:36 AM "rafciu27" <notifications@github.com> napisał(a):

**Comment by monroe1** [comment]
Thanks all!
I had to be pointed to where it was at, lol.
