### ISSUE TITLE
problem z jakością

### ISSUE THREAD

**Issue by tmjumper** [ramicspa/kodi#259]
witam jestem nowym użytkownikiem i chciałem spytać o dzisiejsze działanie bo ogłądłem dziś F1 na tele-wizja na programie Eleven i strasznie zacinał się obraz i kiepska jakość była a 2 tyg temu wszystko było ok, i teraz nie wiem czy coś ja namieszałem w ustawieniach

**Comment by tomasiek** [comment]
To nie wina wtyczki, tylko wina dostawcy czyli tele-wizja. Wtyczka tylko umożliwia odtworzenia streamu który jest dostępny na stronie - nie ma wpływu na jakość itp itd...
Podejrzewam że było duże obciążenie i serwery tele-wizji padały...

**Comment by kashkash18** [comment]
Zauważyłem że nie wszystkie stremy które idę na stronie działają we wtyczce np. PSF
