### ISSUE TITLE
wtyczki nie wyświetlają się w kodi 16.1

### ISSUE THREAD

**Issue by richard74** [ramicspa/kodi#26]
witam wgrałem wtyczki do kodi 16.1 na urządzeniu mk808 i niestety wtyczki nie wyświetlają zawartości (niektóre np. alltube, ekstraklasa czy też ostatnia freedic - pokazuje się tylko czysty ekran bez zawartości tego problemu nie ma np we wtyczce alabamy jeśli chodzi o wtyczki alltube czy freedic) wtyczki testowane na frodo 12 działają prawidłowo nie wiem jak na 17 bo nie moge przetestować gdzie szukać błędu? żeby pokazała się zawartość wtyczki? np. we wtyczce alekino czy segos zawartość pokazuje się ale nie odtwarza nic

**Comment by ramicspa** [comment]
witam, z takim problemem sie jeszcze nie spotkalem. na jakim systemie chodzi mk808? kodi ma rozne kompilacje i uzywa roznych werscji python i czasem moga byc problemy z kompatybiloscia. zeby zbadac przyczyne problemu najlepiej jest zobaczyc logfile; zobacz to gdzie znajduje sie ten plik tekstowy w zaleznosci od systemu: http://kodi.wiki/view/Log_file/Advanced.
wklej go do pastebin'a i przeslij linka

**Comment by xxcriticxx** [comment]
@ramicspa android ale moze byc I Linux

**Comment by richard74** [comment]
Android 4.2.2 po właczeniu ekstraklasy i alltube  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'service'}
19:17:31 T:1751572696  NOTICE: [SPECTO]: ->----------                PARAMS2: ?action=service
19:17:35 T:1694712648 WARNING: static XFILE::IDirectory* XFILE::CDirectoryFactory::Create(const CURL&) - unsupported protocol(androidapps) in androidapps://
19:17:35 T:1751680104  NOTICE: virtual void EPG::CEpgContainer::Start(bool) - EPG thread started
19:17:39 T:1751680104   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting
19:17:44 T:1969454208   ERROR: Previous line repeats 1 times.
19:17:44 T:1969454208  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19b
19:17:45 T:1751680104 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.ekstraklasa/?foldername=%5BCOLOR+gold%5D-%3DOpcje%3D-%5B%2FCOLOR%5D&params=1&ex_link=&mode=Opcje
19:18:03 T:1640624288   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
19:18:04 T:1840872928  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19b
19:18:04 T:1750359688 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.alltube.tv/?foldername=%5BCOLOR+gold%5D-%3DOpcje%3D-%5B%2FCOLOR%5D&page=1&ex_link=&mode=Opcje
19:18:14 T:1640624288   ERROR: Unable to activate the previous window
19:18:14 T:1694712648 WARNING: virtual bool XFILE::CRarDirectory::GetDirectory(const CURL&, CFileItemList&): rar lib returned no files in archive androidapp://sources/apps/com.rarlab.rar, likely corrupt
19:18:14 T:1694712648   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting rar://androidapp%3a%2f%2fsources%2fapps%2fcom.rarlab.rar/

**Comment by ramicspa** [comment]
dzieki za loga ale szczerze niewiele z niego sie dowiedzialem. to bardzo dziwne ze tylko niektore w ogole nie pokazuja zawartosci. sprawdz tez wtyczkie 'kino24' oraz 'kinoiseriale'. Swoja budowa podobne sa do alltube i ekstraklasa.
Byc moze bedziesz musial zaktualizowac androida do 5.0 przynajmniej bo kodi 17 bedzie go wymagal a do tego bardzo duza czesc wtyczek moze stracic kompatybilnosc z poprzednimi wersjami kodi.
