### ISSUE TITLE
Podaj kod ze stony repozytorium wtyczki

### ISSUE THREAD

**Issue by miziaj** [ramicspa/kodi#261]
Witam,

Od pewnego czasu kiedy uruchamiam wtyczke cda.pl, wtyczka żąda kodu.
proszę o pomoc,

Pozdrawiam .

![20170501_154414](https://cloud.githubusercontent.com/assets/28261322/25581025/63783e26-2e85-11e7-98ed-89ad5d957cbd.jpg)

**Comment by ramicspa** [comment]
Witam
Zgadza się. Trzeba podać kod by wtyczka działała. Dobrze trafiłeś, kod jest dostępny na tej stronie.

**Comment by tomasiek** [comment]
Ja bym dodał jeszcze że nowy kod jest dostępny, i że będzie się zmieniał na inny...

**Comment by miziaj** [comment]
A gdzie dokladnie moge go znalezc :) sorki jestem nowy

**Comment by tomasiek** [comment]
Na stronie głównej. Skoro wszedłeś tu, i zalogowałeś się i dodałeś post, to
oznacza że byłeś na stronie głównej repozytorium. Wróć na nią i po prostu
odczytaj kod.

01.05.2017 4:13 PM "miziaj" <notifications@github.com> napisał(a):

**Comment by miziaj** [comment]
widocznie robie cos zle bo nie widze kodu

**Comment by ramicspa** [comment]
Nie poddawaj sie.dasz radę trzymamy kciuki!

**Comment by miziaj** [comment]
Dzięki :) a może jakies podpowiedzi

**Comment by tomasiek** [comment]
Nie czytasz, albo nie chce ci się przewinąć strony. Kod jest, przed chwilą
sprawdzałem. Nikt tu ci go nie poda, próbujemy od kilku dni wymusić,
żebyście wchodzili na stronę główną repozytorium i zapoznali się z całością
pracy autora wtyczek.
https://github.com/ramicspa/kodi wejdź i czytaj.

01.05.2017 4:21 PM "miziaj" <notifications@github.com> napisał(a):

**Comment by miziaj** [comment]
aaaa,  chodzi o waszą stronę główną.

**Comment by tomasiek** [comment]
Nie... No chodzi o stronę Onetu przecież... To oczywiste... LOL.

**Comment by miziaj** [comment]
Dzieki, przeciez to takie oczywiste :) Życzę aby nastepny kod był _nowszy_ :)

**Comment by tomasiek** [comment]
Będzie inny...
Takich dopiero ogłosi głosowanie na nowy kod...

**Comment by miziaj** [comment]
ok Podrawiam

**Comment by niedozwolony** [comment]
Nowy kod jest dostepny na stronie .
Zalogowałem sie zeby podziękować ramicspa za udostępnienie .
Dobra robota tak trzymaj.

**Comment by taurustoro** [comment]
Chciałbym podziękować autorowi za dobrą robotę i naprawdę bardzo dobre repo, które ma wszystko to czego na emigracji szukamy aby choć trochę pooglądać PL TV i wiadomości z kraju.

Wielkie dzięki!

**Comment by swipio** [comment]
no nie , szukam i szukam tego kodu i nie widzę , proszę pomóżcie , przeszukałem całą stronę i nic :(

**Comment by tomasiek** [comment]
No to szukaj dalej, bo przed chwilą sprawdzałem na głównej stronie
repozytorium i kod tam jest. Nikt tu ci nie poda kodu, chcemy żebyście
czytali główną stronę .

02.05.2017 7:54 PM "swipio" <notifications@github.com> napisał(a):

**Comment by swipio** [comment]
Tomasiek nie pisze o pomoc bo mi się nie chce szukać a dlatego ze nie mogę go znaleźć , dzieciaki mi ryczą ze bajkę nie mogą oglądać , bądź miłosierny i napisz gdzie mam wejść albo daj linka na stronę z kodem a już poszukam sam , widocznie z tych nerwów nie mogę znaleść

**Comment by taurustoro** [comment]
Kod jest i dziala, potwierdzam!

**Comment by taurustoro** [comment]
Swipio: main page reposytoriow wlasciciela pluginu... proste jak nidowa cepa... jak tego nie ogarniasz zacznij uzywac youtube kids...

**Comment by swipio** [comment]
ehhhh :( znajduje gdzie jest napis kod nowy ale tam nie ma żadnego kodu a jak to naciskam to nic sie nie dzieje , nie każdy jest dobry we wszystkim

**Comment by tomasiek** [comment]
Żeby tu cokolwiek napisać musiałeś wejść na stronę główną repozytorium i
się zalogować itp itd. Wróć na nią, przewiń i znajdź kod. Dla niepoznaki
znajduje się on po słowie KOD.
  Nie podamy ci go, bo za tydzień jak się zmieni to nie będziesz umiał go
sam znaleźć i znowu będziesz pytał.

02.05.2017 8:02 PM "taurustoro" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
No to widzę że znalazłeś kod... Nawet go tu wpisałeś... Kod to: nowy

02.05.2017 8:06 PM "Tomasz Woś" <tomasz.wos@gmail.com> napisał(a):

**Comment by swipio** [comment]
dziękuję ale było to za mocno podchwytliwe :)

**Comment by swipio** [comment]
tak znalazłem ale uwierzcie mi jak dzieciaki się drą nad głową trudno się skupić i znaleźć tak okropnie skomplikowany kod :) dziękuje za pomoc

**Comment by tomasiek** [comment]
No niestety... Jedyna metoda żeby zapoznać was z innymi wtyczkami ramicspa to odsyłanie na główną stronę. A nowy kod jest specjalnie tak skonstruowany... Dzięki temu jest szansa że część użytkowników buildow których autorzy kradną wtyczki zauważy że można to mieć za free

**Comment by koladka** [comment]
Chodzi o to ze ten Kod zlewa sie z cala strona i fakt jak ktos wchodzi  na strone github to wszystko jest takie samo jednolite;) Hha mam pomysl pogrubcie to haslo na polowe strony bedzie ok

**Comment by miziaj** [comment]
Mysle ze mozna zamknac post.

**Comment by deiwid63** [comment]
tomasiek ty chyba jestes jakims masonem nie podasz kodu to powiedz gdzie jest bo ja tej strony nie znam, a takie zachowanie to nic innego jak chamstwo.

**Comment by koladka** [comment]
Haslo ::  nowy

**Comment by tomasiek** [comment]
Za każdym razem podaję gdzie jest kod - na głównej stronie repo, na którą każdy z was wchodzi nim się tu zaloguje i coś napiszę. Ile razy to powtarzać, tylko dlatego że ludzie mają problem z czytaniem ze zrozumieniem i nie potrafią znaleźć słowa KOD..
Nikt nie będzie też pisał 20 kodów do każdej z wtyczek osobno, bo jest jeden do wszystkich.
A chamstwem jest nieczytanie strony autora, ani niepodziękowanie mu za jego pracę tylko wyzywanie z powodu swojego lenistwa innych.

**Comment by tomasiek** [comment]
@koladka nie podawaj kodu. Za tydzień się zmieni i kolega dalej będzie miał
problem ze znalezieniem. Dawajmy wędkę nie rybę...

13.05.2017 12:43 PM "koladka" <notifications@github.com> napisał(a):

**Comment by koladka** [comment]
Tak czy inaczej od 3 tygodni jest taki sam !  Iholandia dodana oby smigala jak najdluzej jak teraz  pieknie i full pakiet kanalow!:)

**Comment by tomasiek** [comment]
Może i od 3 tygodni, ale wierz mi, może być zmieniany częściej. Więc lepiej
niech się uczą jak go znaleźć.

13.05.2017 10:06 PM "koladka" <notifications@github.com> napisał(a):

**Comment by deiwid63** [comment]
tomasiek tobie nie bede dziekowal bo nie jestes nikim tylko udajejesz gniujsza a do niego ci 100000000000km

**Comment by deiwid63** [comment]
Mam teraz CDA.Pl ale nie moge wbic na Polish TV bo znowu chce jakis kod.

**Comment by tomasiek** [comment]
Jesteś właśnie przykładem gniujsza (to już drugie moje ulubione słowo które tu poznałem). Wyedytowałeś drugi post w którym pisałeś że:
"Mam teraz CDA.Pl ale nie moge wbic na Polish TV bo znowu chce jakis kod.
(Github to nie zwykłe forum, wysyła powiadomienia z treścią pierwotna postu)
Udowodniłeś tym samym moja tezę, że nie należy podawać kodu, tylko poddawać miejsce gdzie można go znaleźć.
I ja nie chciałem żebyś to mi dziękował, ale tu znowu kłania się czytanie ze zrozumieniem.
Dobranoc.

**Comment by koladka** [comment]
Chcialem mu pomoc ale teraz widze ze po podaniu hasla .Tu mu juz nic nie pomoze  ;);)

**Comment by tomasiek** [comment]
Hehe - i dlatego właśnie odsyłamy do strony głównej. Szanujmy Michała i jego pracę...

**Comment by makbazy** [comment]
test

**Comment by wiola1212** [comment]
Witam !
Czy jest jakaś szansa na pomoc w uzyskaniu takiego kodu ?

**Comment by Katapulta** [comment]
@wiola1212 nie wiem. Trzeba by było sprawdzić jak to wygląda prawnie i czy takie rozdawanie kodu na lewo i prawo się opłaci... 

A tak na poważnie - wystarczy czytać ze zrozumieniem co jest napisanie na stronie głównej tego repozytorium.... albo nawet w tym temacie :) 

https://github.com/ramicspa/kodi

**Comment by tomasiek** [comment]
Najlepsze jest to, że ten kod nie jest nigdzie ukryty, a oni go wiecznie szukają. Toż to lepsze niż Monthy Python

**Comment by wiola1212** [comment]
Tak wiem ze to nie jest fer rozdawanie kodu na prawo i lewo :( 
Tylko ze ten link mi się nie otwiera w całości na telefonie dlatego nie mogę tego znaleść :( 
Potrzebuje do telewizji firetv z amazona tam mi wyskoczyło po jakimś czasie żeby podać kod 😱

Wysłane z iPhone'a

Dnia 06.08.2017 o godz. 06:55 Katapulta <notifications@github.com> napisał(a):

**Comment by Katapulta** [comment]
@wiola1212  ... wchodzisz na stronę główną repozytorium - link podany we wcześniejszych postach.... i kurna czytaj co pisze bo jest tam KOD napisany... rany kioskiem...

**Comment by Katapulta** [comment]
To nie jest chyba aż tak trudne do zrozumienia że kod do wtyczek jest na stronie głównej repozytorium... Wystarczy czytać ze zrozumieniem 

http://prntscr.com/g6f5ja

**Comment by wiola1212** [comment]
Dziękuje Ci bardzo :)
Jesteś zajebisty !!!
Udało się z Twoja pomocą :)
Jeszcze raz dziękuje :) 
I trzymam język za zębami :) 
Wielkie dzięki !!!!
Pozdrawiam :) 

Wysłane z iPhone'a

Dnia 09.08.2017 o godz. 17:41 Katapulta <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
Boże.... Widzisz i nie grzmisz... Będzie tragedia jak ramic zmieni kod....

**Comment by Katapulta** [comment]
@tomasiek nom, ale specjalnie się słowem nie odezwałem. Może w końcu się nauczą ... już nie wytrzymałem i musiałem tego ssa walnąć... Byłem tylko ciekaw czy bez zaznaczania na nim kolorem doczytają się...
