### ISSUE TITLE
 problem z freedisc

### ISSUE THREAD

**Issue by bartek00** [ramicspa/kodi#263]
Witam. Zainstalowałem ,wtyczkę freedisc jak do niej wchodzę raz są  użytkownicy i wchodzę na ich pliki i wszystko jest dobrze ,a za chwilę  ,jak wchodzę, na tą wtyczkę to jest pusto  ???

**Comment by xxcriticxx** [comment]
@bartek00 teczka na stronie nie pusta?

podaj jakis example

**Comment by ramicspa** [comment]
dzieki za info ... zobacze co nie tak. Pewnie w przyszlym tygodniu bedzie update wtyczki oraz vider'a - bo pewnie tez juz nie chodzi jak trzeba.

**Comment by bartek00** [comment]
Witam. Ponownie, jest to samo co było z tą  tyczką freedisc    /kilka  dni było dobrze /
