### ISSUE TITLE
Ciemny obraz w Kodi - android

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#264]
Mam bardzo duży problem i proszę o pomoc , w Kodi na androidzie wszystkie wersje ma przyciemniony obraz w trakcie oglądania filmów , grzebałem już w ustawieniach i nie przyniosło to żadnych skutków , mam też zainstalowane SPMC i tu tego problemu nie mam ale SPMC ma problem z odtwarzaniem filmów z niektórych hostów (np.raptu.com , streamango.com itp. - na kodi jest ok) , barzdo proszę o podpowiedź co mogę zrobić aby w Kodi było z obrazem ok , bo  filmów nie można normalnie obejżeć gdzyż w niektórych scenach nic praktycznie nie widać

**Comment by tomasiek** [comment]
Tego próbowałeś? http://forum.kodi.tv/showthread.php?tid=304219 - u mnie pomogło na andku.
A przy okazji - jeśli używasz tvboxa z andkiem tylko do kodi, to może lepiej libreelec?
