### ISSUE TITLE
Cda hd

### ISSUE THREAD

**Issue by Menkind1978** [ramicspa/kodi#265]
Witam! Chciałbym się dowiedzieć czy jest możliwość dodania wtyczki cda hd, jeżeli tak to kiedy to może nastąpić? Dzięki, Pozdrawiam

**Comment by ramicspa** [comment]
bedzie dodana wtyczka do cda-hd ... dzieki za przypomnienie

**Comment by kashkash18** [comment]
Wtyczkę CDA Kino można usunąć gdyż serwis nie dziala

**Comment by tomasiek** [comment]
Strona cda-kino.pl prowadzi teraz do cda-x.pl który działa :) Więc może to podmienić?

**Comment by kashkash18** [comment]
A nie chodzi czaszek o kino24tv ??

**Comment by tomasiek** [comment]
wtyczka cda-kino prowadziła do strony cda-kino.pl - po jej wpisaniu jest przekierowanie na cda-x.pl (IMO obie mają dość słabą bazę filmów)
kino24tv - nawet nie mogę znaleźć w sieci... bo http://kino24-tv.pl to zwykły wyłudzacz, clickbait z bazą 4 filmów...

**Comment by kashkash18** [comment]
Może być jak piszesz , zasugerowałem się tym że nazwa w ZIP jest plugin.video.kino24tv.

**Comment by ramicspa** [comment]
wtyczka poczatkowo dedykowana byla dla kino24 ... ale tego typu strony szybko padaly lub zmienialy sie. Na razie wyleciala z repo - zobacze w przyszlosci czy warto dodac cda-x. 
poki co cda-hd sie pojawilo
