### ISSUE TITLE
cda.pl brak miniaturek + błąd z kodowaniem przy wyszukiwaniu

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#266]
1. W dodatku CDA nie wyświetlają się miniaturki, poza tymi pobieranymi z Filmweb. Może to i dobrze, bo najczęściej są one tak marnej jakości że i tak nic nie wiadomo...
2. I ponownie błąd z polskimi znakami przy wyszukiwaniu. Log ten sam co przy innych.

**Comment by ramicspa** [comment]
1. naprawione
2. kiedys nie bylo wsparcia dla wyskukiwania z uzyciem polskich znkow w cda.pl - sam mam znimi czesto problemu :P Teraz jest are rezultat nie znienia sie

**Comment by tomasiek** [comment]
To że rezultat się nie zmienia to wiem. Na stronie tak samo wyszukuje z polskimi znakami jak i bez. Mi chodziło o wykorzystanie autouzupełniania, które podpowiada z polskimi znakami... Przy dłuższych tytułach wpisuję początek tytułu a resztę wybieram z automatu. I wtedy gdy są polskie znaki pojawia się problem.
