### ISSUE TITLE
taka stronka :)

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#268]
Witam 
moze da sie cos wyciagnac :)
http://tele-miki.pl/
pozdro

**Comment by tomasiek** [comment]
https://github.com/ramicspa/kodi/issues/233 i zerknij na wypowiedź ramicspa

**Comment by kopernik1983** [comment]
niby tak ale dzialanie calej reszty pozostawia wiele do zyczenia a tutaj narazie chodzi i jest naprawde tego sporo. wolalbym juz to niz np nowwatchtvlive gdzie nie chodzi praktycznie nic i o zgrozo nie wiem skad ale maja orange sport ktore nie nadaje juz od stycznia :) :) :) wlaczylem sobie canal plus sport niech sobie leci zeby zobaczyc czy nie padnie po jakis 10 minutach

**Comment by tomasiek** [comment]
No i to jest dobre uzasadnienie

06.05.2017 1:03 PM "kopernik1983" <notifications@github.com> napisał(a):

**Comment by kopernik1983** [comment]
dzieki heh. jeszcze sie nie wykrzaczyl wiec chyba to nie serwis typu 5 minut. warto by rozwarzyc mozliwosc zrobienia wtyczki

**Comment by koladka** [comment]
Zapytanie: Niewiem czy to prawda ale Europejski Wymiar Sprawiedliwosci  wydal nowe juryzdykcje ;) Podobno korzystanie na kodi  stream itp. Jest juz nie legalne
.Wszyscy inwestuja w vpn  ;(  ja raczej niewiem w ktora to strone  sie rozwinie?

**Comment by tomasiek** [comment]
Wydano tylko komentarz, to żaden przepis, ustawa. W komentarzu jest że
sprzedaż urządzeń z oprogramowaniem zezwalającym na odbiór streamu jest
nielegalne. Ale kodi i osobne wtyczki są legalne.

07.05.2017 9:20 AM "koladka" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
https://www.dobreprogramy.pl/Sprzedaz-odtwarzaczy-z-Kodi-i-pirackimi-wtyczkami-nielegalna-w-UE,News,80737.html
Czyli mocy prawnej nie ma to żadnej (w sumie jak cała UE).

**Comment by koladka** [comment]
07.05.2017 11:01 "tomasiek" <notifications@github.com> napisał(a):

https://www.dobreprogramy.pl/Sprzedaz-odtwarzaczy-z-Kodi-i-
pirackimi-wtyczkami-nielegalna-w-UE,News,80737.html
Czyli mocy prawnej nie ma to żadnej (w sumie jak cała UE).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/268#issuecomment-299694923>, or mute
the thread

**Comment by kopernik1983** [comment]
Wzruszył mnie ten artykuł. Pic na wodę i nic więcej. Ale widzę plusy. ileż to rewelacyjnych boxów jest na przeróżnych aukcjach z gotowymi bulidami itd. nielegalne tak naprawdę w całej tej zabawie jest tylko stream a nie korzystanie z niego. a że ów takiego zacnego człowieka który go udostępnia nie jest prosto znaleźć no to  pokażmy że coś robimy i taka jest ta decyzja, która i tak nic nie zmieni ale na papierku może będzie ładnie wyglądać.
