### ISSUE TITLE
Telewizja

### ISSUE THREAD

**Issue by rokibalboa** [ramicspa/kodi#269]
Może to warto byłoby dodać bo canal plus śmiga rewelacyjnie w tv.
http://iholandia.tv/index.php/darmowa-telewizja-online/

**Comment by ramicspa** [comment]
ok dzieki, zobacz co z tamtad da cie wyciagnac

**Comment by Zigi1974** [comment]
Czesc 
ja z zapytaniem do ramicspa da cos z tego wyjac bo stronka wyglada naprawde ciekawie 
dzieki

**Comment by kopernik1983** [comment]
@ramicspa iholandia wyrzuca błąd dodatku. reszta bez zarzutu

**Comment by kopernik1983** [comment]
@ramicspa wszystko działa. dzieki za update. pozdrawiam.

**Comment by rokibalboa** [comment]
Widzę że jest ihollandia w livepolish.tv ale nie mogę wejść bo wychodzi błąd dodatku.☹️

**Comment by ramicspa** [comment]
upewnij sie ze masz ostatnia wersje (2.2.5)

**Comment by rokibalboa** [comment]
2.2.4 posiadam ale jak wchodzę w repozytorium aby zaktualizować nie wykazuje nowszej wersji.

**Comment by kopernik1983** [comment]
takie uroki nowego kodi:) nie wchodź przez repo tylko wymuś aktualizacje

**Comment by rokibalboa** [comment]
W jaki sposób wymusić?

**Comment by kopernik1983** [comment]
dodatki i z lewej strony schowane są opcje widoku. tam znajdziesz wyszukaj aktualizacje. w zależności pewnie od skina. tak bynajmniej jest w mimic

**Comment by rokibalboa** [comment]
Ok,dzięki ale samo się w końcu zaktualizowało.Jak się ucieszyłem że źródło dodał mistrz Michał to canal przestał nadawać.Może chwilowo.

**Comment by kopernik1983** [comment]
hehe :) na tele-miki dobrze śmiga. Póki co przez przeglądarkę. ale może i tu sie doczekamy jakiejś skromnej wtyczki :)
