### ISSUE TITLE
Problem z wtyczką Nasze-kino

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#27]
Witam. Wtyczka Nasze-kino ostatnio szwankuje. Nowo dodane materiały nie posiadają, żadnych źródeł. Problem bodajże występuje od 3-4 dni. Podejrzewam, że to problem ze strony serwisu Nasze-kino.eu, dało by się coś z tym zrobić? Pozdrawiam.
PS. Wielkie dzięki za Ekstraklasową wtyczkę!

**Comment by ramicspa** [comment]
Hey, dzieki za info. Faktycznie noweo dodante materialy nie maja zrodel na stronie ... jest link do forum na ktorym sa zrodelka ... dalo sie to jednak naprawic. zrob update wtyczki.

**Comment by rafciu27** [comment]
Super, wielkie dzięki!

**Comment by Marcino2404** [comment]
Hej. Może pisze nie w tym miejscu, ale nie działa Wtyczka Segos. Moglbys to sprawdzic ?
Oraz czy da sie zrobic z tej stronki wtyczke ? http://www.livefootballol.me/
