### ISSUE TITLE
Filiser.tv  UTRresorver error bug

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#270]
Witam wtyczka filiser.tv wyświetla error i nic nie działa (android kodi17.1)
 
Sprawdzałem na kilku filmach i to samo wyskakuje 

![screenshot_2017-05-08-01-40-59-498_org xbmc kodi](https://cloud.githubusercontent.com/assets/20740632/25809526/8c49a708-340d-11e7-973c-b29acc9c4b2a.png)

Proszę o naprawę

**Comment by ramicspa** [comment]
hmm ... ja nie widze zadnego problemu. Moze firewall cos blokuje?

**Comment by kopernik1983** [comment]
@ramicspa trzeba dodac do wtyczki opcje logowania i bedzie po klopocie pewnie bo na stronce trzeba zalozyc darmowe konto bo tez juz sie nic nie obejrzy.

**Comment by tomasiek** [comment]
U mnie też działa, na dość mocnym firewallu, bez logowania
http://filiser.tv/serial/dawno-dawno-temu/s01e02/the-thing-you-love-most/9434 - np. to

**Comment by kopernik1983** [comment]
no popatrz ze u mnnie teraz tez dziala po wylogowaniu a wczesniej jak wchpodzilem to wywyalalo zeby konto zalozyc. nic juz z tego nie rozumiem.

**Comment by Cerber2000** [comment]
Inne wtyczki działają ok na tych samych źródłach filiser.tv nie chce chodzić wywala error 
![screenshot_2017-05-09-20-14-44-585_org xbmc kodi](https://cloud.githubusercontent.com/assets/20740632/25865934/ffe5326c-34f4-11e7-9dbe-2dc3de66b24f.png)

**Comment by Cerber2000** [comment]
Na stronie wszystko chodzi płynne więc to nie firewall

Chyba to jest związane z zabezpieczeniami  na stronie captchad na stronie sprawdza czy to przeglądarka i człowiek

Przed próbą odpalenia filmu wtyczka paruję z https://openload.co/pair i wywala ciągle błąd

**Comment by kopernik1983** [comment]
jest pewna zależność. żeby odpalić coś na wtyczce trzeba odwiedzić stronę i przy próbie odtworzenia filmu wyskakuje captcha i po tej operacji można korzystać z wtyczki natomiast nie sprawdzałem jak to się ma do czasu korzystania, nie mniej pewna niedogodność jest.
