### ISSUE TITLE
Filmy.to brak filmów bug 

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#272]
Witam w pluginie  filmy.to filmy pusto (androidd kodi 17.1

Na stronie http://filmy.to/ nowe zabezpieczenie  captchad

**Comment by Cerber2000** [comment]
![screenshot_2017-05-09-21-08-13-136_mobi mgeek tunnybrowser](https://cloud.githubusercontent.com/assets/20740632/25868003/ad5dac7a-34fb-11e7-8fe7-59bfcb95cbcc.png)

**Comment by ramicspa** [comment]
poszedl update ... teraz poprzez wtyczke mozna udowodnic ze jest sie czlowiekiem przepisujac tekst z obrazka. czasem moze byc to dosc trudne

**Comment by kopernik1983** [comment]
Damy rade:) Polak potrafi heh:)

**Comment by DarDo1** [comment]
Po aktualizacj wersja 1.6 dalej pusto

**Comment by ramicspa** [comment]
1.7 to ostatnia wersja wytyczki
