### ISSUE TITLE
Wtyczka bajki nie działa.

### ISSUE THREAD

**Issue by BrownEmmett** [ramicspa/kodi#273]
Cześć panowie, cześć Michał. 
Na początku dzięki za świetną robotę z tym repo.
Dziś zainstalowałem wtyczkę bajki i niestety nie działa. Czy tylko mi nie odtwarza żadnej bajki czy jest jakiś ogólny problem z wtyczką? 
Pozdrawiam!

**Comment by ramicspa** [comment]
faktycznie nic tam nie chce dzialac ... bedzie aktualizacja.

**Comment by ramicspa** [comment]
powino juz byc lepiej ... zamykamy problem
