### ISSUE TITLE
problem z naszekino eu 

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#275]
problem polega na tym ze nie pokazuja sie dalsze odcinki na wspołnej chociaz na ich stronie przez przegladarke można kolejne odcinki ogladac a przez kodi najnowszych odcinków nie da sie ogladac bo w ogole ich tam nie widac nowszych odcinków po 2285 [
![na wpsolnej](https://cloud.githubusercontent.com/assets/24533475/25998843/0e401e1e-3723-11e7-8b51-1e1c4151c820.png)
![11](https://cloud.githubusercontent.com/assets/24533475/25998886/40a59e10-3723-11e7-9fe1-c241896aa442.png)

](url)

**Comment by ramicspa** [comment]
zgadza sie, wtyczka pokazuje zawrtosc tylko jednej (pierwsze strony) z forum.
trzeba bedzie dodac stronicowanie

**Comment by krzysztof222** [comment]
czyli czekamy jak będziesz miał czas żebyś się tym zajął miłego weekendu pozdrawiamy

**Comment by ramicspa** [comment]
jak problem rozwiazany to prosze zamknac issue ...
