### ISSUE TITLE
Filiser - problem z serialami.

### ISSUE THREAD

**Issue by kokosz887** [ramicspa/kodi#276]
Dzień dobry.

Mam pytanie. Zainstalowałem wtyczkę Filiser i o ile w przypadku filmów wszystko wyszukuje ładnie o tyle w przypadku seriali nie wyszukuje nic. Wpiszę jakąś nazwę (np. LOST, albo zagubieni) i wyświetlają mi się jakieś tytuły co zawierają te słowa (ale tylko filmy, żadnych seriali).

Czyli wyszukiwanie filmów działa super, ale wyszukiwanie seriali nie działa (albo ja coś robię źle).

Mógłbym prosić o pomoc?

Pozdrawiam.

P.S. Super wtyczki :D

**Comment by ramicspa** [comment]
fakt tylko filmy byly filtrowane ... poszedl update wtyczki

**Comment by kokosz887** [comment]
No i teraz działa super.

Dziękuje bardzo :D
