### ISSUE TITLE
alltube.tv 

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#277]
filtry na serialach jest tylko pierwsza strona na stronie alltube 1, 2,3, 4,5 etc

**Comment by ramicspa** [comment]
hmm nie widze problemu ze stronicowaniem dla seriali

**Comment by xxcriticxx** [comment]
strona 

![capture3](https://cloud.githubusercontent.com/assets/15007183/26102350/a2d3c7b0-3a02-11e7-885c-26281f8d2dba.PNG)

plugin jest tylko pierwsza strona niema 2, 3, 4, 5 

![capture1](https://cloud.githubusercontent.com/assets/15007183/26102371/b095540e-3a02-11e7-8bd8-7b3e2221a994.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/26102363/abcfae88-3a02-11e7-93c5-51fa78e8b376.PNG)

filtry na serialach nie dzialaja zawsze jest tylko pierwsza strona. jak wybierzesz nowe linki, nowe odcinki , najpopularniesze, najwyzej oceniane pokazuja to samo i tylko jedna strone.

**Comment by ramicspa** [comment]
Dziwne bo ja mam dokładnie to co na stronie.
Może zainstaluj wtyczka ponownie.

**Comment by xxcriticxx** [comment]
filmy mam ok problem jest z serialami potestuje na innym komp i dam znac

**Comment by ramicspa** [comment]
brak odzewu to chyba wsyzstko dziala :)
