### ISSUE TITLE
Brak zalukaj w repozytorium

### ISSUE THREAD

**Issue by meriox** [ramicspa/kodi#278]
W urządzeniu z androidem 6 na kodi 16.1 po instalacji repozytorium ramic, wszystkie wtyczki wideo są widoczne poza wtyczką zalukaj. Dlaczego?

**Comment by xxcriticxx** [comment]
zalukaj tylko na kodi 17 and up

**Comment by meriox** [comment]
Wielkie dzięki za info. Pozdrawiam, MariuszOd: "xxcriticxx" &lt;notifications@github.com&gt;Do: "ramicspa/kodi" &lt;kodi@noreply.github.com&gt;; Wysłane: 13:50 undefined 2017-05-14Temat: Re: [ramicspa/kodi] Brak zalukaj w repozytorium (#278)zalukaj tylko na kodi 17 and up—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
