### ISSUE TITLE
Ponowny problem z wtyczką freedisc. 

### ISSUE THREAD

**Issue by bartek00** [ramicspa/kodi#280]
Witam  kilka dni było dobrze    Ponownie, jest to samo co było z tą tyczką freedisc wchodzę . a tam nie ma nic , chyba tak sie stało po tej aktualizacji 10.05./   ,   proszę to naprawić.

**Comment by ramicspa** [comment]
ktos ma tu jeszcze jakis problem bo mi wszystko chodzi jak trzeba

**Comment by kopernik1983** [comment]
@bartek00 wtyczka działa. nie ma z nią problemów.

**Comment by bartek00** [comment]
Mam kodi 16.1      tu podaje link   jak to wygląda /
https://youtu.be/hIxvWDXdx6w

**Comment by kopernik1983** [comment]
problemem może być samo kodi. a konkretnie jego wersja. z tego co sie orientuje to nie ma wsparcia dla kodi 16. ale to już niech sie @ramicspa wypowie.

**Comment by tomasiek** [comment]
bartek - a wrzuć na pastebin logi

**Comment by bartek00** [comment]
Pastebin   ???

**Comment by tomasiek** [comment]
pastebin.com

**Comment by bartek00** [comment]
@tomasiek   gdzie  te logi  znajdę ?   kodi używam od nie dawna  i nie bardzo wiem ..

**Comment by ramicspa** [comment]
Log pewnie nie pomoże. Trzeba zainstalować najnowsze kodi.

**Comment by bartek00** [comment]
@ramicspa  teraz zainstalowałem,  kinoiseriale   i tez pusto       chyba ze zrobię, aktualizacje kodi  jak będzie to samo   to przywrócę, tą 16,1 ?

**Comment by tomasiek** [comment]
Tak, ale po co się cofać? Coraz mniej wtyczek będzie działać z k16

**Comment by bartek00** [comment]
@ramicspa  zaktualizowałem kodi  do najnowszej 17   chwile było dobrze i znów jest to samo ???
