### ISSUE TITLE
LivePolishTV - nie tworzy listy m3u - błąd

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#281]
W najnowszym LivePolishTv nie tworzy się lista m3u - na różnych serwisach
Logi:
https://pastebin.com/GuuCFs5x

**Comment by dziobek9** [comment]
Potwierdzam,funkcja wywala błąd.Pewnie przez dodanie nowych serwisów i cos się poknociło :D

**Comment by ramicspa** [comment]
Hmm dziwne bo mi lista tworzy się bez problemu na win/lin/android. Polskie znaki się za to sypnely.

**Comment by kashkash18** [comment]
U mnie po aktualizacji wtyczki do najnowszej wersji i utworzeniu m3u wywala błąd

HTTPS://paste.ubuntu.com/24596125/

**Comment by rokibalboa** [comment]
Listę tworzy ale tylko z tele-wizja..

**Comment by kashkash18** [comment]
Teraz działa , ale z Black nie tworzy listy , no i wintex się wysypal

**Comment by tomasiek** [comment]
Tak zauważyłem jedną rzecz przez przypadek - dajemy tworzenie listy z Black - nic się nie dziej, wyskakuje błąd. Dajemy od razu tworzenie listy z nova.tv czy z innej działającej - lista się tworzy, w prawym rogu pokazuje się że tworzy listę, szukam [novatv.net], raz po raz zastępowane szukam [none]. Oczywiście nie dzieje się to jak od razu damy wyszukiwanie "działające"

**Comment by ramicspa** [comment]
z black bywaja problemy - czasem dziala czasem nie ... jak bedzie wicej problemow z tym serwisem to wyleci
