### ISSUE TITLE
Filiser na LibreELEC

### ISSUE THREAD

**Issue by dr4cul4** [ramicspa/kodi#284]
Zaraz po instalacji udało mi się uruchomić wtyczkę, ale wyskakiwał komunikat o niekompatybilności z tą wersją KODI mimo to dodatek działał.

Po wyjściu i ponownej próbie wejścia już nie działa, a na dokładkę sczyściło mi wszystkie ustawienia.

**Comment by tomasiek** [comment]
W komunikacie miałeś informacje o niekompatybilności wtyczki z twoją
konfiguracją i prośba aby ją usunąć. Najprawdopodobniej używasz jakiegoś
rewelacyjnego buildu typu alientv lub mmes. Wtyczki ramica nie lubią tych
wynalazków ze względu na to, że ich autorzy sprzedają (sprzedawali) to, co
jest za darmo. Ponieważ kradzież jest dość powszechna, zaś autor nie życzy
sobie aby ktoś handlował jego praca, została wprowadzona mała
"niespodzianka" w postaci komunikatu, do którego niedostosowanie się (czyli
pozostawienie wtyczki ramica) prowadzi do przykrych konsekwencji w postaci
usunięcia profilu kodi. Czy to słuszne czy nie - nie chce mi się znowu o
tym pisać. Autor uznał że to dobra metoda...


18.05.2017 12:30 AM "dr4cul4" <notifications@github.com> napisał(a):

**Comment by dr4cul4** [comment]
OK, zatem sprawa jest dziwna.

Zainstalowałem ten dodatek najpierw na maszynie z Windowsem, tam działa bez zarzutu, Bombkę zrzucił na instancje na LibreELEC. Zaznaczam, ze oba profile to klony i jedyna różnica to dodatki systemowe z LibreELEC.

Dość dokładnie przeczytałem kod waszego zabezpieczenia i nie widzę co u mnie w systemie (na LibreELEC) mogło by podpaść pod nie, jedyne co mogło pójść nie tak to rozkodowywanie stringów, ale nie mam w tym momencie możliwości sprawdzenia czy faktycznie do tego doszło, ale z przyjemnością to sprawdzę.... a skąd ta sugestia, ano stąd, ze o ile zaszyty string komunikatu to:  "Wtyczka nie dziala z tym buildem. Wylacz natychmiast kodi", to na LibreELEC zawierał na końcu sporo krzaczków.

Btw. Jak na Open Source to sporo zachodu z czytaniem źródeł jest.

**Comment by tomasiek** [comment]
Też mam libreelec i nie mam na nim żadnych problemów, niech się ramic
wypowie. A źródła są ciut zagmatwane, bo podkradają regularnie co lepsi
Janusze biznesu i sprzedają jako swoje.

18.05.2017 10:06 AM "dr4cul4" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
najlepiej instalowac wtyczki na czystym kodi - nie bedzie wtedy zadnych problemow z dzialaniem
