### ISSUE TITLE
propozycja tv 

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#286]
jest taka stronka https://www.firstonetv.eu/Live

moze dalo by cos z tego zrobic

pozdrawiam

**Comment by plumers** [comment]
Ramic - w dodatku livepolish TV jest kilka juz nieaktywnych stronek - można wyrzucić je
 - a  http://tele-wizja.com zmieniła trochę kanały kod itp ,i  dodali więcej - na www chodzą,a  wtyczka nie odpala ich :) większość jest poprzez pakiet  IPLA HD :)
