### ISSUE TITLE
freedisc

### ISSUE THREAD

**Issue by bartek00** [ramicspa/kodi#288]
witam ,problem  z wtyczką , freedisc ,   aktualizacja, do kodi 17, nie pomogło chwile było dobrze  , a jak wyszłem i za chwile wróciłem , do tej wtyczki  to już było pusto ......................
mam  MXQ PRO/

**Comment by ramicspa** [comment]
to tak raczej nie dziala ze chwilek jest dobrze a potem juz nie. czy przez przegladarke tez masz problemy z tym serwisem? Moze sporo pobierasz materialow - i serwis blokuje twoje IP?

**Comment by bartek00** [comment]
Na freedisc ,to tylko oglądam  filmy . Ogólnie to jak nie miałem Android  box .to na tv smart  przez przeglądarkę . Ale tam to była tona reklam .

**Comment by bartek00** [comment]
@ramicspa  A może ,to być wina/softu tego Android box' bo mam wykupione goldvod i też  wszystkie kanały działają A za jakiś czas  żadne  nie chodzą muszę wyjdź z goldvod lub nie raz z KODI, i ponownie wejdź i wtedy  działa......//

**Comment by ramicspa** [comment]
to masz odpowidz ... fajnie ze postarales sie i sam sprawdziles w czym jest problem
