### ISSUE TITLE
cinema hd

### ISSUE THREAD

**Issue by mrowak1980** [ramicspa/kodi#289]
witam problem jest typu takiego ze nie moge otworzyc nic zadnego filmu nic nie rozumiem od dluzszego czasu tak sie dzieje 
14:18:17 T:5896 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
14:18:45 T:4552 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.CinemaHD/?mode=decodeVideo&foldername=&params=%7B%7D&ex_link=ydodHRwczovL3d3dy5yYXB0dS5jb20vZS9GRjJKMjdNUEZJJ10%3D&xfile=

**Comment by ramicspa** [comment]
na kodi 17.1 wszystko dziala - jesli nie uzywasz tej wersji to jest duza szansa ze pojawia sie problemy
