### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#29]
moze troche anime?

**Comment by eko5** [comment]
http://www.animezone.pl/
http://on-anime.pl/anime/
http://anime-odcinki.pl/

Jestem za takim świetnym dodatkiem .

**Comment by ramicspa** [comment]
cos z tego wyjdzie :)

**Comment by Marcino2404** [comment]
A czy z tego da sie zrobic wtyczke spotrowa ? http://www.livefootballol.me/
Bede wdziwczny.

**Comment by ramicspa** [comment]
da sie i z tego zrobic

**Comment by Marcino2404** [comment]
Super :)

**Comment by eko5** [comment]
pojawil się problem z anime.pl a dokladnie z seria Tales of Zestiria the X 

Openload.co resolve failed.Pigeons?

A drugie putanie czy pojawią się nowe serwisy ??

**Comment by ramicspa** [comment]
jak padl urlresolver to nie bedzie zadnego streamingu z openload - trzeba poczekac na naprawe.
co do innych anime ... to wszystko w zasadzie to samo? - cos konkretnie interesuje?

**Comment by eko5** [comment]
https://github.com/tknorris/script.module.urlresolver

wystarczy skopiowac do kodi i openload.co zaczyna działać 

Konkretnie mnie interesuje animezone gdyż ma więcej linków video
