### ISSUE TITLE
problem  na kinoiseriale 

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#290]
kiedy chce wejść na filmy lub serial i wpisuje np. to wszędzie wyskakuje czarna plansza  nic niema   ,jak bys miał czas to prosimy żebyś sie przyjżał temu problemowi pozdrawiamy 
![kinoseriale](https://cloud.githubusercontent.com/assets/24533475/26348021/9e374c5a-3fab-11e7-914d-7c28f822f986.png)

**Comment by ramicspa** [comment]
wtyczka wymagala aktualizacji. powinno wszystko juz dzialac

**Comment by krzysztof222** [comment]
jesz
![tak kochanie](https://cloud.githubusercontent.com/assets/24533475/26395951/fb952cde-4071-11e7-9c98-dcb0451f65f6.png)
cze nie działa serial tak kochanie wyskakuje tylko tak coś

**Comment by grzech87** [comment]
Witam czy ktos z was ma tez taki problem jak u mnie z wtyczka nasze kino na androidzie że po wejscie do kategorii rozrywka nic mu nie wyswietla ? do jakiegos czasu nie wystepowal problem, niestety ale nie ma w konfiguracji wtyczki opcji proxy bo moze to bylaby tego wina. Wersja wtyczki 2.4. De facto temat odnosi sie do podkategorii tej samej wtyczki i dlatego nie chcialem zakladac nowego tematu. Dziekuje za pomoc.

**Comment by ramicspa** [comment]
@grzech87  @krzysztof222 a jaka wersja kodi?

**Comment by grzech87** [comment]
ramicspa v17.1

**Comment by krzysztof222** [comment]
mam wersje 17.1 reszte serial dziala tak jak zauwazylem tylko tak kochanie nie chce sie włączyc

**Comment by grzech87** [comment]
Byc może coś w ustawieniach kodi zmienilem, lecz na rowno czy to na androidzie czy na windowsie nie dziala...
