### ISSUE TITLE
Ramic repo zip file 

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#291]
Czesc, 

Jak zainstalowac repositorium zip file na fire tv stic,?
Mozesz podac link ktory musze wpisac ?

Chcialem uzyc indigo do add ons ale wyrzuca blad przy wgrywaniu, 
Dzieki

**Comment by tomasiek** [comment]
Link jest na głównej stronie repozytorium.
https://github.com/ramicspa/kodi/raw/master/repository.ramic.zip

**Comment by wisiann** [comment]
Super  
Dzieki!

**Comment by wisiann** [comment]
Cos nie moge go odpalic?
Jeszcze poprobuje

**Comment by wisiann** [comment]
Nie moge otworzyc zip file,
Jak by puste?

**Comment by wisiann** [comment]
Ok
W koncu zatrybilem, 

Dzieki!
