### ISSUE TITLE
lista nie chce sie zapisywac z live polish tv :(

### ISSUE THREAD

**Issue by jabarroo** [ramicspa/kodi#293]

**Comment by jabarroo** [comment]
tzn. nie można ustawić własnej listy m3u z LivePolishTv od jakiegoś czasu wcześniej nie było z tym problemu . cały czas pokazuje uruchom program ponownie czy jakos tak ?

**Comment by ramicspa** [comment]
jak bys podal wiecej szczegolow bo bylaby szansa na odpowiedz.
