### ISSUE TITLE
LivePolishTV: 'module' object has no attribute 'l1ll1ll_tv_'

### ISSUE THREAD

**Issue by WMP** [ramicspa/kodi#297]
Dla wtyczki LivePolishTV mam bład po wybraniu opcji "Utwórz listę m3u" albo "Uaktualnij ustawienia PVR...":
https://pastebin.com/48YZw4ts

Ten base64 koduje to: http://ddecode.com/hexdecoder/?results=896fe04ddae2e3f3343cae9129979f35 

Kodi 16, openelec 7.

**Comment by ramicspa** [comment]
zaktualizuj wtyczke i kodi
