### ISSUE TITLE
Witam. nie moge stworzyć własnej listy z LivePolishTv czy jest jakas możliwość żeby to naprawić prosze o pomoc.

### ISSUE THREAD

**Issue by jabarroo** [ramicspa/kodi#299]
Witam. nie moge stworzyć własnej listy z LivePolishTv czy jest jakas możliwość żeby to naprawić prosze o pomoc.

**Comment by tomasiek** [comment]
Logi, logi i jeszcze raz logi. Bez tego jest wróżenie z fusów

30.05.2017 4:17 PM "jabarroo" <notifications@github.com> napisał(a):

**Comment by xxcriticxx** [comment]
czary mary hokus pokus

**Comment by ramicspa** [comment]
hmm a ja nie mam z tym problemow zadnych ... jak chcesz jakies pomocy to podaj wiecej szczeogow ... np wersje wytczki, system itp
