### ISSUE TITLE
Ekstraklasa

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#30]
Taki mały drobny problem ze skrótami meczów polskiej ligi ze strony strony estadios.pl. Skróty z najświeższej kolejki ekstraklasy się nie otwierają, a na stronie estadios.pl można odtworzyć jest bez problemu. Problem występuje tylko ze skrótami z naszej ligi. Dałoby się to jakoś naprawić? Pozdrawiam.

**Comment by ramicspa** [comment]
faktycznie nie wszystko dzialalo jak trzeba, naprawione w wersji 1.4

**Comment by rafciu27** [comment]
Nie chce zakładać nowego wątku, ale live zniknął z wtyczki ;(

**Comment by duri2** [comment]
Czy tylko u mnie wrócił problem ze skrótami na Estadios? Tzn. na stronie ok, w kodi nie włączają się. Kodi 17 RC3, Win 10
