### ISSUE TITLE
Błąd dodatku LivePolishTv podczas tworzenia listy

### ISSUE THREAD

**Issue by Slawekchorz** [ramicspa/kodi#300]
Błąd dodatku LivePolishTv podczas tworzenia listy m3u. System windows, wersja kodi 17.3. Najnowsza wersja repozytorium, instalowałem to już z 10 raz wg instrukcji i dalej nic. Dodam że dodatek bajki po polsku działa, zalukaj również. Proszę o pomoc.
Pozdrawiam i dzięki.

**Comment by ramicspa** [comment]
Podaj linka do pastebin z całym logiem kodi. Zobaczymy w czym problem

**Comment by Slawekchorz** [comment]
https://pastebin.com/Hss03tJS

Pozdrawiam

**Comment by ramicspa** [comment]
tak na szybko problem jest ze sciezka ... uzywasz polskie znaki w nazwie uzytkownika
"C:\Users\S�awek\AppData\Roaming\Kodi\add" i wtyczka ma problem z zapisaniem pliku m3u.
