### ISSUE TITLE
No i mamy nagonkę

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#304]
Linki do filmów tych producentów : 
Paramount Pictures Corporation
Sony Pictures Entertainment Inc.
Twentieth Century Fox Film Corporation
Universal City Studios LLC
Warner Bros. Entertainment Inc.
Walt Disney Studios Motion Pictures

Znikają w oczach , jest nagonka i stronki z filmami online aby się utrzymać na rynku wywalają całymi seriami no ale mamy wtyczke która jest bezpieczna ..... i jej to nie grozi :) , jak coś wywalą zaraz jest z powrotem :)

**Comment by Katapulta** [comment]
Na Specto czy Exodusie nie widzę żeby coś znikało ;P Ale to przecież nie pierwszy raz  :P

**Comment by Seico** [comment]
Ja pisałem o polskich stronkach

**Comment by Katapulta** [comment]
No wiem że pisałeś o polskich - ale prawdę mówiąc też nie widzę żeby coś znikało... przykładowo na filmy.to  nie widzę "ubytków"

**Comment by Seico** [comment]
Poczekaj , zaczeło sie od wczoraj , no i oczywiście mówię o filmach w dobrej jakości

**Comment by Katapulta** [comment]
Przeskoczyłem kilka stron i również nie zauważyłem żeby coś miało zniknąć... Jeśli były by usuwane materiały to w każdej jakości nie tylko w dobrej.. no ale spoko :)

**Comment by Seico** [comment]
Na filiser wywalili mi wczoraj ponad 400 pozycji , jak napisałem do nich i poprosiłem wyjaśnienie dlaczego tak sie dzieje to mi własnie odpisali to co napisałem wyżej

**Comment by Katapulta** [comment]
Filister padło całkiem - więc przypuszczam że to po prostu akcja jak z Kinomanem - zawineli manatki i za chwile pojawią się pod innym "szyldem". Możliwe że jakieś "pojedyncze" akcje ale nie sądzę. Z kinomanem było tak samo. Alltube działa, zalukaj działa... w Kodi na wtyczkach FanFilm etc wszystko jest dostępne jak było więc ubytku nie widzę żadnego. Zresztą poczekajmy, jesli jest jakaś zorganizowana akcja na pewno w sieci pojawi sie jakieś info - chyba że Kurski robi konkurencję dla swojego PiSFlixa i będzie zmuszał do oglądania filmów i seriali z PRLu.. :D

**Comment by Seico** [comment]
Takie info od wczoraj jest na alltube : 
"AWARIA HOSTA STREAMIN I FLAS/X OMIJAJCIE TE PLAYERY * JEŚLI JEST JAKIS PROBLEM NAPISZ NAM TO W ZAKŁADCE KONTAKT ;)

Wiec , obym się mylił ale coś zaczyna sie dziać

**Comment by Katapulta** [comment]
No mylisz się - na all tube hosty mają jaką awarię ale inne źródła działają bez problemu bo oglądam w tym momencie wiec nie wiem po co ta panika :D 
http://prntscr.com/ffcfd1

**Comment by Seico** [comment]
Ja nie robie paniki , tylko piszę że może wkrótce "życzliwi" przyjdą gdzie indziej tak jak na filiser i poproszą o usunięcie wszystkich filmów które naruszają prawa autorskie tych producentów

**Comment by patolu** [comment]
Coś jest na rzeczy ? Wczoraj padła stronka z linkami pebx.pl, a od kilku dni nie działa exsite.pl.
