### ISSUE TITLE
E-kino tv nie działają filmy

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#305]
Witam

Wtyczka E-kino.tv nie działaja filmy 

Android kodi 17.3 

Proszę o naprawę

Ps. Dzięki za pracę włożoną w repo

**Comment by ramicspa** [comment]
Hej. Podaj jakiegoś działającego linka. Łatwiej będzie naprawić wtyczkę.

**Comment by Cerber2000** [comment]
Na stronie http://ekino-tv.pl filmy działają

[http://ekino-tv.pl/movie/show/skrzypek-the-violin-player-2016-lektor/19889](url)

Film Skrzypek działa, wtyczka wywala błąd dodatku

**Comment by ramicspa** [comment]
ok dzieki za linka ... pojawi sie aktualizacja
