### ISSUE TITLE
repo nie dziala ?

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#306]
Witam
zainstalowalem od nowa kodi na win I repo ze zrodla lecz nic nie chce dzialac. 
nic sie nie instaluje jakis pomysl .
ps. wczesniej natomiast mialem komunikat o aktualizacji repo , poniewaz tez nic nie chcialo dzialac. 
pozdro

**Comment by krriss** [comment]
Chyba wszystkim padło

**Comment by ramicspa** [comment]
nie wszystkim ;) ... problem powinien zniknac niebawem
