### ISSUE TITLE
cda.pl - wyszukiwarka omija wersje HD

### ISSUE THREAD

**Issue by drrak** [ramicspa/kodi#308]
Zwróciłem na to uwagę kiedy szukałem filmu pt. _Porąbani (2010)_. Na stronie cda.pl wyszukiwarka pokazuje pierwszy znaleziony film w jakości 720p, a w Kodi (17.3) jest wszystko poza tym filmem. Dziwne to trochę, bo inne tytuły w jakości HD/1080p znalazłem bez problemów.

cda.pl 1.9.2, LibreELEC 8.0.2, RPi2

**Comment by ramicspa** [comment]
aktualnie poskie znaki sa usuwana przy wyszukiwaniu

**Comment by drrak** [comment]
Nie używam polskich znaków w wyszukiwarce. Tytuł 720p jest omijany tak czy siak.

Btw. Dziś wyskoczyło mi coś takiego: "_Problem. Uaktualnij repozytorium oraz plugin by go uruchomić_". Z tego co wiem, to mam ostatnią wersję repozytorium (1.3.1) i cda.pl (1.9.2).

**Comment by drrak** [comment]
Mam tu taka teorię. Może wynik wyszukiwania nie jest usuwany przez polskie znaki (bo przecież inne tytuły z ogonkami są wyświetlane), tylko przez **link** w opisie pod filmem. Spróbowałem wyszukać inny film z linkiem w opisie i wtyczka też go wywaliła.

**Comment by ramicspa** [comment]
wtyczka dostala aktualizacje
