### ISSUE TITLE
cda.pl parsowanie tytułów filmów

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#309]
Witam.
Przy wpisaniu np lego batman dostajemy listę tytułów (m.in)
Lego Batman: Film PL Dubbing
Lego & reg ; Batman: Film PL Dubing (zrobiłem spacje przy reg bo inaczej parsuje w ®)
 
Czy byłaby możliwość przeparsowania tak nazw plików żeby wywalić z nich określenia typu & reg ; (i zastąpienie ich ®) ale także usunięcie Dubbing pl i wrzucenie tego do opisu jak to np. ma miejsce we wtyczce alltube.tv (tam pod dacie filmu pojawia się eng /lektor/napisy)
Jeśli w parsowaniu nie znaleziono by dubbing czy " PL " to wtedy z automatu by wciskać org., w innych przypadkach wychwytywać czy to lektor czy dubbing - to chyba nie jest awykonalne - to tylko przeprasowanie nazwy pod kątem słów kluczy takich jak: lektor, dubbing, pl, napisy, eng,  dubing pl

**Comment by Zigi1974** [comment]
Tomasiek a Tobie wszystko normalnie dziala ja mam caly czas na kazdej wtyczce blad polaczenia z repo . jak na win i andku to samo .
pozdro

**Comment by ramicspa** [comment]
mi tez wszystko dziala normalnie ...
co do cda - to fakt - przyda sie poprawka parsowania tekstu

**Comment by tomasiek** [comment]
Powiem tak. Na libreelec działa mi świetnie, na linuksie pojawił mi się ten
błąd, musiałem wyczyścić kodi do zera i zaczęło działać.

07.06.2017 10:48 PM "ramicspa" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
opcja 'czyszczenia' tytulow dodana

**Comment by tomasiek** [comment]
Ale padło pobieranie okładek z filmweb

14.06.2017 11:20 PM "ramicspa" <notifications@github.com> napisał(a):
