### ISSUE TITLE
Poradnik tworzenia wtyczek 

### ISSUE THREAD

**Issue by eko5** [ramicspa/kodi#31]
Jesli jest to mozliwe napisał byś poradnik tworzenia takich wtyczek , bo powiem szczeze sam bym się pobawił w pisanie dodatków . Wersej angielskie nie wyjaśniaja dużo problemów które się pojawiaja podczas procesu tworzenia .

**Comment by Marcino2404** [comment]
Przyłączam się do tematu.

**Comment by ramicspa** [comment]
Dokumentacja odnosnie tworzenia dodatkow jest calkiem dobra i wyjasnia wiekszoc problemow zwiazanych z tworzeniem dodatku dla kodi (http://kodi.wiki/view/Add-on_development). To co tam pomineli to zbieranie informacji ze stron (web scraping) ale sa inne tutoraiale do tego np: https://www.summet.com/dmsi/html/readingTheWeb.html. Po tez kod zrodlowy wytczek jest dostepny na githubie byscie mogli to wykorzystac. Spora czesc stron jest zabepieczona i z nich duzo trudniej wyciagnac informacje ale duzo jest bardzo prostych. 
Rozbierzcie najpierw na czesci np wtyczke iitv bo jest bardzo prosta.

Jak sie pojawi jakis konkretny problem to piszczie smialo - pomoge.

**Comment by sebciu0** [comment]
Hejka,
A czy mogłbyś mi pomóc w zrobieniu repozytorium? Repka by była dla wsłanych potrzeb także nie potrzebowałbym githuba. Ogólnie to wygląda tak, chciałbym wrzucić zrobić repkę z moich zasobów które mam na NASie.
POzdro
