### ISSUE TITLE
zalukaj.com nie dziala jak trzeba

### ISSUE THREAD

**Issue by luk1982x** [ramicspa/kodi#314]
witam
odtwarzanie filmow z zalukaj.com dziala ale tylko z limitami bez logowania
po dodaniu loginu z oplaconym kontem w kodi nie idzie odtworzyc zadnego filmu
niby sie laduje i w pasku source gdzie powinno wyswietlic bitrate do wyboru nie ma nic
po zalogowaniu na stronie tym samym loginem wszystko dziala jak trzeba
pozdrawiam

**Comment by ramicspa** [comment]
witam, moze i tak byc. nigdy nie testowalem wtyczki z profilem premium.
