### ISSUE TITLE
Problem z iitv

### ISSUE THREAD

**Issue by Migdal44** [ramicspa/kodi#318]
Witam, 
jak w temacie problem mam z wtyczką iitv, wszystko ładnie się instaluje, mogę przeglądać zawartość ale w momencie uruchomienia jakiegoś filmu a konkretnie z rozszerzeniem openload.co to kiedyś wołało o sparowanie ze stroną openload.co/pair a od pewnego czasu nic się nie dzieje i nie uruchamia.
Na innych wtyczkach filmy z rozszerzeniem openload.co działają idealnie, woła o sparowanie i działa.
Zrobiłem reset wszystkiego do ustawień fabrycznych razem z tv i bez rezultatu niestety.
Na iitv wszystko działa więc nie bardo rozumiem gdzie może być problem.
Proszę o pomoc

**Comment by ramicspa** [comment]
witaj, podaj przyklad gdzie jest problem ... sprawdzalem na ostatnio dodanych i wszystko mi dziala

**Comment by Migdal44** [comment]
nie działają mi wszystkie filmy z serwerów openload.co, jeśli to to tylko u mnie to poradźcie co zrobić bo jeśli reset wszystkiego razem z tv do ustawień fabrycznych nie pomaga to nie mam pomysłu co z tym zrobić.
Najbardziej mi zależy na dostępie do supernatural :)

**Comment by Katapulta** [comment]
U mnie na każdej "platformie" jeśli o openload chodzi działa i śmiga wszystko. A sam osobiście używam jeśli chodzi o repo Ramica tylko Filmy.to. Z innych wtyczek - Exodus, Specto, Fan-Film i z openload nie mam żadnego problemu... Źródła ittv również śmigają bez problemu... Może sparować trzeba ;> http://olpair.com/

**Comment by Migdal44** [comment]
na wszystkich innych platwormach u mnie też działa openload.co i jak jest nie sparowane 
http://olpair.com/ to wyskakuje komunikat żeby to zrobić tylko na iitv ani komunikatu ze niesparowane i żadnej informacji żeby coś się  ładowało. 
czasem pojawia się komunikat że nie może otworzyć danego pliku i że błąd jest zapisany w rejestrze tylko że nie mogę znaleźć tego rejestru żeby tam zajrzeć i zobaczyć co poszło nie tak :(

dzięki za zainteresowanie i mam nadzieje że uda nam się znaleźć wspólnie rozwiązanie :)

**Comment by ramicspa** [comment]
dlatego prosilem cie o jakis konrekty tytul by sprawdzic.
Jesli na openload nic nie wyskakuje to znaczy ze link jest martwy - zwsze mozes sprawdzi to na stronie - jak tam dziala a we wtyczne nie - to wtedy zglaszasz buga,

**Comment by Migdal44** [comment]
http://iitv.pl/nie-z-tego-swiata/s10e10-the-hunter-games

Odcinek 10 s10 na iitv smiga jak miło u mnie na tv zero reakcji a po 3 prubie uruchomienia pojawia sie komunikat
![img_20170613_203300](https://user-images.githubusercontent.com/29373353/27098546-40edc5e6-5078-11e7-8255-9caac337a021.jpg)

mam nadzieję że o to prosiłeś?

**Comment by ramicspa** [comment]
dokladnie o to chodzilo.
to uruchom 6 link - ten jest ok ... wczesniejsze sa nieaktywnce co na stronie jest potwierdzone
![image](https://user-images.githubusercontent.com/12544737/27098892-5b02c53e-5079-11e7-806f-9ed5dfa7a5dd.png)

**Comment by Migdal44** [comment]
masz rację że nie wszystkie linki działają na pc ale na tv niema znaczenia który chcę uruchomić, przy każdym bez reakcji, nawet nie woła o sparowanie http://olpair.com/ a po sparowaniu bez zmian. na innych dodatkach filmy z openload działają i wyskakuje komunikat o potrzebie parowania.
wszystko zaktualizowane wczoraj z nowego repozytorium.

**Comment by Migdal44** [comment]
zastanawiam się czy w tym dzienniku diagnostycznym nie będzie jakiejś informacji o problemie tylko że nie mogę go znaleźć, podpowiesz mi gdzie to się znajduje?
