### ISSUE TITLE
LivePolishtv padła cała nic nie można załączyć :(

### ISSUE THREAD

**Issue by jabarroo** [ramicspa/kodi#319]

**Comment by VictorDorian** [comment]
u mnie wszystko działa bez zarzutu. Aktualizacja repozytorium poszła szybko i gładko, dodatki się zainstalowały w moment, sprawidziłem kilka niedziałających wczesniej i śmiga pięknie. Odbieram z UK, brexitu jeszcze nie ma :)

**Comment by VictorDorian** [comment]
już nie działa, zero linków na tele-wizja, dosłownie zero...

**Comment by Katapulta** [comment]
U mnie działa bez problemu... Właśnie w tym momencie oglądam przez tele-wizja..

**Comment by Katapulta** [comment]
Zmienili stronę główną może tu jest problem że nie trybi coś we wtyczce. CHociaż dziwnie u mie wszystko śmiga...

**Comment by grzech87** [comment]
U mnie tez dziala na androidzie ale np wtyczka LiveTV: tele-wizja jest pusta.

**Comment by koladka** [comment]
Wszystko padlo nic nie dziala
