### ISSUE TITLE
Ekstraklasa problem vol.2

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#32]
Witam. Z wtyczki ekstraklasy zniknął Live. To jakaś bardziej skomplikowana sprawa? Wiem, że Ekstraklasa S,A, robi problemy ze wszystkim więc nie zdziwię, że i tu zadziałali. Pozdrawiam

**Comment by ramicspa** [comment]
dailymontion przestalo nadawac live ... poczekamy zobaczymy. jak na stronie sie pojawi to wtyczka tez to znajdzie

**Comment by rafciu27** [comment]
Dzięki za info :)

**Comment by ramicspa** [comment]
live sie pojawilo ... zamykamy temat
