### ISSUE TITLE
Live Polish Tv - Tele-wizja

### ISSUE THREAD

**Issue by Katapulta** [ramicspa/kodi#321]
Dosłownie chwilkę temu zaktualizowałem repo do 1.3.3 i z automatu wszystkie wtyczki których używam. Po aktualizacji 👍 

http://prntscr.com/fj9q6i

Błędy w nazwie kanałów i nie wszystkie kanały da się załadować... poznikały i nie działają min. hbo

W wolnej chwili fajnie by było to poprawić :P

**Comment by koladka** [comment]
Wszystko padlo po dzisiejszej aktualizacji w uk

**Comment by Katapulta** [comment]
No tu nie padło wszystko - działać działa jako tako tylko nazwy kanałów popsute i nie ładuje wszystkich które powinno... Oglądać te które załaduje też się da..

**Comment by ramicspa** [comment]
@koladka Nie badzmy az tak dramatyczni - nie moglo wszystko pasc od tak. Postaraj sie bardziej precyzyjnie przedstawic problem jesli liczysz na pomoc.

**Comment by abrus7** [comment]
Mam to samo, nie mam wgl kanałów na tele-wizja.com jest pusto.. Jakby nie widziało nic.

**Comment by ramicspa** [comment]
poszla aktualizacja ... powinnos sie troche poprawic

**Comment by koladka** [comment]
Niestety widze poprawe tylko na ,,telewizja,, na reszcie stream niewchodzi lub wyrzuca;)

**Comment by kawamic** [comment]
Tylko z tele-wizja był zgłoszony problem. Inne strony nie były testowane.

**Comment by ramicspa** [comment]
telewizja powinna chodzic - ktore serwisy jeszcze wymagaja poprawki?

**Comment by koladka** [comment]
Tak jak pisalem chodzi tylko ::telewizja;;; co do -wizja tv-  i --yoy tv-- wiem ze trzeba miec premium a cala reszta ?

**Comment by ramicspa** [comment]
Reszta powinna działać bo nikt nic nie zgłaszał. Jak coś we wtyczce nie działa jak trzeba a na stronie chodzi to daj znac.

**Comment by koladka** [comment]
Ja zglaszam ze chodza na  ich stronach;)

**Comment by ramicspa** [comment]
Ok fajnie. Sprzedaże więc i inne serwisy przy kolejnej aktualizacji. Im więcej szczegółów się poda tym łatwiej znaleźć problem i go naprawić.

**Comment by koladka** [comment]
Sory za natarczywosc hhe ;) Swietnie ze dzialasz dalej!

**Comment by abrus7** [comment]
Pytanie:D Jest możliwość yoy.tv tylko no właśnie jest to konto premium,jak wpisać tam login i hasło abym mógł zrobić listę:D?

**Comment by koladka** [comment]
Jak masz premium to skorzystaj z ustawien  i konfiguracji  , ja probowalem wykupic pakiet ale z nieznanych mi przyczyn  nie da sie przejsc przez weryfikacje konta ?

**Comment by abrus7** [comment]
No wszystko jest,ale tam nie ma gdzie wpisać loginu i hasła;D

**Comment by koladka** [comment]
Faktycznie ale jest opcja na ftyczce -- Mrknow tv --tam mozesz w opcjach wpisac haslo;)

**Comment by abrus7** [comment]
Po coś chyba na livepolishtv jest ta wtyczka i zapytaniem zapytałem się jak to działa:D

**Comment by Katapulta** [comment]
@ramicspa  coś się sypło... przynajmniej u mnie nie da się listy załadować po tej aktualizacji
https://pastebin.com/UkLytg5Z

**Comment by abrus7** [comment]
U mnie to samo.. Działa tele-wizja są kanały ale nie można ich wgrać do telewizji

**Comment by kashkash18** [comment]
Ramic czy jesteś w stanie dodać do LivePolishTV www.rojadirecta.me , ciekawa alternatywa dla sport365live

**Comment by koladka** [comment]
Chcialem prosic o mozliwosc logowania w yoy tv i poprawe kanalow na nim coby premium tam dzialalo? Dzieki z gory!

**Comment by ramicspa** [comment]
zasoby premiuim nie sa obslugiwane i raczej sie to nie zmieni.
dodatkowo pisales ze cos inne gonie dziala - sprawdzilem sporo i sporo dziala. Wiecej konkretow nastepnym razem

**Comment by abrus7** [comment]
Kodi 16.1 nie działaj tele-wizja. Nie ma kanałów android. Na laptopie mam tele-wizję na 16.1. Aktualizowałem tu i tam,czemu nie działa;)?

**Comment by koladka** [comment]
Niestety tak dziala te serwery sa obciazone ,raz cos dziala raz nie ;) Mam alternarywe zainstaluj apke z google store -- ketchup tv swietnie chodzi Polska tv i inne przebija nawet Yoy tv;)

**Comment by abrus7** [comment]
A co ma jedno do drugiego? Jak działa tele-wizja ale na livepolish nie ma kanałów pusta lista.

**Comment by koladka** [comment]
To ma jedno do drugiego ze w przeciwienstwie do ciaglego  motania i naprawiania wtyczki ta apka dziala non stop;) tak samo Mr know ma to samo raz tam dziala raz nie;)

**Comment by tomasiek** [comment]
@koladka - a sprawdź czy ta apka nie działa na zasadzie p2p zanim wpadnie do ciebie cbś

**Comment by koladka** [comment]
Chocby nawet wszystko w internecie tak dziala ;) wiec spoko nie strasz ludzi? Pozatym urzywam vpn, a co do wyboru kazdy  oglada co wybiera i tyle

**Comment by Katapulta** [comment]
@koladka w przypadku telewizji obciążenie nie ma nic do rzeczy - więc nie wiem o czym piszesz i skąd takie rewelacje wyciągasz. Jeśli w przypadku telewizja nie działa coś na Kodi to jest to spowodowane głównie tym że "u źródła" czyli na stronie telewizji padły hosty bądź je zmienili albo @ramicspa  coś się "wkradło" podczas aktualizacji.  Stąd ciągłe jak to piszesz "motanie się i naprawianie". I tak super że człowiekowi chce się z tym babrać i co chwilę poprawiać. Telewizja jest darmową stroną bez płatnego dostępu - i tak powinno być. Płacenie za dostęp do stron które TV nielegalnie udostępniają jest największą głupotą i w przypadku "zamknięcia strony" może skończyć się przykrymi konsekwencjami dla abonenta czyli osoby która sobie dostęp wykupiła - i bywało tak nie jeden raz. Jak chcesz płacić za kechupy i inne syfy ( co to w ogóle za badziewne strony to nie wiem ) - płać twoja sprawa ale większość korzysta z tele-wizja bo jest darmowa. A "padanie" hostów / streamów jest wpisane w "koszta" używania darmowych rzeczy.

**Comment by tomasiek** [comment]
@koladka 

> Chocby nawet wszystko w internecie tak dziala

No właśnie nie wszystko. cda, openload, youtube, cinemahd i tysiące innych nie działa na zasadzie p2p. Ale takie wynalazki jak apki na andka z iptv b.często działają na zasadzie p2p, zaś uŻywanie vpn nic nie da... wydłuża tylko czas namierzenia z 30 sekund do 30 minut.
> w przeciwienstwie do ciaglego motania i naprawiania wtyczki

Ale wiesz że obowiązku używania wtyczek ramicspa jeszcze nie ma?

**Comment by koladka** [comment]
Ja tylko swoje uwagi pisze i tyle odnosnie repo ;) Niemam zamiaru swoich racji wciskac  jak tu nie ktorzy poniekad;) A odnosnie vpn np vanish to sobie kolego TOMASiek rozne zdania kazdy moze miec swoje zrodla wiedzy;( typowo Polskie dogrysc

**Comment by Katapulta** [comment]
@koladka  typowo polskie - wpaść i jęczeć że coś złe a ja mam dobre. Nie wiem skąd ty masz takowe informacje ciekawe i źródła wiedzy - pewnie od kolegów bo jeśli ktoś ci powie że vpn daje ci ochronę i anonimowość w sieci to najwidoczniej nigdy w życiu z komputera nie korzystał :) A jeśli masz różne zdania - idź opowiedz o tym komuś kto słucha - to nie jest miejsce na gorzkie żale czy sesje terapeutyczne i leczenie problemów tylko na zgłaszanie błędów i pomoc z wtyczkami napisanymi przez ramica.

**Comment by koladka** [comment]
Moze jeszcze jakis Polaczek cos napisze hhhaa

**Comment by tomasiek** [comment]
@koladka patrząc na twój styl wypowiedzi, ortografię i interpunkcję,
proponuję darować sobie uwagi o "Polaczkach".  Bo dość słabo słabo to
wygląda...

20.06.2017 6:03 PM "koladka" <notifications@github.com> napisał(a):

**Comment by koladka** [comment]
Hha nastepny ciekawe ilu jeszcze ;)

**Comment by tomasiek** [comment]
EOT. Na mnie już nie licz. Kolejny Marcinek nam się pojawił.

20.06.2017 6:15 PM "koladka" <notifications@github.com> napisał(a):

**Comment by clowni** [comment]
@ramicspa Pisalem wczesniej na temat wtyczki, ze Wizja TV uzywa portu 81 w adresie IP dla uzytkownikow premium, natomiast uzytkownicy standard sa na 80 i stad limit uzywania Wizja TV tylko 3h, gdzie czesto jest to mniej. Prosilem o ta poprawke.

Natomiast inna sprawa tworze listy TV i ciagle mi nic nie chodzi na Kodi Jarvis 16.1, mam crona i ustawienia tak jak opisane i ciagle nie chca mi sie ladowac streamy. Co mozna poprawic ?

**Comment by Lupuses** [comment]
Hej podbijam pytanie.. Jest jakaś opcja ze bedzie możliwość używania konta premium na wizja.tv?

**Comment by witstg** [comment]
Hej, można poprosić o dodanie opcji tworzenia listy m3u z serwisu televhs? zależe mi na programie domo+ a tylko tam jest działający stream.
