### ISSUE TITLE
Kotek

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#322]
Co jest z tym kotkem co spiewa piosenke po restarcie kodi? 
Po drugie nie moge zrobic zanego update ramic repository a co za tym idzie nie dzialaja wtyczki, 
Czytalem serverach ale nie wiem czy to jest ten problem? 
Jakas pomoc?

**Comment by tomasiek** [comment]
A repozytorium skąd masz? Stąd czy z Fusion? Jeśli to drugie, to zainstaluj
z tej strony.

15.06.2017 12:50 AM "wisiann" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
A kotek nie ma nic wspólnego z reportaż ramica.
http://www.ares-project-blog.com/kodi-news/dancing-skeletons-raving-pigeons/

15.06.2017 6:07 AM "Tomasz Woś" <tomasz.wos@gmail.com> napisał(a):

**Comment by wisiann** [comment]
Repo mam stad,
Moze musze wszystko przeinstalowac?

**Comment by tomasiek** [comment]
Ostatnio była zmiana, przeinstaluj samo repo, pobierając je na nowo.

15.06.2017 12:41 PM "wisiann" <notifications@github.com> napisał(a):

**Comment by wisiann** [comment]
Dzieki
