### ISSUE TITLE
cda premium - szukanie, rozdzielczość, seriale

### ISSUE THREAD

**Issue by drrak** [ramicspa/kodi#324]
Dziękuję za ostatnią aktualizację, wyszukiwarka działa lepiej, chociaż filmów i seriali premium nie widać w wynikach szukania, mimo że mam je uwzględnione w opcjach "szukaj cda.pl" (np. film "Naznaczony 2010" i serial "Hannibal").

Wszystkie filmy premium uruchamiane są w niskich rozdzielczościach.

Zastanawiam się, czy mógłbyś kiedyś dodać przeglądanie folderów z serialami na cda.pl. Chodzi o wygodny dostęp do całych sezonów.

**Comment by ramicspa** [comment]
nawet nie wiedzialem ze na premium sa dostepne jakies seriale. powinno dac rade dodania przegladania katalogow dla premium.
faktycznie, premium nie sa uwzgledniana ... pojawi sie poprawka
