### ISSUE TITLE
Filiser zmartwychwstał

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#325]
Hejka
Filiser zmartwychwstał :)  - https://fili.tv
Bardzo proszę o zmianę we wtyczce adresu dostępowego

**Comment by Katapulta** [comment]
Ale nie wiem czy to filister czy jego podrubka. Bo na oficjalnym http://filiser.pl/ informacja jest jednoznaczna : 
"Nie oferujemy już filmów i seriali online, ale możesz obejrzeć powyższy klip"

Chyba że to zamiennik albo fanowska strona.

**Comment by Seico** [comment]
Cała baza filmów została przeniesiona z fliliser.pl

**Comment by Migdal44** [comment]
jak by zadziałało to było by super, rozwiązało by mój problem z iitv, baza seriali jest naprawdę imponująca, dajcie znać kiedy uda się będzie działać, 
dzięki pozdrawiam

**Comment by Seico** [comment]
Wtyczka już jest zaktualizowana , działa ok

**Comment by Migdal44** [comment]
działa super, polecam

**Comment by ramicspa** [comment]
ok, jak znow cos padnie dajcie znac
