### ISSUE TITLE
Nieudane instalowanie zależnego dodatku

### ISSUE THREAD

**Issue by krz87** [ramicspa/kodi#327]
Hej,
zachciało mi się odświeżenia Kodi i postawiłem 17.3 od zera. Wszystko ok, do momentu jak zabrałem się za repozytorium Remic. Przy próbie instalacji z repozytorium wyskakuje mi taki błąd:
"Nieudane instalowanie zależnego dodatku".
Przy każdym dodatku jaki wybiorę.

Co ciekawe, w necie brak inforamcji o takim błędzie. A przynajmniej rozwiązaniu. Później spróbuję zmienić na język angielski i wyszukać jakiegoś rozwiązania, ale może mi coś w między czasie podpowiecie.

Pozdrawiam.

**Comment by tomasiek** [comment]
Skąd instalowałeś? Z oficjalnego repo?
`Repozytorium wtyczek dla programu KODI repository.ramic.zip (wersja 1.3.3) 
Zainstaluj z pliku zip poprzez źródło: `http://ramicspa.github.io/kodi/`

**Comment by krz87** [comment]
Leciałem z jakiegoś poradnika kodiwpigulce.pl Był link do oficjalnego zipa i jakiegoś mirrora od nich. Na obu to samo. Część wtyczek wykrywa w innych repo jako Superrepo i tam błąd wyskakuje ten sam. Dodam, że z innymi wtyczkami nie miałem takiego problemu.
Wpisując ten błąd w necie wyskakują ze 4 wyniki i chyba wszystkie odnoszą się do Ramica.

**Comment by tomasiek** [comment]
Czyli pewnie stare repo - były pewne zamieszania w związku z problemami offshoregit, pewnie nie wszędzie się zaktualizowało. Zainstaluj z stąd:
https://github.com/ramicspa/kodi/raw/master/repository.ramic.zip

**Comment by krz87** [comment]
Ok, później spróbuję. Dzięki.

**Comment by krz87** [comment]
Odinstalowałem repo i dodałem jeszcze raz z Twojego linku. Nie pomogło. 
Log viewer pokazał: Failed to install dependency script.module.ramic.
Znalazłem w necie, doinstalowałem i dopiero teraz wtyczki działają.

Problem rozwiązany, ale dlaczego występuje tylko u mnie?

**Comment by ramicspa** [comment]
faktycznie to dziwne bo wszystkie zaleznosci powinny sie same zainstalowac. Zwykle reinstalacja i/lub restart pomaga
