### ISSUE TITLE
eKinko.pl

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#328]
Od dnia 31.05.2017 serwis eKinko.pl funkcjonuje pod nowym adresem! BoxFilm.pl

**Comment by ramicspa** [comment]
warto wiedziec ... nigdy tam nie zagladalem ... cos ciekawego?

**Comment by xxcriticxx** [comment]
no clue tak tylko podalem source sa na openlodzie

**Comment by xxcriticxx** [comment]
sorry do tego nawet wtyczki niema

**Comment by tomasiek** [comment]
Na 3 testowe filmy nie ma żadnego :(
Z box office http://www.filmweb.pl/boxOffice/ranking z pierwszej piątki nie ma niczego :(

**Comment by xxcriticxx** [comment]
dzieki za recenzje
