### ISSUE TITLE
tele-wizja

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#332]
Witam, tele-wizja na kodi 16.1 nie działa w polishlivetv nie można listy ani w livepolish tv tele-wizja jest pusta lista.
Yoy.tv - nie można aby się zalogować i listę utworzyć? Pozdrawiam

**Comment by tomasiek** [comment]
Na kodi 16.1 coraz mniej rzeczy będzie działać. Zaktualizuj do k17. 
Na k17.3 zarówno pokazuje listę, jak i odtwarza.
Co do yoy.tv i logowania - już było: https://github.com/ramicspa/kodi/issues/321#issuecomment-309566760

**Comment by abrus7** [comment]
Mam 17.3 zaktualizowalem to nie dziala tez:)

**Comment by abrus7** [comment]
A 17.3 to gorzej mi dzialalo od 16.1 musialem cofnac wszystko aby tv mi odbierala

**Comment by tomasiek** [comment]
W takim razie pokaż logi.
Pamiętaj o tym że pod 16.1 będzie działać coraz mniej dodatków i serwisów

**Comment by ramicspa** [comment]
kodi 16 nie jest wspierany wiec jesli cos ci tam nie dziala to najpierw zaktualizuj kodi do najnowszej wersji.
aktualizacja powinna rozwiazac wiekszosc problemow.
i jeszcze raz - permium nie jest i nie bedzie obslugiwane!
