### ISSUE TITLE
yoy.tv

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#333]
Witam,da radę jakąś aplikację zrobić do yoy.tv i z niej aby można zrobić listę? Pozdrawiam

**Comment by tomasiek** [comment]
Ale przecież yoy.tv jest we wtyczce LivePolishTv....

**Comment by ramicspa** [comment]
zgadza sie. yoy jest i liste tez mozna zrobic, ale konta premium nie beda obslugiwane.
