### ISSUE TITLE
Rojadirecta

### ISSUE THREAD

**Issue by kashkash18** [ramicspa/kodi#334]
Ramic czy jesteś w stanie dodać do LivePolishTV www.rojadirecta.me , ciekawa alternatywa dla sport365live

**Comment by ramicspa** [comment]
jest juz wtyczka do tego

**Comment by kashkash18** [comment]
Sprawdzałem dziś w SportsDevil i faktycznie jest tam ta wtyczka aczkolwiek nie działa . Nawet zaktualizowałem wtyczke do najnowszej wersji i beret. Może jednak dał byś się namówić by dodać to do LivePolishTv. Na sport365 brak dzisiejszych meczy polskich drużyn a na Roja lecą .

**Comment by kashkash18** [comment]
Ramic jest jakaś szansa w tym temacie ?? W przyszłym tygodniu rozpoczną się męczę rewanżowe a na polską TV nie ma co liczyć , niestety streamów z tych spotkań w sport365 też pewnie nie będzie.

**Comment by ramicspa** [comment]
sprawdzilem SportsDevil i dziala tam Rojadirecta - bez sensu jest duplikowac. zrodla pochodza z wielu roznych stron - jak to czesto bywa nie wszystkie dzilaja - ale cos zadziala. a jeszcze jedno - badzo slaba jakosc streamow.
