### ISSUE TITLE
iitv-seriale android box  - brak odtwarzania streamów

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#335]
Witam
Mam android boxa z kodi 17.3 i we wtyczce "iitv-seriale" jest brak odtwarzania filmów z np.openload.co , dodam że w innych wtyczkach nie ma tego problemu , na windowsie 10 jest wszystko ok

Bardzo proszę o poprawe tej wtyczki

**Comment by ramicspa** [comment]
hmmm ... android mowisz sprawia problemy ... i nie lubi sie z openload ... ciekawy przypadek, zobacze co da sie zrobic

**Comment by Seico** [comment]
Poszła aktualizacja ale wyskakuje błąd , przesyłam log
https://pastebin.com/fmmWacR2

**Comment by ramicspa** [comment]
fakt, naprawilem jedno a popsulem drugie ... poszedl update powinno juz wszystko smigac.

**Comment by Seico** [comment]
Ok, teraz wszystko działa ok , dzięki :)
