### ISSUE TITLE
efilmy problem 

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#336]
Witam 
nie moge wlaczyc zadnego filmy , wyskakuje caly czas blad

log.......

22:19:11.605 T:3780   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.efilmy.online/?foldername=&page=1&ex_link=https%3A%2F%2Fefilmy.online%2Fkategoria%2Fakcja%2F&mode=ListMovies
22:19:11.605 T:3780   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.efilmy.online/?foldername=&page=1&ex_link=https%3A%2F%2Fefilmy.online%2Fkategoria%2Fakcja%2F&mode=ListMovies) failed
22:19:11.635 T:632  NOTICE: URLResolver: Initializing URLResolver version: 3.0.29
22:19:15.509 T:3780   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
22:19:16.069 T:4232  NOTICE: URLResolver: Initializing URLResolver version: 3.0.29
22:19:35.545 T:6728  NOTICE: Previous line repeats 2 times.
22:19:35.545 T:6728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\......\AppData\Roaming\Kodi\addons\plugin.video.efilmy\main.py", line 2, in <module>
                                                import zlib, base64; exec(zlib.decompress(base64.b64decode('eNrtXVt2rLCOHU53//Ey2HO5PxioMdzhd6CAkoQ2NmAqlZx8ZJ06CQXGDz22pK3hv0P3v//zn/8W5ddP9vXTf/20879f/6+/fl8/vn6qrx/39TN8/TT/+W/ZPv/emK+f8W/18zul3d4na+fvfn1usuf9muL5vekeX89o3PPf6dru6z75f/5rxuea573Hz+O1Zb/9TvE1pqZ+Xjvdt5yf93iOd7rPMvb6+fvxHsZ/3W/8t3/de7l/WfCxjP/Sn72xjd8d71tWz/mQ9wm9W9nM36le10xrIe6BxlHYnXG659qN98/ccy2na8frvsZdz/elz6M/8n7rfZSxhd5z2Qd1FTHueb2mPZbPa+a2z6drtfvswHPKlj9Le07o/rHzURgyJvPcp3Q+gu/l9HWImYOYOVvmY+/dlzNU+OP33rvv+Fw2/257HrTvLNdrcxIlX+Z1mJ5HZaB5rc0479Pn8bp2vsbx9Rvfb3Mv+9z36xpr52C+bjyP07WOyNXsmFxavkP3U2ge5DoG97Hb7uWY6xd5vMxH1Pg6opvoHGV8/pezNM1//9IP0/ViLYPnxikyxzyvnfSNSbTvyufY6P6I3Wd/e+v37K3pXrNt1Sz3Js+e7B2iq7Xn7M3PEZtsnJNlPMVsK6y22t49lnEv43FPG2O6H/jbandF3nf6e07sPhPxfTvbOv1znafxiN+NdtG0tg78PZ/1QfWyM48+t5n35PSc5rW/Dr3/sk8WHdVxWzh0r3Wfm/mzn9+3en1vmdNFLjXEhpz2XkbOB3iOmeXaKo/y+Z3N82+r7S7HbuZ5W67Jnvc5+vxm5/kNeH5dkfPdP9+7WPZbefG9lj1E5p/qgTP3HfXDqe/ZY77FOCfF1/eGr/+348/y+et7bU0+W/K5e332GflMvusfyj2z5z2LRU857k/F6te9H+RTLnJlkgU19xeRbxi09ZXnLud+2qs2chzCB2LXlOF3hnMQkK2Tr638fny/ZjkXse9QPN9heZ/F1pdrLNd6z/+KescIWT6OudJ+b/EePDMu5C8G7zkQ+VXpY60k5nH1nFv9DLcV+X1Oft+S7/bkc7M9zyZ7voMZ38XGr+WPmDdH5qck82PI78k17cDnis4/koPaPMTKn409NLx0/XQ2hvmcd9y+NRn5v9Xn6SPXoyXzTvduQz4boNNaZZ2orht/PF97umbTz0CwPYktXH03T96h1T+v75PxveZbZY7mz3LfbfBXuRcWmZ/Nf1swkFnHrfjf3velrzt/byMruotzRm0TC84nkHH0eo9sH6+c/2y7Z9Y5vvo+vW53sb1bgbXutvtVs3UoJgzHJuTMZt38xfckspHZlJW+Dux80/X0uj1K9VrbKOucifXs+Bos87hny+xiKzt6rxpe8jHG50XyGOkJ6uNocQBtzLFj0ObgyDikvX12PKt+61/YbOiZoVhI7FxN8k259y4W3p+TmYdshC6djUjPDLWBqHxisrRU7KHx5wFkcgG+S21T7btS9g77dtWhmFZH9tSMIYz/X+ysCVtxr/gpw2ftfI17ysZpjYpnHHXFHmj8A33XzN/Lthj13ve0/RsdSwPvjM6Pds91TlLY2lKvPcgag3OywdDtwX1gX2s8/n3FrQEe3VgFVz4wX8VA7KrUdmQL7N8a+CzkbHmql2t9PcYzyuyMgcc+xjlpSPwjhAuEbJGP3Ktetx1GmfjOvbrEue/er8sa3ur/dMAGz4F9SPcqkR3egrUpFF1BZfJsl602T0hfL/i2I/u/TDAPPdCfDujeTLkmE3ayATjGAHRsy+1kOm8afl/M2H495+HIGMSKFWh/IzpMuyeNW8i/I3tUne8O29Kh6zUb8mgeSVDWJcBg1jhBReZ5vubyvmxATCDXzySVkeNe1LCUhsTSpnNUJcQ6x+d2YE+brSzY7K2d+NWn7z2Zn3PVHltlTEZkiZSvdUIcpAX7qEn4DM91g2YDMR1DMNwljrTZM1SfiNjQof2y6POcYL2zfF0w3vHz9L0lV2SO/yD5fFa2ar77bh5MQWR+TWRQ9cp7mHIfEtoLjsggS3SmNUAWAOyHYkJszz90+9oNihyUe8vxPbuXP1EM4u8PjsEmsy0kvmZ0LJT55o0+H0wePICdUSp4diYwu073/ZnN53RMEMVjPMJyi3AMDGHFMAZRHcQ9cmCrAduX2Woe+HUoDtKAsYX0eM7tUTbOMmyjI1yd4bDkemeVszt+JvNmyT0dsX2tU86xHGcF7IRW8WlnObbEmNd8Pifyz3f831QYuYxLreP2YTvmrF1zVO6nstnY+3Uciw++m9vPuUfvEaszY54XZd8J3f6Ose7p99j8T5iHQXPuxrjv4nvkpEahIWdoIPYRqUVJGa93SAY4IOeozZkDzLsAceNFVn393WbAp86Bvm2A7q3AZwfuiWJn2n3EOJnONEAHmsCcZHG6yCPdNQTiANIe77ldtdq07mUzTVhEaK+6Z0xujHEa84xxjntsjHdW3Rz7tPP/h+c1VR8vk47IkFPnciC2YsNzAxc/gtZHfYesifUtYjGVYIzDJvQ/nS47bKacf2EHMp/DAtlB/Q8az5qxsVi/D/nDcI66nXv3BCt26fZ6aB/E4F1N+Sa8y4O8VxNhTz7COEUox//y3IIal39qDZF/g2LL4nwnz+sROKrNBbbuE9pXj7kmICHu6/IIfxHEGhiGQv22GCy5AmvnwbOMnuPugV3HfPoa2HsFiJ9qcauv59smwt4DesYWCfee1X3ntgq/Mxp3C2oIWN6i1W07huG0YB5LBatDdq2wO1uQH8Ywk4qsE4qRA9wp6t2Rz9CAzzH3jMh3VddIvlcP1qIEZyw/6RfJ/V1H5LQWYE/aCIxrAM8F+7lFPo8J5+HC81KD8XgdT2O+DT3/JdALsjaDxqBn/7nMjmFBKwZdn8d/kmBATsfYLYkdnsZp/vwN1Say5nf5G7/Sn5j19lV/Yo+TRPtR845IbGoaR0XyYmY8U+Y37+aMLDWwOa5l02JkhnxvsovNC4OPGSfMN6HjGXh92XoGSEwgWR0mjWUCm1a1TUT+PI2ZMHvKA72EfJ9mi62lijvaHpyDLqLmNA/EtETeIovhloo/IcbmgG3E7CGk+71irwi7x5K5d0avmWVrW4HYdM1jQJp95igWXij7S3xX9UXEPS3A1FGNDd13rgF5qZU+P8y+dHq8mX2uQD5gDvJbvbJGUu5SXdnq70J9YpfrOSXU32V+JziXbP6NfnZaA+pdEDbfg3s6YLuXJ/MNxV5iZ+EBcm5ysLdb3bZRY+17+xnEmFu0JwvgB6JckRbsPSSjjH493Q/WhmO7lENiqZOpB14zEKtTQ3knTDeinLmd2EVs3hB8l52Y/Km5WXLvCS9KMB91j9vl4LvH8sQFc0YHkhdvSCxM2EDT/XuRs92Fc1VRPdOUd97hXEgYU+rT4ZHWRNQsIX8enHGG2yHMGOUDWaU+d09+tuDsO8X+ErXU1VIPUXCsf7LBCcfQuq/n+1QzfmBITUXjyL26V+zULDmChnAI1a/a8pVLotLXNcYnRPnRaO8s9Q7QpzA4L0X+wPoKn7CW7hHGyVS+hdnmoNjHkTN8Nm8CYYIqP8Qe3n+WZ2J8b6+8N5BzyWqlHMBITbgmm73rAM40rc/OBA+rlNOpcAYTgT3XwAfs+Roc1RFNH7YTjtaABeNiHa/HqdyL82LCnTR9GWHLSCwJyabLOfcdwMgRVwGKY3ruU93BT8D88iwiHuH0XGJ27h8Jx9ro+cct8muKCJ3e8NzTO2J07HMFxodiIwA/dHnCsTowjgzohyYinlqBveE5hpG8vkSOD2AXbR6un2Pv5sGa9Dw/MXkty15cfgA6G/HloGs8OA9VwvcBtQBtGZA/sj7DRNTsRMp3ZlNWL96JFXNu93O/g/fvtpzKMTyuR2t9Y8ay1vu6a3N2WR8iPpwCyJ0G6B6A+bDvAjvI1XwPsX0AfKFNbvjedRrPw7vmtwG4JLL7LahTcUBWIrxeYKlHzmgMPwuN6VV0vu2B8+giavxkzXisj94eqGeI9Pkv+6wlsDEBx5aqK0W+hbNhP665Y80V3jktN/zSfFUgHwzFkDzIaS95zOYK7hN7bczejsaJYvfyhfU0C/ZKcOnlTE/8Ogk5U1h80nI9ENRFHsRk6ohzQ22pNnH81YfrI1U7UOrCiHozhBOEbKpRl4Xkf9Q9Q/yFCWP1tNaY2ddNuIaG7YMayIwW5AjSNenui9WzeswS1FjXej2vBe/E4mltoPZWzvcA7lMDX8ADm6PXuRKvyiyaL1KVJOZUvXL1Jv3U8z4EEqdCPDIhzggWo6KcSbMs1Z4D4wVoTpa88h1cDvHjb+Zo9qPWuJ7gQB9lu4rhWWJPVzxmcZjbW4mXTfaUwJgprliLMdHnRu0Vcr+qfvH/05yivTjOOkeEUwGt7ZH4Cox7nlxfU3LuxmXfLzxKSxxjrwdGcN0in6HVAu69xzj26vHMNVtrAsc1MS8e1PHv1fK3Yf7/8LyG7R1hg40x92mcM1+lPE9JOP1F7pEDORMqn+x4/QPwo+bAZinBc4cDeQxaXH2WN3vxci0XMjZWvshl8yB5EcPzmWo+45WYeYZj8Zf9EYAh+yKQu4O4MSSGLLF52l9r4frued+Ky+/k9Lg89KuaiHrlWs99Oh3rlBzGJcCEO4BrZRdj/Wh/po7T79gztbBn0LjuiPWvsdPvjvkjW7YK7KVsy3f4lpg/qI3yKN5twucMxqjKiPcu3hTzB3nRDM/MgF/XBeRqtsVRtZj/ns5J7cMxmV8AGWrBvqjA+G/KBZBcdx+TC6DwuiXDeI+8/3fgnAWId+YR+GcLzrr5ZpzzO3I7UA4HwuYQ14zI3bkjro/4s7wF+SnALpJcO7fE72Pqd4dwHU0r8m3uiM0ju5zpVpR7juq1HdA97qZ4PKp9r0H80ICYPahZYL6pyJG8pc+KO8AFqNhNPy6/IMJv+5S8gkO68M447xHf56Dej8F2y/7YGO6wO34qtr3JYd/hez7Dl3NHvOuj41+NXhOHsCWVQ3aHP7StgH6pgAxOHf+yPA6r1ZowvmGrc5naPKy7mT9ZAhtqALV6j4BdIWv+Oq5vWfyrO8AZ8Y/Ijb+YmB4TY3X1B+Niwf1CfMFQbEyrTfqLi/3FxYL5WlLG13odMsuBMYpOED04W+D3OoR3viEuFtU3ItB/CJ0HZB/t9RUK1vf4nXxA4Y9QrLSp4/ob7b7TwOXXyuWt6KAjXEQSO5z2tXvVIq+yanjppGn/1lwO14Pw3aowv0qwB0Qt5r9+X28yhnU5UGNvcU3lGd7zDdfV2fUgfO+X5/+DegozLMlx2/7wfB+UAxM24bc59uMcpajF33v2UX4kGEOkfESzrRbFf7TzDpruV9ffp42N0d4pMp+RxoSW5yJ+iQ23xAHZEtJbaL5DnFcax4KqF6WdvfRvmeXC9J2lx00364gZQ6uLBLGXHtTIlYE6l2yb0yFzN+h7mdQxowbUfQhcIKavHJXXR+c+ZU4Nw9xBvxlUz+5PcBgyf4r4cqveovtS9IFL2UfBNwFOJhTLyLY9hm7tD5aLHmSRemqqaTCvHBnmb9w9zx5w5IZqT5U1Sh7rkXvYnpjb7GVHr73QwN5e+ivTtYiyMyS3XyAPKLbuZBnD0qu12pE1K2+mfKc7bbs+zF/LOOkzwBPa8TMtccHN+Qj0+43RL6f6+UiuyQs9e+SZbhZskD5jWaNI7sjNOyeszVTrryWenkXooXZby1r4N8o7C2LEiP8AcVU2vOYqeQ6E9FW7i1iNmNcj/sYu99deHlkkRhOVOx3oa/sxPWpbkGuJeBpArR/qZ8B4RDw4Y318jVzU/AV4lmPXKypuuLMHz+y/YFz94HvRvntn47NnOPUu+xFezy2l8TxWU9cDflEDemI04f4NrCbjofTy3OEYd4BzCOU5ox4DsA4wpr/ChX4ALaiPUd+drlHG70lrIFnvyQFw7dZgDD23+zd9zETc7co5ua3eBOSGO7A/mOxsw/lXKu+t9Ckf27k7wm94KMa7E0fU+vNGyXYXGevYiW/EPCdaVtZ6zDaIk9VYT+3aFSnz+DQO50L0cXJv1hn1DTZ0ar+g2PahgnKovtcngH1tMkXuFKJPkrtR1rmw7PKAbx3yyPd6P+R1HQvRB+Ys1+4da9ZG9AHSep4VvJ/L6fz/OiGf7cGaNDUmfJetm//ZuslsXZGTZwtg61YH+ppXT/6NUIyGxUCycK90b8K1GOo9d2xaN+j90a1V5lz0PqC2LpufDMgtc5NNm/9ym7bY9vq506Y9kvfFcu2VPM4V37+Qs5bMFkQ8tRbkFjvA90ptpGZrR4biy0f6hQXj3Xt5BCDOkizPG/QsQT4567Hhwxy7Leo96IDdF6jPCs3l0ZrAH4uHIlwd9VcqIjjQQd4+tGHdMc6wmPmnNaDIno05T5ex2Ys4a3Cf2eNzc9QWjZrv4Ykn/Sg71Cm2j+ARobYM9dmofcp4bUDNJjtDLeh/RfS973nPd5ULsoqwExH3YBPBvz18k32qvfu77dM2wj6N4WhIbX8inYjqh/IwxzHbs6Wio6Wd48P1VDFcR4fllugp9Ifjfg6OG7Ldk+VAoT3Zncdwz3KD3YadoR4fLiKOZYE86wGmFuA2u+X9+rCeYHUzLXmP4U14bgw3fAN4wgyIhZYBXvkcYN3St3kAbpQYrrWb8XnUw5jlQpB3cVkirNcdy2P5szMDsf0SxCpqkN9bEbwT9dDLQQ6wCdxzr9do6J6iTo/a0vTd2ZwUCdZI8mMSGSZ77fzZlmRuim+yLX1i2/LmuNGvwmURvxXgPmB2UA7q14DudGU8RqvlhN+VYxnM5UyQrxdt45/J2Tvgx8S879txpB9ix7vqG/MwLtjttM/WJ9ntDvB4stxD1KvNkferPzQP44pt3nxQHsa/oAcd8AMBT6F3gT6fct+D+Iuzx3ViECu5qBOP5r1r/DGpdCiq93qHrkyN+ZmUHNaoDqcN8D9K2el4zdGn5xcxv9QCf+gR4FHORZ+EXolbKH18Njw0oo8O8z9zPS7C8s8H0BeC6m4aC/E/yFbyvyyvt4/okVQfy5Nw3Tfakw2IHVaA65Wubf8me9KGz7G3+plrHxEc8QacueFD7UnA7ctwuA5gO48Py+vd63/xYTnRbRbZj+ykbQHzOt5pW/iwbQs5oRv9HNFeGUlsi07X96frviT+HZNDUUTYGYXOD8piCO0b8e9Sl+O0p8dttsUNerMtf1G8+YZ6obb6oHjzhfqh1nxm/ZD1gfXY67tjwfUO6J76w+LNV/RoYkzr7TaEBz43yqsjdQOtjbMhfhWmhmJID8Bf5Y/lYrTuXDzp7pjSXVgYqsm5wkFytJ8z9HdS2AhSXhDsIzYvPeiXpdDV8mz7/XGG6j9C+yUmXxzlRu7uQ3e+P3xsvHT0S6beJHfGVh6B3k1Sbkjc5WA/ldC8xvaNmHIMjvRMW+pPluc/XnUohRN4ecf56VNiDxbVSaMenQ6cm16vE7rSFyaljAius58xkP5mO6uL0JeAX0HymG84O8tn/cia3630WkmWYyLP4WNfbu7KvOHVS+DUOp/lpzv4nJRcT0Gf9RP2LYgleJA3pHK4CpzCZzf0FhO2hlc4Nj5iPhvgm9Y65rbhEk6hY0XMUHIDf8xcuWP53v5xoEdiwXmCb+HILQQPrztfL5hC9oX4MU5hyx5gfVW4Vo7Fa+ic1ZzzPKbPxJ164YzPFDO2t65ZdywvnMkp0KdRzfGScrj5mWt51Zc/0//laD+ks/ZU1Bx887nZq+ef9M5jzut2r95Lk41bv/oTLNeteukfmP+FJ7q50Cfl6poyH5jkPqycvWC99jCxozX7KdZT62kz+fTlq7/dsr4V+Nu0J2Yct+iO9bq8+6wls7XtMb/vO3CUtWdgQvvddaBfZRGulWc1O1mEDm70WDnNRfMAQ2vLQK6X1Ovv4mMtBAd+J3o92Ve+8lks9nKM04B4Zw38ONC/g63xwbipb+P4d47YmXt2ZSrddDb2ZXb0xNTPkfbFvBAL0/KYouSN6MOp9Qed3jV/9X/UZG9MH8zU/ZM/fU1Q/d871+VyD4NC9EmI5DCL4TE73d+sJH14LemX8gaMG9VZMN8T8eB0ACOQMZ+lT0pG+uQmzhFgNd1Uh/XX6iBj7Noo/qqDseyzMe2YPRqrc46Oh8Yhk/ddKjg//Bku2DPzu9eb/vB9B95fc+3VN5+FkVcsVAt+mOsMyBaqP1LmHcKcK2Srgf59/gH8mUdCXLgBfaAWOVgKzvRx/dpZx7r9HIAQLj/u3dKQ3gSR8ilol/xG2XTinK094+f8xcUeOjs/qWVmtOx6x/kFZxbFwr0L5176Fpyn/J4eVYw70JPnFe8/v6n8gWj+Thtvw4buAeUAslErngPT3NAf+1Z7tRS9BZZ5FHnPTK4t9bHNjIfd2QsT8bpXgXrTUvQXWHy44YV50nrzKSdL5OG/9Z07sN4g/wlyidUReF0fMXeCt/2yTavhsyXnOF/kCO1ZNK3NXl7pO9eoAbH9VudB8kc4J6geKgXHeIr5t2CdbcT8H+VTfueagDwMxo3Qgfmm+9Bt53vtMaDNCbV9FFm5YD2azIm1NU/VDSXSORbkWiLZhHLuUb8Odk0D1kRiy6lrcTwY5yPAjSxjEgXQq7IfaaAmaqObuvj6G4k/FgPpy5sTn7vjfW2NwByneZJYZj7PeUXiheNYtN/TuBY559q1lajFSZoPCPjrmA3RKnu/3HLMrjWLqfTfA/gbyJcodD5s9o6IJ4HKepkDfaAWqhlz6fp4H/Xtsqu4N/aJ4pTeBupyBT85u6YHsrQD/TmrBBwnko+EytvhmLy6w+dmfjaIdTKs+6H0NZe+Uavk+4mzpOa37/UOzpT+GPJ8tnq+MbMLj/bieOj13swOqsF9tBhuCXiGb6x7hTUdVp87m7qHTyn4iA/o2WT2VQTmpPZUkfuQclO3wO8vAn6zyJGEvXzLQN1tueW83a2b3cF1j+RGfbvuARwPlB9Z7ZUs9JYFuoGtR/maayZrrMJhVW55dm+V6R04a+Ub5EsP+qUAOdoWF/rDA2zXVd8gUxrd1mG+lgM2JuLvrnReEI84j5Aut7quYvsZcUwQP8qZf1CmAA54B9bVoz4/dE5zwF/VKutRcX3Czkge4ccbsn71G2WQA7wmFtiG1C5rFRst2+Ge9jq27qswR2frA7ohFxz2iJew0cfZHtElkhPkAWSgBzKiivBvjM7H75H/6yJ4FetAjVopuG3fwaffBHocSnvJfoPO8MDmQD5QAeTMQz9fjLMG4bAmXHeFYj++CnCglJxr9J/RGY1ikwp/C/VxawHXKcR1H7pesXUEFxHigDSK/isFL+nd+gPk8ngTiLFlQF5nO7k/Vpe/UI6jekYUH/ZAh1lwjbkBA6nDOf20FzfbG2AeLOg72ppwfJRhowQDcf4NeqKJiDc0wAbuvkFPWP1cw3yZGtTVdgDHs8D/yML7n2LiyF5h+8eDde//QT1R6f2frMZzKXSJ8zreRPui05obaNOhumuQu6LiewJvOYSzl0KO+4gaIwf4tCne8k4MHdX21MD/o3bnOzBfD9amiegrizDyh+4Lq3yWwiZsvwPz7fTzAv3CEuhpENuwKXKFLsYV238R87Wgp/EQ0WcPyUrQi4+dhV6/p4oJ7OTMsTVGe2UAn3Nd96r6QGBB7Tvx6AbgDE1gToSN0L4Dv7bAJ6/C8TGIN3UAEy+AH0ff+TuwbKfjzm2M3WAA3lWD3q2IP64N8/T4LIKvG8RC2n8RyzZA9p3t5y5kH/IZmU1n9N6sLC/CRujAJtDz5h0c61SevhNbBz5U28TVgO/18WS1X6llawd63LqwHcp4AlwYB2V4RKhvQSm4mt8lZ3uA3SMfvwpz67F8jTqcA92G4lgZrmmAvP10Xv9F/LcAsb46EOeVMtoFdGCOc2fV9ZZ+WPsNeWbSZ/HvzXlyqObTRMx1HYGJmAjci/j/bfeX/3RH/lPb/+U/qflPaG+XegyBrpNDvYA6kqtQAz1WRcRjqWwaviFfaqc+SK0vzUC8RerMPhB32stFvZAT5RGfUAvGmUrftBG2g9PfxRbHYvge5K22ZTgnh+1hVIOSBXrHlZzT+h15dZCrC+Re+OwvH+6OfDif/+XDqTgpqNFH8Qa2Zii2CGouYC1yEYhhUH1ZKhzaf7lxt+fG+Rt8emQzqlikyIEL5gLs5EgwPV0FcuNQLpfAc3z52TlzvvrLmbsjZ86bfzhnTvb5LABe3Cfoxy3wGY96kWVA9oF8MjpONrYhAQYt9G5rwDhb/Wyweetvns8qkPsl6zMbvebzljpSZPsj3iEX0QOxjqhRz4H8+gm9bYU/xHKQKn2fwDgKyJFFOUgQs85BDP+G+YQ1omD8dK7YWmcJ6oeFTQx7RFVA/pib5dIjgBXtcbHYCBniwjgWyxPrdBvxtKxD+kjGGhG/teX5b3951W/Oq/bARkSxN1BzE+QdyHj8hc1DptudEKMCWCCcnxLEHxLVq/vmvbnaFuhsNm4LMAlzjJdd7UtW8j4Gf/nf6fK//U+IE6eKQd6hb9uI/Q16WaM8HIatO7AvQK+6W/WtiCGHeh9c7tFWCq72mzmwHOnlabMIPALFQ+n4uy23ZKhXjDwfyc9Ed7O93h/MyQZ4KsMggL/donwAq2CHwkaEebxnfapc4PQUs+tv7qtZcn70ZNzYYi9Av3sAuCXJ/ZTc3dXMEWgywsvmCAdX9zrjau8J9+LHXO11wElI+QvXfgQV13HT75pXf4KFDy4Zz1MObAJUY25A/qMlcf+My5eyvd6zTfKioV5t03w5wmtJuS7rC+sj+gkk0/9FhN+bgXpcOuck/hjistRsHdgb4DH3yJj7yxvC8b32KxsIl6j9kDlugU6swnyE7Hw0APsqAebZkzUpwmtC+91pPPWS+3uvr13jP4DjueLc1WWbthfp4VxhVBeA8AUDcjHp+ykc1slwmBR5ulKW5IH70PNScZ7pJOvXAJlVJ55HcG7ZWpcRuSIDqBmhe0D0qV3naQev2+Pq1Lhi1/6RZu69Rbjs6+LVy2qyPyq9f8Bl/eSBv6ZxpAk8yYI+wAifY7bbI5DXtJMf6uqIGA6wGWHNaqfrFsbR48A+pziRUeT+v6YvLdCX7h/Vl+0H6cs7a2uqLf/2r9Od3Zt0Z/+DdecAdGfqvoqV4NHNEmKCcp/UYY41un6U67Y80c/hx9gSKN/E6rEcW4GYGOihgrid2xCXYiTvgrMRuV7Ib28AFjuAHI0K1HWS/cy4fG+yJZLhuBG8g1QuuAh/uRY9WmXvb+38qOMf9jFu2GNzr+/NQSwdxpfI+2gY49H+zCn06a18Y3IflFxmr7Io4F8d7WF2Zj1OYWik58Yefpa0F9LR3O0unA/Rotx5Kp+qiNjSjOFOPdszsm/pOivnPHp9ay7HtLVWz3aN7YPd/dEltL3QvJrwvCaJ4Wm5vPXNPaJAjosHdWHQpqpFj5huqx9ve58WjLsB+RENGXejj/vW3kpdBIcwyrHJA7nzwq+XfLqh3qQaF8UtaxbD02WBjnJgzQ7071nkzaTnD8QdzdxDarLZTbw8kH7B0vt8uk9D5K/o5VqRnKZVJg/6GtRdhKxN7fen7kVSCX7bnxDTbUBeQh7Ijc14zTbjXD0QSwyNebWfYuYre81z8l7COdCvIidmHFfRv/oNhuYgRoZd7heJ9Eqv7G2RL8R8scUeN8SvlvORGl+itYqoRgHoUMRRDGvUhgDXRrXlBL38fj6ijsIE+o1WgoOjAWc0Zb/5Ts9HbrPAfO5hHQPHe9W4AsDCKR9o6NxF9Uknsidlv1wPcNk2vyHfKRM8E+DMbngcE3H0sFpGDaOqtnyMyXqod2DOyXmgvIhoz0icaNNPs3lhoFMfzcU3X+T74+WjL700Fxtpsc3qMr0v4WwgZiO4TtVYptwnhmOIh3R5d0zvQQyg2vroobM8nt/JRu63mNdkUw8vna31uD8qO2R/4TOxyEs+Wh/mFqUYGjsrqD9pF+CiyXC9e7L+NTWoBSojYuxDmCOUjoH1JUA9NCqdK1jt9yrnH/CTtGhOQhjaTpyWycUBcOrWQD7XIm5gT5z7auc8fzMur8VAjmLkIf8lyfnuwj5psAetXNsmHDf5ZzDwK/ELVPttda5cZp9TG9aewGpvxsR/PEbeRMy7Oz7vPwozR1zIHah3zcN+cNt+I2buwLhrECMk+Fzr34SZt2FuCMaz20XkHQwBvp9qywX6MZi5j6gvRr5x/4eZfytm3oV7yEHuCBuxZ4eI2K/wyY7EdN+qH1NwIN1x/nrgG6CaX8TLTdftAc5liHvijvdrgB6oQH8MYgf77E06wYb7oDIesTaC564KY9wxcSvJQ7mekRhegpt1PJM/eaAvRyV4GK/oi39R1rcBDpS9GEsW5p5k565MECtN6WN70FP7EeZ7t4i3og3HQxh+Reweyo0YE0/V9snZXMRvXYcPrkPwJn5Ngpwi9nj+9kesTx/Rq7AG3DAV8ANcOPYZg1dSHqwjZ+Zq7u63rkcTrqnygAMB8qf5cD2rb67Jpx873xbwBXZh/mrUj6UtIupDOt0Op3xSsesQ9Es+fQ1cuBcns0F8uC6UyjVnAnEYaXNG1CDWSz7X/O/VOEd0LPVs/QFdVzH2I/ECaWPL3IppXCD/bcIS3dOmXmPoil8/3mPj14sxo3hsbHyWjTX/jLEiuyGU0/Jj8hi8whO/w+OJ+iuxGhOtjkqeZ4pv+8D56cA+j43hKPHFqF57JG/hLF71G+uiKc/ab+QR8d3vroWm/GJ31kL74efWQvuHXgtNzzPNW4yRJ6PO2asPPoqD/XGR/BIuEiO42X4AF4lDfRldgO+WzoH5ffxoH8svauJ4z97Kt/tGbtErPSDQXvcN2N8F6Cc7gPxE8FzUc0vNexK9nU73LJC1OB3ZP+XNvKRmy+F2J1c55XL2IFeHrQGw3ewQjtGwnFJ6Js05zt9d+beDe4RwjCisYpGv1bXxJav/sEC31Lz+4HROA4gh7NW2MOzh4Pyczo1Q4p2jbTh97kn802xxl1g85NIzF97XjOvmesY0ktqkNtBX1RBcU8qg5qYaO9knqdF1jC0B17SJyIF3ETUCj2O90VwT7uGm5pmhfMgM2Cg5qDWQ51rh7fuxeIrZ8uslxVMcsDkQLxaIHzrEo2BA/o/j5+w2PAXEI6Ad1QO8KAeywMdxooV0wuL3r3PgfoG8bYCdaxRbypA4tbTTtXUzRA5Wou9cGdFXB2GHGcDQOl5jrdq/3X14Fj1frO9XrsT5pa1fBnoCSV/FRMSnDegvlYVrINuYfsI1kPMon3VQzr8RfIvZN+sD0H+F6UYXyP03nIcxiT5odV1O++oyDBXxTHUH7CvJWYPygAZlnIbzQyaTnTf0Tw36ArE5u0fvO8zYoCG8HPmsH0zCegIUwzOcKzMp3wHQxYxj8c484j6ibgT1lW0i+pYVwN5q9bPgCkXv7PTeqoaXjTDthe647VD2B22N78ZOPwzXcWVcvkrqnIFFrjTZKxaUsr4tSe8x6f8VAGstwzYFuyfoW4/2AMMCUA/io3yNLei5WYZzKFD/cp/rvTLZHi4DsQAUL5MyXemhMcVM3MuHGPdrcK+6pxwaa8CMedZ5jXusyp91AePvKzv/f3heU/XxuVJn6qmjehzZ/Xr6y3l/1QfISpcoPuGBXVkDuVCCPWfOxwBT5uN9VHz9DzNMihm6eosZ/nTc0DUfjhsK/ITyjVKf7pPqLRzIIVN51CSW8gB5lWW4f7NFGFUOZKY7FssP6bwfIRMbfX+yHpyZIisF15JFcg1wIbG93Qd6d+/0W3ZVuC80qvNWbeGL2BnjUv1umQh8M+Yr24AvYThPatL+JalsJSnDuw+ViS3Yn1UEjgHy7xim0Uf0lMpmbKN8/tA5CfEUnK0ZNgumtmAf3bM/6fTc6umnrDl5F2qI1R61XSQOsHDwzvUAleBXmNYzI/UONmFumtTpglti2btH5p/GparHcywL1rFgnEvtw5KXMfqjp+Z/Gt///N//AyRXqwM=')))
                                              File "<string>", line 1, in <module>
                                              File "<string>", line 275, in <module>
                                              File "<string>", line 177, in l1llll11_ef_
                                              File "<string>", line 302, in l1lll1ll_ef_
                                              File "<string>", line 266, in l1111l111_ef_
                                              File "<string>", line 42, in l11l1111l_ef_
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
22:19:35.566 T:3780   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.efilmy/?foldername=Obcy+Przymierze+%5BCOLOR+green%5D+Napisy+PL+%5B%2FCOLOR%5D&page=1&ex_link=http%3A%2F%2Fwww.efilmy.tv%2Ffilm%2C31366%2CObcy-Przymierze-Alien-Covenant-2017-Napisy-PL.html&mode=getLinks]

**Comment by ramicspa** [comment]
Uaktualnij urlresolver bo masz starą wersje i będzie wszystko działać.
Nie wklejają też tu loga a użyj pastebin.com.
