### ISSUE TITLE
efilmy ???

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#337]
urlresolver v 3.0.33.01 ? nowy ?
i niestety ten sam blad 
https://pastebin.com/0MG303kr

**Comment by ramicspa** [comment]
ja nie widze zadnego problemu ... Geniusz-Genius normalnie sie odpala jak kazda inna pozycja.
sprawdz czy przez strone wszystko ci dziala bo wyglada na to ze wtyczka nei znajduje zadnego linku i wywala blad.
