### ISSUE TITLE
od kilku tygodni przestala wtyczka tvp.pl

### ISSUE THREAD

**Issue by tomusfl** [ramicspa/kodi#338]
Nie wiem gdzie jest problem, jestem zagranica, wczesniej dzialalo przez 2-3 misiace poprawnie. A wczesniej byl podobny problem i teraz juz nie mowi ze material niedostepny za granica i czy sprobowac liste serverow proxy, ale po prostu wywala blad, W logach byl error ze invalid source zdaje sie bylo. Sprawdze dla pewnosci i dodam jesli inny error.

**Comment by ramicspa** [comment]
a co konkretnie nie dziala? ktora pozycja?

**Comment by tomusfl** [comment]
np. archiwum teleexpressu (wczesniej dzialalo)
rowniez vod nie dziala - seriale np. komediowe-> rodzinka.pl

**Comment by tomusfl** [comment]
generalnie nic z vod menu nie dziala - te dosc nowe pozycje, choc oczywiscie nie wszyskie pozycje sprawdzalem :)

**Comment by ramicspa** [comment]
ok faktycznie jest problem bedzie aktualizacja

**Comment by tomusfl** [comment]
ok, dzieki

**Comment by Rolex37323** [comment]
Przepraszm 
Czy ktos mi moze pomoc jak znalesc ten kod do uruchomienia wtyczek

**Comment by Katapulta** [comment]
@Rolex37323 ... na stronie głównej... 
http://prntscr.com/fmp8ko

**Comment by tomasiek** [comment]
@Katapulta - podawajmy im wędkę a nie rybę. Większość osób pytających o kod od razu zadaje pytanie, nie patrząc nawet czego dotyczy wątek w którym piszą, nie zaglądając nawet na stronę główną repozytorium. Za miesiąc jak kod się zmieni, przyjdą ponownie z zapytaniem o kod. Odsyłajmy ich do głównej z linkiem - resztę wystarczy przeczytać.

**Comment by ramicspa** [comment]
wtyczka dziala, zamykam temat.
