### ISSUE TITLE
nowa strona od naszekino 

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#339]
wyszła nowa strona od naszekino moze jest mozliowśc zrobienia go pod kodi ?

https://nasze-kino.tv

**Comment by tomasiek** [comment]
Na 3 testowe filmy nie ma żadnego :(
Z box office http://www.filmweb.pl/boxOffice/ranking z pierwszej piątki nie ma niczego :(
IMO szkoda czasu i pracy. Zniknie za miesiąc jak wiele jej podobnych.

**Comment by Seico** [comment]
Stronkę zrobiła ekipa z : nasze-kino.online , a ta stronka jest cały czas , nasze-kino.tv dopiero została otwarta i moim zdaniem przetrwa , ja bym jej dał szanse tylko url resolver trzeba będzie dostosować

**Comment by tomasiek** [comment]
No zobaczymy... Może się uda - natomiast jak dla mnie baza słaba - to że są nowości to fajnie... ale to nie wszystko...
Mam 3 filmy testowe:
1. Przygody Picassa (wpisuję picasso/picassa) - b. rzadko gdziekolwiek jest ten film, jak jest to w słabej jakości
2. Donie Darco - rzadko jest, czasem się pojawia się w HD
3. Wielki Błękit - ten raczej w większości serwisów się pojawia.
Do tego dorzucam boxoffice.
Rozumiem że wszystkich na pewno nie będzie w żadnym serwisie (choć i tu są 2-3 chlubne wyjątki). Zobaczymy jak serwis się rozwinie.

**Comment by krzysztof222** [comment]
coraz lepsza baza z filmami, seriale jeszcze troche leżą

**Comment by ramicspa** [comment]
zobaczymy co z tego wyjdzie, wtyczka gotowa

**Comment by krzysztof222** [comment]
miejmy nadzieje ze bedzie zajebista wtyczka w kolekcji naszych stron

**Comment by krzysztof222** [comment]
repozytorium nie widzi tej wtyczki

2017-06-23 0:10 GMT+02:00 ramicspa <notifications@github.com>:

**Comment by Seico** [comment]
**krzysztof222** Zaktualizuj repozytorium

**Comment by krzysztof222** [comment]
Seico dzienki za pomoc
