### ISSUE TITLE
Polsat boxing night

### ISSUE THREAD

**Issue by pawlak1212** [ramicspa/kodi#343]
Witam czy bedzie dostepny stream z walki Adamka dzisiaj ? Pozdrawiam

**Comment by Katapulta** [comment]
A kto tu streamy udostepnia ?? Chyba się fora / strony pomyliły :) Zawsze można poszukać odważnego na facebooku który udostępni i pójdzie za to siedzieć :D

**Comment by pawlak1212** [comment]
Realy 😂

**Comment by Katapulta** [comment]
@pawlak1212 no realy :) Nikt tu na zawołanie linków do streamów nie robi :P

**Comment by pawlak1212** [comment]
Czy na zawołanie to nie wiem , informacyjnie zapytałem.

**Comment by Katapulta** [comment]
@pawlak1212 po poprzedniej akcji chyba z KSW ostatniego jak koleś udostepnił na facebooku strema z gali dostał w prezencie od Polsatu wjazd na chatę i chyba 3 lata paki jakoś tak mu grozi :P A tutaj nikt nie robi "okazyjnych" stremow - tutaj tylko stałe i konkretne pluginy i wtyczki do kodi :)

**Comment by pawlak1212** [comment]
Dziękuję za wyczerpującą odpowiedź.  Pozdrawiam

**Comment by pawlak1212** [comment]
Znalazłem na Livepolish tv 🖒
