### ISSUE TITLE
bajki nie działają.

### ISSUE THREAD

**Issue by darzur** [ramicspa/kodi#345]
Hej,

Żadna z bajek się nie otwiera. Wyszukuje i listuje je prawidłowo ale samego strumienia już nie otwiera. To wszystko na RPi2 z Libreelec 8.0.2 (Krypton 17.3). Błedy jak poniżej:

10:28:25.966 T:1479205792  NOTICE: URLResolver: Initializing URLResolver version: 3.0.29
10:28:26.030 T:1962018944  NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
10:28:26.037 T:1962018944  NOTICE: VideoPlayer: Opening:
10:28:26.037 T:1962018944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:28:26.042 T:1450562464  NOTICE: Creating InputStream
10:28:26.056 T:1450562464   ERROR: Error on dvdnav_open
10:28:26.056 T:1450562464   ERROR: CVideoPlayer::OpenInputStream - error opening []
10:28:26.057 T:1450562464  NOTICE: CVideoPlayer::OnExit()
10:28:26.057 T:1962018944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=6+W+Pracy++Odchodz%C4%99%21&page=1&ex_link=http%3A%2F%2Fbajkionline.com%2F6-w-pracy-odchodze%2F&mode=getLinks]
10:28:26.070 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
10:28:26.070 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
10:28:26.071 T:1962018944  NOTICE: VideoPlayer: finished waiting
10:28:26.071 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
10:28:26.071 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
10:28:26.071 T:1962018944  NOTICE: VideoPlayer: finished waiting
10:28:46.381 T:1570796448 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
10:28:46.909 T:1570796448 WARNING: Previous line repeats 1 times.
10:28:46.909 T:1570796448  NOTICE: LoadJpeg: unable to load http://bajkionline.com/wp-content/uploads/2017/06/dlaczego-mam-zielone-oczy-480x293.jpg
10:28:54.078 T:1479205792  NOTICE: URLResolver: Initializing URLResolver version: 3.0.29
10:28:54.142 T:1962018944  NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
10:28:54.149 T:1962018944  NOTICE: VideoPlayer: Opening:
10:28:54.149 T:1962018944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:28:54.151 T:1458951072  NOTICE: Creating InputStream
10:28:54.151 T:1458951072   ERROR: Error on dvdnav_open
10:28:54.152 T:1458951072   ERROR: CVideoPlayer::OpenInputStream - error opening []
10:28:54.152 T:1458951072  NOTICE: CVideoPlayer::OnExit()
10:28:54.152 T:1962018944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=Dlaczego+lubi%C4%99+s%C5%82odkie&page=1&ex_link=http%3A%2F%2Fbajkionline.com%2Fadibu-dlaczego-lubie-slodkie%2F&mode=getLinks]
10:28:54.166 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
10:28:54.166 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
10:28:54.166 T:1962018944  NOTICE: VideoPlayer: finished waiting
10:28:54.167 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
10:28:54.167 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
10:28:54.167 T:1962018944  NOTICE: VideoPlayer: finished waiting

**Comment by jabarroo** [comment]
Witam potwierdzam . juz zadna z bajek nie otwiera się

**Comment by ramicspa** [comment]
uaktualnij URLResolver ... najnowsza powinna byc 3.0.33 lub wyzsza.

**Comment by darzur** [comment]
OK, zrobię to, ale coś mi się kojarzy że ten zainstalował się właśnie z dodatkiem bajki.

**Comment by darzur** [comment]
OK, aktualizacja URLResolvera do 3.0.33 nic nie dała. Poniżej log błędów:

16:48:29.409 T:1489687456  NOTICE: URLResolver: Initializing URLResolver version: 3.0.33
16:48:29.477 T:1962018944  NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
16:48:29.484 T:1962018944  NOTICE: VideoPlayer: Opening:
16:48:29.484 T:1962018944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:48:29.487 T:1457329056  NOTICE: Creating InputStream
16:48:29.503 T:1457329056   ERROR: Error on dvdnav_open
16:48:29.503 T:1457329056   ERROR: CVideoPlayer::OpenInputStream - error opening []
16:48:29.503 T:1457329056  NOTICE: CVideoPlayer::OnExit()
16:48:29.504 T:1962018944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=Przesy%C5%82ka+ekspresowa&page=1&ex_link=http%3A%2F%2Fbajkipopolsku.com%2Fprzesylka-ekspresowa&mode=getLinks]
16:48:29.518 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:48:29.518 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:48:29.518 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:48:29.519 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:48:29.519 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:48:29.519 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:48:29.565 T:1489687456 WARNING: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.bajkionline/main.py): the python script "/storage/.kodi/addons/plugin.video.bajkionline/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
16:48:55.714 T:1457329056  NOTICE: URLResolver: Initializing URLResolver version: 3.0.33
16:48:55.782 T:1962018944  NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
16:48:55.789 T:1962018944  NOTICE: VideoPlayer: Opening:
16:48:55.790 T:1962018944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:48:55.791 T:1469051808  NOTICE: Creating InputStream
16:48:55.792 T:1469051808   ERROR: Error on dvdnav_open
16:48:55.792 T:1469051808   ERROR: CVideoPlayer::OpenInputStream - error opening []
16:48:55.792 T:1469051808  NOTICE: CVideoPlayer::OnExit()
16:48:55.794 T:1962018944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=1++T%C4%99cza&page=1&ex_link=http%3A%2F%2Fbajkipopolsku.com%2F1-tecza&mode=getLinks]
16:48:55.808 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:48:55.808 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:48:55.808 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:48:55.808 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:48:55.808 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:48:55.808 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:48:55.893 T:1457329056 WARNING: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.bajkionline/main.py): the python script "/storage/.kodi/addons/plugin.video.bajkionline/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
16:49:26.235 T:1576194976 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
16:49:26.635 T:1576194976 WARNING: Previous line repeats 1 times.
16:49:26.635 T:1576194976  NOTICE: LoadJpeg: unable to load http://bajkionline.com/wp-content/uploads/2016/09/r2gE9_super_auta1.jpg
16:49:33.927 T:1742730144 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
16:49:34.325 T:1742730144 WARNING: Previous line repeats 1 times.
16:49:34.325 T:1742730144  NOTICE: LoadJpeg: unable to load http://bajkionline.com/wp-content/uploads/2016/09/euqJF_super_auta1.jpg
16:49:34.786 T:1751118752 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
16:49:35.167 T:1751118752 WARNING: Previous line repeats 1 times.
16:49:35.168 T:1751118752  NOTICE: LoadJpeg: unable to load http://bajkionline.com/wp-content/uploads/2016/09/ZTsxF_super_auta1.jpg
16:49:37.605 T:1489687456  NOTICE: URLResolver: Initializing URLResolver version: 3.0.33
16:49:37.673 T:1962018944  NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
16:49:37.681 T:1962018944  NOTICE: VideoPlayer: Opening:
16:49:37.681 T:1962018944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:49:37.682 T:1469051808  NOTICE: Creating InputStream
16:49:37.685 T:1469051808   ERROR: Error on dvdnav_open
16:49:37.685 T:1469051808   ERROR: CVideoPlayer::OpenInputStream - error opening []
16:49:37.685 T:1469051808  NOTICE: CVideoPlayer::OnExit()
16:49:37.686 T:1962018944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=10++Jestem+odpowiedzialna&page=1&ex_link=http%3A%2F%2Fbajkionline.com%2F10-jestem-odpowiedzialna%2F&mode=getLinks]
16:49:37.700 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:49:37.700 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:49:37.700 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:49:37.700 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:49:37.700 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:49:37.700 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:49:37.770 T:1489687456 WARNING: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.bajkionline/main.py): the python script "/storage/.kodi/addons/plugin.video.bajkionline/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
16:49:49.487 T:1489687456  NOTICE: URLResolver: Initializing URLResolver version: 3.0.33
16:49:49.555 T:1962018944  NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
16:49:49.563 T:1962018944  NOTICE: VideoPlayer: Opening:
16:49:49.563 T:1962018944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:49:49.564 T:1457329056  NOTICE: Creating InputStream
16:49:49.565 T:1457329056   ERROR: Error on dvdnav_open
16:49:49.565 T:1457329056   ERROR: CVideoPlayer::OpenInputStream - error opening []
16:49:49.565 T:1457329056  NOTICE: CVideoPlayer::OnExit()
16:49:49.566 T:1962018944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.bajkionline/?foldername=Kotka+Pusia++Kot+Rakieta&page=1&ex_link=http%3A%2F%2Fbajkionline.com%2Fkotka-pusia-kopalnia-pianki-marshmallow%2F&mode=getLinks]
16:49:49.575 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:49:49.575 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:49:49.575 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:49:49.576 T:1962018944  NOTICE: CVideoPlayer::CloseFile()
16:49:49.576 T:1962018944  NOTICE: VideoPlayer: waiting for threads to exit
16:49:49.576 T:1962018944  NOTICE: VideoPlayer: finished waiting
16:49:49.643 T:1489687456 WARNING: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.bajkionline/main.py): the python script "/storage/.kodi/addons/plugin.video.bajkionline/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

**Comment by ramicspa** [comment]
to w dalszym ciagu problem resolvera ... cos nie dziala najlpiej z rosyjskimi serwerami.

**Comment by darzur** [comment]
W takim razie jaki resolver zainstalować lub co zrobić żeby bajki chodziły na KODI?

**Comment by ramicspa** [comment]
resolver'owi zawsze mozna troche pomoc ... poszla aktualizacja wtyczki - powinno juz wszystko dzialac.

**Comment by darzur** [comment]
WIELKIE DZIĘKI!! 👍 🥇 
Wszystko działa jak należy.
