### ISSUE TITLE
Nieudane połączenie z repozytorium

### ISSUE THREAD

**Issue by Venom3x** [ramicspa/kodi#347]
Witam, przy próbie instalacji z repozytorium wywala "Nieudane połączenie z repozytorium".
Error z logów:

> ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
> ERROR: CCurlFile::Open failed with code 403 for http://www.ramic.ga/ramicspa/kodi/addons.xml.md5
> ERROR: XFILE::CFileCache::Open - failed to open source <http://www.ramic.ga/ramicspa/kodi/addons.xml.md5>
> ERROR: CRepository: failed read 'http://www.ramic.ga/ramicspa/kodi/addons.xml.md5'

Ma ktoś pomysł jak się z tym uporać?

Kodi 17.3 windows & android

**Comment by ramicspa** [comment]
faktycznie, nowo dodane repozytorium nie moze miec zadnych bledow odczytlu plikow ... bedzie poprawka

**Comment by ramicspa** [comment]
pobierz nowa wersje repozytorium.

**Comment by Venom3x** [comment]
Dzięki, teraz działa.
