### ISSUE TITLE
Wtyczki przestały obsługiwać filmy z openload.co

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#35]
Wszystkie wtyczki nieobsługują filmów z openload.co - "ERROR.Stream Url Not Found.Deleted?"

**Comment by xxcriticxx** [comment]
Gołębie[2] (Columbinae) – podrodzina ptaków z rodziny gołębiowatych (Columbidae).

**Comment by ramicspa** [comment]
zgadza sie ... trzeba troche poczekac az urlresolver bedzie naprawiony

**Comment by eko5** [comment]
https://github.com/tknorris/script.module.urlresolver 
naprawia sprawę .
