### ISSUE TITLE
FilmwebBooster

### ISSUE THREAD

**Issue by kashkash18** [ramicspa/kodi#350]
Czy tylko ja nie widzę wtyczki w repo ?? (1.3.4)

**Comment by xxcriticxx** [comment]
@kashkash18 kodi16 czy 17 masz?

**Comment by kashkash18** [comment]
17.3

**Comment by kashkash18** [comment]
Dobra , po odinstalowaniu repo i ponownej instalacji widnieje na liście. Zamykam

**Comment by kashkash18** [comment]
Wtyczka rewelacja :) Czy zostanie dodana opcja Szukaj i czy seriale też będą dodane ??

**Comment by tomasiek** [comment]
No to trzeba chyba głowy pochylić, bo to chyba najlepsza wtyczka do kodi jaką mogliśmy sobie wyobrazić. Dzięki wielkie za jej zrobienie.
Ps. Jest literówka "Baza filów".

**Comment by tomasiek** [comment]
@kashkash18
Co do opcji szukaj. Na pewno będzie. Wtyczka ma taki potencjał że niewyobrażam sobie żeby nie było.
@ramicspa - Dla mnie koniecznie przy bazie filmów musi się pojawić gatunek i kraj. Bez tego wyszukiwanie szwedzkich kryminałów jest z deka utrudnione.
Dajmy czas Michałowi, to pierwsza wersja zawierająca absolutne minimum, bardziej do testów niż do pełnego korzystania. Chociaż działa idealnie.

**Comment by DarDo1** [comment]
Wtyczka rewelacja. Chłopaki czapki z głów. Jeszcze tylko seriale i nic więcej nie trzeba oprócz sportu. Czy da się dorzucić do tego opisy filmów?

**Comment by tomasiek** [comment]
No ale przecież są opisy taksamo okładki

**Comment by DarDo1** [comment]
To może ja jeszcze nie doszedłem do tego jak to uruchomić. Okładki widzę opisów nie.

**Comment by tomasiek** [comment]
Nic nie trzeba uruchamiać. One po prostu są. Może zmień typ widoku w kodu.

**Comment by DarDo1** [comment]
Właśnie patrzę, ale mam tylko widok listy gdzie widzę tylko okładkę oraz miniatury

**Comment by tomasiek** [comment]
A podziękowania to do Michała. Ja tylko rzuciłem pomysł

**Comment by DarDo1** [comment]
Podziękowania należą się wszystkim, którzy przyczynili się do powstania wtyczki. Pomysł jest czasami tak samo ważny jak wykonanie. Dla was wszystkich dzięki. Ale dalej nie wiem jak sobie poradzić z tymi opisami.

**Comment by tomasiek** [comment]
Jaką masz skórkę. Na domyślnej kodi jest

**Comment by Katapulta** [comment]
Ja mam Aeon Nox Silvo czy jakoś tak i tez mam opisy. Na xconfluence ( poprzedniej której używałem ale przestały mi tam działać "widgety" ) tak samo opisy działają.

**Comment by DarDo1** [comment]
@tomasiek Ja jadę na RpPi3, skóra mimic, którą zresztą sam pomagałeś mi skonfigurować, za co gratki :-)

**Comment by tomasiek** [comment]
Oj... Ja sprawdzałem na telefonie tylko, w domu rzucę okiem na mimic...opisy zawsze są pod prawym przyciskiem jakby co...

**Comment by DarDo1** [comment]
Ok. Dzięki.

**Comment by tomasiek** [comment]
Yhm. Faktycznie pokazuje tylko 2 widoki. To wada mimic że w widoku listy nie pokazuje opisów. 
@ramicspa mógłbyś usunąć ograniczenie wyboru widoku? Tak jak w CDA.pl kiedyś.

**Comment by DarDo1** [comment]
@tomasiek Dzięki za sprawdzenie
@ramicspa przyłączam się do prośby

**Comment by Seico** [comment]
Extra :) , fajnie by było aby przy linkach z cda.pl oprócz jezyka pokazało się też jakość wideo tak jak jest przy linkach z openload.co , nie wiem czy to Michał jest w stanie zrobić czy trzeba by było poprosić właściciela "**FilmwebBooster**"

**Comment by tomasiek** [comment]
Z tego co mi się wydaje mogą to zrobić obaj :)

**Comment by kopernik1983** [comment]
@ramicspa wybór widoku ok. do sprawdzenia w bazie filmów ; gatunek i kraj wyrzuca błąd dodatku.

**Comment by ramicspa** [comment]
fakt cos sie tam popsulo, dzieki za sprawdzenie

**Comment by kopernik1983** [comment]
I już wszystko gra :)

**Comment by tomasiek** [comment]
Wszystko jest super. Opcja "dziś w tv" jest zajebista.

**Comment by Katapulta** [comment]
Wszystko jest rewelacyjnie... I rewelacyjnie działa :D Jedyne co znalazłem - to jak ustawiłem sobie widget "Dziś w TV" to mam taki myk że wyświetla mi tylko kilka "pozycji" a później "folder" i nie przewija tego dalej :) 
![va5b1jftrcyzxo6g34iqna](https://user-images.githubusercontent.com/26973858/27763309-a5eb6aae-5e81-11e7-9fb4-85ae6c859e42.png)

Ale ogólnie wtyczka best of the best chyba - najlepsza jaką można było zrobić.

**Comment by Seico** [comment]
No teraz to już wtyczka wymiata :) czekamy teraz tylko na dodanie seriali i będzie komplecik :)

**Comment by kodishu** [comment]
@ramicspa nie wszystkie filmy mają opisy, gatunek, czas trwania i rating. Nie wiem od czego to zależy. "Gladiator" np. ma, a "Jak wytresować smoka" nie ma. 

Druga rzecz. Czy jako tło mogłyby być pobierane fanarty, a nie powiększone plakaty? Dodałoby to atrakcyjności tej i innym wtyczkom. Dla oka to o wiele przyjemniejsze niż rozciągniety plakat. 

Poza tym super robota. To jest fantastyczne.

**Comment by DarDo1** [comment]
No i mamy najlepszą wtyczkę. Zauważyłem, że nie znajduje wszystkich źródeł. Przykład film "Bunt" z widoku rankingu. We wtyczce pokazuje brak źródeł. Sprawdziłem, przez stronę i źródła znajduje.

**Comment by Zigi1974** [comment]
Czesc, wtyczka swietna nie wiem czy nie najlepsza :) czasami nie moze znalesc zrodel jak podal kolega wyzej  
moze cos Michal poprawi jeszcze  ale i tak jest swietnie . 
pozdro.

**Comment by Seico** [comment]
Polska czcionka nie działa przy wyszukiwaniu , a i jest mały problem z wyszukiwanie niektórych filmów np. "Dorwać Cartera (2000)" tego filmu nie znajduje , a na stronie filmweb jest wszystko ok

**Comment by ramicspa** [comment]
dzieki za uwagi i sugestie, czesc z nich zostala uwzgledniona kolejnej aktulizacji.
informacje o mediach pobierane sa tylko ze strony. moznaby dodac wiecej info ale wplynie to negatywnie na szybkosc dzialania

**Comment by Seico** [comment]
Dzieki za dodanie seriali :) , po małym teście zauważyłem że tam gdzie jakiś odcinek serialu ma tylko jedno źródło to wtedy w kodi wyskakuje brak źródła , testowałem na serialu "Gwiezdne wrota SG-1" , możesz to sprawdzić ? , a i akurat w tym serialu jest 10 sezonów , a w kodi jest tylko 9 sezonów , to też jakby można było sprawdzić dlaczego

**Comment by ramicspa** [comment]
@Seico fajnie ze podales przyklad - bedzie latwiej znalesc problem i go naprawic

**Comment by kopernik1983** [comment]
Z tego co zauważyłem narazie to w rankingu sortowanie seriali po gatunku nie działa. Co byśmy nie wybrali lista jest ta sama.

**Comment by Katapulta** [comment]
COś mi dzisiaj Ta wtyczka jakiś błedy wywala ... nie korzystam a co chwila jakiś error... log w całości :
https://pastebin.com/xkAu3Xx7

CO chwila monit o błedzie dodatku... Końcówka w pastebin odnosi się do tej wtyczki

**Comment by ramicspa** [comment]
problemem byly polskie znaki w linkich - wersja 1.3 powinnto to juz naprawic
