### ISSUE TITLE
Filmy.to przestalo dzialac (tydzien moze dluzej)

### ISSUE THREAD

**Issue by tomusfl** [ramicspa/kodi#351]
Przestalo wyswietlac jakiekolwiek wyniki wyszukiwan (filmy czy seriale), rowniez nie mozna zmienic opcji wyszukania - (brak opcji wyboru -. U mnie ostatnia opcja przed zepsuciem byly filmy polskie i nie da sie juz tego zmienic - a poz tym pusta strona wynikowa (dla filmow polskich)

Fire stick, kodi 16.1, pozniej update to Kodi 17.3 - ten sam problem.

**Comment by tomusfl** [comment]
Sorry to chyba strona przestala dzialac :(

**Comment by kashkash18** [comment]
Strona seagos.es też nie dziala

**Comment by Katapulta** [comment]
Filmy.to działa calutki czas. Jak Strona tak wtyczka. Jeśli "nie działa" ci Filmy.to ale wtyczka - "odpal" wtyczkę, wejdź na przykład w "Filmy" ( nie w wyszukiwanie )  i poczekaj aż wyświetli Ci się kod capcha do wpisania - wpisz i działaj :)
