### ISSUE TITLE
Efilmy kod

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#353]
blad kodu wtyczki , prosi o kod z repo za kazdym razem kiedy wybieramy jakas zakladke. i tak na okraglo ..:)

**Comment by tomasiek** [comment]
Pokaż jakiś log. U mnie działa normalnie, przyjmuje kod jednorazowo i potem już nie pyta.

**Comment by Zigi1974** [comment]
hej . temat do zmkniecia . nie wiem o co chodzi ale na macu os sierra taki byl komunikat. lecz dzis jest juz ok. 
poz.
