### ISSUE TITLE
cda.pl - brak okładek z filmweb

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#355]
Witam.
W cda.pl nie pobiera okładek filmów z filmweb. 
W logach nie ma absolutnie nic, poza tym:
13:44:24.771 T:4117567504   ERROR: Control 50 in window 10025 has been asked to focus, but it can't

**Comment by ramicspa** [comment]
ok zobacze w czym problem

**Comment by tomasiek** [comment]
Już mam w czym jest problem - okładki pobiera i wyświetla gdy opcja "oczyszczaj tytuły" jest wyłączona - przy włączonej pokazuje miniaturki z cda

**Comment by ramicspa** [comment]
thx, bedzie latwiej naprawiac problem
