### ISSUE TITLE
tvp.pl znowu przestalo dzialac

### ISSUE THREAD

**Issue by tomusfl** [ramicspa/kodi#357]
z zagranicy jestem
po naprawie w 2.0.2 dzialalo przez tydzien moze, ale teraz pozycje z VOD nie dzialaja. np komediowe, rodzinka.pl kazdy odcinek, o mnie sie nie martw tez
error:
![image](https://user-images.githubusercontent.com/25443833/27894799-73c19482-61dc-11e7-9aa5-7cd17b9de5d4.png)
![image](https://user-images.githubusercontent.com/25443833/27894840-9ddbd85e-61dc-11e7-9a6b-32f8741ef812.png)

**Comment by ramicspa** [comment]
wtyczka dziala dobrze - linki nie sa serwowane z serwera (pretensje do Kurskiego). sprobuj wybrac inne bitrate'y zrodla - jakis na pewno zadziala.

**Comment by tomusfl** [comment]
rozumiem, dzieki

**Comment by tomusfl** [comment]
Chcialbym to otworzyc ponownie, bo sprawdzilem, i to nie jest problem ze strona. Sprawdzilem dla serialu rodzinka.pl (208 odcinek). Laczac sie z zagranicy przez Hola na strone vod.tvp.pl mozna obejrzec bez problemu. Jak uzywam wtyczki to juz nie dziala, dzieki.

**Comment by tomasiek** [comment]
Nie korzystaj z hola! https://zaufanatrzeciastrona.pl/post/uzytkownicy-popularnej-uslugi-vpn-stali-sie-nieswiadomie-czescia-botnetu/
No chyba że lubisz nocne wizyty interpolu.
Ewidentnie jest to problem ze stroną która filtruje użytkowników wg. kraju.

**Comment by tomusfl** [comment]
dzieki za info
wyglada ze znow nie dziala, ale chyba zmieniaja jakies zabezpieczenia na stronie, teleexpress na you tube mozna znalezc, reszta dobrych seriali gdzie indziej sie znajdzie

**Comment by Huero23** [comment]
Czy TVP VOD działa?

**Comment by donald73** [comment]
TVP VOD zaczęło działać

**Comment by Huero23** [comment]
Żadne serial nie działa? Chyba dalej nie działa...

**Comment by donald73** [comment]
sprawdzałem przed wpisem Ojciec Mateusz seria 7 działa własnie oglądam odcinek 93

**Comment by Huero23** [comment]
U mnie nic nie działa? Kazdy serial jak clickne opening stream i zaraz error message..

**Comment by daxkiller7777** [comment]
U mnie US proxy nie dzieła

**Comment by donald73** [comment]
U mnie nic nie działa

**Comment by ramicspa** [comment]
jak cos nie dziala warto odwiedzic tez strone tvp ... mozna sie tam dowiedziec np tego:
"#4 WIDEO (ODC. 682) NIE MOŻE ZOSTAĆ ZAŁADOWANE ZE WZGLĘDU NA PROBLEM Z SIECIĄ BĄDŹ SERWEREM."

**Comment by donald73** [comment]
sprawdzałem na stronie vod.tvp.pl dział na kodi nie

**Comment by Huero23** [comment]
Vod.tvp.pl noe działa od naj mniej 2 tygodni zadne serial nie dziala.

**Comment by ramicspa** [comment]
@Huero23 sprawdzilem czy WSZYSTKO nie dziala. ... no i dziala np
Seriale-> komediowe -> o mnie sie nie martw.

**Comment by Huero23** [comment]
@ramicspa seriale>oobyczajowe>Elif czy działa u Ciebie?

**Comment by tomasiek** [comment]
u mnie działa - odcinek 111 i inne...

**Comment by Huero23** [comment]
@tomasiek u mnie nie pokazuje odc. 111 jak clickne to opening stream i zaraz TVP ERROR  CHECK LOG FOR MORE INFORMATION

**Comment by tomasiek** [comment]
I co w tych logach siedzi?

**Comment by Huero23** [comment]
@Tomasik jak to się sprawdza?

**Comment by Huero23** [comment]
@tomasiek jak to się sprawdza ?

**Comment by tomasiek** [comment]
Zadaj sobie troszkę trudu i wpisz w google "kodi logi"
