### ISSUE TITLE
pomocy błąd dodatku tele-wizja

### ISSUE THREAD

**Issue by szymon900** [ramicspa/kodi#359]
błąd podczas wczytywania listy dokładnie przy kanale polsat cafe prosze o pomoc dodam tylko ze na laptopie tworzenie listy kanałów poszło bez problemowo mam problem na xiaomi mi box 4x

**Comment by tomasiek** [comment]
Logi, logi i jeszcze raz logi. Bez nich to wróżenie z fusów.

**Comment by ramicspa** [comment]
bylo juz pare aktulizacji wiec problem jesli byl to sie juz sam dawno rozwiazal
