### ISSUE TITLE
rapidvideo.com

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#36]
Filmy z rapidvideo.com są HD a w kodi wyswietla jako SD

**Comment by ramicspa** [comment]
jaka wtyczka? przyklad by sie przydal

**Comment by Seico** [comment]
Jeden film wrzuciłem na "iwatchonline" dla sprawdzenia jakości : "Underdogs" z lektorem PL

**Comment by ramicspa** [comment]
zgadza sie ... sa 2 jakosci dostepne "360p","default":"true" oraz "720p","default":"false" a resolver bierze pod uwage tyko pierwszy link - trzeba to poprawic. czy przy uploadzie mozesz ustawic jaka jest domyslna?

**Comment by Seico** [comment]
Nie mogę , ale widzę że jak otworze w przeglądarce to jest ikona "HD" i tam dopiero sie zmienia jakość , więc moze to jest rozwiązanie
