### ISSUE TITLE
darmowa-telewizja.info/

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#365]
Oglądam od dwóch tygodni http://darmowa-telewizja.info/canalsport-2/ za darmo wszystko full HD i fajnie jakby dodać to:)Da radę?

**Comment by Katapulta** [comment]
Spoko stronka z tego co widzę. Coś ala tele-wizja ale ciut lepsze źródła i szybciej chodzi. Jak na razie większość kanałów działa  - nie udało mi się tylko HBO odpalić. @ramicspa można by było testowo spróbować wrzucić do LivePolishTV + ładowanie do PVR list m3u...

**Comment by abrus7** [comment]
od 2 tygodni i zero przerw działają,więć napisałem bo moze się przyda naprawdę od telewizji szybciej chodzi itp

**Comment by abrus7** [comment]
i jak:>?

**Comment by Katapulta** [comment]
@abrus7 jest juz we wtyczce - zaktualizuj sobie :)

**Comment by abrus7** [comment]
darmowa-telewizja? To już dawno było.. Ale to nie ta wtyczka chyba bo innej nie mam:D
A ta darmowa-telewizja dużo kanałów nie działa;D

**Comment by abrus7** [comment]
#ramicspa mógłbyś odpisać jak będziesz miał czas?

**Comment by clowni** [comment]
@ramicspa Pisalem wczesniej na temat wtyczki, ze Wizja TV uzywa portu 81 w adresie IP dla uzytkownikow premium, natomiast uzytkownicy standard sa na 80 i stad limit uzywania Wizja TV tylko 3h, gdzie czesto jest to mniej. Prosilem o ta poprawke.

Natomiast inna sprawa tworze listy TV i ciagle mi nic nie chodzi na Kodi Jarvis 16.1, mam crona i ustawienia tak jak opisane i ciagle nie chca mi sie ladowac streamy. Co mozna poprawic ?
