### ISSUE TITLE
Szukajka.tv

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#367]
We wtyczce szukajka.tv nie można odtworzyć żadnego streamu , za każdym razem wyskakuje błąd
Przesyłam loga : 
https://pastebin.com/fmmWacR2

**Comment by tomasiek** [comment]
No u mnie to samo...

**Comment by ramicspa** [comment]
nie pamietam czy cos tam robilem ... ale jak patrze teraz to wszstko dziala. wiec temat do kosza.
