### ISSUE TITLE
Sport.tvp.pl - wybór jakości

### ISSUE THREAD

**Issue by bart7890** [ramicspa/kodi#37]
Mam prośbę odnośnie sport.tvp.pl, przydałby się wybór jakości, 1080 jest troszkę za mocne na moje łącze. Istniałaby taka możliwość?
Tak w ogóle to prześwietna robota z tym repo, pozdrawiam :)

**Comment by ramicspa** [comment]
witam, wyglada na to ze jest mozliwosc wyboru jakosci ... update pojawi sie niebawem. pozdrawiam
