### ISSUE TITLE
tele-wizja padła

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#370]
tele-wizja padła znowu:/
Co chwilę z nimi błędy:
http://darmowa-telewizja.info/eurosport-2/
Polecam naprawdę jak najszybciej. Bo w tele-wizja już kanały znikają tvp1,2, itp nie ma.
Pozdrawiam

**Comment by Katapulta** [comment]
TO źródła padły. Prędzej czy później na "darmowej" też zaczną padać. Bo już nie kazde działa. Na to wpływu nie masz - non stop są banowane "nielegalne streamy" więc analogicznie znikają źródła z tego typu stron. Za jakiś czas wynajdą nowe źródła i po krzyku. Swoją drogą - dobrze że TVP nie ma :P Ten PISowski kabaret powinien nawet z platform cyfrowych i kablówek zniknąć :P

**Comment by abrus7** [comment]
Katapulta tu się zgodzę.. Kto chce płacić za te programy to powinny być jak abonament;)
No dzięki:D Za szybką odpowiedz

**Comment by Katapulta** [comment]
@abrus7 głównie dlatego ktoś robi i ogląda wtyczki z tv bo nie ma zamiaru płacić za nie. Tak samo jak "kupowanie abonamentu" na stronach z pirackimi "źródłami".

**Comment by koladka** [comment]
Ty sie posrancu z Po nieodzywaj jak niepasi to won

**Comment by Katapulta** [comment]
@koladka pomyliłeś pokoje ?? To nie sala dla chorych. Jak TObie coś nie pasuje to do widzenia. Albo znajdź sobie forum / miejsce gdzie ktoś taką gimnazjalną wieś jak TY będzie tolerował.

**Comment by koladka** [comment]
Przestan sie zalic koryto ucieka hhhaa

**Comment by Katapulta** [comment]
@koladka polecam dobrego psychiatrę bo jakiś problem z główką chyba @ramicspa moze by takich wywalać z tego forum bo widać chyba kompleksy i problemy muszą agenci rozwiązywać w sieciach i tylko śmiecą . 

Swoją drogą @koladka jak chcesz się pożalić to napisz do Antka - na pewno swój chorego wysłucha... :P A moje koryto nigdzie nie ucieka. Ono dopiero się zbliża.

**Comment by koladka** [comment]
Przypominam dzieciaku ze to ty zaczoles politykowac i wyzywac , wciskac swoje polityczne bzdury!;)

**Comment by Katapulta** [comment]
@koladka od dzieciaków to możesz smarku kumpli wyzywac anie 30sto paro letniego faceta.  Widać kompleks "Kaczora". Jak nie masz nic madrego do powiedzenia w temacie wtyczki czy repozytorium to wyjdź bo znowu kolki ze śmiechu dostanę :D Przerośnięte ego w sieci = brak rodziców w domu i blokady na kompa.

**Comment by koladka** [comment]
Hhaa pojechane!!;) Jedz sie poskarzyc do Brukselki

**Comment by Katapulta** [comment]
@koladka jak chcesz ja ci znajdę jakiegoś dobrego psychiatrę - bo ewidentnie problem z główką :) Masz coś "ludzkiego" i mądrego do powiedzenia w temacie repozytorium ?? Jeśli nie to rób z siebie debila i błazna dalej :) Pozdrawiam :)

**Comment by tomasiek** [comment]
@Katapulta i @koladka - dajcie na luz - obu wam się pomyliło to forum z forum onetu/gazety wyborczej. Tam przelewajcie wzajemnie swoje frustracje. Proponuję się uspokoić, choć i tak wątek poleci do kosza...

**Comment by koladka** [comment]
Ok  przyjolem .Ciekawe czy katapulttaaa przyjal zeby nierobic wywodow o polityce;)

**Comment by Katapulta** [comment]
@tomasiek  dyskusja była między dwoma osobami - do momentu jak jakiś pisuar się przyplątał  i zaczął płakać i się napinać jak sznur na maszcie... niczym bodyguard z filmu o ochronie pszczół:P Nie mam 15 lat jak ten typo żeby się "walić" na puste łby który lepszy kappa... :P Jak nie ma nic sensownego do powiedzenia - napisałem mu żeby poszukał atencji i polotu gdzie indziej bo nikt jakimś fas.....  zerem z internetu ( do tego z problemami emocjonalnymi ) przejmował się tutaj nie będzie. Niech takie zaczepy robi sobie pod wawelem może na kumplach ze szkoły zrobi to wrażenie :P O_o Jak przyszedł tu "walnąć" postem i myśli że ktoś się nim przejmie - to powodzenia.

**Comment by tomasiek** [comment]
@Katapulta - miałem ci napisać wcześniej żebyś nie karmił trola, ale widzę że też nie jesteś do końca fair w tym wszystkim. Dałeś się sprowokować - czy słusznie czy nie - nie moja sprawa, nie łączę światopoglądu z technicznymi rzeczami (a wiesz mi że bliżej mi do koladki w poglądach chyba...). jak dla mnie Panowie umówmy się prosto - ramicspa na 100% to wywali - chyba że sami z siebie wywalicie swoje dziecinne posty. Bo bawicie się jak donald i jarek w piaskownicy. To nie miejsce na to. Szanujmy pracę ramicspa i nie wciągajmy w to wszystko naszego piekiełka.

**Comment by Katapulta** [comment]
@tomasiek kwestia jest taka ze specjalnie trola nakarmiłem. Bo tylko to można było zrobić i się pośmiać. Skoro jakiś bzbek wpada nagle wielce oburzony nie interesując się "treścią" tematu założonego tutaj i pieprząc jak już nie powiem kto.. to wybacz :D Skoro nie brał udziału w dyskusji mógł użyć rozumu i nie puszyć się chcąc zdobyć sobie "widownię" :P Ja sobie nie mam nic do zarzucenia ani nei mam zamiaru się spuszczać czy produkować :P Ja nie wchodzę do "czyjegoś domu" i podczas rodzinnego obiadu nie mówię mu ze "sąsiad ma wróble na działce" :P

**Comment by abrus7** [comment]
Trolle,spam na email dostałem.. Tutaj ma odpisać tylko ramicspa.. Dziękuję,dobranoc

**Comment by VictorDorian** [comment]
źródła nei padają, na stronie tele-wizja są aktualizowane cały czas, brak tylko aktualizacji linków w repozytorium.
