### ISSUE TITLE
efilmy -blad dodatku

### ISSUE THREAD

**Issue by slavo77** [ramicspa/kodi#375]
witam wszystkich. mam problem z wtyczka efilmy. Gdy wejde w jakis film odtwarza go bez problemu, ale gdy wyjde z niego i chce wejsc jeszcze raz wtedy pokazuje mi juz tylko blad dodatku, tylko ze od teraz nie moge wejsc juz w jakikolwiek film/serial, zawsze jest blad dodatku. Zaznacze, iz mieszkam za granica wiec moze tu tkwic jakis problem. Czy wy tez tak macie? Pozdrawiam

**Comment by ramicspa** [comment]
wiem, nie spotkalem sie z takim problemem (kraj i zagranica), nik tez nic o tym nienapisal. najelpiej przeinstaluj dodatek i/lub sprawdz jak dziala z innego ip - moze twoj dostawca cos blokuje.
