### ISSUE TITLE
błąd generowania m3u z wizja.tv na andku w kodi 17.1

### ISSUE THREAD

**Issue by grzechocnik** [ramicspa/kodi#376]
Witam
mam androidTV H96pro+ z andkiem 6 i kodi 17.1 
tydzień temu pobrałem repozytorium i zainstalowałem LivePolishTV
generowanie z tele-wizja działa prawidłowo i wszystkie dostępne kanały zapisują się do listy i wszystko działa OK.
ale gdy generuję z wizja.tv to niby ładnie pobiera wszystkie kanały (56) nie zatrzymując się zbytnio na żadnym a na koniec, po ostatnim pokazuje "Błąd dodatku PolishLiveTV..." i listy m3u nie zapisuje.
W logu kodi pokazuje się informacja o powstaniu jakiegoś błędu, która zawiera m.in.
"AttributeError: 'NoneType' object has no attribute 'group'"
w linii 2 main.py

Czy u innych jest podobnie? czy to może jakaś ostatnia przypadłość wtyczki albo mojego układu hard-soft?

Czy w trakcie tworzenia m3u dane kanałów zapisywane są w jakimś pliku tymczasowym?
Może bym go przechwycił zanim zostanie skasowany i utworzył z jego zawartości jakąś osobną listę.

Jeśli to już gdzieś było a ja nie doczytałem to przepraszam i proszę o nakierowanie na rozwiązanie.

PS.
w ciągu ostatnich 2 dni w yoy.tv nie widzi ani jednego aktywnego kanału do tworzenia m3u.

**Comment by ramicspa** [comment]
powinno sie porprawic po aktualizacji

**Comment by grzechocnik** [comment]
@ramicspa : Dziękuję.
Właściwie błąd zgłoszony został naprawiony w LivePolishTV w wersji 2.3.8 więc zgłoszenie teoretycznie do zamknięcia. Lista m3u z dostawcy "wizja" się generuje pełna, wszystkie 56 kanałów. Po przeładowaniu Kodi w opcji "Telewizja" widać wszystkie kanały i tylko nieliczne nie mają EPG. 
I niby jest super bo o to chodziło, tylko że żaden z tych kanałów w tej opcji się nie odtwarza mimo iż gdy wejdę w opcji "Dodatki" na wtyczkę LivePolishTV i wybiorę wizję to kanały się odtwarzają. 

Załadowałem tu fragment loga kodi z błędami przy wywołaniu sprawdzanych 3 kanałów wizji. Niestety za cienki jeszcze jestem i nie wiem o co biega.

[kodi_log.txt](https://github.com/ramicspa/kodi/files/1170880/kodi_log.txt)

No i jeszcze zauważyłem, że w tworzonym pliku m3u pierwszy kanał jest powielony 2 razy ale za to nie ma informacji o dacie utworzenia listy, tak jak przy innych dostawcach. Podwojony w liście kanał nie wyświetla się 2 razy w opcji "Telewizja". Przy generowaniu z innych dostawców info o dacie generowania i dostawcy jest zamieszczane w m3u i widać w opcji "Telewizja".

**Comment by jac76** [comment]
Witam,

U mnie jest trochę inny problem,mianowicie lista m3u z serwisu wizja tv tworzy się i jest widoczna w kodi,jednak podczas próby uruchomienia jakiegokolwiek kanału,następuje próba połączenia i nie uruchamia się żaden kanał.....epg jest widoczne.
Mam jeszcze pytanie,jak zrobić żeby każdy kanał miał epg?bo np HBO1,2 ma epg a HBO3 już nie.
pozdrawiam

**Comment by grzechocnik** [comment]
@jac76 Co do EPG to u mnie jest tak samo z tym HBO3 i kilkoma innymi. Według mnie to chodzi o zgodność kodu kanału w liście m3u z nazwą w serwisie EPG oraz czy ten serwis w ogóle prezentuje EPG dla tego kanału.

**Comment by grzechocnik** [comment]
Miałem chwilę czasu i pobawiłem się kombinacjami uruchomień wizji z m3u i wtyczki.
Znalazłem prawdopodobną przyczynę braku odtwarzania kanałów wizji w kliencie TV. Po prześledzeniu logów kodi wyszło mi, że wtyczka wizji z repo ramicspa (która poprawnie odtwarza kanały) musi wysyłać zaraz po swoim uruchomieniu żądania o nowy token do serwisu, bo wartość tokena za każdym razem się zmienia. Zmienia się też port strumienia tego samego kanału. Zatem przepisanie tokena i portu przechwyconego przez wtyczkę LivePolishTV dezaktualizuje się zaraz po zapisaniu m3u z kanałami wizji. 
Klient PVR w kodi nie wysyła żądania o ustalenie tokenu, tylko próbuje czytać strumień zapisany w m3u ze starym tokenem - no i serwis wizji odmawia pewnie z powodu niezgodności tokenu dla tego połączenia.
Sprytne rozwiązanie zastosował ten serwis.
Topic do zamknięcia.
