### ISSUE TITLE
Nie zapamiętuje haseł w Kodi 18

### ISSUE THREAD

**Issue by zbigzbig20** [ramicspa/kodi#377]
Witam. Od jakiegoś czasu zaczęły się już pojawiać pierwsze buildy testowe Libreelec 9 oparte na nowym Kodi 18 Leia. Dostałem info od developera który kompiluje je pod androidowe zabawki (odroid c2 czy wetek play2, hub) że w nowym Kodi zmieniła się struktura pliku settings.xml i autorzy wtyczek pod to muszą je uwzględnić. Bardzo lubię kilka wtyczek z twojego repo @ramicspa . Niestety nie zapamiętuje haseł i każde wejście w danej wtyczce sekcję dalej woła o podanie hasła i raz wpisane niestety nie zostaje zapamiętane i za każdym razem trzeba je wklepywać  . Pod Kodi 17 krypton czy 16 jarvis nie ma tego problemu . Była by możliwość przystosowania twoich wtyczek wideo pod nowe Kodi 18 ? 
Pozdrawiam

**Comment by ramicspa** [comment]
czy Leia ma juz jakas dokumentacje?

**Comment by Katapulta** [comment]
@ramicspa  jak narazie nie jest chyba nawet betą.... tylko ciągle alfą... oficjalna dystrybucja może będzie dopiero w połowie bądź końcem 2018 - info z oficjalnego forum.

**Comment by zbigzbig20** [comment]
@ramicspa , póki co Leia jest w fazie alfa . Działa już dość przyjemnie tylko ten problem z zapamiętaniem hasła dla twoich wtyczek . Nie chciałbym się cofać do Kryptona ponieważ tam nie ma wsparcia dla obsługi netflixa czy amazon prime i obsługa live tv lekko kuleje a na nowym jest ok . Dało by radę coś wykombinować aby non stop nie wołało o hasło ? 
Pozdrawiam

**Comment by zbigzbig20** [comment]
@Katapulta , na innej skarcie sd mam skonfigurowany libreelec na kodi krypton 17.3 i tam tylko raz woła o hasło gdy świeżo zainstaluję daną wtyczkę wideo i później już pamięta aż do czasu jak hasło się zmieni . Głównie korzystam z cda.pl , nasze-kino, segos, tvp pl i obecnie jest to bardzo uciążliwe bo wejście w każde podmenu woła o hasło, nawet przed odpaleniem filmu

**Comment by Katapulta** [comment]
@zbigzbig20 no własnie u mnie dość często wołało i woła. Ale już sie przyzwyczaiłem.

**Comment by zbigzbig20** [comment]
Przyzwyczaił bym się gdyby sporadycznie zawołało ale za każdym razem , do tego przechodząc z sekcji filmy na seriale czy przed odtworzeniem filmu to już trochę dużo klikania . Ja jestem w miarę opanowany ale moja druga połówka dostaje furii momentami i boję się o pilot :)

**Comment by Katapulta** [comment]
@zbigzbig20 u mnie jest podobnie. Sam z ciekawości spróbuję jutro tą wersję kodi zainstalować - ponoć ma wersję x64 ... Zobaczymy potestuję też z ciekawości co i jak.

**Comment by zbigzbig20** [comment]
@Katapulta , na pc używasz Kodi czy jakimś androidowym pudełku czy mini pc na windzie? Ja już kilka zabawek na androidzie przerobiłem i obecnie zatrzymałem się na wetek play2 ,w nand ostatni ich android ale na microsd (dual boot) Libreelec (obecnie jako główny build bazowany na Kodi 18 leia ). Lubię tego typu zabawki z obsługą sat tv (tuner sat) ponieważ to u mnie podstawa ze względu na hobby (tvsat) którym się zajmuję od kilkunastu już lat a że androidowe zabawki są obecnie na czasie to fajnie mieć połączenie zabawki do multimediów i sat

**Comment by Katapulta** [comment]
@zbigzbig20  laptop, tablet, tv. Zależy co aktualnie robię - głównie laptop i TV . Tablet syn używa jak czasami chce bajki pooglądać. TV smart jakiś z androidem. Ale testy głównie na lapku / pc.

**Comment by zbigzbig20** [comment]
@ramicspa , może była by możliwość stworzenia przez Ciebie np. Takiej wersji extra twojego repo z dodatkami gdzie nie ma hasła. Np. Stworzylbys sobie na paypal konto dla dotacji, każdy z nas zainteresowanych wpłaciłby jakąś kwotę i dostałby dostęp do repo z dodatkami bez hasła . Jest to tylko propozycja ale wydaje mi się że trochę zainteresowanych osób by się znalazło

**Comment by Katapulta** [comment]
@zbigzbig20 ja tam nie mam nic przeciwko, ale badź co bądź jest to trochę sprzeczne z filozofią "wtyczki" i autora - kod jest po to żeby było wiadomo że wtyczka jest free. Zresztą masz w kazdej wtyczce info gdzie jest to wyjaśnione i dlaczego właśnie tak - bo jakiś pacan próbował zarabiać na pracy ramica: 

http://prntscr.com/g044ny

Już prędzej zrobić drugie repo pod kodi 18 albo zacząć korzystać ze stabilnej wersji. Ja jeszcze się nei bawiłem w 18stkę ale czytam że nie jest tak do końca dopracowana i dobra. Poczekam raczej aż wyjdzie jakaś stabilniejsza beta bądź też finalna wersja. Jak na razie stwierdziłem że nie ma sensu rezygnować z 17.3 i kolejnych wersji jakie wyjdą skoro działa dobrze i co najważniejsze - stabilnie. Tak samo widzę to w przypadku repo - ale to tylko moje zdanie tzn. nie ma sensu pakować się jeszcze w przystosowanie pod 18stkę skoro jest to wczesny projekt alpha.. Gdyby weszło juz w fazę beta i było by bliżej wydania oficjalnej wersji wtedy - moim zdaniem - można by było pomyśleć , bo więcej osób zaczęło by się przesiadać.

**Comment by zbigzbig20** [comment]
Pierwsza beta 18 ma  się już niedługo pojawić . Nie mam nic do kryptona bo działa dobrze i stabilnie ale brak w nim wsparcia dla netflixa czy amazon prime i live tv trochę kuleje . Ja już od jakiegoś czasu jadę na Libreelec bazowanym na 18 i jest naprawdę ok pod moją androidową zabawką . Developerzy cały czas nad tym pracują i z wersji na wersje jest co raz lepiej

**Comment by Katapulta** [comment]
@zbigzbig20 ale aktualizować trzeba ręcznie czy automatycznie się aktalizuje jesli nowa wersja bulidu wychodzi ??

**Comment by zbigzbig20** [comment]
Jak wychodzi nowy build to tylko przenoszę plik softu .tar do katalogu .update po ftp , restart boxa i automatycznie aktualizuje bez usuwania czegokolwiek . Tak samo można się cofnąć build wcześniej gdyby coś było nie tak

**Comment by Katapulta** [comment]
@zbigzbig20 tak do twjej informacji oraz @ramicspa     - w 17.3 woła mi o kod z repo wtyczki po każdym uruchomieniu kodi :) Wiec nie jest to tylko kwestia 18stki tak mi się zdaje. Będę za niedługo robił czystki i na świeżej czystej instalacji zaobserwuję co i jak - bo może to być jakiś problem nie zwiazany z programem i repo a tylko i wyłącznie po mojej stronie ;)

**Comment by tomasiek** [comment]
@Katapulta - jaki system? Na pewno zamykasz prawidłowo kodi?

**Comment by Katapulta** [comment]
@tomasiek ta tak. System win 10 akurat w tym przypadku. Na androidzie jest inna sytuacja - woła dość często przy uruchamianiu dodatków z repo o kod do wtyczki, czasami nawet w trakcie używania ( wyszukiwanie filmu / seriali ) ale jak napisałem wyżej może to być kwestia po mojej stronie - bo mam trochę syfu i muszę poczyścić dyski i komputery i ustawienia. Tak uściślając informacje - zaczęło wołać od dzisiaj :P Już kilka razy w ciągu ostatnich 30 min uruchamiałem kodi na nowo i za każdym razem przy uruchamianiu prosi o kod do repozytorium wtyczki przy wczytywaniu widgetów :) Tak więc w ciągu dnia poogarniam , zrobię czystą instalację i zobaczymy co będzie. Muszę tylko znaleźć patent na zapis wszystkich repo jakich używam żebym nie musiał wszystkiego wpisywać na nowo.

**Comment by Katapulta** [comment]
@zbigzbig20  jak ty ogladasz tv na 18stce ?? Bo nigdzie nie mogę IPTV znaleźć, ani też w jaki sposób ją na tej wersji zainstalować...

**Comment by zbigzbig20** [comment]
@katapulta , mój box posiada wbudowany tuner dvb-s2 i oglądam tv z sat + moja karta nc+

**Comment by zbigzbig20** [comment]
Witam. Można uznać temat za rozwiązany. Wczoraj zainstalowałem nowy build libreelec z z kodi 18 i już bez problemu hasło zapamiętuje :-)
Pozdrawiam
