### ISSUE TITLE
wtyczka zalukaj nie działa

### ISSUE THREAD

**Issue by NitroFuN** [ramicspa/kodi#379]
Chciałem skorzystać z wtyczki zalukaj, ale wyświetla błąd.

Kodi.log: https://pastebin.com/xYzqVDRm

**Comment by ramicspa** [comment]
niestety nie widze zadnego bledu we wtycze. czy strona ci normalnie dziala?

**Comment by drrak** [comment]
U mnie nie udało się włączyć ani jednego filmu. "No Video Link Found" i tyle.

**Comment by NitroFuN** [comment]
U mnie strona zalukaj działa bez problemu, tylko wtyczka ma problem. Wydaję mi się, że problem leży w pobieraniu linku (ucina tak jakby http: z linku)

**Comment by ramicspa** [comment]
link jest znajdowany prawidlowo - problem jest w urlresolver, ktory wymaga aktulizacji - jak sie "sam" nie naprawi to zobacze czy jakis patch nie pomoze

**Comment by ramicspa** [comment]
urlresolver nadal nie wspiera vshare ale wtyczka dostala swoj wlasny wiec powinno juz wszystko dzialac
