### ISSUE TITLE
kinex.tv

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#38]
hyba kiedys pytalem maybe?

**Comment by ramicspa** [comment]
stronka niby fajna i moznaby zrobic cos i dla niej ... ale jakos brakuje mi tam info o jakosci video. chcialbys otworzyc to czego szukalesz w SD? Pewnie poszukalbys gdzies indziej w lepszej jakosci

**Comment by xxcriticxx** [comment]
dla tesciowej jak znalazl. nie wiem czy wie co do HD

**Comment by ramicspa** [comment]
jak dla tesciowej to co innego ... podobno byly prowadzone badania z ktorych wynikalo ze czlowiek zyje dluzej jak tesciowea jest happy ;)
