### ISSUE TITLE
TVP.pl - archiwum nie jest aktualizowane

### ISSUE THREAD

**Issue by adams2** [ramicspa/kodi#380]
TVP.pl -> Informacja i Publicystyka -> Wiadomości
Archiwum z lista nie jest aktualizowana. Ostatni rekord sięga początku lipca. Co się dzieje?

**Comment by Katapulta** [comment]
Wakacje :)

**Comment by ramicspa** [comment]
sluszna uwaga, vod tvp troche zmienil sie ostatnio - wtyczce tez aktualizacja nie zaszkodzi.

**Comment by ramicspa** [comment]
jak wszystko dziala to zamykam temat

**Comment by adams2** [comment]
Wszystko dziala, mozna zamykac. Dzieki.

**Comment by adams2** [comment]
"Archiwum wiadomości" ponownie nie odświeża listy. Ostatni rekord jest z 10 września. Korzystam z plugin wersja 2.1.0. Proszę o rzucenie na ten problem okiem. Dzięki.
