### ISSUE TITLE
Witam przez przypadek odinstalowało mi się kodi i zainstalowałem na nowo ale mam problem tzn. nie moge zapisac listy na iptv wszystko ładnie wyszukuje liste znajduje lecz nie może jej zapisac ? 

### ISSUE THREAD

**Issue by jabarrson** [ramicspa/kodi#384]

**Comment by tomasiek** [comment]
Na przyszłość wpisz swój problem w description...
Załącz logi. Masz.moze polskie znaki w nazwie użytkownika w systemie?

**Comment by jabarrson** [comment]
ok będe pamiętał . nie nie mam polskich znaków . wczesniej wszystko działało a teraz nie zapisuje listy a na windowsie jest wszystko ok a na tv android lipa :(

**Comment by jabarrson** [comment]
dziwi mnie to ze lista sie wyszukuje od karzdego dostawcy a nie zapisuje? moze potrzebna jest jakaś aktualizacja?

**Comment by Katapulta** [comment]
Zapytam tak głupio bo to pierwsze co mi na myśl przychodzi gdyż miałem podobny motyw kiedyś i się długo głowiłem... @jabarrson zmieniłeś w ustawieniach IPTV http://prntscr.com/g1pl7g   bo kiedyś tego nie zrobiłem i było na TV to samo.. - lista się robiła ale nie wczytywało kanałów...

**Comment by jabarrson** [comment]
i tez teraz często mam ze mi sie wszystko kasuje tzn. czysci mi wszystkie wtyczki tak jak bym na nowo zainstalował kod? może to zależy od sprzętu tzn. tv android może mój philips juz nie daje rady albo jest zawirusowany :)

**Comment by jabarrson** [comment]
i nic już nikomu nie przychodzi do głowy co może byc przyczyna?

**Comment by jabarrson** [comment]
KATAPULTA ścieżkę zawsze zmieniam z lokalnej na zdalną ale to nie jest jednak przyczyna :( na lapku wszystko mi smiga zapisuje jak trzeba a na tv lipa
