### ISSUE TITLE
[nowy dodatek] Fork exodusa/covenant z polskimi zrodlami

### ISSUE THREAD

**Issue by homik** [ramicspa/kodi#385]
Czesc,

myslales moze nad tym aby zrobic forka exodusa/covenant z polskimi zrodlami ?
Mrknow mial cos podobnego pod nazwa FanFilm, ale od kwietnia wtyczka nie jest aktualizowana.

Za czasow exodusa dodalem polskie zrodla do niego, ale od kiedy zamknieto tvaddons i exodus stal sie covenantem autorzy nie utrzymuja githuba przez co społecznosc nie ma mozliwosci dokladania swoich zrodel linków.

Ps.
Wielki szacun za prace nad tyloma polskimi wtyczkami!

**Comment by Katapulta** [comment]
Exodus + Convenant dalej działają jako dwie osobne wtyczki i Exodus wcale nie zniknął tylko zmienił repo. 
Jak w Exodus tak w Convenant możesz w ustawieniach zmienić / ustawić żeby wyszukiwał język źródłowy jako Polski. 

Dodatkowo masz wtyczkę Specto , masz wtyczkę Filmwebbooster z tego repozytorium ramica. A jeśli jeszcze byś coś chciał... to w repozytorium gdzie znajduje się Specto znajduje się wtyczka FanFilm MrKnow która a ustawione tylko i wyłącznie polskie źródla filmów i seriali.

**Comment by homik** [comment]
Exodus zostal porzucony, nikt go nie rozwija. O FanFilm sam napisalem, ale wtyczka tez juz nie jest rozwijana. Wiem ze w exodus/covenant mozna dac polskie zrodla bo sam je tam dodalem. Covenant jest nastepca exodusa ale tak jak pisalem nie ma juz mozliwosci aktualizowania zrodel bo tworcy nie chca wsparcia community

**Comment by Katapulta** [comment]
@homik w takim razie skoro tak mówisz pozostaje ci nowa wtyczka z tego repozytorium- Filmwebbooster. Gorąco polecam bo świetna ;)

**Comment by drrak** [comment]
Sprawdziłem na szybko wtyczkę Filmwebbooster i wg mnie nie jest taka świetna. Jest tu za mało źródeł, jakość filmów (zazwyczaj słaba) nie jest opisana i większość filmów jest tylko z lektorem. W tym momencie Exodus a nawet Specto są lepsze. Przy okazji, @homik jaką masz wersje Exodus? Ja mam 3.1.22 i repo SMASH.

**Comment by homik** [comment]
3.1.22, ale ostatnia oficjalna wersja wydana przez tvaddons to 3.1.19. Reszta to tak naprawde tylko nieoficjalne repozytoria podnosily sobie wersje zeby przyciagnac ludzi do siebie.

**Comment by Katapulta** [comment]
@homik ale TV addons jako repo wcale nie znikło tylko się ukryło. Rozsyłali nawet informacje o tym w prywatnych wiadomościach do wielu ludzi. Więc pochowali się w innych repo i wtyczka działa. I nie wiem co tutaj aktualizować... skoro wszystko jest tak jak powinno.

**Comment by homik** [comment]
TVaddons zniknelo na dobre. Ich domene przejela firma prawnicza z Kanady. Pojawiaja sie informacje np. wtyczka indigo zaczyna dzialac, ale ludzie przestrzegaja przed jej uzywaniem ze wzgledu na niezaufane zrodlo.

Exodus narazie dziala ale liczba zrodel, ktore dzialaja maleje bo nikt nie dba o ich aktualizacje to tylko kwestia czasu, az wtyczka zniknie z repozytoriow (podobnie jak jego poprzednik genesis).

Co tutaj aktualizowac ? @ramicspa stworzyl ponad 30 wtyczek do roznych serwisow streamingowych, a aktualnie w covenant/exodus dzialaja jedynie alltube, filiser, szukajka, cda-hd i nie ma mozliwosci zmiany tego stanu. Pomijajac fakt ze jakakolwiek zmaiana w ktorym kolwiek serwisie wylaczy go calkowicie z uzytkowania.

**Comment by Katapulta** [comment]
@homik i tak będzie. Jedno źródło się pojawi inne zniknie. Raczej wątpliwe żeby ktoś się tym aż tak przejmował. Co do filwebboster ja nie wiem gdzie tam są słabe źródła @drrak  - weź sprawdź "źródło" wtyczki i zainstaluj ją sobie w przeglądarce chrome bo jest ona zrobiona na podstawie "wtyczki" do google chrome. 

Co do reszty kurde ludzie ale wy jęczycie.... Jak nie ma źródła  - poszukajcie w innej wtyczce. TO że nie są aktualizowane... przejmijcie wtyczkę i zacznijcie aktualizować bo branie się za exodusy / convenanty tylko dlatego ze komuś źródeł brakuje ... i nie pasuje język czy coś tam... I nie wydaje mi się żeby @ramicspa  brał się za przerabianie innych wtyczek pokroju właśnie Exodusa bo to bezsens , skoro w swoim repo posiada ich sporo i jest w czym wybierać :D 

Jak korzystam jak z exodusa tak z convenant i nie narzekam na braki czy jakieś problemy - wszystko jest, nowe filmy się pojawiają. Niczego nie brakuje. 

Poza tym przejęcie przez @ramicspa wtyczki i robienie nowej na jej bazie... może skutkowac narażeniem się na "większe ryzyko".

**Comment by kopernik1983** [comment]
@homik https://github.com/Colossal1/repository.colossus/tree/master/plugin.video.covenant
@Katapulta homik ma racje. exodus zostal porzucony , dzialac dziala ale zaleca sie jego odinstalowanie w celach bezpieczenstwa bo nie wiadomo kto i co moze z tym zrobic. autorzy exodusa wspolpracuja teraz z autorami covenant

**Comment by homik** [comment]
@kopernik1983 wiem ale to nie sa zrodla tylko juz gotowy dystrybucyjny zip. Pytalem autorow i nie chca commitow ludzi z zewnatrz.

**Comment by kopernik1983** [comment]
to moze ladnie ich poprosic zeby dodali :)

**Comment by drrak** [comment]
Chciałem zainstalować plugin.video.covenant-1.1.4.zip z linku podanego przez @kopernik1983, i niestety nie działa. Spróbuję jeszcze przez jakieś repo.

**Comment by ramicspa** [comment]
z tego co widzialem to convenant ma jakies polskie zrodla - nie bardzo wiem czy aktualnie ale cos tam jest. 
Jesli nie chca brac z zewnatrz zawsze mozna zrobic "patcha" - ktory dogra sie go instniejacej instalacji i uaktualni pluginy

**Comment by ramicspa** [comment]
@homik ... a tak w ogole to napisz to Mrknow - moze zrobi aktualizacje FanFilm

**Comment by homik** [comment]
@ramicspa  no wlasnie problem w tym ze MrKnow sie zapadl pod ziemie i nie ma z nim zadnego kontaktu :(

**Comment by tomasiek** [comment]
pomysł patcha do covenanse/pochodnych jest całkiem niezły...

**Comment by homik** [comment]
z patchem problem jest taki ze gdy wyjdzie aktualizacja wtyczki to moze ci go nadpisac albo sie nie zaktualizowac co wymaga duzo 'recznej' roboty
