### ISSUE TITLE
PVR Lista nie aktualnia się ?

### ISSUE THREAD

**Issue by jabarrson** [ramicspa/kodi#386]

**Comment by jabarrson** [comment]
tak mi wyskakuje za każdym razem jak uaktualniam ustawienia PVR IPTV Simple Client i (reaktywuj Live TV

**Comment by jabarrson** [comment]
dalej nie moge znalesc rozwiązania żeby lista m3u zapisała mi sie znajduje wyszukuje ale nie zapisuje

**Comment by tomasiek** [comment]
Fajnie. Drugi temat zakładasz, a logów o które prosiłem wciąż nie dałeś.
Tylko one nam powiedzą co i jak. Jeśli nie wiesz ja je znaleźć to
przeglądania google za hasłem kodi logs

30.07.2017 7:42 AM "jabarrson" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
@jabarrson to moze zmiej lokacje pilku gdzie ma zapisac ... tak troche kreatywnie trzeba jak cos nie chce dzialac jak trzeba.
