### ISSUE TITLE
Monthy python i inne... prośba o wtyczkę...

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#389]
Modrzew....
Znalazłem ciekawy zbiór filmów które są w cda, ale są prywatne, przez to nie znajduje ich wyszukiwarka...
http://www.monty-python.org/
Z ciekawych:
MPFC (żeby nie było - w żadnej z wtyczek nie ma wszystkich 4 sezonów - nawet w filmwebooster)....
Technicy Magicy (też nie wszędzie występuje...)
Za chwilę dalszy ciąg programu...
benny hill
jaś fasola...
itp itd.
Full absurdalnego humoru...
Larx.... modrzew....
Się prosi wtyczka do tego.... 
Źródełka z cda... strona też prosta...
(właśnie oglądam MP z innego źródła - ale szukałem z 20 minut...)

**Comment by tomasiek** [comment]
Nie mam jak sprawdzić, bo sieć na wakacjach uboga.... Ale dzięki wielkie... 
Modrzew..

**Comment by garbatyprostak** [comment]
wow ,Ramic jestes przekot:)

**Comment by ramicspa** [comment]
Stronka jest fajna, ale warto pamietac ze to uzytkowicy tam dodaja pozycje. warto by byla ciagle aktualizowana

**Comment by tomasiek** [comment]
No to jak hiszpańska inkwizycja na to pozwoli, to jak wrócę z urlopu będę o tym pamiętał...
