### ISSUE TITLE
livepolish tv aktualizacja nieudana

### ISSUE THREAD

**Issue by ebot2007** [ramicspa/kodi#39]
wiatm, pojawila sie aktualizacjia livepolish tv lecz nie chce mi jej zaktualizowac, odinstalowalem wtyczke i chcialem na nowo zainstalowac lecz teraz nie moge , jakies pomysly ?
pozdrawiam

**Comment by ramicspa** [comment]
zakladam ze instalowales przez repozytorium. jaka jest wersja repo? ... powinna byc 1.2.1

**Comment by ebot2007** [comment]
tak przez repo mam 1.2.1 , sprawdzilem teraz ina wtyczke kinex tv i tez komunikat jest instalacjia nieudana

**Comment by ramicspa** [comment]
hmm dzieki za info
sprawdzam co jest nie tak ...

**Comment by ebot2007** [comment]
dziekuje

**Comment by ramicspa** [comment]
ok problem znaleziony i sie naprawia ... ale tak dla pewnosci odinstaluj moje repozytorium 1.2.1 albo starsze (samo repozytorium, pluginny mozesz zostawic). sciagnij je ponownie z githuba (https://github.com/ramicspa/kodi/raw/master/repository.ramic.zip) i zainstaluj ponownie

**Comment by ebot2007** [comment]
wszystko juz dziala

**Comment by ebot2007** [comment]
a  i jeszcze moze by tak wykasowac mohe filmt tk nie dziala od dawna i juz raczej nie bedzie

**Comment by ramicspa** [comment]
moje filmy nie dostepne w repo od jakiegos czasu ... musisz usunac samemu ze swoich wtyczek

**Comment by ebot2007** [comment]
chodzi mi o to ze jest moje filmy tk dostepne w livepolish tv , 
http://zmniejszacz.pl/zdjecie/496/6241696_IMAG0225.jpg
