### ISSUE TITLE
Problem z odtwarzaniem przygotowanych kanałów IPTV

### ISSUE THREAD

**Issue by HowItWorks** [ramicspa/kodi#390]
Windwos10, Kodi 17.3 zainstalowany na czysto, wrzucony dodatek LivePolishTV i IPTV Simple Client. Korzystając poprzez wtyczkę mogę oglądać stream (yoy i wizja), plik m3u generuje się poprawnie, ładuje się do IPTV. Po restarcie i zaciągnięciu EPG nie mogę odtworzyć żadnego z kanałów poprzez IPTV, poprzez wtyczkę dalej działają normalnie. Załączam logi. Może ktoś wie o co chodzi? Dzięki za każdą wskazówkę!

**LOGS**: https://wklej.to/EF8Fp

**Comment by jabarrson** [comment]
mi juz od jakiegoś czasu nie zapisuje w ogóle listy IPTV ładuje wczytuje ale nie zapisuje:(

**Comment by tomasiek** [comment]
@jabbarson... A my cię od jakiegoś czasu prosimy o logi... Ale po co, prawda, lepiej wszędzie dopisywać że ci nie działa, a my mamy zgadywać... Nudne to już jest. Nikt tutaj nie wróży z fusów...
@HowItWorks... Wygląda na problem z kodekami (we wtyczce radzi sobie bo streaming  jest inaczej podawany niż w iotv - podejrzewam inny typ minę). Pod linuksem wystarczy doinstalować ffmpeg. Pod windows... Podejrzewam że może pomóc jakaś paczka kodeków... K-lite codec pack za czasów jak korzystałem z windy pomagał.

**Comment by Katapulta** [comment]
@tomasiek tyle że kompletnie żadnych kodeków nie mam zainstalowanych w systemie i wszystko śmiga - kodi nie potrzebuje chyba "zewnętrznych paczek" bo ma swoje własne. Ja po czystym formacie kompa instaluje kodi i od razu oglądam bez żadnych kodeków - jak autor tematu napisał "win 10 , instaluje kodi na czysto i działa. 

A może w ustawieniach IPTV - ale tych nie z poziomu wtyczki , tylko z poziomu "dodatki-klienty telewizji-iptv" potrzeba aktywować sam addon IPTV Simple Client albo zmienić coś w ustawieniach - może "ładowanie listy m3u ustawić na "lokalnie buforuj" czy jak to tam było...

**Comment by HowItWorks** [comment]
@tomasiek Zainstalowana paczka K-Lite_Codec_Pack_1340_Full, reboot, ale dalej to samo :(
@Katapulta Ustawienia wtyczki zostały przywrócone do ustawień fabrycznych. Zostało podane tylko źródło pliki, nie pomogło (zrzut ustawień w załączniku). 
![iptv](https://user-images.githubusercontent.com/16439154/28976607-dcd76b80-793e-11e7-8579-e0c783d54ed9.png)

**Comment by jabarrson** [comment]
Tomasiek prawda jest taka ze nie wiem jak to zrobic i jak podac te logi ?

**Comment by tomasiek** [comment]
Pisałem ci już: www.google.pl kodi log. Instrukcji jest pełno, w dowolnym
języku.

04.08.2017 6:53 PM "jabarrson" <notifications@github.com> napisał(a):

**Comment by peptydek** [comment]
Mam podobny problem, zainstalowany klient kodi-pvr-iptvsimple.
Testowane na wizja.tv
Plik z listą m3u tworzy się bez problemu, EPG działa poprawnie. Sama wtyczka odtwarza kanały bez problemu, jednak klient simple iptv nie odtwarza strumienia.
Fragment z logów:
`
ERROR: ffmpeg[7F5D2DF1F700]: [rtmp] Unknown connect error (unsupported authentication method?)
ERROR: ffmpeg[7F5D2DF1F700]: [rtmp] Server error: Connection failed.
DEBUG: Error, could not open file rtmp://77.123.139.165:1935/stac47cUdR7XevEz?event=110&token=F1jGmOBIC4kLPZ82Nih6dyopAz5aQc
`
Ten sam komunikat jest przy odtwarzaniu samym ffmpeg, też na systemach bez kodi. Testowane też na VLC.
Możesz jakoś naprowadzić czym może być to spowodowane?

**Comment by grzechocnik** [comment]
Mam z wizją ten sam problem na TVBOX Anroid6 kodi 17.1. Wtyczka wizji pokazuje streamy a to samo z dopiero co wygenerowanej listy m3u ich nie pokazuje przez klienta simple PVR. Po analizie logów wyszło mi, że wtyczka uzyskuje z serwisu wizji token i z jego użyciem dobiera się do streamów a klient PVR tego nie robi tylko ma token zapisany w adresie wywołania. Tylko że ten token był do innego połączenia i do tego z PVR już jest nieaktualny. Takie są moje osobiste wnioski. Czy ktoś ma inną teorię lub wiedzę?
yoy mi nie działa ani tu ani tu, tylko tele-wizja pokazuje i we wtyczce i w PVR - nie wiem dlaczego tak a nie inaczej :(

**Comment by ramicspa** [comment]
nie zawsze streamy z list m3u beda dzialac bo sporo (coraz wiecej serwisow) generuje linki jednorazowe. w takim wypadku tworzenie listy m3u nie ma sensu i nic na to sie nie poradzi.
