### ISSUE TITLE
Problem z odtwarzaniem streamu z cda.pl

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#391]
Od wczoraj nie można obejrzeć żadnych filmów z cda.pl w żadnej z wtyczek, bardzo proszę o poprawę

**Comment by BrownEmmett** [comment]
Zaktualizuj do 1.9.5 i będzie działać. :)

**Comment by Seico** [comment]
Dzięki , teraz działa , **ramicspa** znowu na posterunku 👍
