### ISSUE TITLE
LivePolishTV- nie uruchamia się

### ISSUE THREAD

**Issue by DarDo1** [ramicspa/kodi#395]
Nie uruchamia się LivePolishTV. Czy coś dzieje z dodatkiem czy tylko ja mam problem?

**Comment by laquarico** [comment]
Hello is there an english speaker? When i try to load live polish tv it ask for a code again which code is it please? Thx you

**Comment by tomasiek** [comment]
Please go to https://github.com/ramicspa/kodi and look for word  "KOD:" it's means code in Polish

**Comment by laquarico** [comment]
Dziękuję I naprawdę doceniam

**Comment by ramicspa** [comment]
@laquarico there is no english translation in this addon - due to its nature it's meant only for polish speaking folks.
