### ISSUE TITLE
CDA.pl nie można  odtworzyć żadnego filmu

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#396]
Witam problem polega na tym ze cda.pl wydawałoby sie ze fajnie działa a mianowicie: znajduje wszystkie filmy, można obejrzeć zwiastun, wybrać jakość obrazu i na tym sie kończy. Przykład: wybieram film, jakość i zaczyna ładować film i koniec nic więcej sie nie dzieje. Próbowałem różne filmy i od kilku dni to samo. Używam:
kodi v17.3 - Krypton
system: Android 5.1.1
Ktoś coś?
Pozdrawiam

**Comment by Kiniuxxx** [comment]
U mnie na Raspberry OSMC Kodi 17.3 Skompilowany: Jul 29 2017
CDA ver: 1.9.5
Działa wszystko ok

**Comment by krriss** [comment]
U mnie jest dostępna tylko wersja 1.9.4 i może stad ten problem?

**Comment by krriss** [comment]
![image](https://user-images.githubusercontent.com/23279310/29253793-7f53b63e-807e-11e7-904e-729a7364d5d7.jpg)

**Comment by krriss** [comment]
Sorry to zdjęcie chciałem dodać:

![image](https://user-images.githubusercontent.com/23279310/29253808-f4894252-807e-11e7-93b2-80bd6df7779c.jpg)

**Comment by xxcriticxx** [comment]
update repo zrub do 1.3.5

**Comment by krriss** [comment]
Tak samo jak wyżej: dostępne są tylko 3 te SAME wersje w tym przypadku taka: 1.3.3
![image](https://user-images.githubusercontent.com/23279310/29260835-39f0a962-80c4-11e7-8943-ab3f6703c691.jpg)

**Comment by tomasiek** [comment]
Pobierz ręcznie najnowsze że strony, lub dodaj lokalizację zgodnie z
informacją że strony głównej repozytorium.

14.08.2017 8:43 AM "krriss" <notifications@github.com> napisał(a):

**Comment by krriss** [comment]
Dzięki @tomasiek podzialalo! Pozdrawiam

**Comment by 40ii4** [comment]
A działa wam po zalogowaniu własna zawartość, tj. ulubione, folder główny, obserwowani użytkownicy? U mnie pusto po otwarciu folderu.

**Comment by superGrzes** [comment]
Mi premium nie dziala. Jak odpale chrome i wejde na cda to chodzi ladnie ale na wtyczce pokazuje ze zalogowane normalnie ale filmu z premium nie odpale...

**Comment by ramicspa** [comment]
Zawartości premium (płatne) mogą nie działać ...nie będą też wspierane przez wtyczke.

**Comment by djvolt1942** [comment]
Czyli juz nie bedzie dzialac cda.pl premium z filmami? A co trzeba zrobic, zeby dzialalo? Ile trzeba zaplacic?

**Comment by Katapulta** [comment]
@djvolt1942 nic nie trzeba robić bo nie będzie działało.

**Comment by tomasiek** [comment]
Można kupić na CDA pakiet premium i sprawdzić czy wtedy będzie działać. Jak
tak, to u nich kupować...

19.08.2017 7:00 PM "Katapulta" <notifications@github.com> napisał(a):
