### ISSUE TITLE
LiveTV: sport.tvp - Pusty

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#397]
Chyba wtyczka padła? Bo otwieram a tam nic nie ma?
Dzięki i pozdrawiam

**Comment by Kiniuxxx** [comment]
U mnie na Raspberry OSMC Kodi 17.3 Skompilowany: Jul 29 2017
LivePolishTV ver: 2.4.0
Działa wszystko ok

**Comment by krriss** [comment]
U mnie jest dostępna tylko wersja 2.3.7 i może stad ten problem?

**Comment by krriss** [comment]
![image](https://user-images.githubusercontent.com/23279310/29253800-b5b7d3ae-807e-11e7-8c74-d623655af93f.jpg)

**Comment by mbebe** [comment]
Instaluj repo za pomoca zrodla http://ramicspa.github.io/kodi/
Wtedy aktualizacja bedzie ok.

**Comment by krriss** [comment]
Dzięki @mbebe podziałało pozdrawiam

**Comment by noirrak** [comment]
@krriss masz teraz na liście tylko jedno repo?

**Comment by ramicspa** [comment]
Są dwa tak na wszelki wypadek gdyby jedno przestało działać
