### ISSUE TITLE
Przegląd wtyczek

### ISSUE THREAD

**Issue by kopernik1983** [ramicspa/kodi#398]
Zalukaj : brak źródeł ( na stronie wszystko działa )
Kinostacja : niby jest źródło ale nie znajduje video ( na stronie działa )
Efilmy.tv : nie działa wyszukiwanie ( błąd dodatku ), prośba o ile jest taka możliwość dodania wpisywania CAPTCHA ( na tą chwilę żeby obejrzeć coś we wtyczce trzeba odwiedzić stronę i odpalić cokolwiek żeby wpisać kod inaczej wtyczka nie działa. doliczyłem się 3 odsłon tak na szybko bez oglądania tylko włączając po kolei i proces trzeba powtarzać ).
Efilmy-online : odświeżenie źródeł  ( na stronie wszystko działa we wtyczce tylko źródła ze streamango.com. które nie znajduje się we wszystkich filmach sprawdzone wyrywkowo na filmach z 2017 ). 
e-kino.tv : nie można odtworzyć żadnego filmu we wtyczce ( żadnego info typu inny link itd. nic sie nie dzieje. na stronie działa.
To dodam jeszcze IITV . Zero żródeł. tez by się aktualizacja przydała.

**Comment by ramicspa** [comment]
Dzieki za info.pewnie od przyszłego tygodnia zaczną pojawiać się aktualizacje

**Comment by przemex8123** [comment]
Nie mam kodu i nie potrafię to znaleźć

**Comment by Katapulta** [comment]
@przemex8123 wejdź na stronę główną repozytorium .... i czytaj dokładnie. Wszystko jest napisane po POLSKI i dużą czcionką...

**Comment by kopernik1983** [comment]
@przemex8123  ileż można to wałkować. https://github.com/ramicspa/kodi szukaj a znajdziesz albo nie szukaj a zacznij czytać.

**Comment by ramicspa** [comment]
zalukaj i konostacja dziala ok, problem byl w urlresolver - ktory nie dziala dla vshare ... ale dorzucielm obejscie wiec jest ok.
co do Efilmy to captcha dziala we wtyczkie i kiedy trzeba wyskaluje
efilmy-online i ekino.tv dostaly aktulizacje podobnie jak iitv seriale. wszystko juz powinno smiagac jak trzeba.
