### ISSUE TITLE
CinemaHD pytanie 

### ISSUE THREAD

**Issue by Kamilo87** [ramicspa/kodi#399]
Czy jest szansa na to że będą się pojawiać nowe pozycje? Nie pamiętam kiedy ostatnio były dodane jakieś nowości . 
Zauważyłem również że znikają źródła z raptu .
Czy ta wtyczka powoli się kończy ? Naprawdę było by szkoda :(

**Comment by abrus7** [comment]
Nie tylko Ty zauważyłeś,że admin chyba już kończy też tutaj:/

**Comment by Katapulta** [comment]
Sami się kończycie :) Kappa :) @Kamilo87 skoro znikają źródła z raptu to znaczy że problem nie jest we wtyczce tylko w samym raptu - a łopatologicznie znaczy to tylko tyle że na raptu filmy są usuwane i ich nie ma :D I nic sie na to nie poradzi :) 
@abrus7 co kończy ?? Wszystko działa więc czego ty chcesz ?? Wtyczek w repo jest wystarczjąca ilość - jak ci jakichś brakuje zainstaluj z innych repo. Wszystko działa więc nie wiem o co znowu żal dupy i płacz się robi :) 

A jeśli ktoś nie rozumie - skoro jakieś źródło w jakiejś wtyczce nie działa jak np wspomniane raptu to piszcie do właściciela RAPTU dlaczego nie ma filmu bo to nie wina wtyczek czy ramica a tego kto w RAPTU film umieścił i go usunął :) Ja nie wiem , coś nie tak z tokiem rozumowania się dzieje na tych upałach.

**Comment by abrus7** [comment]
Czemu tzw Ty odpisujesz a nie Ramic? Nie widziałem jego posta już dawno..

**Comment by Katapulta** [comment]
@abrus7 a co on się musi spowiadać i meldować żebyś jego posty zobaczył ?? :D Jak ma coś do powiedzenia to pisze :) Jeśli coś nie jest warte - zapewne nie zwraca na to uwagi ;)

**Comment by abrus7** [comment]
Jak pamiętam,zawsze przenosił "kiepskie" pomysły do archiwum lub napisał,że coś nie opłaca się lub coś.

**Comment by tomasiek** [comment]
Ramicspa raczej nie odpisuje na posty. Jak do tej pory jest dość lakoniczny
w wypowiedziach. Uszanujmy to. Poza tym - nie ma on żadnego wpływu na
źródła... On tylko dostarcza wtyczki. W przypadku cinemahd trzeba pytać
kogoś innego... Zapytam jak będę miał okazję...
Ramic ostatnio wypowiedział się tydzień temu aktualizując repo. Są wakacje,
okres urlopowy....


17.08.2017 2:19 PM "abrus7" <notifications@github.com> napisał(a):

**Comment by abrus7** [comment]
A nie wiecie,czy wykonuje wtyczki za opłatą dedykowaną?

**Comment by tomasiek** [comment]
Nie. Wtyczki są darmowe. Chcesz płacić to idź do alientv.

17.08.2017 2:30 PM "abrus7" <notifications@github.com> napisał(a):
