### ISSUE TITLE
Wtyczka ekstraklasa oraz privatehd

### ISSUE THREAD

**Issue by Wolframos** [ramicspa/kodi#40]
Witam,
czy tylko u mnie występują jakieś dziwne problemy z wtyczką ekstraklasa? Po jej wybraniu nic się nie dzieje, mam pustą bibliotekę... Tak już jest od kilku dni. Testowałem na Kodi 16 oraz 17 (przez aplikację w windows store).

Druga sprawa. Czy jest szansa na dodanie do wtyczki nowego źródła tj  privatehd.pw ?

**Comment by ramicspa** [comment]
Witam,
Dzieki za info. Wtyczka powinna dzialac poprawinie ostatni update (wersja 1.6) dodaj wybor jakosci strumieni live.
Sprobuj najpierw odinstallowac wtyczke oraz repozytorium (tak na wszelki wypadek) sciagnij ponownie z githuba i po restarcie kodiego zainstaluj repo oraz potem wtyczke z repo. Daj znac czy pomoglo

**Comment by Wolframos** [comment]
Ściągnąłem ponownie z git, ale nie pomogło. Po kliknięciu na ekstraklasa "Menu" na sekundę się pojawia i znika.
Może jakieś logi podesłać? Tylko w jaki sposób je włączyć? ;)

**Comment by ramicspa** [comment]
hmm dziwna sprawa. Logi najlepiej podesla przez http://pastebin.com/. Najlepiej wylacz kodiego, usun log.txt, odpal kodiego i od razu wtyczke (tylko interesujaca czesc bedzie w logu)
A tak poza tym to chyba cos kodim nie tak, moze sprobuj zainstalowac repo i wtyczne na swierzym kodi (trzeba wywalic program i jego ustawienia i potem zainstalowac ponownie) Kodiego pobierz przez oficjalna strone https://kodi.tv/ a nie windows store. Mozesz tez sprawdzic na androidzie (przez google play store)

**Comment by Wolframos** [comment]
OK. Teraz działa. To chyba była kwestia Kodi w wersji beta 17.1.

**Comment by ramicspa** [comment]
Ok to super. Trzeba uważać na wersje beta. Pozdrawiam

**Comment by Wolframos** [comment]
Możliwe, że stare wtyczki nie są kompatybilne z Kodi 17. Pewnie coś pozmieniali.

**Comment by ramicspa** [comment]
problemy z ekstraklasa zniknely - wtyczka tez jest juz kompatybilna z kodi 17. zamykam temat

**Comment by kalaprezes** [comment]
czesc mam problem z aplikacja ekstraklasa .Najpierw prosila o uaktualnienie aplikacji czego nie dalo sie zrobic.Zdecydowalem sie usunac wtyczke a teraz nie moge jej zainstalowac ,bardzo prosze o pomoc w tym temacie .Pozdrawiam Kala

**Comment by tomasiek** [comment]
Zauważyłeś że repo jest zamknięte? Na głównej stronie masz.
