### ISSUE TITLE
Nieudane instalowanie zależnego dodatku

### ISSUE THREAD

**Issue by shaggee** [ramicspa/kodi#401]
Od 2 godzin próbuję zainstalować którąkolwiek wtyczkę z repo ramicspa. Instalacja każdej wtyczki się nie powodzi. Wyświetla się komunikat "Nieudane instalowanie zależnego dodatku". Udało się jedynie zainstalować LivePolishTV.
Jak sobie z tym poradzić?

**Comment by ramicspa** [comment]
Upewnij się że masz zainstalowana ostatnia wersje repozytorium. Kodi czasem ma problem z zainstalowaniem zależności więc restart może pomóc. Doinstaluj też jakieś repo co ma urlresolver bo sporo wryczek z niego korzysta

**Comment by shaggee** [comment]
Dzięki. Urlresolver pomógł. Może warto to też dodać do repo ramic?
