### ISSUE TITLE
Cda.pl nie widzi zawartości folderów z sekcji "Ulubione"

### ISSUE THREAD

**Issue by 40ii4** [ramicspa/kodi#403]
Po zalogowaniu we wtyczce cda i wejściu w Ulubione, wtyczka nie widzi zawartości plików wideo wewnątrz danego folderu. Jest pusto bez żadnego błędu.

**Comment by ramicspa** [comment]
pewnie nie ma obslugi folderow dla ulubionych ... powinno dac sie to naprawic

**Comment by 40ii4** [comment]
[kodi.txt](https://github.com/ramicspa/kodi/files/1251653/kodi.txt)

Jak będziesz sprawdzał to sprawdź jeszcze obserwowanych użytkowników. Widzę zawartość wszystkich obserwowanych użytkowników prócz cda.pl/ratownik99 
Wywala błąd przy próbie otwarcia. Przez stronę działa.

**Comment by 40ii4** [comment]
Działa. Dzięki
