### ISSUE TITLE
LiveTV: sport365 padło - puste

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#404]
Tak jak w temacie. Juz 2 dzień brał jakiejkolwiek zawartości. 

Pozdrawiam

**Comment by ramicspa** [comment]
a mi sie cos tam pojawia i nawet dziala. pewnie cos innego blokuje dostep. stronka ci biega?

**Comment by DarDo1** [comment]
Wczoraj chciałem oglądać ligę mistrzów i faktycznie we wtyczce pusto. Przez stronę działa.

**Comment by krriss** [comment]
Wywaliło sie sie wszystko około godziny 20:55. Ale dzis nie miałem jeszcze szansy sprawdzać.

**Comment by ramicspa** [comment]
Jak coś padło to już naprawili bo wszystko działa.
