### ISSUE TITLE
filiser tv padło ogladnie 

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#405]
nie da sie włączyć seriali np. zoo i innych seriali  sezon 3 wyskakuje taki komunikat 
![problems](https://user-images.githubusercontent.com/24533475/29736643-8f093d68-8a03-11e7-8e55-b17c8e09d572.png)

**Comment by krzysztof222** [comment]
używam kodi 17.,3

**Comment by krzysztof222** [comment]
nie moge zaktualizowac na wersje 1.6

**Comment by ramicspa** [comment]
Restart kodi zwykle pomaga w takich sytuacjach

**Comment by krzysztof222** [comment]
po 24 godzinach w końcu się zaktualizowało
