### ISSUE TITLE
gomovies.to - proponuję dodać ten serwis

### ISSUE THREAD

**Issue by slawek12** [ramicspa/kodi#408]
Witam.
Proponuję dodać serwis 
https://gomovies.to/
Ogromna baza i w dobrej jakości.

**Comment by krzysztof222** [comment]
jestem za bardzo dobry serwis

**Comment by zm1c4l** [comment]
Sporo materiałów jest w HD można by komfortowo oglądać filmy i seriale z napisami. Też jestem za dodaniem tego serwisu.

**Comment by ramicspa** [comment]
glownie patrze na polskie strony/materialy bo do nich ciezko o wytczke.
