### ISSUE TITLE
Steam Link

### ISSUE THREAD

**Issue by mejzer** [ramicspa/kodi#411]
Żadna wtyczka nie chce działać na Steam Link. Komunikat: Uaktualnij repozytorium oraz plugin by go uruchomić. Na dwóch komputerach wszystko ok. Problem z samym Steam Link. Od Kodi Add-on repository wszystko działa.

**Comment by ramicspa** [comment]
sorki za zwloke z odpowiedzia ... nie wiem co to za urzadzenie, nie pomoge.
