### ISSUE TITLE
CinemaHD

### ISSUE THREAD

**Issue by wudekadowsky** [ramicspa/kodi#412]
Cześć, mam problem z wtyczką CinemaHD, nagle zniknęły mi wszystkie kategorie. Czy wie ktoś, jak to naprawić? Będę bardzo wdzięczny za pomoc. Proszę zerknąć na poniższy screen shot.

![2017-08-30](https://user-images.githubusercontent.com/31480557/29877845-a806a5e2-8d98-11e7-9dd2-2d5c30b36fc6.png)

**Comment by rokibalboa** [comment]
Potwierdzam,pusto.

**Comment by flexfit1983** [comment]
Pusto, ogolnie ostatnio ciezko o jakiekolwiek info co sie dzieje z CinemaHD

**Comment by kizdebski** [comment]
U mnie to samo. Być może udałoby się jakoś wspomóc autora w fixach tego typu bugów? Jestem akurat programistą z wieloletnim doświadczeniem. Ot tak w ramach community ;)

**Comment by flexfit1983** [comment]
Ciezko wspomoc jesli autor sie nie odzywa ogolnie zapanowala totalna cisza 
Trudno trzeba szukac nowych zrodel

**Comment by ramicspa** [comment]
Technicznie nie ma żadnego problemu z tą wtyczka. Po prostu baza danych aktualnie nie jest dostępna. Dzięki za ofertę pomocy.

**Comment by Kamilo87** [comment]
Wiadomo kiedy będzie dostępna baza danych ?

**Comment by iwanator** [comment]
teraz to samo tyczy się też innych wtyczek u mnie od dziś pusto brak baz danych
