### ISSUE TITLE
wielka prośba 

### ISSUE THREAD

**Issue by krzysztof222** [ramicspa/kodi#415]
mógłbyś zrobić nową wtyczkę pod tvnplayer ,gdyż mr.know raczej nie baw  się swoimi wtyczkami w ogolę nie robi aktualizacji , wiec liczę ze na ciebie , a wyszła nowa wersja TVN Playera ,

**Comment by krzysztof222** [comment]
tak jak zrobiłeś osobno altube chociaż  mr .know też ma w swoim repozytorium tą wtyczkę

**Comment by wisiann** [comment]
Sprubuj tego ,
http://kodiwpigulce.pl/jak-ogladac-player-pl-za-granica-bez-vpn-poradnik/
