### ISSUE TITLE
Live IPTV

### ISSUE THREAD

**Issue by luxjac** [ramicspa/kodi#418]
Przepraszam, jeśli temat nie na miejscu, Gdzie można poczytac jak ustawić dodatek live iptv aby działał w kliencie tv.?
Co zrobić aby stream z tego dodatku nie urywał się po paru lub parunastu sekundach ?

**Comment by grzechocnik** [comment]
tu jest wpis z obrazkiem
https://github.com/ramicspa/kodi/issues/13
