### ISSUE TITLE
Mecze online

### ISSUE THREAD

**Issue by plumers** [ramicspa/kodi#420]
Witam , jako że nie ma już alternatyw - w Tobie nadzieja ramic... wtyczka sportowa z linkami stronki 

https://www.meczyki.pl/

https://www.meczenazywo.pl/

https://www.mecze24.pl/

jeżeli znajdziesz czas i ochotę - pozdrawiam

**Comment by rokibalboa** [comment]
Oj przydało by się w repozytorium.😀

**Comment by krzysztof222** [comment]
mozna było by dolaczyc do tego vipbox .nu duzo sportu w hd 
![opera snapshot_2017-09-05_165646_www vipbox nu](https://user-images.githubusercontent.com/24533475/30067495-44cb5834-925b-11e7-8c2b-bc56a461ab80.png)

**Comment by ramicspa** [comment]
@plumers thx za info. jak sie cos spodoba do dorzuce jak bedzie chwilka.

**Comment by kashkash18** [comment]
@ramicspa będzie coś z tego ??

**Comment by plumers** [comment]
podbijam :) ostatnio by się zdało LM już ruszyła i ni ma gdzie zalookać :) pozdro

**Comment by plumers** [comment]
dziś znów LM  uda się --- pomożecie ?? :)

**Comment by plumers** [comment]
ok mam już od znajomego dostęp do nc+go --- pozdrawiam :)

**Comment by ramicspa** [comment]
@plumers nie ma jak znajomosci :)
