### ISSUE TITLE
jak zainstalować starszą wersję LivePolishTV?

### ISSUE THREAD

**Issue by grzechocnik** [ramicspa/kodi#421]
chciałbym zrobić eksperyment i zainstalować u siebie zamiast obecnej wersji 2.4.2 to starszą, a konkretnie 2.3.8 tej wtyczki. Aby przekonać się czy wersja ma wpływ na odbiór kanałów wizji. W starszej odbierałem wszystkie a w nowej mam to co niektórzy zgłaszali o konieczności premium.
Pytanie: jak i skąd pobrać starszą wersję zipa repozytorium z wtyczką 2.3.8?

**Comment by abrus7** [comment]
kanały dłużej działają polsat itp.. U niektórych jest że trzeba premium i ze za darmo są 3h.
Oglądam Polsat i zobaczę ile h pociągnę.

**Comment by grzechocnik** [comment]
Jeżeli ktoś zorientowany lub sam autor @ramicspa odpowiedziałby na moje pytanie, byłbym wdzięczny.
Proszę nie wpisywać komentarzy nie dotyczących pytania, bo to zaśmieca wątek. Dzięki.

**Comment by Katapulta** [comment]
Nie da się zainstalować starszej wersji.

**Comment by grzechocnik** [comment]
a może ktoś ma zipa z wersją 3.8.2 pobranego lokalnie i może wystawić?

**Comment by ramicspa** [comment]
jak cos nie dziala w aktualnej wersji to na pewno nie bedzie w starszej.
starszych wersji wtyczek nie archiwizuje.

**Comment by waldi22** [comment]
Az sprawdzałem z ciekawości wczoraj wieczorem i dzisiaj rano .LivePolish wersja 2.3.3 android tv, KODI16.1 wszystkie kanały z Wizji.tv wchodzą jak narazie bez problemu , natomiast w wersji 2.3.3  brak listy kanałów w tele-wizja .

**Comment by ergonom** [comment]
[repository.ramic.zip-1947902576.zip](https://github.com/ramicspa/kodi/files/1285968/repository.ramic.zip-1947902576.zip)

**Comment by ergonom** [comment]
Up dla grzechcnik
[repository.ramic.zip-1947902576.zip](https://github.com/ramicspa/kodi/files/1286019/repository.ramic.zip-1947902576.zip)gm

**Comment by grzechocnik** [comment]
Dzięki za ZIPa. Rozpakowałem, przejrzałem ale on nie zawiera kodów wtyczek tylko linki do github.
Jest tak jak tu powyżej napisał @ramicspa że nie ma archiwum starszych wersji bo linki są do katalogu github, a tam jest tylko bieżąca wersja wtyczek.
Wniosek jest taki: 
żeby zainstalować starszą wersję wtyczki trzeba mieć skopiowany dawniej, na boku jej kod z katalogów wtyczek KODI i podgrać go w to samo miejsce, nadpisując najnowszy kod.
Temat zamykam jako wyczerpany.
