### ISSUE TITLE
Mała prośba yoy.tv

### ISSUE THREAD

**Issue by byczuniuniu** [ramicspa/kodi#424]
Hej,

istnieje możliwość dodania yoy.tv? Jeżeli potrzeba to mogę podrzucić sposób logowania po api (mobile) + otrzymanie linku streamu. Mrknow zapadł się pod ziemię więc w Tobie nadzieja :D

**Comment by tomasiek** [comment]
yoy.tv obecnie nie działa bez premium. A zasoby premium z definicji nie będą obsługiwane
https://github.com/ramicspa/kodi/issues/407#issuecomment-327306256
https://github.com/ramicspa/kodi/issues/332#issuecomment-309875163

**Comment by byczuniuniu** [comment]
Co do premium to się zgodzę. Link #407 co podesłałeś dotyczy wtyczki LivePolishTV, a mi raczej chodzi o dodanie do repozytorium wtyczki obsługującej ten serwis. Więc każdy kto posiada tam konto (premium) mógłby sobie spokojnie oglądać. Istnieje jeszcze jedna opcja i raczej każdy byłby zadowolony jednak wolę tutaj o tym nie pisać z tego względu, że dostęp tutaj jest publiczny.

**Comment by koladka** [comment]
Popieram prosbe do yoy tv dla logowania premium!;)

**Comment by abrus7** [comment]
ja tak samo:)

**Comment by ramicspa** [comment]
Obsługa premium nie jest planowana.
