### ISSUE TITLE
Szukajka

### ISSUE THREAD

**Issue by Menkind1978** [ramicspa/kodi#427]
Witam!  Jest problem z Szukajka we wtyczce pusto. Jeszcze jedno pytanie: zródło Streamango nie działa w żadnej wtyczce, czy to problem samego źrodła? Ktoś coś wie? Pozdrawiam

**Comment by mbebe** [comment]
Potwierdzam Streamango. Jest pusto w wyborze rozdzielczosci. W sobote bylo ok.

**Comment by zm1c4l** [comment]
Pomimo braku wyboru w rozdzielczości to jednak odtwarza. W kwestii szukajki to trzeba oczywiście poprawić bo nie wyświetla żadnych wyników.

**Comment by ramicspa** [comment]
Dzięki za info. Niebawem pojawi się poprawka

**Comment by homik** [comment]
@ramicspa  poprawilem to juz dla covenanta zmienilo sie pare spanów na divy, prosty fix (https://github.com/homik/plugin.video.covenant/commit/f3fef3684530c4d431bfa99783eda0ab1a6858b7#diff-61edefe65167537beffb00751b4e7fefL82)

**Comment by ramicspa** [comment]
dzieki za info. wtyczka juz poprawiona
