### ISSUE TITLE
CDA.PL kaput wtyczka nie działa

### ISSUE THREAD

**Issue by BrownEmmett** [ramicspa/kodi#429]
Wtyczka CDA nie działa. Czasami nawet wyskakuje, że film jest dla kont premium ale na stronie nie jest dla kont premium. 

https://image.prntscr.com/image/jRQ5lNn8Slqwts7itjoGNg.png

`11:38:15.781 T:8824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\NAZWA\AppData\Roaming\Kodi\addons\plugin.video.cdapl\main.py", line 2, in <module>
                                                import zlib, base64; exec(TUTAJ BYŁ STRASZNIE DŁUGI KOD)
                                              File "<string>", line 1, in <module>
                                              File "<string>", line 514, in <module>
                                              File "<string>", line 171, in l1l1ll1l_cda_
                                              File "<string>", line 199, in l1ll1ll1_cda_
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)
                                            -->End of Python script error report<--
11:38:15.809 T:6756   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.cdapl/?json_file=&foldername=111+%C5%9Awiat+Wed%C5%82ug+Bundych&ex_link=https%3A%2F%2Fwww.cda.pl%2Fvideo%2F15889484&mode=decodeVideo]
`

**Comment by kopernik1983** [comment]
coś tam znowu pozmieniali dlatego nie trybi. trzeba czekać na aktualizację. jak komuś potrzeba to phantom już zaktualizowany i działa.

**Comment by BrownEmmett** [comment]
@kopernik1983 wiem, że Phantom działa tylko chciałem dać znać bo wczoraj się do wyra położyłem i zawsze odpalam na sen Świat według Bundych (polecam dodać sobie tego pana cda https://www.cda.pl/Znajomywy) i dupa blada była. :P

**Comment by ramicspa** [comment]
poszla aktualizacja wtyczki, powinno juz wszystko biegac.
