### ISSUE TITLE
KINO FREEDISC

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#43]
jest znowu

**Comment by ramicspa** [comment]
czy byl problem z instalacja pluginu (przez pewnie czas)?

**Comment by xxcriticxx** [comment]
nie

plugin miales wypuscic i zabrali kino freedisc ze strony teraz znowu jest `http://freedisc.pl/seriale-online/najnowsze`

**Comment by ramicspa** [comment]
![image](https://cloud.githubusercontent.com/assets/12544737/18871204/a71d36ca-84b4-11e6-9701-0298e95377d8.png)

**Comment by xxcriticxx** [comment]
umnie dalej dziala moze to na weekend tylko wlaczaja

**Comment by xxcriticxx** [comment]
znowu zniklo to ze strony
