### ISSUE TITLE
eFilmy

### ISSUE THREAD

**Issue by ormex** [ramicspa/kodi#431]
Witam .Jeśli można to proszę o poprawkę wtyczki efilmy - od ponad tygodnia nie ma możliwości obejrzenia filmów. Lista z wyborem działa ok - ale przy próbie odtworzenia wyskakuje błąd. Z góry dzięki za poprawkę i pozdrawiam

**Comment by ramicspa** [comment]
dzieki za info. powinno sie poprawic w nowej wersji (1.14) choc niektore zrodla czasem moga miec problem. uaktulaniaj urlresolver.

**Comment by zm1c4l** [comment]
W chwili obecnej streamango pasywnie blokuje możliwość oglądania w kodi o ile nie wyjdzie opcja parowania urządzeń to obawiam się że efilmy pójdą w odstawkę na długi czas.

**Comment by bart00777** [comment]
Szkoda bo to moja jedna z ulubionych wtyczek..

**Comment by ramicspa** [comment]
nie widze problemu z ta wtyczka. jak jest dostepne zrodlo i dziala to wtyczka tez sobie z nim radzi.
