### ISSUE TITLE
IPLA TV

### ISSUE THREAD

**Issue by lampardzino** [ramicspa/kodi#432]
witam jest szansa zrobienie wtyczki do tego ? ponieważ Mr know czy jak mu tam ma ale nie ma dużo nowych programów chyba nie aktualizują sie wog , a Ty Player zrobiłeś superowo i była by szasna ?

**Comment by ramicspa** [comment]
ipla nie ma zbyt wiele darmowych materialow ... no chyba ze ma ... podaje jakies przyklady

**Comment by lampardzino** [comment]
The Brain genialny umysł , Wyspa Przetrwania , Modelki Plus Size i wiele seriali swoich

**Comment by ramicspa** [comment]
kodi 17 natywnie nie obsluguje streamow z ipla - Leia powinna roziwazac ten problem. ipla zdaje sie ze od pewniego czasu zaczela uzywac tych samych protokolow co netflix.
Jak wyjdzie K18 to wrocimy do tematu.

**Comment by MDIV666** [comment]
To jak możemy wrócić do tematu? netflix śmiga aż miło (Kodi 18 linux mint) teraz fajnie byłoby mieć iple

**Comment by MDIV666** [comment]
@ramicspa 
ping

**Comment by tomasiek** [comment]
Ale kodi 18 to ciągle alpha. Nawet nie beta, że już nie mówię o jakimś RC. Nie ma sensu robić wtyczki jeśli za tydzień wszystko się może zmienić. Poczekaj aż kodi dojdzie do jakotakiej stabilności (rc1) to wtedy będzie można mówić o robieniu wtyczki.

**Comment by MDIV666** [comment]
Jeśli chodzi o to że mogą być zmiany to już rozumiem. Bo jak dla mnie stabilność Alfy jest bardzo dobra. Dzięki za odpowiedź.
