### ISSUE TITLE
efilmy.online

### ISSUE THREAD

**Issue by KML73** [ramicspa/kodi#434]
Po otwarciu przedmiotowej wtyczki w tym poszczególnych folderów np. "Filmy", "Rok" itd. nie wyświetla się nic ...

**Comment by ramicspa** [comment]
sprawdze strone jak bedzie online

**Comment by mers1** [comment]
Po ostatniej aktualizacji i wpisywaniu kodów wyświetlających się na ekranie wyskakuje komunikat nie udane odtwarzanie, wersja 1.14 dodatku. a wcześniej występował komunikat "unexpected token var"

**Comment by ramicspa** [comment]
jak wroci serwis to wtyczka tez sie pojawi.
