### ISSUE TITLE
Live Polish TV nie dziala od kilku dni.(Niemcy)

### ISSUE THREAD

**Issue by lancakyr** [ramicspa/kodi#436]
Witam, jak w tytule, od kilku dni wtyczka LivePolishTV nie działa.
Chciałbym wiedzieć czy to znany problem lub u mnie coś nie działa, 
pozdrawiam
![screenshot000](https://user-images.githubusercontent.com/32078997/30566428-507954c6-9ccc-11e7-9ec2-3fd15d644aec.png)

**Comment by abrus7** [comment]
Nie działają zródła. Telewizje pozmieniały zródła co 2-3 dni zmieniają a nie ma możliwości zapewne automatycznej aktualizacji i trzeba czekać na aktualizację od repa

**Comment by zm1c4l** [comment]
Za darmo i bezproblemowo obejrzeć można jedynie z PilotWP pozostałe źródła to jak loteria. Natomiast jeśli nie żałujemy $ to można skorzystać z wizji tv z osobnej wtyczki która działa pod premium oferując stabilny stream z jakością 540p.

**Comment by abrus7** [comment]
PilowWP działa na terenie Polski chyba,że proxy:D

**Comment by ramicspa** [comment]
PilotWP działa wszędzie :)

**Comment by zm1c4l** [comment]
Z kodi istotnie działa wszędzie z przeglądarki już nie :)

**Comment by bart00777** [comment]
PilotWp w darmowej wersji to troche bida niestety.

**Comment by koladka** [comment]
Ja potwierdzam ze  Pilot WP nie dziala w UK  i to samo problem ze zrodlem w Live Polish tv

**Comment by ramicspa** [comment]
po aktualizacji powinna juz wiekszosc dzialac.

**Comment by joann12** [comment]
Wtyczka nie działa. Po jej kliknięciu, kręci chwilę i kompletnie nic się nie dzieje. Reinstalacja kompletnie nic nie dała.
