### ISSUE TITLE
ekino-tv

### ISSUE THREAD

**Issue by KML73** [ramicspa/kodi#437]
Problem dotyczy wyboru źródeł, praktycznie działa tylko openload oraz (jeśli jest) vshare. Nie działają bliżej mi nie znane takie źródełka (umieszczane prawie zawsze) jak fone, smango czy streamin. Czy da się z tym coś zrobić (poprawić) ?

**Comment by zm1c4l** [comment]
Hosting streamin zakończył działalność. Za działanie źródeł odpowiada moduł urlresolver którego autorem jest jsergio123 i tam należy zgłaszać bugi.
