### ISSUE TITLE
TVP.pl - archiwum nie jest aktualizowane (#2)

### ISSUE THREAD

**Issue by adams2** [ramicspa/kodi#438]
"Archiwum wiadomości" ponownie nie odświeża listy. Ostatni rekord jest z 10 września. Korzystam z plugin wersja 2.1.0. Proszę o rzucenie na ten problem okiem. Dzięki.

**Comment by ramicspa** [comment]
archiwum jest aktualizowane, sprawdz ponownie

**Comment by adams2** [comment]
Teraz rzeczywiści jest aktualizowane. Dzięki za korektę. Możemy zamykać problem.

**Comment by ramicspa** [comment]
jesli bylo cos nie tak to po stronie vodtvp ... im zapomialo sie uaktualizowac. zwsze mozesz sprawdzic na stronie.
