### ISSUE TITLE
prosze o dodanie do wtyczek w repozytorium

### ISSUE THREAD

**Issue by plumers** [ramicspa/kodi#439]
http://seriale.co

no i co będzie z meczami online ??:) pozdro

**Comment by zm1c4l** [comment]
Nie wiem jaki jest sens dodawać tę stronę do repozytorium skoro linki pochodzą z alltube a jest przecież wtyczka do niego.

**Comment by xxcriticxx** [comment]
duplicate of https://github.com/ramicspa/kodi/issues/340

**Comment by ramicspa** [comment]
jak linki pochodza z innego serwisu to raczej nie ma sensu dodawanie takiego serwisu.
