### ISSUE TITLE
Sport365

### ISSUE THREAD

**Issue by kashkash18** [ramicspa/kodi#44]
Sport365 nie dziala

**Comment by ramicspa** [comment]
dzieki za info, nie zawsze moge sam wszystko sprawdzic. itivi tez dostalo nowe zabezpieczenia oraz telewizja-live zmienila stronke.
bedzie update

**Comment by xxcriticxx** [comment]
poto jest github :)

**Comment by kashkash18** [comment]
Po aktualizacji linki widzi , po odpaleniu widać pierwsza klatkę i bufor zatrzymuje się na 0%

**Comment by ramicspa** [comment]
Press play i buffor zniknie a vide pojdzie normalnie.

**Comment by kashkash18** [comment]
Tylko że nie widzę tych opcji. Odrazu pojawia się pełna lista linków. To o czym piszesz jest w Zem.tv i to działa , ale u Ciebie niestety tego nie widzę :/

**Comment by kashkash18** [comment]
Ok. Wszystko leci :)
