### ISSUE TITLE
filmwebbooster issue

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#440]
Witam
nie dziala ranking nie pokazuje , pusto 
nowosci w polsce pusto 
top swiat , polska tez pusto 
moze jakis maly upadte :)
pozdro

**Comment by tomasiek** [comment]
Potwierdzam. Na szczęście działa "Dziś w TV"

**Comment by ramicspa** [comment]
Potwierdzam, tez zauwazylem ze cos jest nie tak.

**Comment by tomasiek** [comment]
No to jesteśmy w domu :) trzy osoby nie mogą się mylić. Czas powiadomić @ramicspa o sytuacji.
