### ISSUE TITLE
cda-online kodi 16,1 android

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#45]
Cda-online na kodi 16.1 android nie działa

**Comment by ramicspa** [comment]
Sprawdzilem i wszystko chodxi jak trzeba na andoidzie. Z czym konkretnie
masz problem?

**Comment by Seico** [comment]
Mi pokazuje błąd wtyczki , zaden film się nie odtwarza , android 4,4

**Comment by ramicspa** [comment]
troche wiecej szczegolow by sie przydalo ...
zawartosc wtyczki sie pojawia, lista filmow sie wyswietla, po wybraniu filmu widzisz rozne zrodla?
jak wyskakuje blad - znajdz go w logu i przeslij

**Comment by Seico** [comment]
po wybraniu zródła filmu wyskakuje błąd

**Comment by ramicspa** [comment]
to jeszcze loga podeslij przez pastebin.com
/android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by Seico** [comment]
ok , ale to jutro

**Comment by ebot2007** [comment]
Witam, sprawdzam tez i jest wszedzie pusto. nie ma nic , kino24 to samo pusto

**Comment by Seico** [comment]
Proszę bardzo : http://pastebin.com/fmmWacR2 , pomyliłem sie nawet nie widzę streamów

**Comment by ramicspa** [comment]
i od razu wiadomo gdzie jest problem ... bedzie update.
Natepny bug report prosze z dokladnym opisem co i gdzie jest nie tak ... a jak wyskoczy blad to log jest bardzo pomocny

**Comment by ebot2007** [comment]
dobrze jak bedzie blad dam loga , lecz teraz nic nie pokazuje

**Comment by ramicspa** [comment]
podzedl update, wtyczka jest rowniez kompatybilna z K17

**Comment by ramicspa** [comment]
@ebot2007 
kino24 jest zwieszlone (chyba tymczasowo) mniejmy nadzieje ze stronka wroci niebawem

**Comment by ebot2007** [comment]
witam ponownie niestety nadal pusto , wersja wtyczki cd onlin 1.7.2 , odinstalowalem wszystko cale repo i ponowna instalacjia nic nie dala .

**Comment by ramicspa** [comment]
Hmm a czy zagladales do opcji wtyczki?

**Comment by Seico** [comment]
Po kliknięciu w film wyskakuje okienko ze zródłami ale nie widać żródeł

**Comment by ramicspa** [comment]
dziwna sprawa ... i tak masz tylko na androidzie? na innych systemach jest ok?
probowales aktywowac lub deaktywowac bramke proxy z opcji pluginu?

**Comment by Seico** [comment]
tak , tylko na androidzie , klikałem aktywuj i dezaktywuj i jest tak samo

**Comment by ebot2007** [comment]
witam ponownie tak zaznaczylem proxy i smiga az milo , android 5.1 q-box  .

**Comment by Seico** [comment]
dalej brak widocznych strumieni , nawet na windowsie z kodi 17

**Comment by ebot2007** [comment]
Czesc u mnie dziala i na win i na android box 

http://zmniejszacz.pl/zdjecie/498/6278970_2016-10-04_105348.png

pozdro

**Comment by Seico** [comment]
To spróbuj coś wyszkukać w szukajce na "efilmy" , ekino faktycznie działa mój błąd bo zapora blokowała stronkę
Android box masz z androidem 5.1 więc nie możesz powiedzieć nic na temat działania na androidzie 4,4

**Comment by ebot2007** [comment]
prosze kolego specjalnie dla ciebie podlaczylem box z 4,4,2  i wszystko dziala jak trzeba 

http://zmniejszacz.pl/zdjecie/498/6279997_14571964_10205961163508693_926415546_o.jpg

http://zmniejszacz.pl/zdjecie/498/6280014_14536908_10205961162628671_1385566277_o.jpg

pozdrawiam

**Comment by Seico** [comment]
Ok , poszła jakaś aktualizacja i jest w miare ok , ale nie odtwarza mi streamów z rapidvideo.com :
http://pastebin.com/fmmWacR2 
Na efilmy nie można niczego wyszukać
Na ekino nie ma zakładki "Seriale"
Na kinex brak jest szukajki
