### ISSUE TITLE
serialosy issue

### ISSUE THREAD

**Issue by Zigi1974** [ramicspa/kodi#450]
witam
na stronie zrodla dzialaja lecz nie we wtyczce . moze jakis maly update 
pozdrawiam

**Comment by ramicspa** [comment]
dzieki za info, zajrze do wtyczki i zobacze czy da sie naprawic

**Comment by ramicspa** [comment]
dalej jest problem ze zrodlami?

**Comment by Zigi1974** [comment]
witam , juz dziala pieknie . dziekuje 
zamykam
