### ISSUE TITLE
Nie Działa

### ISSUE THREAD

**Issue by xczesio12345** [ramicspa/kodi#451]
Cinema HD nie działa
Filiser brak linków
Joy nie działa link
CDA-KINO nie działa
efilmy.online nie działa
iitv-seriale linki nie działają
Football Video nie działją linki
FootballOrgin nie działają linki
GoolsArena nie działają linki

**Comment by tomasiek** [comment]
1. Jak baza ruszy to będzie działać.
2. Strona padła i wyłudza kasę, wtyczka zniknie z repozytorium
3-6 już zgłoszone, trzeba czekać na aktualizację.
7-9 a to chyba nie to repozytorium...

**Comment by Kamilo87** [comment]
1. @tomasiek a wiadomo czy ruszy? Masz jakieś potwierdzone info ? pozdro

**Comment by ramicspa** [comment]
out: cinemaHD,Filiser,CDA-KINO,efilmy.online
iitv dostalo aktualizacje
Joy dziala tak dobrze jak strona - niektore sie odpalaja, niektore nie!

@xczesio12345 
spradz czy serwisy z ekstrakalsy dziala na stronie.

**Comment by kashkash18** [comment]
@tomasiek 7-9 znajduje się w dodatku ekstraklasa

**Comment by tomasiek** [comment]
To ja się nie znam. Wszak wiadomo że tomaśka ani seriale ani sport nie
kręcą..

27.09.2017 8:16 PM "kashkash18" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
@ramicspa czy out oznacza że można je już usunąć? Zwłaszcza cinemahd...

27.09.2017 8:17 PM "Tomasz Woś" <tomasz.wos@gmail.com> napisał(a):

**Comment by ramicspa** [comment]
Jak nie biega wtyczka to wywalic. Jak coś się zmieni to znów pojawi się w repo

**Comment by krzysztof222** [comment]
poelcam dodac wtyczke yes movies

**Comment by Katapulta** [comment]
@krzysztof222  Yes movies ma już swoją wtyczkę. Więc po jakiego wała dublować.. ?? http://kodiwpigulce.pl/jak-zainstalowac-dodatek-yes-movies-na-kodi-17-poradnik/

**Comment by xczesio12345** [comment]
@ramicspa ok dzięki za info sprawdzałem i odnośnie: 
Football Video 
FootballOrgin 
GoolsArena
na stronie działa

**Comment by ramicspa** [comment]
juz wszystko dziala.
