### ISSUE TITLE
Ekstraklasa - przewijanie materiałów

### ISSUE THREAD

**Issue by bart7890** [ramicspa/kodi#46]
Witaj
Podczas przewijania magazynów i skrótów z Ekstraklasy wyrzuca mnie z danego materiału, zarówno na PC, Androidzie i Raspberry, da coś radę z tym zrobić?
Pozdrawiam.

**Comment by rafciu27** [comment]
Raczej nie, niektóre serwisy tak mają. Powinniśmy się cieszyć, że w ogóle można odtworzyć taki materiał. Ale ja się nie znam ;)

**Comment by ramicspa** [comment]
Witaj, ja nie mam problemu z przewijaniem streamow na ekstraklasie. To moze zalezec rowniez od szybkosci netu i/lub lokalizacji (IP). Sprawdz czy na innym dostawcy netu tez ten problem wystepuje.

**Comment by kashkash18** [comment]
Czy dało by się wyciągnąć coś z www.footballorgin.com ??

**Comment by ramicspa** [comment]
mozna cos wyciagnac ... bedzie update

**Comment by ramicspa** [comment]
wtyczka dostala update

**Comment by kashkash18** [comment]
A z tego coś się wyciągnie ??

www.goalsarena.org

**Comment by ramicspa** [comment]
cos tam dalo sie wyciagnac :)
