### ISSUE TITLE
Wtyczka "folder". 

### ISSUE THREAD

**Issue by BrownEmmett** [ramicspa/kodi#460]
Uszanowanie, czy ktoś z państwa mógłby mi powiedzieć jak dodać wtyczki do "folderu"? Bo jak wchodzę w folder to jest pusto, nie ma tam żadnej opcji dodawania wtyczek. 
Używam Kodi 17.4. Proszę o wyjaśnienie o co kaman. 
Kłaniam się.

**Comment by ramicspa** [comment]
Wtyczka może mieć mały problem z kodi 17. W wolnym czasie pojawi się aktualizacja
