### ISSUE TITLE
Pluse build

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#464]
Czesc,
Mam pulse build,
Wczoraj pojawil sie napis na Ramica wtyczkach ze wkrotce przestana dzialac z tym buildem,
Czy to prawda?

**Comment by kopernik1983** [comment]
@ramicspa buildom każdym mówi stanowcze nie więc pewnie prawda

**Comment by wisiann** [comment]
No to kicha

**Comment by ramicspa** [comment]
Też słyszałem że wtyczki przestaną działać z buildami więc pewnie to prawda.

**Comment by wisiann** [comment]
To go wywale i zrobie czyste kodi,
Dzieki

**Comment by kodiultimate** [comment]
Ja slyszalem ze Kodi 18 Leia ma nie wspierac polskich wtyczek, czy to prawda?

**Comment by garbatyprostak** [comment]
wisiann zainstaluj sobie jakiegos forka kodi np wookiespmc 17,4 i tam zainstaluj wtyczki Ramica lub odwrotnie

**Comment by wisiann** [comment]
Dzieki
