### ISSUE TITLE
Pleyer.pl

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#465]
Mieszkam w usa, zapytalem juz o to w innym topicu ale troche chaotycznie i nikt mi nie odpowiedzial
Czy jest mozliwosc obejscia vpn na player.pl ?
Jak mialem mrknow to wrzucalem server proxy z polski i dzialalo ,
Dzieki z gory !

**Comment by BrownEmmett** [comment]
Przecież u Ramica nie ma wtyczki do tvn player. Tutaj jest myk bez VPN: http://kodiwpigulce.pl/jak-ogladac-player-pl-za-granica-bez-vpn-poradnik/

**Comment by wisiann** [comment]
Sorry, ale nie moge tego znalesc?

**Comment by tomasiek** [comment]
To pisz na tamtej stronie a nie tutaj.

14.10.2017 7:43 PM "wisiann" <notifications@github.com> napisał(a):

**Comment by frijerz** [comment]
@wisiann napisz do mnie satman@gazeta.pl

**Comment by wisiann** [comment]
Tomasiek,
Jak gledziliscie na innym topicu ze mrknow przestal dzialac to bylo ok 
Ja po prostu pytalem czy mozna to zrobic z wtyczkami Remica,
Btw,
Remic czy mogl bys zrobic cos zeby mozna bylo ogladac pleyer za granica albo chociarz sciagnac poszczegolne seriale na favorites i potem odtwarzac?

**Comment by tomasiek** [comment]
Temat o mrknow od początku był oznaczony jako offtopic. Nikt nie chciał pomocy w sprawie wtyczek mrknow tylko padło pytanie o przejęcie "inwentarza". To istotna różnica. Ty zaś chcesz żeby tu się zająć konkretnym problemem z wtyczką z którą to repo nie ma nic wspólnego. Dostałeś odpowiedź, skierowano cię do artykułu który jeszcze tydzień temu na tamtej stronie był. Ale zniknął. I to już problem tamtej strony która ma nawet własne forum... 
Co do oglądania za granicą. Zainwestuj w VPN i po problemie. Nie męczysz się wtedy z darmowymi proxy które raz działają a raz nie. Jak to zrobić w kodi? Na stronie kodiwpigulce.pl są instrukcje. Przed chwilą patrzyłem.

**Comment by wisiann** [comment]
Dzieki

**Comment by frijerz** [comment]
@wisiann dostales ode mnie na tacy gotowe rozwiazanie, nie uslyszalem ani "dziękuje", ani zadnej informacji czy ci to dziala czy nie, dalej drążysz temat. Podalem ci rozwiązanie, bo sam jestem poza Polską i rozumiem cie.

**Comment by wisiann** [comment]
Przeciesz tobie odpisalem na @ ze wszysto mi dziala,?
Nie dostales?
