### ISSUE TITLE
DEEP SESJE ?

### ISSUE THREAD

**Issue by jakubbrach** [ramicspa/kodi#47]
Czesc

Jest szansa na zrobienie pluginu do kodi dla tego kanału:

http://www.dailymotion.com/deepsesje

Pozdrawiam

p.s

kawał dobrej roboty ;-)

**Comment by ramicspa** [comment]
witam,
jest szansa ... niebawem pojawi sie nowa wtyczka do DM - pozwoli ona nieco poukladac obszerne zasoby tego serwisu.

**Comment by ramicspa** [comment]
Wtyczka jest juz dostepna w repozytorium. mozesz dodac deepsesje i kazdy inny kanal z dailymotion

**Comment by jakubbrach** [comment]
witam

wszystko działa perfekto ;-) dzieki

**Comment by ramicspa** [comment]
jak wszystko dziala to zamykam temat
