### ISSUE TITLE
propozycja

### ISSUE THREAD

**Issue by rokibalboa** [ramicspa/kodi#470]
Może warto byłoby ten serwis dodać?
Sporo kanałów TV i niezły filmów.
http://strefakino.eu/

**Comment by tomasiek** [comment]
W kategorii animowane... uwaga... 7 filmów!
W kategorii horror - 12 filmów
Toż to mega baza
Poza tym:
_Zarejestruj się aby oglądać i pobierać filmy z naszego portalu TV ONLINE po zarejestrowaniu_

i np dla tego filmu: http://strefakino.eu/filmy/horror/108-hostel-2005.html brak jakichkolwiek źródeł - wszędzie jest "Serwer highspeed5.net odrzucił połączenie."

**Comment by ramicspa** [comment]
@rokibalboa sam tez mozesz ocenic serwis, ale wyglada na to ze nic z niego nie ogladales .... to po co proponujesz?

**Comment by tomasiek** [comment]
ej @ramicspa  - od oceny serwisów to ja tu jestem... - przy okazji - boxfilm.pl - już kilka razy o nim mówiliśmy - jest od dłuższego czasu, baza jest dość mocna...
