### ISSUE TITLE
Crash we wtyczce alltube

### ISSUE THREAD

**Issue by Kamil-H** [ramicspa/kodi#473]
Dzień dobry,
ostatnimi czasy spotykam crash we wtyczce alltube. Czsto pojawia się przy wyszukiwaniu czegoś, bądź przy uruchamianiu jakiegoś materiału wideo. 
Crash jest reprodukowalny na trzech urządzeniach Amazon FireTV Stick, na Androidzie 5.0 w Kodi w wersji 17.0 i 17.4, zaś tutaj jest log błędu:
https://pastebin.com/4fWDNhwc
Przepraszam, że pastebin, ale log jest naprawdę długi ze względu na to, że zawiera fragment zakodowany Base64.

Z góry dziękuję za pomoc,
Pozdrawiam.

**Comment by zm1c4l** [comment]
Błąd dodatku alltube jest powodowany brakiem dostępności strony o czym w logu mówi komunikat HTTP 503. Niestety strona czasem jest offline z powodu ataków ddos.

**Comment by Kamil-H** [comment]
Czy możliwe byłoby obsłużenie tego błędu w ten sposób, aby ponowić request w razie jego wystąpienia? Ewentualnie z jakimś timeoutem, tak aby nie odpytywać w nieskończoność.

**Comment by ramicspa** [comment]
zobacze co da sie zrobic

**Comment by kopernik1983** [comment]
ostatnio była na altube przerwa konserwacyjna pare dnie wiec moze cos tam pozmieniali

**Comment by Kamil-H** [comment]
Dziękuję za zajęcie się sprawą i trzymam kciuki.

**Comment by Kamil-H** [comment]
Wygląda na to, że problem ustał. Błąd już się nie pojawia.
