### ISSUE TITLE
Boxfilm 1.0 - nic nie działa...

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#474]
Przed wszystkim dzięki za wtyczkę.... ale niestety nie działa...
Kodi 17.5-RC1, Libreelec 8.1.10, praktycznie czysty profil.
Nie działa.
1 - puste kategorie
2 - w serialach niby coś jest, ale nic się nie otwiera
3 - wyszukiwanie nie działa...
logi: https://pastebin.com/0a0B04Dz

Co ciekawe - na Ubuntu i Kodi 17.1 z dość starym i zasyfiałym profilem działa...

**Comment by ramicspa** [comment]
nie testowalem na kazdym systemie ... i dziwne ze pojawiaja sie problemy

**Comment by tomasiek** [comment]
Nie - no tyle to wiem że nietestowane na libreelec - przywykłem już :) i dlatego staram się każdą wtyczkę sprawdzić, bez względu na to czy z niej będę korzystał czy nie.
Natomiast na ubuntu też się pojawiają problemy - komunikat "UrlResolver sobie nie poradził" przy wielu filmach. Nawet jak znajdzie linka - nie otwiera go...
Tu masz jeszcze logi z ubuntu:
`revious line repeats 1 times.
21:04:01.288 T:140100774435200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.boxfilmpl/?foldername=Sezon+1%2C+Epizode+1&page=1&minfo=%7B%27season%27%3A+1%2C+%27href%27%3A+%27http%3A%2F%2Fjbofilm.pl%2Fseriale%2Fgra-o-tron%2Fsinglepage.php%3Fid%3D63%27%2C+%27episode%27%3A+1%2C+%27img%27%3A+%27http%3A%2F%2Fjbofilm.pl%2Fimages%2F7728238.6.jpg%27%2C+%27title%27%3A+%27Sezon+1%2C+Epizode+1%27%7D&ex_link=http%3A%2F%2Fjbofilm.pl%2Fseriale%2Fgra-o-tron%2Fsinglepage.php%3Fid%3D63&mode=playSeriale]
21:04:30.259 T:140100774435200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.boxfilmpl/?foldername=M%C4%99%C5%BCczyzna+w+pomara%C5%84czowej+kurtce+%282014%29&page=1&minfo=%7B%27plot%27%3A+%27Lektor%3A+Z+lektorem+Dodany%3A+11.10.2017+12%3A52+Gatunek%3A+Horror+%27%2C+%27code%27%3A+%27Z+lektorem%27%2C+%27img%27%3A+%27http%3A%2F%2Fwww.boxfilm.pl%2Fzdj%2F27806.jpg%27%2C+%27title%27%3A+%27M%5Cxc4%5Cx99%5Cxc5%5Cxbcczyzna+w+pomara%5Cxc5%5Cx84czowej+kurtce+%282014%29%27%2C+%27href%27%3A+%27%2Fboxfilm%2F31288%2Fmezczyzna_w_pomaranczowej_kurtce__the_man_in_the_orange_jacket__m.o.zh._%282014%29%27%2C+%27year%27%3A+%272014%27%7D&ex_link=%2Fboxfilm%2F31288%2Fmezczyzna_w_pomaranczowej_kurtce__the_man_in_the_orange_jacket__m.o.zh._%282014%29&mode=playboxfilm]
21:04:32.476 T:140098389640960  NOTICE: script.module.metadatautils --> Rate limiter active for themoviedb.org - delaying request with 4 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
21:05:03.173 T:140100774435200   ERROR: Control 550 in window 10025 has been asked to focus, but it can't
21:05:05.987 T:140099056551680 WARNING: CreateLoader - unsupported protocol(script) in script://script.mtvguide/-poster.jpg
21:05:05.987 T:140099056551680 WARNING: CreateLoader - unsupported protocol(script) in script://script.mtvguide/-poster.png
21:05:05.987 T:140099056551680 WARNING: CreateLoader - unsupported protocol(script) in script://script.mtvguide/-banner.jpg
21:05:05.987 T:140099056551680 WARNING: CreateLoader - unsupported protocol(script) in script://script.mtvguide/-banner.png
21:05:21.376 T:140098381248256 WARNING: Attempt to use invalid handle 16
21:05:29.433 T:140100774435200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.boxfilmpl/?foldername=Przygody+Picassa+%281978%29&page=1&minfo=%7B%27plot%27%3A+%27Lektor%3A+Bez+lektora+Dodany%3A+17.12.2016+15%3A27+Gatunek%3A+Komedia+%27%2C+%27code%27%3A+%27Bez+lektora%27%2C+%27img%27%3A+%27http%3A%2F%2Fwww.kinoline.pl%2Fzdj%2F6083.jpg%27%2C+%27title%27%3A+%27Przygody+Picassa+%281978%29%27%2C+%27href%27%3A+%27%2Fboxfilm%2F6058%2Fprzygody_picassa__picassos_%27%2C+%27year%27%3A+%271978%27%7D&ex_link=%2Fboxfilm%2F6058%2Fprzygody_picassa__picassos_&mode=playboxfilm]
21:05:33.510 T:140100774435200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.boxfilmpl/?foldername=Banda+Picassa+%282012%29&page=1&minfo=%7B%27plot%27%3A+%27Lektor%3A+Z+lektorem+Dodany%3A+17.12.2016+07%3A43+Gatunek%3A+Komedia+%27%2C+%27code%27%3A+%27Z+lektorem%27%2C+%27img%27%3A+%27http%3A%2F%2Fwww.kinoline.pl%2Fzdj%2F22580.jpg%27%2C+%27title%27%3A+%27Banda+Picassa+%282012%29%27%2C+%27href%27%3A+%27%2Fboxfilm%2F5622%2Fbanda_picassa__la_banda_picasso_%282012%29%27%2C+%27year%27%3A+%272012%27%7D&ex_link=%2Fboxfilm%2F5622%2Fbanda_picassa__la_banda_picasso_%282012%29&mode=playboxfilm]
21:05:42.580 T:140100774435200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.boxfilmpl/?foldername=Wielcy+Malarze+-+Pablo+Picasso+%282011%29&page=1&minfo=%7B%27plot%27%3A+%27Lektor%3A+Z+lektorem+Dodany%3A+14.12.2016+18%3A28+Gatunek%3A+Dokumentalne+%27%2C+%27code%27%3A+%27Z+lektorem%27%2C+%27img%27%3A+%27http%3A%2F%2Fwww.kinoline.pl%2Fzdj%2F13713.jpg%27%2C+%27title%27%3A+%27Wielcy+Malarze+-+Pablo+Picasso+%282011%29%27%2C+%27href%27%3A+%27%2Fboxfilm%2F2773%2Fwielcy_malarze_-_pablo_picasso_%282011%29%27%2C+%27year%27%3A+%272011%27%7D&ex_link=%2Fboxfilm%2F2773%2Fwielcy_malarze_-_pablo_picasso_%282011%29&mode=playboxfilm]
21:07:17.182 T:140099903788800  NOTICE: script.module.metadatautils --> Rate limiter active for themoviedb.org - delaying request with 4 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
21:07:42.411 T:140100774435200   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https://s106.vshare.io/s,110-1000-1-0-0/193561/341758/184862/ff-590fea3a6feaced7b214ad5050530c2f,59dfb406,0ebcf88_720.mp4
21:07:42.435 T:140100774435200  NOTICE: VideoPlayer: Opening: https://s106.vshare.io/s,110-1000-1-0-0/193561/341758/184862/ff-590fea3a6feaced7b214ad5050530c2f,59dfb406,0ebcf88_720.mp4
21:07:42.435 T:140100774435200 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:08:02.570 T:140100774435200   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https://s106.vshare.io/s,110-1000-1-0-0/193561/341758/184862/ff-590fea3a6feaced7b214ad5050530c2f,59dfb406,0ebcf88_720.mp4
21:08:02.573 T:140099912181504  NOTICE: Creating InputStream`

**Comment by ramicspa** [comment]
sprawdze co nie tak i wrzuce patcha ... wyglada mi na problem z ciasteczkami, ktore roznie sa tworzone

**Comment by ramicspa** [comment]
no i powinno juz smigac :)

**Comment by tomasiek** [comment]
Popraweczka troszkę poprawiła. Działa odtwarzanie w ostatnio dodanych - ale strasznie muli przy próbie otwarcia:
`06:10:12.198 T:4102099600   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https://s107.vshare.io/s,110-1000-10-0-0/188823/361946/184863/ff-669e018d59f5cab089bc371006e39fbd,59e0332d,99ebcaa_360.mp4
06:10:12.288 T:4102099600  NOTICE: VideoPlayer: Opening: https://s107.vshare.io/s,110-1000-10-0-0/188823/361946/184863/ff-669e018d59f5cab089bc371006e39fbd,59e0332d,99ebcaa_360.mp4
06:10:12.288 T:4102099600 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
06:10:32.487 T:4102099600   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https://s107.vshare.io/s,110-1000-10-0-0/188823/361946/184863/ff-669e018d59f5cab089bc371006e39fbd,59e0332d,99ebcaa_360.mp4
06:10:32.487 T:3371168672  NOTICE: Creating InputStream
06:10:33.314 T:3371168672  NOTICE: Creating Demuxer`
Po otwarciu kategorii są one listowane, ale nie zawierają filmów - później wyślę logi, bo w sumie w logach nic nie widzę...

**Comment by jorg35** [comment]
Witam.Na Windows działa bez problemu dzięki.

**Comment by kopernik1983** [comment]
Faktycznie odtwarzanie z ostatnio dodanych działa ale muli okropniście, seriale działają cacy, kategorie niestety u mnie pusto tak na win jak i boxie z andkiem

**Comment by ramicspa** [comment]
resolver: vshare wolno dziala ... zobacze czy da sie to jakos przyspieszyc ... 
zawartosc kategori powinna sie niebawem pojawic.
