### ISSUE TITLE
darmowa-tv.pl 

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#475]
Witam

Pojawił się serwis darmowa-tv.pl  zastępuje chyba darmowa-telewizja.info

Proszę o dodanie do wtyczki LivePolishTv

**Comment by ramicspa** [comment]
dzieki za info. darmowa sie pojawi we wtyczce

**Comment by lubietv** [comment]
@ramicspa rozważysz również dodanie dekoder.ws, strefakino.eu- po zalogowaniu jest dostęp do darmowej tv

**Comment by lubietv** [comment]
@ramicspa odnośnie filmów to polecam ekinomaniak.tv, superkinomaniak.pl, openkatalog.com i iholandia.tv

**Comment by koladka** [comment]
Niestety przestala dzialac ta nowo dodana tv

**Comment by ramicspa** [comment]
sprawdzilem pierwszych 5 kanalow i wszystko dziala

**Comment by kopernik1983** [comment]
@tomasiek mam coś dla ciebie bo widzę że ostatnio trochę bezrobotny jesteś heheh :) http://filmosy.tv/ przypadkiem na nią natrafiłem i widzę że wspólnego na pewno coś ma z serialosami bo tam właśnie kieruje odnośnik do seriali. Są serialosy więc może i filmosy :)

**Comment by abrus7** [comment]
Ramic czemu na www działają kanały a na tym nie? Jakieś adobe czy coś;>?

**Comment by zbyszek789** [comment]
Witam Panowie ,  widze ze jest dotepna aktualizacja PolishTv 2,4,4 ale za diabla nie moge tego zaktualizowac w kopdi .... zainsatlowalem cale nowe repo ale dalej pokazuje 2.4.3 ...Jakies sugestje ?

Dzieki wielkie

**Comment by kopernik1983** [comment]
@zbyszek789  mi tam się samo zaktualizowało bez żadnych problemów. Skąd repo ? takie nasuwa się pierwsze pytanie. spróbuj ze źródła jak z zipa ci nie idzie

**Comment by koladka** [comment]
Co z tego jak po aktualizacji wieksza lipa z tv jak byla?;( Prosba o poprawke

**Comment by koladka** [comment]
W --UK --nie dziala heja tv.
Pilot tv rowniez nie dziala.
Tele-wizja dziala 40% kanalow.
TV -WEEB -20% dziala.
Darmowa-tv -- 50% dziala.
Inatv- 60% dziala.
Wizja tv dziala kolo 3 godz.

**Comment by zbyszek789** [comment]
A teraz to ... podczas instalowania z repo ..:(


![image](https://user-images.githubusercontent.com/26359259/31789378-e1ccf540-b509-11e7-83ca-29f9d5e8b308.png)

**Comment by ramicspa** [comment]
pewnie to byla jakas chwilowa niedogodnosci bo teraz nie widze zadnego problemu

**Comment by ramicspa** [comment]
@abrus7 @koladka -  jak na stronie zrodelko nie dziala to wtyczka sama nic nie wygeneruje.
