### ISSUE TITLE
cda.pl - nieprawidłowy czas przy krótkich filmach

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#476]
Przy krótkich filmach pojawia się nieprawidłowy czas. Przy długich pojawia się np 1:30:04 (czyli 1h i 30m), przy krótkich - np w szukajce "baranek shaun" - pojawia się czas 7:04:00 - co daje 7 godzin, w rzeczywistości jest to 7 minut...
Przy okazji - da się coś zrobić z kolorystyką w dodatkach - te niebieskie, zielone... troszkę to niewygodne... pisałem o tym tutaj https://github.com/ramicspa/kodi/issues/382

**Comment by ramicspa** [comment]
dzieki za info ... bedzie niebawem aktualizacja wiec uwzglednie i ten problem

**Comment by tomasiek** [comment]
Dzięki - jest super.
Dzięki też za poprawienie kolorystyki - teraz jest subtelna, a przede wszystkim czytelna.
P. - nie do końca rozumiem obsługę biblioteki w tym przypadku... ale dojdę i przetestuję.

**Comment by tomasiek** [comment]
No i jak dodać film do biblioteki...

**Comment by ramicspa** [comment]
Filmy z root można przenieść do biblioteki. Druga opcja to przeszukanie CDA.pl - aktywuje się z opcji na razie później pewnie seria będzie działał.
Filmy których dane zostały uaktualnienie z filmwebooster też można dodać.
Ogólnie posprawdzaj co w menu contekstowym jest

**Comment by tomasiek** [comment]
Czyli druga opcja przeszukuje root i dodaje z automatu do biblioteki?
Obecnie z biblioteki korzystam w covenant i w filmwebbooster, nie ukrywam
że CDA ma full niszowych filmów które ciężko dodać z innych źródeł. Także
dzięki za opcje.

22.10.2017 9:44 PM "ramicspa" <notifications@github.com> napisał(a):

Filmy z root można przenieść do biblioteki. Druga opcja to przeszukanie
CDA.pl - aktywuje się z opcji na razie później pewnie seria będzie działał.
Filmy których dane zostały uaktualnienie z filmwebooster też można dodać.
Ogólnie posprawdzaj co w menu contekstowym jest

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/476#issuecomment-338503725>, or mute
the thread

**Comment by ramicspa** [comment]
Druga opcja patrzy bezpośrednio na nowe pozycje w serwisie. W opcjach ustala sie jak wiele stron przegladac. Na stronie jest ok 20 pozycji z czego ok połowa jest znajdowana na filmweb i  może być dodana do biblioteki

**Comment by tomasiek** [comment]
O. No to już wszystko wiem.
