### ISSUE TITLE
Zalukaj 2

### ISSUE THREAD

**Issue by lampardzino** [ramicspa/kodi#477]
Znów zalukaj nie znajduje źródeł przy każdym filmie , po aktualizacji chwile chodziło i znów nie wyszukuje jak możesz coś tam poprzestawiać byłbym wdzięczny Pozdrawiam. :) ! i kawał dobrej roboty odwalasz ;)

**Comment by ramicspa** [comment]
hmm dziwne bo mi wszystko dziala. Zrodelka z vshare dosc wolno sie laduja wiec trzeba troche poczekac by strumien sie otworzyl
