### ISSUE TITLE
TVP.PL dodanie obsługi treści DRM

### ISSUE THREAD

**Issue by rexio8** [ramicspa/kodi#479]
Niektóre treści na VOD TVP.pl są prawdopodobnie chronione DRM. Czy istnieje możliwość wprowadzenia ich obsługi? Chociażby na zasadzie uruchomienia z poziomu KODI pełnoekranowej przeglądarki Chrome nakierowanej na odtworzenie danej pozycji typu:
subprocess.Popen('C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe https://vod.tvp.pl/sess/tvplayer-pre-release.php?object_id=ID_FILMU&autoplay=true&backendVersion=1.8', shell=False, creationflags=0x00000008, close_fds = True)

Przykładowy program: Pierwsza Randka

**Comment by zbigzbig20** [comment]
Kodi18 wprowadza możliwość odtwarzania contentu z drm programowo lub sprzetowo (jeśli dany sprzęt posiada odpowiednie klucze drm) poprzez inputstream adaptative. Póki co nie ma jeszcze oficjalnego  buildu kodi18 ale można już sobie skompilować libreelec z tego co jest już dostępne bazujący na kodi18 leia i działa to już spoko lub użyć jakiejś wczesnej wersji z kanału kodi nightly i na tym obadać

**Comment by rexio8** [comment]
Dzięki za informację. Będę kombinować z kluczami.
