### ISSUE TITLE
Openload 

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#48]
Przy wczytywaniu linkow z openloada wyskakuje info o parowaniu  i nieda sie wczytac filmu . Czyzby znowu cos pokombinowali . Da rade cos z tym zrobic.

**Comment by ramicspa** [comment]
mozna sie zastosowac do instrukcji ... twoje ip zostanie dodane i zrodla beda dostepne

**Comment by adaski8** [comment]
A jak mam zmienne ip to mam za kazdym razem po zmianie tak robic

**Comment by eko5** [comment]
Da się skopiuj zawartość script.mrknow.urlresolver do script.urlresolver , nie nadpisując addon.xml . Tak zmodyfikowany katalog odpala openload.co bez zadnych IP
