### ISSUE TITLE
Pytanie dot. buildów

### ISSUE THREAD

**Issue by Dexterrus** [ramicspa/kodi#480]
Cześć, mam takie drobne pytanie.
Czy wtyczki z tego repozytorium można rozprowadzać z 100% darmowym buildem Kodi?

**Comment by tomasiek** [comment]
To zależy jaki model biznesowy wybierzesz... Mieliśmy już kilka tutaj np.
1. model AlienTV - build wpierw darmowy, potem się okazało że ktoś to sprzedaje i musi zrobić płatny.
2. model Multimedia Master - wersja darmowa i płatna jednocześnie. Darmowa ograniczona mocno, płatna full wypas... 
3. Model mariobox - czyli build jest darmowy, sprzedaję urządzenia z buildem, płaci się za urządzenie. Ewentualnie za instalację buildu.
4. Inne modele - build jest darmowy, ale zbieram datki na utrzymanie serwera, chorej córki, psa.

Jak na razie żaden build nie spotkał się jeszcze z akceptacją autora.... także życzę powodzenia.

**Comment by Dexterrus** [comment]
Raczej wolałbym model 5, czyli wszystko sam utrzymuje. :)

**Comment by krzysztof222** [comment]
amerykanskie buildy  nic nie poisza zebyu palcić włąsnie taki mam ?

**Comment by koladka** [comment]
Zobaczcie "" Kodi Ultimate Build""" swietna robota !

**Comment by tomasiek** [comment]
Heheh wpisujecie buildy... Będzie łatwiej.


17.10.2017 1:37 PM "koladka" <notifications@github.com> napisał(a):

**Comment by ramicspa** [comment]
@Dexterrus wtyczki z tego repo moga slabo dzialaz z buildem albo w ogole. Moze lepiej zamiast bawic sie tapetami i pakowaniem folderu kodi zrobic cos pozytecznego - ostatno pojawila sie sugestia aktualizacji wtyczke mrknow - lepiej sie chyba tym zajac.

**Comment by Dexterrus** [comment]
@ramicspa ok, dzięki za odpowiedź. :)
