### ISSUE TITLE
Box film 1.2 - nie działa wyszukiwanie

### ISSUE THREAD

**Issue by Katapulta** [ramicspa/kodi#481]
Witam. Nie działa wyszukiwanie we wtyczce boxfilm. Nie wiem czy tylko u mnie ale przy jakiejkolwiek próbie wyszukania jakiegokolwiek filmu... nie wyszukuje go i pokazuje ciągle tą samą listę filmów...

**Comment by ramicspa** [comment]
wyszukiwanie zostalo poprawione
