### ISSUE TITLE
canalplussport.pl

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#482]
Witam,da radę wstawić to w kodi:>? Mecze online można oglądać itp. Aplikacje itp lepiej nie pisać,bo na telewizorze nie działa. Aby był z logowaniem byłoby miło:)
Pozdrawiam

**Comment by kopernik1983** [comment]
A czy czasem nie trzeba być abonentem nc+ żeby oglądać ów mecze bo coś mi się wydaje że trzeba. Jakoś nie chce mi się wierzyć że canal od tak za darmoszkę da oglądać ligę mistrzów. Ale sprawdzę to jeszcze później.

**Comment by kopernik1983** [comment]
I wszystko w tym temacie. Odpowiedz uzyskasz w zasadzie po przeczytaniu dwóch pierwszych zdań. 

Oglądanie transmisji meczów na żywo, a także oglądanie pozostałych materiałów wideo, dostępne jest tylko dla uprawnionych Abonentów nc+, którzy posiadają w swoim pakiecie m.in. program CANAL+ Sport HD. Oglądanie materiałów wideo możliwe jest tylko i wyłącznie z terytorium Polski.
Uwaga:
- czasami może się okazać, że mimo iż przebywają Państwo na terenie Polski, to przy próbie odtworzenia materiału wideo zobaczą Państwo komunikat o tym, że materiał nie może być odtworzony, bo... jest dostępny tylko z terytorium naszego kraju,
- dzieje się tak dlatego, że nie wszystkie adresy IP są automatycznie rozpoznawane jako te przydzielone dla Polski,
- jeśli zobaczą Państwo powyższy komunikat, a znajdują się w Polsce, uprzejmie prosimy przesłać nam numer Państwa IP przy pomocy tego formularza:
https://moje.ncplus.pl/index.html#/contactForm


Oglądanie materiałów wideo wymaga logowania, zaś by można się było zalogować, należy najpierw utworzyć konto w serwisie.

Na jedną umowę o abonament nc+ można utworzyć jedno konto.
Konto zakłada się tylko raz, codzienne logowanie do serwisu wykonuje się wpisując wybrany przez siebie adres e-mail i hasło,  podane w czasie rejestracji konta.

Rejestrację konta możesz wykonać już teraz, możesz również zrobić to z poziomu aplikacji mobilnej (jeśli masz już zainstalowaną aplikację "CANAL+ Sport online"). W czasie rejestracji należy podać wszystkie wymagane dane, w tym numer umowy abonenckiej i  numer Pesel lub NIP (w zależności od tego, czy umowa o abonament zawarta była jako osoba prywatna lub firma).

Jeśli nie jesteś abonentem nc+ lub nie masz w swoim pakiecie programu CANAL+ Sport HD, zobacz jakie pakiety oferuje nc+ i wybierz taki, który najbardziej Ci odpowiada.

Korzystanie z innych funkcji serwisu (poza oglądaniem transmisji na żywo i materiałów wideo) nie wymaga ani rejestracji ani logowania.

**Comment by ramicspa** [comment]
no to sprawa wyjasniona
