### ISSUE TITLE
Filiser 2.0 problem z wyszukiwaniem

### ISSUE THREAD

**Issue by fiodger** [ramicspa/kodi#486]
Hej,  mogę przeglądać filmy i seriale oraz je odtwarzać, ale wyszukiwanie nie zwraca żadnych rezultatów. Czy to problem lokalny na moim sprzęcie, czy ogólny i da się coś z tym zrobić?
Dzięki i pozdrawiam :)

**Comment by kokosz887** [comment]
Hej.

U mnie jest ta sama sytuacja. Kiedy przegląda się zasoby, to pokazuje seriale i źródła. Ale kiedy jakiegoś się szuka, to nic nie znajduje (mimo, że na stronie filiser dany serial jest).

Pozdrawiam i jeśli to możliwe to proszę o naprawę.

Z góry dziękuję :)

**Comment by ramicspa** [comment]
wyszukiwanie powinno juz dzialac tak jak powinno.
dodatkowo dorzucilem opcje darmowego proxy ... wiec wtyczka powinna tez dzialaz z IP z poza kraju
