### ISSUE TITLE
Debrid

### ISSUE THREAD

**Issue by gjedeer** [ramicspa/kodi#487]
Mam zainstalowane URLResolver 4.0.0.7 i skonfigurowane konto real-debrid, próbuję odtwarzać w dodatku filmy.to materiał z openload, nadal prosi mnie o odwiedzenie olpair.com.

Czy dodatki ramicspa obsługują urlresolver? Widzę wersję 3.x w XML-u z zależnościami, muszę się downgradować żeby działało?

**Comment by ramicspa** [comment]
Wtyczki używają tej wersji urlresolvera jaka jest zainstalowana. Minimalna to 3.x.x. Zaleca się używanie najnowszej.
Nie wiem czy filmy.to w ogóle mają jakieś źródła z  real-derbid.

**Comment by gjedeer** [comment]
Dzięki za odpowiedź. Filmy.to używają głównie openload który jest wspierany.
