### ISSUE TITLE
Aktualizacja kodi 17.5

### ISSUE THREAD

**Issue by Katapulta** [ramicspa/kodi#488]
Po aktualizacji kodi do wersji 17.5 wtyczki między innymi FilmyTo, Alltube, Boxfilm, Filiser , Cda.pl, Segos przestały u mnie działać - działa wyszukiwanie, lista filmów nie ma jednak dostępnych źródeł i nie ma możliwości oglądania.

**Comment by ramicspa** [comment]
juz wiesz w czym byl problem?
