### ISSUE TITLE
Lech tv

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#49]
Witam
Jest jakaś szansa na stworzenie wtyczki ze strony Lech.tv?

**Comment by ramicspa** [comment]
jest szansza, dorzuce to do ekstraklasy

**Comment by kashkash18** [comment]
A nie lepiej było by zmienić nazw wtyczki na "Sport" i wrzucić do tego sport365live ??

**Comment by ramicspa** [comment]
moze i lepiej ... ale w ekstralasie jest tylko football to moze lepiej cala pilke nozna trzymac razem.

**Comment by kashkash18** [comment]
Rozumiem , aczkolwiek w weekendy na sport365 rządzi piłka hehe dla mnie to problem nie nie jest , najważniejsze że działa :)

**Comment by ramicspa** [comment]
zasoby Lechtv sa juz dostepne we wtyczke ekstraklasa

**Comment by rafciu27** [comment]
Super, wielkie dzięki!

**Comment by rafciu27** [comment]
Zakładka nowe trochę szwankuje gdyż, najnowszym filmem w zakładce jest film po którym wyszło już następne 8 filmików.
