### ISSUE TITLE
libreelec ver 8.1.2

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#491]
@ramicspa lookniesz please 

nowa instalacja libreelec 8.1.2 + kodi 17.04

tak samo mam z pliku zip i zrodla z githabu

sciagam repo w ver 1.3.5 kodi pokazoje mi ze to jest ver 1.3.2 i nie moze polaczyc sie z repozytorium

**Comment by tomasiek** [comment]
Też ma libreelec na 905. Bez problemu działa repozytorium, zarówno pobieranie jak i instalacja. Może spróbuj pobrać na komputerze i wrzucić na libreelec.

**Comment by tomasiek** [comment]
A może ściągasz w inne miejsce niż to z którego instalujesz... Logi z trybem debug by troszkę więcej powiedziały.

**Comment by xxcriticxx** [comment]
@tomasiek potem sprobuje na usb i wepne go prosoto w elec

**Comment by tomasiek** [comment]
No jakieś 2 tygodnie temu robiłem czystą instalkę libreelec (po zadymie z informacją że dodatki przestaną działać) i instalowałem bezpośrednio ze źródła.

**Comment by xxcriticxx** [comment]
pomogo przez usb mozna zamknac

**Comment by tomasiek** [comment]
Czyli na przyszłość - pobierałeś z cache a nie ze źródełka...
Ps - i to ty możesz zamknąć.

**Comment by xxcriticxx** [comment]
@tomasiek bobieralem na NAS i potem motowalem z NAS i wtedy byl problem
