### ISSUE TITLE
Propozycja seriale

### ISSUE THREAD

**Issue by roperper** [ramicspa/kodi#493]
Bardzo dobra strona z serialami tvlinks.pl taka wtyczka bardzo by się przydała 
często używałem wtyczki freedisc ale przestała działać

**Comment by xxcriticxx** [comment]
niektore serialy maja takie cos

![capture](https://user-images.githubusercontent.com/15007183/32143503-9e2519d4-bc80-11e7-9ef6-e9ed83b25535.PNG)

**Comment by roperper** [comment]
hasło seriale i się nie zmienia nie można wstawić hasła w wtyczce ?

**Comment by ramicspa** [comment]
Widze ze czesto aktualizowana jest ta stronka chyba warto dorobic wtyczke.
