### ISSUE TITLE
serialosy.pl - problem z odtwarzaniem wideo

### ISSUE THREAD

**Issue by therealmikz** [ramicspa/kodi#494]
Po wybraniu pozycji i źródła film się nie uruchamia, brak jakiejkolwiek komunikatu, w logu pojawia się błąd:

T:139677670184704  NOTICE: URLResolver: Initializing URLResolver version: 4.0.08                           12:54:36.568 T:139680991071744  NOTICE: VideoPlayer: Opening:                                                           12:54:36.569 T:139680991071744 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED                              12:54:36.569 T:139677866637056  NOTICE: Creating InputStream12:54:36.570 T:139677866637056   ERROR: Error on dvdnav_open12:54:36.570 T:139677866637056   ERROR: CVideoPlayer::OpenInputStream - error opening []                                12:54:36.570 T:139677866637056  NOTICE: CVideoPlayer::OnExit()                                                          12:54:36.571 T:139680991071744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.serialosypl/?foldername=Dr+House+S07E22+Lektor+PL&params=%7B%7D&e

Aktualizacja  URLResolvera nie pomogła, nie mam już pomysłu co może być nie tak.

**Comment by therealmikz** [comment]
17.3

**Comment by xxcriticxx** [comment]
na stronie dziala

**Comment by therealmikz** [comment]
Nie zrozumiałem. Wiem, że strona serialosy.pl działa, ale nie zbliża mnie to do rozwiązania problemu.

**Comment by xxcriticxx** [comment]
@therealmikz u mnie ten odcinek tez nie odpala

**Comment by therealmikz** [comment]
Tylko na stronie odcinki tego serialu działają, więc możliwe że to bug w samej wtyczce.

**Comment by ramicspa** [comment]
serialosy to dobry serwis a nowe odcinki czesto sa dodawane. poszla aktualizacja wytczki.

**Comment by therealmikz** [comment]
Fantastycznie, zabanglało bez zająknięcia, wielkie dzięki za fantastyczną robotę :)
