### ISSUE TITLE
Nieudane połączenie z repozytorium

### ISSUE THREAD

**Issue by Kuziem** [ramicspa/kodi#495]
Witam!

Próbuje zainstalować dodatek FilmwbBooster z Ramic Kodi Add-ons Repository. Z pliku zip repozytorium się instaluje, natomiast nie mogę wejść do wnętrza tego repozytorium - dostaje komunikat jak w tytule problemu.

Jakieś rady?

Pozdrawiam

**Comment by Wodzu1984** [comment]
Witam, Mam identyczny problem. Pierwszy raz zainstalowałem Repo Ramic z z pliku ZIP. Chcę zainstalować z repozytorium. Wybieram " Ramic Kodi Add-ons Repository i pojawia się identyczny komunikat "Nieudane połączenie z repozytorium". Proszę o wsparcie ;)

**Comment by Katapulta** [comment]
A macie uaktywnioną opcję instalacji z nieznanych źródeł ?? Ustawienia -> Dodatki - > nieznane źródła czy jakoś tak :P 

I dlaczego instalujecie z pliku zip a nie ze źródła - http://ramicspa.github.io/kodi/ które chyba wiecie jak dodać w menadżerze plików kodi

**Comment by Wodzu1984** [comment]
Tak mam włączoną opcję instalowania z nieznanego źródła :) 
Źródło mam dodane prawidłowo http://ramicspa.github.io/kodi/

**Comment by tomasiek** [comment]
Na 99% problem z dostępem do sieci. Repozytorium działa. Sprawdźcie firewalle itp itd.

**Comment by Wodzu1984** [comment]
@tomasiek  Dzięki. Połączyłem mi boxa z inną siecią i poszło :) Także @Kuziem połącz się z innej sieci lub wyłącz firewalla. pozdrawiam

**Comment by Kuziem** [comment]
Zgadza się, problem minął po przełączeniu na inny router. Dzięki za pomoc.

**Comment by ramicspa** [comment]
jak juz wszystko biega to troche tu posprzatamy .... i zamykam problem
