### ISSUE TITLE
Brak Zalukaj w repo?

### ISSUE THREAD

**Issue by marekodfiranek** [ramicspa/kodi#497]
Czy serwis zalukaj został usunięty?

**Comment by tomasiek** [comment]
Jest. bez problemu się instaluje. Jakie masz kodi? Z tego co pamiętam to z wersją 16.x nie działa, przez co się nie pokazuje w repozytorium.

**Comment by ramicspa** [comment]
jest ... jak @tomasiek napisal potrzeba minimum K17.x
