### ISSUE TITLE
cda - wybór jakości

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#498]
W cda padł wybór jakości - każdy film otwiera mi w minimalnej jakości. Obojętnie czy wybiorę wybór ręczny czy minimalną jakość w ustawieniach. Na liście pokazuje mi 1080, na stronie też jest 1080 ( i faktycznie jest 1080) zaś wtyczka otwiera najniższą dostępną.
https://www.cda.pl/video/166330060/vfilm?wersja=1080p - przykład - na stronie ładnie działa 1080 - w kodi tylko 540...

**Comment by tomasiek** [comment]
Zauważyłem że czym dalej w las tym lepiej działa - filmy które są na dalszych pozycjach działają prawidłowo. Tylko "nowości" mają ten problem. W logach nic nie ma.

**Comment by ramicspa** [comment]
Hmm może linki w hq nie są jeszcze dostępne. Sprawdzałeś na stronie?

**Comment by tomasiek** [comment]
No ten co podałem jest na stronie. Ale na drugiej stronie nowości już wszystko działa w porządku.

**Comment by ramicspa** [comment]
Ok, to dobrze. Niebawem będzie kolejna aktualizacja więc jak jeszcze z czymś jest problem to daj znać

**Comment by tomasiek** [comment]
Nie przy każdym filmie tak się dzieje. Nie potrafię tego w logach wychwycić. Nie różni się niczym taki film od innych. Na stronie jest 480,720,1080 a odtwarza tylko najniższą. filmy bliżej końca i na drugiej stronie już spoko - zapomniałem dodać że korzystam z dodatkowego katalogu że standardowymi ustawieniami.

**Comment by tomasiek** [comment]
Kurcze - samo się naprawiło... zamykam...

**Comment by ramicspa** [comment]
pewnie cos pomieszali z linkami na cda ... ale dobrze ze juz wszystko dziala
