### ISSUE TITLE
TvLinks

### ISSUE THREAD

**Issue by kopernik1983** [ramicspa/kodi#499]
@ramic taka mala sprawuszka w zasadzie. Raczej malo prawdopodobne zeby takowa wtyczka juz istniala ale.... mam dodane SR w zrodlach i po zainstalowaniu TvLinks od razu krzyczy ze aktualizacja. Jest tam wtyczka o nazwie TVLinks.cc i chyba gryzie sie z twoja w jakis sposob. Na szczescie SR chodzi tak jak chodzi czyli wcale bynajmniej u mnie wiec sie nie aktualizuje. Pytanie czy dasz rade cos w tym temacie zdzialac. Pozdrawiam.

**Comment by ramicspa** [comment]
Dzięki za info. Da radę poprawić. Zmiana ID powinna pomoc

**Comment by ramicspa** [comment]
Odinstaluj wtyczke i ponownie zainstaluj z repo nie cache.

**Comment by roperper** [comment]
wielkie dzięki za wtyczkę dobrze działa jak byś mógł poprawić jeszcze freedisc i vider całkiem przestały działać

**Comment by kopernik1983** [comment]
wszystko gra i buczy :) zamykamy :)
