### ISSUE TITLE
problemy 

### ISSUE THREAD

**Issue by donald73** [ramicspa/kodi#5]
nie dział żadne źródło dla cda-online jest szansa na naprawę ?

**Comment by ramicspa** [comment]
Tez to zauważyłem parę dni temu. Większość linkow jest schowanych za
captcha I poki co nie ma sposobu ich wyjecia. Kilka dni temu zrobilem
update I  przynajmniej dwa powinny działać.

**Comment by donald73** [comment]
cytat "Dodatek jest niekompatybilny lub oznaczony jak uszkodzony" po odinstalowaniu nie ma go już w repo..to była wersja 1.4.0 i nie można go zainstalować

**Comment by ramicspa** [comment]
Moze zle sie sciagnal? wywal zbuforowane pakiety:  ~\.kodi\addons\packages
zaleznosc dodatku zostala uaktualniona wiec moze dlatego nie chcial sie zainstalowac.
zrob update wszystkich dodatkow, potem zainstaluj cdaonline

**Comment by donald73** [comment]
odinstalowałem nawet repo i dalej nie widzi w liście wtyczek do instalacji cdaonline sprawdzałem na rp2 i android box wszędzie to samo

**Comment by donald73** [comment]
przy okazji moze wtyczka do tego nie ma captcha

**Comment by crazytv** [comment]
Witaj, "ramicspa" mam nadzieję że postrzał w kolano nie boli, zwłaszcza, że sam sobie strzeliłeś... jak widzisz Twoja wycieczka z kopią kont pokazała ludziom jedynie jak Ty traktujesz otwarte projekty a tym bardziej dane osobowe (o ile to można tak nazwać bo to tylko maile były)... W tym momencie wyłączyłem Ci link z Naszej TV (bierz nowe - ja je zmieniam bo mam API a ty - hmmm) i uwierz mi w to... ja nie będę się bawił w takie pierdoły co Ty odpierdalasz... Szczerze mówiąc... chciałem się dogadać i wedle normalnej umowy dać Ci te TV... ale jesteś na to chyba za młody... (kiedyś też robiłem wtyczki free)...  przeczytaj co sam napisałeś ... "otwarty projekt" więc odpierdol się że z niego korzystam... a gdybyś nie był takim zadufanym w sobie niby "programistą" bo przeczytał byś plik "changelog.txt" gdzie było napisane skąd pochodzi skrypt wraz z podziękowaniem... to nawet było  NAPISANE PODCZAS INSTALACJI PLUGINU!  - mimo wszystko szanuję Cię i utwierdzam się w fakcie, że gówna się nie rusza bo śmierdzi!!!!!!!!!!!!! WAL SIĘ GNOJU!

**Comment by crazytv** [comment]
a tu masz nowy CID żebyś nie płakał:
621163a79c8bf3ed4699b6174511dc18
