### ISSUE TITLE
Anyfiles.video

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#50]
Jest moze mozliwosc dodania tego do repo i stworzenia wtyczki

**Comment by xxcriticxx** [comment]
Server not found
Firefox can’t find the server at www.anyfiles.video.

**Comment by adaski8** [comment]
A polski odpowiednik video.anyfiles.pl

**Comment by ramicspa** [comment]
jakos same krotkie filmiki tam widzialem - ale moze sie myle. wy moze znalezliscie cos ciekawego na tym serwisie by jakos umotywowac robienie pluginu dla niego.
