### ISSUE TITLE
cda-hd

### ISSUE THREAD

**Issue by sabuk97** [ramicspa/kodi#502]
Od wczoraj tj 3.11.2017 wybierając CDA-HD, każda lista jest pusta, czy wybiore filmy, czy seriale, czy premiery 2017. pusto. Próbowałem reinstalować nie pomogło, co mogę zrobić?
Pozdrawiam ^^

**Comment by ramicspa** [comment]
dzieki za info. zmienili troche zabezpieczenia na stronie ale juz poszla poprawka do wtyczki

**Comment by sabuk97** [comment]
Używam Kodiego od jednego Dnia. Jak mogę szybko zaktualizować te zmiany w Kodim?

**Comment by xxcriticxx** [comment]
@sabuk97 jesli masz najnowsze repo same sie zaktualizuja 

or How to Manually Force Kodi to Update All Add-ons and Repositories

https://www.youtube.com/watch?v=cJtaNyWj5uE

**Comment by sabuk97** [comment]
Tak mam najnowszą samo się nie zrobiło niestety, dopiero po kliknięciu "wyszukaj aktualziacje" pobrało, tak mam automatyczne instalowanie. Dziękuję za pomoc!
