### ISSUE TITLE
filmwebbooster kaput - nie działa

### ISSUE THREAD

**Issue by BrownEmmett** [ramicspa/kodi#506]
Uszanowanie panie Michale. Jak zwykle dziękuję bardzo za wkład w polskie wtyczki do Kodi. Niestety od dzisiaj jedna z lepszych wtyczek Filmwebbooster przestała działać. Każdy tytuł wyświetla tylko jedno źródło do youtube, w którym pokazane jest jak odtwarzać filmy w przeglądarce. Wygląda to tak jakby autor filmwebbooster się obraził i przekierował źródła do tego filmiku. 

Może uda się coś zrobić. Chyba, że powstał konflikt interesów. 

Screenshot:
https://image.prntscr.com/image/hTqIy_XgRwmuhHM_Ur5AXg.png

Pozdrawiam serdecznie.

**Comment by ramicspa** [comment]
nie ma co dramatyzowac, wystarczy powiedziec ze poprawka do wytczki jest potrzebna

**Comment by BrownEmmett** [comment]
Nie dramatyzuje, napisałem to z przymrużeniem oka. ;)

**Comment by ramicspa** [comment]
i po problemine ;)

**Comment by wisiann** [comment]
Ramicspa
Dalej wyskakuje tylko zrodlo do youtuba,

**Comment by BrownEmmett** [comment]
@wisiann nie pisz głupot bo już działa. Zaktualizuj do 1.9 i wsio bangla.

**Comment by BrownEmmett** [comment]
@wisiann tutaj screenshot z wersji 1.9 -> https://image.prntscr.com/image/hzaAgX3ER421QoQvxTtZFA.png

**Comment by wisiann** [comment]
Ja mam tylko 1.8 w repo ramica?
gdzie jest 1.9?

**Comment by wisiann** [comment]
Ok,
Teraz me sie pojawio 1.9 na repo 
Dzieki
