### ISSUE TITLE
Ekino

### ISSUE THREAD

**Issue by raiderpl1** [ramicspa/kodi#508]
cześć ekino linki z openload znowu nie działają, kiedy doczekamy się update. Proszę o informacje.

**Comment by Katapulta** [comment]
Ale na stronie też mi linki nie działają więc to nie problem chyba wtyczki tylko strony.

**Comment by ramicspa** [comment]
@Katapulta dzieki za sprawdzenie.

**Comment by koladka** [comment]
Niewiem  o co biega ale Mr know znow mi smiga i telewizja i filmy ;)

**Comment by raiderpl1** [comment]
Ekino na stronie działa normalnie

2017-11-06 14:48 GMT+00:00 koladka <notifications@github.com>:

**Comment by tomasiek** [comment]
Podaj konkretny przykład ze strony i ewentualne logi z kodi. Bez tego to jak wróżenie z fusów.
