### ISSUE TITLE
Błędy we wtyczkach

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#51]
Na efilmy nie można niczego wyszukać . Klikając na zakładkę seriale wyskakuje błąd
Na ekino nie ma zakładki "Seriale"
Na kinex brak jest szukajki

**Comment by ramicspa** [comment]
thx, bedzie update

**Comment by Seico** [comment]
Dzięki
Dasz radę tez naprawić problem w tym wątku : https://github.com/ramicspa/kodi/issues/45
Ostatni wpis ?

**Comment by ramicspa** [comment]
- efilmy dostaly update a wraz z nim dzialajaca opcje szukania
- ekino ma bardzo slaba baze seriali wiec od poczatu nie miala tej opcji ... dorzucilem katalog seriali i spora czesc z nich nie ma w ogole zadnych zrodel
-  wtyczka kinex zniknie z repozytorium 
- zrodla z rapidvideo naprawione beda przez urlresolver'a

**Comment by Seico** [comment]
"zrodla z rapidvideo naprawione beda przez urlresolver'a" 
To chodzi o to ze na 17 jest ok ale na 16 na androidzie 4,4 wywala error

**Comment by ramicspa** [comment]
Wyglada na to ze  stram z rapidvideo nie moze byc zdekodowany przez kodi 16 - wersja uzytego pythona na to nie pozwala. Problem ten poprawiono w kodi17. Nic sie na to nie poradzi
