### ISSUE TITLE
mrknow

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#512]
ma ktoś repozytorium które będzie działać,bo co instaluję niestety nie da rady aby go uruchomić. Dzięki

**Comment by tomasiek** [comment]
To pytanie nie tutaj...
Projekt mrknow umiera śmiercią naturalną.
http://mods-kodi.pl/forum/viewthread.php?thread_id=229&rowstart=480#post_21803

**Comment by abrus7** [comment]
Dzięki i szkoda mrknow
