### ISSUE TITLE
Problem z Alltube

### ISSUE THREAD

**Issue by pawelfrac1** [ramicspa/kodi#513]
Podczas uruchamiania alltube dostaje komunikat ze wtyczka nie dziala z tym buildem wylacz natychmiast kodi. Problem w tym, ze nie mam zadnego buildu. Komunikat dostaje tylko na wtyczce alltube, pozostale z tego repo otwiera normalnie. Nie wiem czym jest to spowodowane, a nie chce utracic swojego konta. Prosze o pomoc.

**Comment by ramicspa** [comment]
Zainstaluj więc repo i wtyczkę na nowym profilu, powinno to pomoc a jak się pojawi komunikat to lepiej się do niego dostosuj

**Comment by pawelfrac1** [comment]
Sprawdzałem problem na większości wtyczek z tego repo, komunikat mam tylko na alltube. Moje kodi przygotowywałem od dłuższego czasu, szkoda mi teraz to wszystko robić od nowa :( nie wiem co może być przyczyną nigdy na ten profil nie wgrywałem żadnych nakładek (buildów). Jedyne co odstaje od oryginalnego profilu kodi to skórka xonfluence. Co muszę usunąć, aby nie dostawać tego komunikatu ,oczywiście nie usuwając tego repo:)

**Comment by wisiann** [comment]
Hmmm?,
Nie ma tego problemu,
Moze gdzies po drodze w budowaniu kodi cos zle nacisnoles?

**Comment by tomasiek** [comment]
Z własnego doświadczenia powiem tak, nie miałem nigdy buildu, ale miałem repozytorium i programik udostępniany z jednego z repo gdzie był też jeden z popularnych buildów. Profil ustawiałem przez kilka miesięcy. Pojawił się komunikat że wtyczki przestaną działać z tym buildem. Nic nie pomogło.. tylko nowy profil. Ps. jeśli korzystasz ze skórki która posiada opcję backupu, zrób backup skórki, a wtyczki dograsz na czysto - w eminence mod po kliknięciu skrótu sam prosił o instalację wtyczki.

**Comment by pawelfrac1** [comment]
Tylko nie wiedząc jakie programy i repozytoria powodują występowanie tego komunikatu, mogę znowu coś niepożądanego zainstalować i cała prace pójdzie na marne.

**Comment by tomasiek** [comment]
Dlatego metoda jest prosta. Wpierw repo ramicspa i jego dodatki a potem po 2-3 inne i testy

**Comment by pawelfrac1** [comment]
Właśnie to robię :)
