### ISSUE TITLE
PolishLiveTV - nie tworzy list kanałów.

### ISSUE THREAD

**Issue by broda1125** [ramicspa/kodi#514]
Testowane na Win10 i Linux Mint, po utworzeniu list kanałów i aktualizacji nic się nie pojawia w trybie 'telewizja'. Ścieżki do listy zmieniane kilka razy i dalej to samo, co może być przycyzną?

**Comment by Katapulta** [comment]
Mówisz o IPTV simple client ?? A włączyłeś go w Kodi ?? AKTYWUJ taka opcja Dodatki->Moje dodatki-> Klienty telewizji ->IPTV simple client -> Aktywuj / uruchom jakoś tak.

**Comment by wisiann** [comment]
U mnie hula

**Comment by ramicspa** [comment]
wtyczka powinna sama aktywowas IPTV simple client ... restart kodi jest wymagany. a jak nie hula tak dobrze jak u @wisiann to trzeba recznie.

**Comment by wisiann** [comment]
@ramicspa ,troche z innej beczki ale nie chce otwierac nowego topicu,
Probowalem przestawic czas odtwarznia na 6 h do tylu ale to nie dziala,ani na simple client ani na iptv,gdzie jeszcze moge pogrzebac?

**Comment by bylx** [comment]
Dlaczego takie problemy z tą telewizją,na początku tele-wizja działała eleganco,a po dwóch dniach podla na amen,app w telefonie np.tv line Guide działa mi zawsze,zresztą na tv też tylko tyle że kiepsko się ją obsługuje przez fire stick tv ,trzeba myszkę.dlaczego tyle problemu przez to że tylko że kodi używam
