### ISSUE TITLE
Dopasowanie wtyczek odświeżania do pilotów Yatse, 4-Head

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#515]
Witam

Czy istnieje możliwość dopasowania odświeżania wtyczek do pilotów na smartfona  np.  Yatse, 4-Head.
Chodzi mi np alltube.tv (pozostałe też) filmy strona 1  pokazują się w pilocie a strona 2, 3 itp już się nie odświeża, podobnie jest w serialach 

We wtyczce Covenant  odświeżanie filmów i seriali działa, przechodzi na następne strony i wyświetla  filmy i seriale okładki opis itp

**Comment by ramicspa** [comment]
czy stronicowanie dziala w jakies innej wtycze z tego repo?

**Comment by Cerber2000** [comment]
Witam

Nie działa to odświeżanie = stronicowanie (android box kodi 17.4 + smartfon) następnych stron 2,3,4 tylko pierwsze strony we wtyczkach działają

Czy istnieje możliwość dodanie tej opcji w repo?

Brakuje tej opcji we wtyczkach.

Można odpalić np iptv i ogladając wiadomości poszukać sobie filmu na smartfonie

**Comment by ramicspa** [comment]
z podowu braku odpowiedzi na pytnie zamykam temat
