### ISSUE TITLE
Telewizja!

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#516]
Dowiedziałem się,że kablówka j cyfrówka blokuje strony z dostępem do darmowej telewizji! No cóż będzie trzeba wybrać płatne które nie dadzą rady zamknąć

**Comment by abrus7** [comment]
Tv-weeb zostało już zablokowane ciekawe co następne kilka co udostępniało stream też zablokowane

**Comment by Katapulta** [comment]
kablówka i cyfrówka nie blokują bo nie mogą :P Mogą co najwyżej zgłosić odpowiednim organom ścigania :) tv-weeb nie wiem co to był za syf ale chyba mało ważny i syfiaty bo niestety pierwsze o nim słyszę :) Jak ktoś jest "łebski" poszuka , poszpera i znajdzie sobie np bulid w którym autor udostępnia za free dostęp do kont premium z telewizją :) Trzeba poszperać :P

**Comment by Katapulta** [comment]
@abrus7 ja korzystam z jednego i nie ma żadnych wirusów :D Nie wiem gdzie i kto pisał - trzeba mieć sprawdzone i pewne ;p I takie gdzie masz to za free :P Pierwsze słyszę że w jakimś bulidzie są wirusy :P

**Comment by Katapulta** [comment]
@abrus7 i trzeba też uważać na Aliena bo jemu się dupa pali bo u niego musisz bulić i kupę hajsu zostawiać zebu z bulidu korzystać i zaczyna się podszywać pod innych i "robić im koło tyłka" zmieniająć hasła do kont czy też kopiując bulidy i próbując w ten sposób zarobić :)

**Comment by koladka** [comment]
Uwarzajcie na ALIENA ?

**Comment by meserak86** [comment]
zrobic build kazdy moze (sam jestem tego przykladem), wystarczy wiedziec jakie repozytoria, jak skora, jakie wtyczki, jak pogrupowac, rozpisac sobie w notatniku, organizacja i wyklikanie, czerpanie z tego kasy to zupelnie inna bajka bo zeby build byl platny i ludzie chcieli placic to albo trzeba zaoferowac cos extra co faktycznie bedzie warte placenia jak pozadne EPG, debirdy, wlasne bazy i wszystko PL (do tego jakas forma zabezpieczenia przed zaprzestaniem placenia) albo szukac frajerow i probowac naciagac ludzi, w necie latwo znalezc mozna tylko KodiUltimate, Multimedia Master, i Alienwizard, buildow jest multum, ale z polskimi wtyczkami EPG itd trzeba wojowac samemu a przecietnemu zjadaczowi chleba sie nie chce

**Comment by koladka** [comment]
Z tym ze Kodi Ultimate jest darmowe i smiga ladnie

**Comment by meserak86** [comment]
to samo co moj build... nie zawiera polskich EPG, i jest na darmowych wtyczkach, aczkolwiek KodiUltimate najprawdopodobniej kopiuje buildy... moze to byc nawet alien w nowej odslonie bo jego ostatni build z przed tego na Skin Bello 6 NTV jest jak dla mnie dokladna kopia angielskiego PERKS build wraz z wizardem, przez jebo build stwierdzilem, ze moge to zrobic lepiej:D, koleny poziom to juz koding, wlasne robienei wtyczek epg itd, za to sie nie wezme ale buildy robic moge bo to proste:D

**Comment by koladka** [comment]
Masz racje wlasnie zobaczylem ze bedzie mial platna wersje!;) tak czy inaczej w tym tygodniu padlo mnustwo repositoriow poczawszy od Ares Wizard i filmonych jak Covenant ciekawe czy to tylko przeniesienie na nowe repo. Telewizja Polska Ramica tez czeka na maly update bo wiekszosc juz niestety niedziala?;(

**Comment by meserak86** [comment]
w sumie to najbardziej potrzebna wtyczka do anime, poskie radia i podcasty, i update do televizji IPTV-nowe EPG... kontent filmowy i serialowy angielski z lektorem PLznajdziesz scraperami w topowych wtyczkach wiec najbardziej kuleje kontent typowo POLSKI

**Comment by meserak86** [comment]
kodi ultimate ma na razie powylanczane wszystkie linki do buildu albo nie potrafie na szybko znalezc paczki zawierajacej addons i userdata foldery  zeby zobaczyc w srodku jakie ma wtyczki podpiete do skorki, ale nawet jakby co to i tak napewno build jest zrobiony na darmowych wtyczkach ogolno dostepnych i ewentualnie platne listy epg, wiec i tak nie bedzie mogl miec wiecej niz inni mogli by zapiac w build chyba ze zabierze sie za tworzenie czegos, w co watpie

**Comment by koladka** [comment]
RAMIC PROSBA O ODNOWIENIE WTYCZEK TV BO JUZ WSZYSTKO PADLO!!!!;(

**Comment by koladka** [comment]
Po dzisiejszej aktualizacji i dodaniu nowych wtyczek z telewizja potwierdzam ze wiekszosc znow padla;(
