### ISSUE TITLE
addon Pair plugin HD

### ISSUE THREAD

**Issue by meserak86** [ramicspa/kodi#517]
Czy istnieje mozliwosc dodania pluginu do parowania openload, the video me, vid up me i vshare
(doslownie cos takeigo jak z cerebro repozytorium)

**Comment by ramicspa** [comment]
a po co dodawac skoro jest juz dostepny w innym repozytorium

**Comment by tomasiek** [comment]
@meserak86 - a podaj nazwę wtyczki która dodaje taką funkcję.

**Comment by kashkash18** [comment]
Są tam dwie wtyczki , CerebroTv Pair With i Pair ME UP ale żadna nie sparowała mi Openloada

**Comment by kashkash18** [comment]
Aczkolwiek pomysł na taką wtyczkę jest spoko

**Comment by meserak86** [comment]
`a po co dodawac skoro jest juz dostepny w innym repozytorium`
1. jest przydatna do kazdego buildu
2. niewiele z tym zachodu
3. owa wtyczka w cerebro ma podstrone z reklamami nabijajacymi kase kolesiom od cerebro i timerem 6s (tu na dole w paczce wyciete i wsadzone linki bezposrednie)
[script.qwer.pairwith.zip](https://github.com/ramicspa/kodi/files/1478973/script.qwer.pairwith.zip)
4. skrypt dziala tez na androidach itd

**Comment by tomasiek** [comment]
@meserak86 
ad. 1 - to niech autorzy buildów ją dodają - tu nie promujemy żadnych buildów
ad. 4 - skrypt nie działa z libreelec na boxach z androidem :(
