### ISSUE TITLE
NBA

### ISSUE THREAD

**Issue by kamilinho1** [ramicspa/kodi#519]
Czy jesteś w stanie stworzyć wtyczkę do oglądania powtórek NBA? Są strony gdzie takie mecze są udostępniane już kilka godzin po końcowym gwizdku. 
http://tvrex.net
http://nbareplaytv.com
http://nbahd.net
Było kilka wtyczek, już nie są kontynuowane i niestety ale nie działają. 
A sezon w pełni. Liczę na Ciebie:-)

**Comment by krzysztof222** [comment]
JESTEM ZA

**Comment by kamilinho1** [comment]
Czy mam mieć nadzieję? A może ktoś ma namiary na coś już istniejącego?

**Comment by garbatyprostak** [comment]
Project D ma powtorki NBA NHL etc

**Comment by kamilinho1** [comment]
Ale bardzo późno je uploadują. Dodatkowo często w słabej jakości.
Testowałem ten serwis też.

27.11.2017 napisał:
>Project D ma powtorki NBA NHL etc

**Comment by garbatyprostak** [comment]
jak dla mnie ok ,mecze sa okolo dzien po

**Comment by ramicspa** [comment]
@kamilinho1 jak dobrze poszukasz to znajdziesz odpowiednie wytczki - jak nie dzialaja to napisz do ich autora o poprawe
