### ISSUE TITLE
ekino - filmy z streamin.to

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#52]
Nie wiem czy to tylko u mnie ale jest problem z odtwarzaniem filmów na ekino - generalnie nie odtwarza żadnego filmu z streamin.to - pokazuje że film jest w ogóle niedostępny , a wrzeczywistości na stronie ekino film startuje normalnie , bardzo proszę o sprawdzenie tego i w miare mozliwości poprawę lub podanie sposobu na rozwiązanie tego problemu

http://pastebin.com/fmmWacR2

**Comment by ramicspa** [comment]
hmm nie wiem czy zauwazyles ale sa dwa rozniace sie miedzy soba serwisy ekino: ekino-tv.pl oraz ekino.tv.  Sprawdze ktory lepszy i zmodyfikuje wytczke
