### ISSUE TITLE
Wtyczki które były w zestawieniu mrKnow a są też w ramicspa

### ISSUE THREAD

**Issue by ghost** [ramicspa/kodi#520]
alltube.tv
cda.pl
efilmy
filmy.to
zalukaj
bajkionline.com
bajkipopolsku.com
filmydokumentalne.eu
inatv.pl
tele-wizja.com
WP Pilot

**Comment by kacper91** [comment]
Brak:

**Do wtyczki, gdzie są bajki i anime**
kreskowkazone.pl
a-o.ninja (dawne anime-odcinki.pl)

**Do wtyczki LivePolishTV**
EskaGo.pl
meczyki.pl
meczelive.tv
Itivi.pl
pierwsza.tv
weeb.tv
yoy.tv

wykop.pl

Czy wymienione powyżej serwisy zostaną one w najbliższym czasie dodane do repozytorium?

**Comment by tomasiek** [comment]
itivi.pl - było ale wyleciało 
yoy.tv - ma tylko premium - nie będzie obsługiwane.

**Comment by kacper91** [comment]
Więc pozostają jeszcze te

**Do wtyczki, gdzie są bajki i anime**
kreskowkazone.pl
a-o.ninja (dawne anime-odcinki.pl)

**Do wtyczki LivePolishTV**
EskaGo.pl
meczyki.pl
meczelive.tv
pierwsza.tv
weeb.tv

wykop.pl

**Comment by tomasiek** [comment]
Co do wykop.pl - nie wiem jakby to miało wyglądać nawet... przecież to serwis ze śmiesznymi obrazkami.

**Comment by meserak86** [comment]
Wykop to polski dig/reedit, nie mylmy z portalami typu komiksy/wiocha

**Comment by meserak86** [comment]
Co do anime 
https://shinden.pl
A jak wejde do domu dodam jeszcze pare linkow...
Pytanie czy nie dalo by sie zrobic wtyczki do mangi np do mangafox(jak myslicie jest sens?)

**Comment by tomasiek** [comment]
@meserak86 nie musisz mi mówić czym jest wykop - zbyt długo tam jestem, tak samo jak na reddicie. Tylko jakoś nie widzę "zastosowania" pod kodi. Przeglądanie wykopaliska? Przecież cały urok wykopu to wcale nie filmy w znaleziskach tylko komentarze.

**Comment by meserak86** [comment]
co do wykopu to slaby pomysl, ale tv i anime napewno zasluguja na uwage

**Comment by kacper91** [comment]
Temat dotyczy wtyczek które były na mrKnow a są też (albo ich nie ma) na ramicspa.
Zostawmy więc temat tego wykopu :) czyli zdecydowanie on odpada. Jak poprzednik napisał trzeba zwrócić uwagę na tv i anime.

**Comment by kacper91** [comment]
Wszyscy wolą anime, a ja zauważyłem brak możliwości obejrzenia na kodi czegokolwiek co leci lub co leciało na kanałach Disney Channel, Disney XD, Cartoon Network, Boomerang itp choć też są serwisy które archiwizują seriale aktorskie jak i animowane w całości.

**Comment by meserak86** [comment]
taka mala analiza kontentu:
scrapery typu covenant/genesis/elusium/poseidon itp wyciagaja filmy i seriale z lektorem jak sie ustawi PL wtyczki typu salts/strictly hd/1080p/star tec/myriad itp +napisyPL
do szczescia brakuje tylko polskiej TV, i polskiego kontentu
alltube, i bofxilm, FilmwebBooster robia robote, ale brakuje lepszych wtyczek do kreskowek anime i update dla TV

Disney Channel, Disney XD, Cartoon Network, nickelodeon, boomerang, starsze kreskowki ze stron typu kreskowki.pl itp i pozadnej wtyczki z anime z polskimi napisami z podzialem na gatunki i ostatnio dodane odcinki
dodalbym tez wtyczke do 
https://www.serialeonline.pl/
http://seriale.co/
http://www.filmosy.tv/

PS: https://fili.tv/ calkowicie umarl, mozna wyciac wtyczke z repo albo oznaczyc ja jakos jako nie dzialajaca
aktualnie, ide testowac wtyczki z ramica bo musze przebudowac sekcje polskie w swoim buildzie

**Comment by meserak86** [comment]
nasze-kino (nie dziala bez zalogowania konta)
tvlinks (nie dziala albo same eng)
efilmy dziala
ekabaret dziala
ekinotv nie dziala
IItv nie dziala

**Comment by kacper91** [comment]
Fajne podejście, tym też się kieruje

**Comment by tomasiek** [comment]
Coś mi się wydaje że szukacie po prostu zestawu do uzupełnienia swoich buildów.... A pamiętajcie że wtyczki ramica nie lubią buildów....
Co do nowych serwisów z filmami i serialami (o anime się nie wypowiem bo nie znam), to samo podanie serwisów to za mało. Musisz udowodnić że mają coś, czego już dostępne serwisy nie posiadają. Albo super bazę, albo lepszą jakość, albo wypełniają jakąś lukę, muszą mieć coś, czego gdzie indziej nie ma. Bo tworzenie wtyczki dlatego że coś jest nie ma sensu. Serwisy pojawiają się jak grzyby po deszczu i tak samo szybko znikają. Potem zrobię krótki test tych które podałeś, ale wydaje mi się że te serialowe już omawiane były.

**Comment by tomasiek** [comment]
Więc tak
tvlinks  - działa , są też polskie, a to że same angielskie... można napisy pobrać jednym kliknięciem przecież.
ekinotv  - działa - nie wszystkie linki, ale te które sprawdzałem i nie działały to na stronie też są martwe.
**fili.tv** - strona działa, wtyczka też...  Informacje o śmierci są więc stanowczo przesadzone.
**serialeonline.pl** - wymagana rejestracja, więc szkoda czasu na to w ogóle...
**seriale.co** - coś tam jest, ale niewiele...
**filmosy.tv** - https://github.com/ramicspa/kodi/issues/483#issue-266603459 - kicha kompletna.

Przy okazji - stwierdzenie "nie działa" jest kompletnie nieprzydatne dla nikogo. Podaj co konkretnie nie działa, gdzie itp itd. załącz logi. Tylko w ten sposób można pomóc.

**Comment by meserak86** [comment]
Wtyczki ramica nielubia buildow bo znalazl sie debil ktory chcial zarobic na czyms za darmo, ja nie mam zamiaru na niczyjej pracy zarabiac


Co do anime
https://shinden.pl
http://www.animezone.pl/
http://www.superanime.pl/
https://on-anime.pl/
DRAMA
https://centrum-dramy.pl/
http://drama-online.pl/
https://www.dramaqueen.pl/

Wtyczka anime dziala, ale brakuje jej podzialu na gatunki i dzialu z nowymi odcinkami,sezony nie dzialaja poprawnie... Podane strony to podstawa kazdego kto oglada anime albo dramy, dodam, ze przydala by sie wtyczka do animesub.info to najwieksza baza napisow do anime, dedykowanych do anime

**Comment by meserak86** [comment]
Ekino.tv to kwiatek ktory wyrosl na smierci kinomaniaka w okresie transformacji w kinomana, portal jest slaby, tv links jak nie posiada duzo polskiego kontentu i trzeba napisy sciagac to lepiej mose zajac sie jakims innym leprzym portalem

**Comment by tomasiek** [comment]
LOL... mam problem z czytaniem... 
Co do tego że wtyczki się nie lubią z buildami nie musisz mi tłumaczyć. Jak dla mnie buildy to kompletna porażka - full śmieci nikomu niepotrzebnych - ja wolę "skrojone na miarę" a nie All in One.
Te portale bogate w polski content już są dodane - cda, filmwebbooster, alltube, vider, freedisc, Szukajka.tv, Dailymotion channels - to całkiem mocna ekipa. Jeśli tam nie ma, to pewnie w całej sieci też nie ma. Jeśli do tego dodasz covenant - to do filmów/seriali masz wszystko. Anime i drama się nie wypowiadam - nie mój content.

>  lepiej mose zajac sie jakims innym leprzym portalem

(muszę to dodać do swoich kwiatków)
Znajdź lepszy, zaproponuj, sprawdzimy, przetestujemy. Jeśli będzie warty uwagi, to gwarantuję że ramicspa rozważy zrobienie wtyczki. Jeśli będzie tak "rewelacyjny" jak filmosy.tv, to marne szanse.

**Comment by kacper91** [comment]
Covenant od kilku dni już nie działa znacie jakiś dobry odpowiednik tego?

**Comment by tomasiek** [comment]
Covenant działa - nie siej fermentu. Developerzy zamknęli repo, ale sama wtyczka działa - da się odtwarzać filmy, działa synchronizacja z trakt, biblioteka, wyszukiwanie... źródła jak na razie działają - wszystko jest w jak najlepszym porządku (pewnie z czasem zasoby źródeł zaczną padać - ale jak na razie działa idealnie). 
Nie działa natomiast repozytorium w którym się znajdował kod wtyczki, więc nie da się go zainstalować - ale jak ktoś ma zainstalowane to działa bez problemu: http://kodiwpigulce.pl/repozytorium-colossus-covenant-ares-wizard-smash-dandymedia-nie-dzialaja-co-sie-stalo/
Na razie nie ma żadnego "pewnego" forka ani zamiennika (znalazłem coś takiego - niby to samo, ale nie potwierdzone: https://mykodiaddons.com/install-fantastic-kodi/)
Na mods-kodi.pl ktoś udostępnił ostatnią wersję Covenant która była w repozytorium wraz z wszystkimi zależnościami:
http://mods-kodi.pl/downloads.php?cat_id=9&download_id=281

> Sposób instalacji:
> 1. Rozpakować archiwum zip
> 2. Zainstalować wszystkie 5 wtyczek wg przypisanej numeracji.

W tvaddons.co pojawił się natomiast exodus - czyli "poprzednik" covenanta będący obecnie IMO kopią covenanta.
Trzeba czekać aż to się wszystko rozwinie. Do czasu aż Covenant działa można śmiało z niego korzystać.

**Comment by kopernik1983** [comment]
@tomasiek no ten fantastic tez mi sie trafil ale wszystko to kopiuj wklej covenant wiec dopoki jakis tam aktualizacji nie bedzie ( bo z covenanta juz sie zerznac kodu nie da ) to tak naprawde nie ma oczym rozmawiac. Jak jakies beda no to wtedy moze cos z takiej wtyczki sie urodzi. trzeba czekac na efekty.

**Comment by tomasiek** [comment]
Widziałem że tvaddons.co i glass repo przejmuje urlresolver... więc pierwszy najważniejszy krok zrobiony.
Trzeba też obserwować exodusa - co z nim...

**Comment by kopernik1983** [comment]
To sie zgadza bo juz wczesniej sie zadeklarowali ze przejma piecze nad urlresolver i juz poszzla aktualizacja bo w jakims chamskim repo crebero czy jakos tak gosc juz cos tam namieszal dokladnie sie nie zaglebialem i stad poszla aktualizacja do 4.0.12 . Nie mowie ze bym nie chcial ale tvaddons po tym jak sie kategorycznie odcial od exodusa wiadomo kiedy i w jakich okolicznosciach raczej pchal sie nie bedzie , bardziej moze cos w Looking Glass wykombinuja.
 Teraz to sie wysyp z tymi forkami zrobil jak na jesieni grzyby po deszczu.

**Comment by meserak86** [comment]
pochodne exodusa:
covenant
genesis reborn
Poseidon
rebirth
Picasso
No Name
SolarMovie
gurzil
elysium
specto fork
Project M
Safehouse Movies

http://repo.lookingglass.rocks/

**Comment by kacper91** [comment]
Co więc będzie dobrym rozwiązaniem covenant, exodus czy fantastic  ?

**Comment by koladka** [comment]
Urlresolwer jest w movericTv. A co do wtyczek to uwazam ze ramic powinien sie skoncentrowac na wtyczkach z telewizja bo to najwieksza liczba ogladajacych

**Comment by tomasiek** [comment]
>  to najwieksza liczba ogladajacych
Jakieś dane? Ja osobiście nie oglądam TV, wolę obejrzeć program/serial wtedy kiedy ja chcę, bez reklam itp itd, w jakości jaka mi odpowiada...

**Comment by koladka** [comment]
Niemam zadnych danych ale Poloni kozysta mnostwo sam dostaje zapytania na meila o tv i wtyczki od znajomych

**Comment by meserak86** [comment]
Anime,manga i drama
majstarsze portale polskie 
https://shinden.pl
http://www.manga-lib.pl/
https://love-drama.pl/
najstarsza strona z napisami
http://animesub.info/
najstarsza stronka z torrentami z ktorej zasysaja wszyscy z animesub
nyaa.se / nyaa.si

ANIME
https://shinden.pl
https://animeon.pl/
http://www.animezone.pl/
https://a-o.ninja/

http://www.wbijam.pl/
https://www.animeonline24.pl/
http://anime-centrum.pl/
https://animefox.pl/

DRAMA
https://love-drama.pl/
http://drama-online.pl/
https://centrum-dramy.pl/
https://www.dramaqueen.pl/


zwykle jest tak, ze jak cos nie ma na pierwszych 3 stronach to znaczy, ze trzeba sobie samemu zassac z nyaa i animesub

**Comment by kacper91** [comment]
Trzeba dodać również strony z kreskówkami i z serialami młodzieżowymi 
http://www.gralandia.tv/
http://kreskowki-online.pl/
https://www.kreskowki.tv/
http://wyspabajek.pl/

**Comment by kopernik1983** [comment]
@tomasiek URLResolver w tvaddons.   
November 22nd: A few days worth of confusion with URLResolver has a plan moving forward. @TVAddons, the original provider of URLResolver has taken over the dependency again. Official updates will be pushed through their repository.

**Comment by meserak86** [comment]
As long as you have one of either TVAddons (http://fusion.tvaddons.co) or Looking Glass (http://repo.looking.glass) sources installed on your Kodi box, the URLResolver dependency will be installed with it.

You can view URLResolver settings and set things like priority and premium accounts up by navigating to SYSTEM > Add-ons > SYSTEM > Dependencies > URLResolver > Configure.

**Comment by kopernik1983** [comment]
raczej nie polecam ani jednego ani drugiego. z powodu niewiadomego pochodzenia. maja takie aktualizacje ktorych nie ma nawet w dedykowanych do poszczegolnych dodatkow repach. ja bynajmniej nie wiem kto tam grzebie i jaki syf póbuje wypuścic na światlo dzienne. ostatnio nawet zainstalowalem http://archive.org/download/repository.xvbmc. poaktualizowalo zaleznosci gdzie nawet w oficjalnym repo kodi nie bylo takiej aktualizacji.
