### ISSUE TITLE
Ramicspa po aktualizacji  17.6

### ISSUE THREAD

**Issue by tabzasnk** [ramicspa/kodi#521]
Nie działa pvr po aktualizacji kodi na 17.6,  gdy daje utwórz listę pisze ze lista jest pusta.  

Czy to chwilowe problemy?

**Comment by wisiann** [comment]
To fakt u mnie tez lipa,
Ale chyba troche trzeba poczekac jak zawsze

**Comment by koladka** [comment]
Co sie stalo wtyczki z tv poznikaly po aktualizacji!??;(

**Comment by wisiann** [comment]
Hula znowu ,dzieki @Ramic,
