### ISSUE TITLE
Adapter.pl

### ISSUE THREAD

**Issue by plaXelos** [ramicspa/kodi#522]
Witajcie. Piszę na Githubie pierwszy raz. 
@ramicspa za dobre wtyczki należy się wielkie piwo!!!, ale dość wazeliniarstwa ;)

Nikt jeszcze nie pokusił się o napisanie wtyczki do portalu **_[adapter.pl](adapter.pl)_**. Umieszczane są tam filmy z audiodeskrypcją. Umożliwia to niewidomym i słabowidzącym w pełni obejrzeć film. 
Najlepiej zajrzyjcie tam i zobaczcie o co chodzi.
A teraz właściwa część posta. @ramicspa może dasz radę napisać wtyczkę? Będę Ci wdzięczny.
Pozdrawiam plaXelos.

**Comment by kopernik1983** [comment]
A pokusil sie juz , jest juz sporo czasu nie wiem czy jakos rozwijana ale to juz trzeba poczytac. znajdziesz ja na mods-kodi z tego co pamietam.

**Comment by plaXelos** [comment]
Dzięki! 
Znalazłem wtyczkę i działa.
Pozdr.
