### ISSUE TITLE
LivePolishTV

### ISSUE THREAD

**Issue by meserak86** [ramicspa/kodi#525]
TOTALNA PADAKA Z LISTAMI, WYWALAJA SIE NA JAKIS CZAS CO PARTE H

**Comment by tomasiek** [comment]
To normalne- zewnętrzne serwery się zabezpieczają co chwilę. Chcesz mieć
pewność działania? Szukaj listy Wojtu. Jest za free ale ciężko ją dostać.

24.11.2017 11:06 PM "meserak86" <notifications@github.com> napisał(a):

**Comment by jorg35** [comment]
Listy Wojtu już nie są free nie wprowadzaj ludzi w błąd.

**Comment by tomasiek** [comment]
Są za free. Opłata jest dobrowolna, możesz zapłacić 5 zł raz na 3 miesiące. Jeśli zalapiesz się do grupy użytkowników, możesz korzystać, problemem jest to, żeby się dostać do grupy użytkowników. Lista ma ograniczoną ilość użytkowników. Dopiero jak się zwolni miejsce to jest szansa na wbicie się. Na wykopie nawet w zeszłym tygodniu były 2 konkursy.
Mi się udało kilka miesięcy temu załapać. Korzystam do dziś.

**Comment by jorg35** [comment]
Ja tam nie wiem czy się coś płaci a jak ty piszesz ze płacisz to niedługo lista się zwolni o jednego członka bo publicznie wypisujesz głupoty gratulacje.

**Comment by tomasiek** [comment]
> Listy Wojtu już nie są free

No ale to ty piszesz że już nie jest za free. Ja mówię że jest za free.
Zerknij na wykop z zeszłego tygodnia. Wojtu ogłosił konkurs i każdy mógł wygrać losowanie. Opłata nie jest za listę. Opłata jest dobrowolna na utrzymanie serwera. Nie za listę.

**Comment by frijerz** [comment]
Potwierdzam: jest dokladnie tak, jak @tomasiek mówi :)

**Comment by jorg35** [comment]
@tomasiek mnie nie musisz się tłumaczyć  takie rzeczy nie pisze się publicznie.

**Comment by tomasiek** [comment]
@jorg35
Ale to ty zacząłeś coś pisać o jakiś opłatach. Nie ja. Trzeźwieć nie musiałem, założyłem że ktoś inny może odpoczywać przy piwku i niedoczytał, mówiąc że lista nie jest za free (już nie będę cytował). Jest, była i będzie. Tylko ciężko się na nią załapać.
Eot bo wydaje mi się że robimy masło maślane.

**Comment by jorg35** [comment]
Co ty człowieku piszesz nie pisałem o żadnych opłatach czytaj ze zrozumieniem,paplasz głupoty a później się wypierasz i próbujesz zwalić winę na mnie posłuchaj starego usera masz listę nie paplaj publicznie tylko na PW.

**Comment by tomasiek** [comment]
1. Zerknij na swój pierwszy post w tym wątku.
2. Rozumiem o co ci chodzi... To co? Kasujemy posty?

**Comment by tomasiek** [comment]
Posprzątałem tu trochę:)

**Comment by tomasiek** [comment]
A w odpowiedzi do @meserak86 bo się można pogubić przez porządki.
Livepolistv działa na zewnętrznych serwerach. Jak tam jest mała zmiana, to lista od razu nie działa. Chcesz gwarancji? Szukaj zewnętrznych list. Część jest płatna, część nie, część łatwo dostępna, część nie. Na wykopie można czasem w konkursie coś wyłapać.
Wilk syty i owca cała

**Comment by gregor35** [comment]
Ale jorg35 ma i tak rację.

**Comment by tomasiek** [comment]
O czym napisałem powyżej... Zaczyna się znowu. Tak, ma rację.

**Comment by jorg35** [comment]
@tomasiek usuń te resztę śmieci nie związane z tematem >>>Posprzątałem tu trochę:) @jorg35 ma rację................

**Comment by jorg35** [comment]
@gregor35 usuń swój komentarz nie pasuje tu.
