### ISSUE TITLE
FilmwebBooster

### ISSUE THREAD

**Issue by meserak86** [ramicspa/kodi#526]
zero kontentu w srodku

**Comment by kacper91** [comment]
No cóż tak czasem bywa

**Comment by tomasiek** [comment]
Hm.... Przedwczoraj działało... Jakieś logi albo coś?

24.11.2017 11:13 PM "kacper91" <notifications@github.com> napisał(a):

**Comment by tomasiek** [comment]
No faktycznie katalog filmów nie działa. Blank Page. Natomiast "dziś w tv"
bangla aż miło.

25.11.2017 5:45 AM "Tomasz Woś" <tomasz.wos@gmail.com> napisał(a):

**Comment by ramicspa** [comment]
@meserak86 ZERO to ty przekazuje inforamcji w swoich komentarzach wiec albo troche wiecej precyzji albo przesztan spamowac!
