### ISSUE TITLE
Wtyczki nie działają

### ISSUE THREAD

**Issue by AndyAndyy** [ramicspa/kodi#528]
Po zainstalowaniu ramic repo wersja 1.3.5 
Wszystkie wtyczki video są puste , po otwarci wtyczki mam tylko (...)
Czy jest jakis do dodatek do repo by to działało?

**Comment by AndyAndyy** [comment]
Na android box wszystko działa tylko ostatnio zainstalowałem kodi na Apple TV i jest problem z wtyczkami
Jesli macie jakies pomysły jak je naprawic ?

**Comment by AndyAndyy** [comment]
Na android box wszystko działa tylko ostatnio zainstalowałem kodi na Apple TV i jest problem z wtyczkami
 Macie może jakies pomysły jak je naprawic ?

**Comment by koladka** [comment]
Niestety na android boxie dziala jak dziala mi na wszystkie te wtyczki z tv dziala moze z 12 kanalow?????

**Comment by witstg** [comment]
Zależy mi tylko na kanale domo+ . Działa tylko na televhs i brakuje mi tego
programu. Może chociaż adres do źródła znasz to bym zmodyfikował m3u

27.11.2017 3:40 PM "koladka" <notifications@github.com> napisał(a):

**Comment by koladka** [comment]
Jezeli chcesz domo+ to jest na appce z google store nazywa sie BISON TV GUIDE. JEST SWIETNA (lepiej miec vpn dla bezpieczenstwa)

**Comment by witstg** [comment]
Właśnie zależy mi aby oglądać na kodi na tv. Dlatego zależy mi na dodaniu źródła do listy m3u lecz nigdzie nie mogę go znaleźć.

**Comment by ramicspa** [comment]
@witstg adres zrodla znajdziesz w logu ... byc moze trzeba ustawic debugging level dla loga http://kodi.wiki/view/Log_file/Advanced
