### ISSUE TITLE
Live polish tv nie  tworzy listy m3u 

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#529]
Ramic,
Mozesz rzucic na to okiem ,na kodi 17.6 jest problem,
Dzieki

**Comment by tomasiek** [comment]
Daj jakieś szczegóły. Logi, opisz na których serwisach nie tworzy itp itd. Bo na razie jest to wróżenie z fusów.

**Comment by ramicspa** [comment]
widze ze jakis blad wywala wtyczka ... pewnie cos gdzies sie zmienilo ... bedzie niebawem poprawka
