### ISSUE TITLE
Tworzenie wlasnej listy m3u 

### ISSUE THREAD

**Issue by witstg** [ramicspa/kodi#535]
Witam czy ktos wie i podzieli sie sposobem w jaki sposob mozna stworzyc własna listę . Jest wiele stron na których lecą kanały live i nie mam pojęcia w jaki sposób sprawdzić źródło strumienia na stronie. Używałem różnych programów do odnajdywania  linków do źródeł ale przykładowo pojawiają się co 5 sekund nowe i żadne z nich niestety nie chce ruszyć na kodi. Czyli zależy mi głównie o odnajdywania adresu źródła streama na roznych stronach.  Z góry dziekuje za poświęcony czas.

**Comment by tomasiek** [comment]
No ale przecież jest do tego wtyczka. LivePolishTv. Przegląda strony i robi
listę m3u.

03.12.2017 3:21 PM "witstg" <notifications@github.com> napisał(a):

**Comment by witstg** [comment]
No tak zgadza się ale przykładowo kanał domo+ nie znajduje się nigdzie na tych serwisach . A w Internecie idzie znaleźć na innych serwisach działający kanał i potrzebuje informacji w jaki sposób odnaleźć adres strema i dodać go do własnej listy m3u.

**Comment by tomasiek** [comment]
A to już nie pytanie tutaj... Pytaj np. na dobreprogramy
