### ISSUE TITLE
FOLDER

### ISSUE THREAD

**Issue by meserak86** [ramicspa/kodi#539]
Tak troszku niesmak czuje widzac, ze folder zawiera 98% wtyczek wg mojego buildu(bodajze wersja 7 z testem) a ramic sie wypina na DARMOWE buildy i robi mi problem

(i prosze innych bez tekstow, ze to nie z mojego buildu ta lista w folderze )
vip.iptvlive.org bez zaproszenia ta wtyczka jest bezuzyteczna[nie liczac radia bo jest nie chronione i aktualne:D] i niewiele osob ja ma w ogole, a ja bylem jedynym ktory ja dal do buildu bo mialem liste z wtyczkami za kase jesli ktos se zechce zaplcacic sobie u konkretnego providera)

MOJ BUILD JEST I ZAWSZE BEDZIE DARMOWY A CIEBIE RAMIC PROSZE O TROSZKE WIECEJ FAIR PLAY

**Comment by tomasiek** [comment]
Jakiś miesiąc temu ci mówiłem że wtyczki ramica nie lubią się z buildami. Zarówno płatnymi jak i darmowymi.
Skąd wiesz ile osób ma dana wtyczkę...? To że jej nie ma w buildach nie jest żadnym wyznacznikiem.
Co do niesmaku. Chodzi o wtyczkę folder czy o folder githubie?
Wtyczka folder integruje zainstalowane wtyczki ramica w jedną. Powstała lata świetlne przed twoim buildem. Nie zawiera wszystkich wtyczek ramica, ale z tego widać że twój build zawiera praktycznie wszystkie..
Jeśli to drugie to gratuluję pomysłu. Zrobić build na czyjejś pracy. I nie. Nikogo nie interesuje że na dzień dzisiejszy jest darmowy. Kodiultimate też był darmowy. Cherrytv też.

**Comment by meserak86** [comment]
folder to ramicowskie super repo, to co tam jest to calkowity scan mojego buildu i nie insynuj mi tu ze to ja zgapialem od ramica "Zrobić build na czyjejś pracy.", to ramic zrobil folder na mojej pracy, ja nikomu nie bronie kozystac z mojej pracy, o ile ta osoba tez kozysta na tym i pozwala mi tez to robic

**Comment by tomasiek** [comment]
Hehe - widzę że twój build ma teraz 2 wersje - z ramic i bez ramic... niereformowalny jesteś...
