### ISSUE TITLE
eFilmy  brak oceny z filmweb.pl

### ISSUE THREAD

**Issue by Cerber2000** [ramicspa/kodi#54]
W pluginie efilmy  zniknęły oceny filmów z filmweb, brak jest także roku produkcji

Proszę o dodanie możliwości sortowania po ocenie filmu z filmweb dacie dodania 

Dzięki

**Comment by Seico** [comment]
Na efilmy - generalnie też nie odtwarza żadnego filmu z streamin.to

**Comment by Cerber2000** [comment]
Na android boxie kodi 16.1 filmy zstreamin.to mi chodzą bardzo dobrze

Nie ma różnicy czy regular lub captcha 

Tam gdzie jest opcja trzeba ustawić proxy i śmiga

**Comment by Seico** [comment]
No właśnie w opcjach nie ma ustawień proxy na efilmy

**Comment by Cerber2000** [comment]
Fakt nie ma proxy mi chodzą filmy z streamin.to

**Comment by Seico** [comment]
U mnie wyskakuje "File not found or remove" i nie mam pojęcia dlaczego , jest to na kodi 17 i 16,1 na windowsie i na androidzie , wkurza mnie to bo jest serial który chcę oglądać  a jest on tylko tam
