### ISSUE TITLE
Wyciaganie adresu strema 

### ISSUE THREAD

**Issue by witstg** [ramicspa/kodi#540]
Witam, czy może mi ktoś wytłumaczyć w jaki sposób mogę wyciągnąć adresy kanałów z programu Delta media Player dawniej telewizjada.net . Chciał bym stworzyć własną listę m3u na tamtych właśnie adresach .

**Comment by tomasiek** [comment]
Człowieku - po raz n-ty piszę do ciebie. To nie forum zajmujące się takimi rzeczami. To forum wtyczek ramica. Delta Media Player to nie jest wtyczka ramica, to tylko jakiś programik - pisz do jego autorów. To nie forum ogólnotematyczne - tylko ściśle określone dotyczące wtyczek ramica. Nie kodi ogólnie, tylko specyficznych wtyczek.
Pisz na forum dobreprogramy lub na np. share.tv, na kodiwpigulce.pl itp itd.
