### ISSUE TITLE
Live Polish Tv

### ISSUE THREAD

**Issue by koladka** [ramicspa/kodi#541]
Zniknela lista  m3u. Prosba o sprawdzenie

**Comment by ramicspa** [comment]
Jaka lista? Jak zniknęła to utwórz ponownie

**Comment by koladka** [comment]
Sory chodzilo mi o Live iptv, tam opcja- iptv linkss.?

**Comment by ramicspa** [comment]
Ok. Zobaczą co tam się dzieje i będzie aktualizacja

**Comment by wiesiek9246** [comment]
Mam pytanie mógłby pan dodać stronę do swojej wtyczki właśnie taką stronę pierwsza.tv idzie za darmo Niech pan se sprawdzi że idzie za darmo a jest dużo kanałów Pozdrawiam

**Comment by wiesiek9246** [comment]
Ja już pan będzie aktualizował wtyczkę to wizję TV Niech pan usunie A niech pan Doda tą stronę pierwsza.tv to w ogóle nie ma blokady Pozdrawiam

**Comment by jorg35** [comment]
@wiesiek9246 to jest darmowa ale kanały są płatne,mam tam konto tylko chwilowa promocja spróbuj oglądać pod wieczór.

**Comment by wiesiek9246** [comment]
Jak wchodzę na tą stronę tele-wizja.is Przez wtyczkę to włączam Canal Plus Sport 2 i nie działa A na stronie działa

**Comment by ramicspa** [comment]
Niedzialajacy we wtyczce kanal powinno się dać naprawić

**Comment by wiesiek9246** [comment]
Niech pan zobaczy na wszystkich stronach czy wszystko działa tak jak należy

**Comment by wiesiek9246** [comment]
Niech pan spróbuje dodać stronę pierwsza.tv do wtyczki i niech pan Zobaczyć działają kanały bo na stronie działają
