### ISSUE TITLE
alltube

### ISSUE THREAD

**Issue by sergioni** [ramicspa/kodi#545]
przestalo dzialas alltube i inne wtyczki np cda (maintenance nie zostalo dokonczone na sticku od amazona - od tego momentu nie dziala.)  Amazon usb plud krypton 17.6

**Comment by ramicspa** [comment]
alltube dziala tak jak i inne wtyczki, ale nie wspolpracuja z buildamy ... nie ma sensu otwierac nowego watku na ten sam temat.

**Comment by sergioni** [comment]
Nie wiem, nie znam sie, nie jestem developerem tylko przecietnym Kowalskim. Po prostu najgle prezstalo dzialac.. Jak mozna to naprawic?
