### ISSUE TITLE
Filmy Dokumentalne

### ISSUE THREAD

**Issue by Harrako** [ramicspa/kodi#553]
Czy komuś działa jakikolwiek link w Filmach Dokumentalnych?? Sądząc po tytułach, zawartość jest super,  ale linki przestały mi działać.

**Comment by ramicspa** [comment]
Faktycznie, wtyczka wymagala malej poprawki ... juz akutlizacji powinno byc juz ok

**Comment by Harrako** [comment]
Wow ! Jak szybko wyszła ta poprawka! Dziękujemy !!!
