### ISSUE TITLE
[LivePolishTV] Długie ładowanie w przypadku, gdy kanał jest nieaktywny.

### ISSUE THREAD

**Issue by teaperr** [ramicspa/kodi#554]
Cześć.
Gdy wywołuję kanał, który nie działa muszę czekać jakieś 40 sekund zanim twoja wtyczka przestaje go ładować. Czy mógłbyś dodać jakąś możliwość zmniejszenia tego czasu? A może jest jakaś możliwość ręcznego przerwania takiego ładowania? Chciałbym jeszcze dodać, że podobny problem mam z klientem IPTV po załadowaniu twoich kanałów z tym, że tam jedyną opcją przerwania jest wyłączenie Kodi.

**Comment by kodiultimate** [comment]
Przycisk X na klawiaturze przerywa proces

**Comment by teaperr** [comment]
Dzięki wielkie, to chyba rozwiązuje problem. ;)
