### ISSUE TITLE
Nasze-kino

### ISSUE THREAD

**Issue by kashkash18** [ramicspa/kodi#56]
Po wejściu we wtyczkę nic się nie wyswietla

**Comment by ramicspa** [comment]
strona ulegla zmianie - bezie poprawka do wtyczki

**Comment by ramicspa** [comment]
forum nie jest najlepsze do jako zrodlo dla wtyczki ... ale cos tam wyszlo

**Comment by kashkash18** [comment]
Żniw się wysypalo
