### ISSUE TITLE
Live polish tv a przesuniecie czasowe o 7 h do tylu

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#560]
moze troche przymule ale chyba sam nie dam rady,
poprzestawialem wszystko na live polish tv i na simple client o 7h do tylu ale i tak oddtwarza mi w czasie rzeczywistym z Polski ale co ciekawe w guide pokazuje mi informacie o programie przesunieta o 7h do tylu w moim terazniejszym czasie,moze to troche chaotycznie opisalem ale moze ktos sie polapie o co mi chodzi,
Jakies wskazowki gdzie popelnilem blad?

**Comment by Janasek** [comment]
czasem należy wyczyścić  
* Kodi/system/telewizja/ogólne/wyczyść dane
* Kodi/system/telewizja/przewodnik/wyczyść dane

**Comment by tomasiek** [comment]
Z tym pierwszym byłbym ostrożny - jak ma się posortowane kanały wg swojego uznania to na bank wszystko pójdzie w niebyt.
Ale to drugie na 99% powinno pomóc.
Trzeba też sprawdzić czy prawidłowo jest ustawiona strefa czasowa i czas w samym kodi

**Comment by wisiann** [comment]
sprubuje  wyczyscic,dzieki @janasek

@tomasiek,
nie wiedzialem ze w kodi tez trzeba przestawic czas?
to znaczy mam ustawic na polski czas?
i gdzie tego szukac ..jak bys mial chwile podpowiedziec

**Comment by koladka** [comment]
Znowu wtyczki z telewizja niedzialaja czekamy na poprawki

**Comment by ramicspa** [comment]
@koladka z czym konkretnie jest problem ... wiecej szczegolow podawaj

**Comment by wisiann** [comment]
ja tez mam problem, 
po utwozeniu listy m3u,
i update Pvr simple client, 
wiekszosc programow nie odpala a te ktore "tak" to sie zacinaja,

**Comment by wisiann** [comment]
Ramic jestes tam? any clues?

**Comment by ramicspa** [comment]
jak z listy nie odtwarza to moze byc:
1. problem z PRV (to samo zrodlo co jest uzywane we wtyczce jest zapisywane do listy)
2. zywotnosc linku jest ograniczona. przy kazej probie otwarcia terzeba na nowo link wygenerowac - wiec takie zrodlo nie jest najlepsze by dodawac do listy m3u - ale z poziomu wtyczki bedzie chodzic

**Comment by wisiann** [comment]
ok, dzieki
