### ISSUE TITLE
problem z livepolishtv na TV Sony z Androidem

### ISSUE THREAD

**Issue by oskag33** [ramicspa/kodi#564]
Witam,
Panowie jest jakiś problem z livepolishtv na Androidzie w TV SONY
przy próbie włączenia niektórych kanałów(np.TVN Turbo) wyskakuje :

"Nieudane odtwarzanie jednej lub więcej pozycji.
 Więcej informacji na ten temat znajdziesz w pliku dziennika diagnostycznego"

Sprawdziłem w logu i jest napisane:

Warning: Createloader - unsupported protocol(http)

in http://tele-wizja.com/logon/canal.gif

PS. Podobno zmieniło sie teraz tele-wizja.com to tele-wizja.is,

Da się coś z tym zrobic? :)

Pozdrawiam

**Comment by ramicspa** [comment]
dobrze ze dales znac ... roblem aktualizaje wtyczki i zostalo juz to poprawione.

**Comment by oskag33** [comment]
Cześć,
np.TVN Turbo
Działa w zakladce LiveTV:wizja.tv
a nie działa jak wcześniej w LiveTV:darmowa tv

Pozdr.

**Comment by tomasiek** [comment]
To normalne - raz działa tu, raz tam, a raz gdzie indziej - jeśli źródło nie udostępnia w danym momencie danego kanału to nie będzie działać. Może być nawet tak że na stronie będzie działać, a 3 sekundy później już nie będzie działać w kodi... mała loteria...

**Comment by oskag33** [comment]
Rozumiem, ale czy nie jest jeszcze jakiś problem ze  tele-wizja.com to tele-wizja.is? Na tym kanale darmowe tv?

Pozdrawiam
