### ISSUE TITLE
cda-hd

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#566]
witam,
nie przeskakuje  na nastepne strony przy wybieraniu filmow,,
trzeba zucic okiem w wolnej chwili

**Comment by kopernik1983** [comment]
po aktualizacji wszedzie pusto. katagerie, premiery etc...

**Comment by ramicspa** [comment]
zmienila sie w nocy nazwa domeny ... poszla juz aktualizacja

**Comment by wisiann** [comment]
dzieki

**Comment by miras851** [comment]
A mi dalej nie działa cda HD może wiesz gdzie jest problem ? Wchodzę w wyszukany film i nie ma żadnych sremów (pusto) a jeszcze wczoraj działało :-\
