### ISSUE TITLE
Problem z obrazem

### ISSUE THREAD

**Issue by markozo** [ramicspa/kodi#567]
Sprawa nie dotyczy wtyczek Ramica , ale pomyślałem że dużo tu fachowców od kodi :) więc ostatnio na kodi wyskoczyły mi życzenia a następnie przy próbie wejścia w jakąś wtyczkę wyskoczyła informacja że ta wtyczka nie pracuje z tym buildem i należy zresetować kodi. Nie miałem builda no ale wyłączyłem i próbowałem włączyć niestety kodi już nie ruszyło. Wiec odinstalowałem i wrzuciłem nowe kodi . Poinstalowałem wszystkie wtyczki i miód malina, ALE niestety nie wiem czemu obraz czasem jakbym płynął w zwolnionym tempie. Może ktoś coś miał podobnie i sobie poradził bo cholernie wkurza to skakanie . Aha wszystko to dotyczy kodi na boxie zoomtak T8H

**Comment by kopernik1983** [comment]
sprobuj wylaczyc w ustawieniach /odtwarzacz/wideo/i po prawej odszukaj zezwalaj na sprzetowa akceleracje mediacodec ( powierzchniowy ) ewentualnie mediacodec ale tego drugie moze nie bedziesz musial. trzeba sprawdzic. powinno pomoc.

**Comment by markozo** [comment]
Tu już ustawiałem tą akcelerację sprzętową na różne sposoby i dalej coś przycina, ale dzięki za pomoc.

**Comment by kopernik1983** [comment]
to kombinuj z netem. innej mozliwosci chyba raczej nie ma. mam zoomtaka z rodziny t8 konkretnie x i niczym sie ze soba w zasadzie nie roznia poza pojemnoscia pamieci wewnetrznej. pa sama grafika , procesor, itd. ustawianie kodi ograniczalo sie u mnie tylko wylaczoniea owej akceleracji.
