### ISSUE TITLE
Kinoiseriale brak zrodel

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#57]
Nie wczytuje listy zrodel przy probie otwarcia filmu

**Comment by ramicspa** [comment]
thx za info. wczytuje liki, tylko akurat jest tam jedno zrodelko schowane za serwisem Vodlock.net ... ktory aktulaniemowi o przeicazeniu serwerow i dostepie tylko dla premium - dlatego ten jeden link sie nie pojawil. Sprawdz jak strona odpowiada.

**Comment by adaski8** [comment]
Nic z tego widze ze wprowadzaja premium i zmiany na stronie. A we wtyczce wyskakuje souruces i puste pole bez linkow
