### ISSUE TITLE
Muzyczny portal

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#574]
Witam, da radę wrzucić portal www.discoarena.pl jak widać nowości są gatunki i ciągle coś nowego dodaja. Jeżeli jest taka możliwość pozdrawiam

**Comment by wisiann** [comment]
czy tam automatycznie .oddwarzaja sie nastepnie teledyski,czy manual?

**Comment by abrus7** [comment]
Odtwarzają się następne teledyski

**Comment by wisiann** [comment]
super!
Ramic klikinij na to "okiem" 

Dzieki!

**Comment by ramicspa** [comment]
mi tez sie podoba ... fajnie zrobiony portal, szkoda ze brak polskich wykonawcow.

**Comment by abrus7** [comment]
Jak pisałem z tym portalem mają wprowadzić w 2018 roku właśnie polskich wykonawców

**Comment by discoarena** [comment]
Dzień dobry,napisał do mnie użytkownik tego portalu abym mógł się wypowiedzieć na temat naszego portalu.
Jesteśmy gotowi do współpracy.
I odpowiadamy od razu na wasze posty:
ramicspa,będą polscy wykonawcy wkrótce.
Codziennie są dodawane nowe albumy,piosenki oraz gatunki.
Wkrótce zostaną dodane takie gatunki jak:
Disco Polo,
Rap Polski,
Pop Polski.
Również w naszym portalu będzie transmitowane LIVE SHOW z YT oraz live radia z całego świata.
Jeżeli macie państwo jakieś pytania,prosimy kierować je na adres email kontakt@discoarena.pl
lub w tym temacie.
Wkrótce zostaną dodane 3 nowe domeny.

**Comment by kashkash18** [comment]
Wtyczka była by z tego zacna :)

**Comment by kopernik1983** [comment]
a no byłaby. Ciekawie portal wygląda i obiecująco.

**Comment by abrus7** [comment]
@ramicspa to jak Twoja decyzja będzie zrobione?

**Comment by abrus7** [comment]
Jak zauważyłem nawet polskie już gatunki wchodzą ładnie się prezentuje

**Comment by ramicspa** [comment]
To dobrze że portal się rozwija. W przyszłym tygodniu będę miał chwilę by się tym zająć.

**Comment by abrus7** [comment]
Działa wtyczka ale nic w katologach nie ma. Strona działa normalnie a kodi jakby katalogów nie widzi. Możesz spojrzeć?

**Comment by wisiann** [comment]
u mnie dziala, 
tylko w pozycji 
-piosenki
-artysci
-albumy 
nic nie ma,

**Comment by abrus7** [comment]
Jutro spojrzę.
Bo tam musisz być zalogowany i to Twoja lista jest tam napisane iż musisz być zalogowany i robisz swoją "playliste"

**Comment by wisiann** [comment]
aha ....teraz rozumiem

**Comment by KML73** [comment]
Niestety strona padła ... wcześniej i tak były problemy z rejestracją a nawet z zalogowaniem się. Także na razie lipa :(

**Comment by abrus7** [comment]
Aktualizacja idzie "WIELKA" i poniedziałek ma działać:)

**Comment by abrus7** [comment]
Zapewne strona będzie działać,ale nie będą wszystkie nowe funkcje działały.

**Comment by abrus7** [comment]
Działa już portal;)

**Comment by KML73** [comment]
Czy macie, taka jak ja problem z rejestracją w tym serwisie ? Sorki za pytanie, które nie dotyczy bezpośrednio wtyczki.

**Comment by abrus7** [comment]
Właściciel serwisu ma dziś wejść i wszystko napisać.

**Comment by abrus7** [comment]
Discoarena,nie może pisać w tym poście to mam przekazać takie coś:

W dniu dzisiejszym powstała nowa domena www.musicstream.pl wkrótce discoarena.pl będzie przekierowywała na musicstream.pl,chcę aby @ramicspa , zrobił aktualizację a potem zrobię przekierowanie.
W dniu dzisiejszym zostało zrobione:
-rejestracja wkrótce zostanie dodana aby można było się logować z poziomu fb,google,twitera.
-dodane Polskie gatunki wkrótce będą aktualizowane oraz nowe gatunki.
-TOP 50 od dziś użytkownicy portalu decydują co będzie w top50 a nie z portalu zewnętrznego.

Co zostanie dodane wkrótce:
-Jeżeli będziecie chcieli posłuchać każdej piosenki z gatunku już nie będziecie musieli wybierać po kolei,wystarczy iż klikniecie "wszystko" i wszystko będzie odtwarzać.

jak będzie coś nowego od niego będę tu dopisywać a kwestie wszystkiego prosi o kontakt na email: kontakt@discoarena.pl
@KML73 - napisz do niego na email lub sprawdz teraz na nowej stronie.

**Comment by KML73** [comment]
@abrus7 
Tak teraz działa logowanie zarówno na nowej jak i starej domenie, dzięki @arbus7 za zaangażowanie ;)

**Comment by markozo** [comment]
Działa komuś tą wtyczka na kodi? u mnie otwiera foldery widzę utwory ale nic się nie da odtworzyć.

**Comment by abrus7** [comment]
U mnie działają niektóre albumy na stronie działają to zapewne musi ramicspa aktualizacje zrobić na musicstream.pl tylko jak będą nowe albumy to ciekawe czy będą działać czy ramic musi aktualizować

**Comment by markozo** [comment]
Na stronie właśnie większość działa jedynie na kodi mi nie śmiga i w musichub  też nic nie śmiga.

**Comment by abrus7** [comment]
@ramicspa w sumie jest tam aktualizacja wtyczek i nowe gatunki,ale czemu nie pobiera playlist? Da się coś robić? Bo co chwilę aktualizację byś robił a tak by aktualizowało się automatycznie,że stroną dasz radę?

**Comment by abrus7** [comment]
Została dodana opcja rejestracji przez twittera wkrótce będzie możliwość rejestracji przez google oraz Facebooka.
Zostały dodane Polscy artyści i codziennie nowe aktualizacje!
