### ISSUE TITLE
Filmwebboster 2.3, programy nie działają.

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#577]
System: Libreelec 8.2.2.2
Kodi 17.6
Repo aktualne.
We wtyczce filmwebboster nie działa nowy dział "ProgramyTV" - ni się nie pokazuje...
logi pełne:
https://pastebin.com/WCPHEY9s
Pod windowsem wydawało mi się że coś tam się pojawiło, ale teraz nie mam jak sprawdzić.
Pod archlinuxem działa.
Sieć ta sama, zestaw dodatków praktycznie ten sam, na archlinuxie profil na mega zawalony (i nic nie wywala...)

**Comment by frijerz** [comment]
U mnie pod Win10 kodi 17.6 nie dzialaja ani filmy ani programy.

**Comment by ramicspa** [comment]
Ciekawe bo ja nie widzę problemu. Baza filmów i programów działa jak trzeba ... Następnym razem wydłużenie timeout strony

**Comment by tomasiek** [comment]
Metodą prób i błędów, pomimo wcześniej ustawień domyślnych w sortowaniu itp itd, dopiero ich przywrócenie do wartości domyślnych spowodowało że programy działają.

**Comment by frijerz** [comment]
Dziwne, mam Filmwebbooster 2.3 kodi 17.6 i nie moge odpalic zadnego filmu, zadnego programu. Ustawienia domyslne. 
wyskakuje taki komunikat: [http://prntscr.com/hvbkhz](url)

**Comment by tomasiek** [comment]
Ale jednak coś jest nie tak, @ramicspa zerknij na to. Noby lista programów jest... ale nie odtwarza. Raz na jakiś czas się uda... ale to praktycznie wyjątki...
https://pastebin.com/A5FPVijq - logi z grand tour

**Comment by ramicspa** [comment]
ok dziki za info ... powinno juz dzialac jak trzeba. poszla aktualizacja wtyczki

**Comment by tomasiek** [comment]
Ok. Thx.
Ps. To info z readme po angielsku (disclaimer) daj też w pl. Nie będą tak stękać.

**Comment by frijerz** [comment]
Dlaczego nie aktualizuje sie automatycznie? Mimo, ze mam wlaczoną automatyczną aktualizację

**Comment by ramicspa** [comment]
Kodi chyba raz na dobę sprawdza czy w repozytoriach jest coś nowego. Żeby to przyspieszyć to albo uruchom ponownie kodi albo wymuś odświeżenie repozytoriów

**Comment by frijerz** [comment]
Odswierzalem, odinstalowalem wtyczke, ponownie zainstalowalem repo, i nadal jest tylko 2.3.
Poczekam jeszcze

**Comment by ramicspa** [comment]
Restart kodi zawsze pomaga. Zawartość repozytoriów się odświeża

**Comment by tomasiek** [comment]
U mnie działa już bez problemów.

**Comment by frijerz** [comment]
W Programy brakuje źródeł. Ani Kuchenne rewolucje, ani Twoja twarz... ani Voice of Poland, Mam talent nie dzialaja. Wczytuja sie odcinki ale brak źródeł. Jedynie Azja expres udalo mi sie uruchomic :( Ale to chyba nie wina wtyczki.
