### ISSUE TITLE
TVP.pl VOD

### ISSUE THREAD

**Issue by farbenh** [ramicspa/kodi#578]
Witam,

VOD.tvp.pl - prawdopodobnie problem ze zbyt duża liczba odcinków dla "Wspaniałe stulecie", brakuje wszystkich. W aplikacji TVP vod są od 1. Jakby się dało zerknąć w czym problem byłbym wdzięczny bo żona zawraca głowę ;)

Pozdrawiam ;)

**Comment by farbenh** [comment]
Przy okazji w ustawieniach w opcji wyboru jakości jest literówka: Najepsza :)

**Comment by wkdk8519** [comment]
Przyłączam się do prośby :-)

Moja luba, też chętnie obejrzałaby sobie od pierwszego odcinka na "dużym ekranie" :)

Pozdrawiam,

**Comment by ramicspa** [comment]
@farbenh zgadza sie ... powinno sie dac to naprawic albo dodac stronicowanie

**Comment by farbenh** [comment]
Kłaniam się zatem nisko ;)

**Comment by farbenh** [comment]
Poprawione, wygląda na to że ładują się już wszystkie odcinki na jednej stronie, gracias :)
