### ISSUE TITLE
LivePolishTV

### ISSUE THREAD

**Issue by masterdzikus** [ramicspa/kodi#58]
Ostatnio korzystam czasem z tej wtyczki. Przykładowo z serwera iklubu smigało mi wszystko. Wymagań specjalnych nie mam i zwykle oglądam discovery, ale testowałem prawie wszystko... W ostatnich dniach nie działał link 1 Discovery, a działał drugi. A od wczoraj nic... Ogólnie mogę wybrać inny serwis, ale problem pojawia się na większości kanałów i na różnych serwerach... Niby się wczytuje, ale się nic później nie dzieje. 
Na androidzie mam wersje kodi 16, na PC też taką miałem, ale po przetestowaniu i zrobieniu listy wtyczek jakie mnie interesują, zainstalowałem 17. No i nie działa jak powinno. 

Nie wiem czy będzie to miało coś z tym wspólnego, ale znajomy używający całkowicie innych wtyczek oferujacych oglądanie kanałów z całego świata, dziś powiedział mi, że u niego praktycznie żaden kanał nie działa od jakiś 3 dni... Może to wina kodi?

Z góry serdecznie dziękuje za pomoc.

**Comment by ramicspa** [comment]
Witam, nie wydaje mi sie ze to problem z kodim. Zrodla z iklub.net nie sa stabilne i czesto znikaja. Najlepiej jest sprawdzic na stronie - jak tam dziala a w kodim nie to dajesz znac i poprawiam wtyczke. Serwery ktore udostepniaja zrodla czesto zmieniaja jakies ustawienia albo dodaja zabezpiecznia i scraper przestaje dzialac poprawnie. We wtycze livePolishTv sa tylko zrodla darmowe i ich jakosc oraz dostepnosc nie jest gwarantowana - wszystko zalezy od stron ktore je udostepniaja.
Nie testowalem tej wtyczki na kodi17 wiec nie wiem jak tam dziala. Niebawem pojawi sie duzy update do tego pluginu - poprawiajac wydajnosc i efektywnosc - przy okazji bedzie na pewno kompatybilny z K17.

Rozne wytczki moga kozystac z tych samych zrodel albo serwerow streamingowych i jak taki padnie to nigdzie nie bedzie dzialac.

**Comment by masterdzikus** [comment]
Wszedłem właśnie  na stronę, pierwszy link niedostępny, zapasowy player chodzi. Na Kodim (17) żaden nie działa, na 16 zaczął działać drugi. Także masz rację, padają i się wznawiają. Fajnie gdyby można wszystkie te strony (jeżeli ktoś wybierze taką chęć) scalić w jedno i zrobić jako dodatkowe linki. Lub jeżeli to możliwe by automatycznie sprawdzało i wybierało działający link. Choć wtedy niektóre auto linki mogły by wkurzać poprzez wolne połączenie i chęć zmiany byłaby nie możliwa...

PS. Gdy włączam cokolwiek na K17 to pojawiają się na ułamek sekundy 2 okienka DOSowskie i znikają. Jeżeli dobrze w ten ułamek s dowidziałem to .ico tych okienek to te nakręcane pudełko.

Dziękuje za szybką odpowiedź, 
Pozdrawiam.

Jeżeli potrzebował byś pomocy przy jakiś grafikach, lub prostych stronach HTML czym CMS'ach, bo raczej do programowania się nie nadaje to daj znać :) Czasu mam nie dużo, ale może akurat.

**Comment by ramicspa** [comment]
Przy wiekszej zmianie wtyczki (wpelni kompatybilnej z K17) zobaczy czy da sie jakos zintegrowac rozne serwisy by latwiej bylo znalesc dzialajacy link. Sporym problemem jest fakt ze link moze zostac znaleziony ale to czy dziala okazuje dopiero na koncu jak kodi probuje go otworzyc.
Dzieki za oferte pomocy. jakby co dam znac.

**Comment by kashkash18** [comment]
Sport 365 padło

**Comment by ramicspa** [comment]
dzieki za info, naprawione

**Comment by kashkash18** [comment]
Nadal nie działa

**Comment by ramicspa** [comment]
faktycznie znow cos zmienilie .... poszedl update, ciekawe jak dlugo wytrzyma

**Comment by kashkash18** [comment]
Heheh no i znów nie działa ;)

**Comment by kashkash18** [comment]
Teraz śmiga :) Dzięki wielkie

**Comment by kashkash18** [comment]
Z sport365live znow coś się dzieje. Streme się odpalaja ale po 2 minutach je wywala

**Comment by ramicspa** [comment]
moze jakies problemy z serwerem streamingowym ... niewiele tu moge poradzic

**Comment by ebot2007** [comment]
Witam , iklub net nie mozna zrobic listy m3u, jest jakis blad . psa tv padlo , pozdrawiam

**Comment by ebot2007** [comment]
witam ponownie po update do v 2.0 niby zaczyna dzialc, robimy liste pvr lecz staje na 56/118 
moze jakis pomysl , sprawdzalem na android i win

**Comment by ramicspa** [comment]
serwis iklub jest dosc specyficzny ... zeby wyciagnac link trzeba kila stron "odwiedzic" wiec przy tak duzej ilosci kanalow i zapytan serwer moze odmowic odpowiedzi. wylaczylem iklub z listy m3u

**Comment by muc001** [comment]
Hi,
i dont speek polish, so i try to find support in english. Using the addon livepolishtv and within "you.tv" there is the following message. Any idea what to do? I use a firestick with kodi.
thanks and best regards
chris

![1477477659478](https://cloud.githubusercontent.com/assets/23074990/19722578/a627c51c-9b77-11e6-977d-64312e33e19c.jpg)

**Comment by masterdzikus** [comment]
There stays that you need to make m3u list and use PVR client to watch without limits "when the sources will be again available". Its mostly alert about limits. But you cannot watch it at all or what?

**Comment by masterdzikus** [comment]
Try then this option with PVR. You can do it with last position in addon menu. I cannot check it now ... I know that the text font is blue.

**Comment by muc001** [comment]
![1477481800449](https://cloud.githubusercontent.com/assets/23074990/19724632/9f455c64-9b81-11e6-9268-abf9d4979761.jpg)
Not working. List empty...

**Comment by masterdzikus** [comment]
With that problem you need to wait for answer from ramicspa. Or maybe someone else can help you. You can also search for tutorials how to do it in other way.  Or just try other server with tv. I know that is the best to have all working stuff in one place but yeah...

**Comment by muc001** [comment]
Thanks for your assistance!!!

**Comment by ramicspa** [comment]
Yoy tv allows only limited access (~3h or so and/or with a few channels in a row) without having a premium account. It looks like you cannot get anything right now from the server – you have to wait a little bit longer. Creating m3u list is a way to cache all the links when you have a limited access to the server. I would suggest to wait till you are able to open anything (from kodi or directly form a website). Do not waist your limited time on watching only but immediately create m3u list to buffer all the sources. In the meantime try to use other source of free live tv.

**Comment by masterdzikus** [comment]
Try then this option with PVR. You can do it with last position in addon
menu. I cannot check it now... I know that the text font is blue.

26.10.2016 1:17 PM "muc001" <notifications@github.com> napisał(a):

**Comment by muc001** [comment]
Works now with m3u! THX!!!

**Comment by wacekrnyna** [comment]
Witam. Mam pytanie. Da się zrobić wtyczkę do TELEWIZJADY, ale tej orginalnej (telewizjada.net), tak żeby po wykupieniu w niej playera można było ją oglądać przez Twoją wtyczkę ,a nie na ich stronie?

**Comment by ramicspa** [comment]
witam, powinno dac rade ale nie jestem w stanie tego potwierdzic bo nie znam tego playera. tez sie troche rozczarowalem ze nie zdrobili swojego rozwiazania tylko placa tereaz arabom

**Comment by wacekrnyna** [comment]
Ramicspa spróbujesz zrobić taki dodatek do Twojej wtyczki? Było by super :)

**Comment by ramicspa** [comment]
nie planuje robic dodatkow do platnych serwisow.
