### ISSUE TITLE
Fałszywa detekcja builda

### ISSUE THREAD

**Issue by Eva850** [ramicspa/kodi#581]
Witam, po ostatniej aktualizacji wszytkie wtyczki z tego repozytorium informują że używam builda. To nieprawda, NIGDY NIE UŻYWAŁEM ŻADNEGO BUILDA. Poza tym spowodowało to usunięcie wielu programów z mojej partycji systemowej. Rozumiem, że należy się zabezpieczać przed kradzieżą wtyczek ale taka metoda to szczyt chamstwa, gdyż to działa na niekorzyść użytkowników. Prosiłbym o przemyślenie tej sprawy. Czy naprawdę nie wystarcza kod i informacja o "Januszach biznesu"?

**Comment by tomasiek** [comment]
Używasz może autocleanera z ares wizard? Jeśli tak, to on jest przyczyną. Albo jakiś inny wizard. Często jest tak, niby nie ma builda, zaś jest "fork" kodi, taki jak wookie kodi - który w rzeczywistości jest zwykłym spmc + narzędzia do ściągnięcia buildu.

Tu masz listę tego co nam się udało "wyłapać"
https://github.com/ramicspa/kodi/issues/570#issuecomment-354752336

A przemyślenie tej sprawy? To repo ramica. Jego zasady. Albo je akceptujemy albo nie...  Przekonać się go nie da.

**Comment by Eva850** [comment]
Nie, nie używałem żadnych wizardów, czyste kodi i kilka polskich wtyczek, superrepo, i collosus repo.
Teraz używam kodi w Sandboxie więc może on sobie usuwać do woli

**Comment by tomasiek** [comment]
Obstawiam coś z super repo.. ale co? Sami tą listę tworzymy... Podaj listę
wtyczek które masz/miałeś

05.01.2018 5:14 PM "Eva850" <notifications@github.com> napisał(a):

**Comment by Eva850** [comment]
SD-XBMC telewizja Polska
Covenant
Z superrepo była ipla
smash repo ale NIE WIZARD, tylko repozytorium
kodiver webcamera sterams
YouTube
vimeo
dailymotion
fanfilm mrknow

Tak swoją drogą to na ile bezpicznie jest używać wtyczek od Ramica skoro dzieją sie takie dziwne rzeczy? 
"o dziś ma się pojawić repo wolne od tych problemów" Ile w tym prawdy?

**Comment by tomasiek** [comment]
No to obstawiam smash repo...
Co do bezpieczeństwa. Przeczytaj readme. Została zaktualizowane i w sumie każdy korzysta na własną odpowiedzialność.
A o repo wolnym od problemów słyszymy od ponad roku. I nic na razie nie ma co by działało...

**Comment by Eva850** [comment]
Swoją drogą wypadałoby wspomnieć w readme jakie są efekty uboczne tych wtyczek gdy znajdą one niepożądane wtyczki w kodi. Dzięki za informację, chyba dla bezpieczeństwa zrezygnuję z tych wtyczek

**Comment by tomasiek** [comment]
Ale taką informację masz przy włączaniu w kodi instalacji z nieznanych źródeł. Wtyczki nie są obowiązkowe... Można z nich zrezygnować.

**Comment by Eva850** [comment]
Oczywiście, rozumiem że ponoszę za to odpowiedzialność ale to trochę zwalanie winy na użytkownika. Raczej ponosi on winę za błędy we wtyczkach a nie celowe niszczenie danych. Trudno, dziękuję za pomoc. Może ktoś mądry skopiuje wasze wtyczki i usunie z nich "zbędne elementy". Temat uważam za wyjaśniony, zamykam sprawę

**Comment by Piotr123456** [comment]
tomasiek proszę cię...Zaczynacie nawalać na ludzi ,że to ich wina ,bo używali wtyczek ,które dajecie w ogólnym ,a oni potwierdzili ,że robią to na swoją odpowiedzialność.Co z wami się dzieje?Chcecie prywatne repo z wtyczkami to je zablokujcie dla innych a nie dajecie konia trojańskiego i jeszcze twierdzicie ,że to wina użytkowników ,że w ogóle zechcieli je zainstalować...Chryste panie ! To wygląda tak jakbyś dziecku dał polizać cukierka a potem zajumał mu kamasze .O co w tym wszystkim chodzi , bo z lekka nie rozumiem??!

**Comment by tomasiek** [comment]
Źle mnie zrozumiałeś. Nie mówię że to jest wina użytkownika. Próbuje tylko uświadomić że nie powinno się kodi, jako maszyny do rozrywki, używać na sprzęcie służącym do pracy, z newralgicznymi danymi. Próbuję im wytłumaczyć, a może nawet i nauczyć żeby nie walili w ok na każdym komunikacie, tylko nauczyli się czytać ze zrozumieniem. I o to mi chodzi w przywoływaniu komunikatu o instalacji z nie znanych źródeł. Absolutnie nie są winni utraty danych, ale nie mogą też powiedzieć że nie byli świadomi ryzyka. Komunikaty były (chociaż z tego co wiem, niektórzy twórcy buildów je poukrywali, nie wyłączając jednocześnie funkcji autodestrukcji).
I nie, nie popieram metody kasowania danych zwykłym użytkownikom, chociaż uważam że twórcom buildów przydaje się lewatywa. Ale niestety, autor wtyczki uznał że używanie buildu tak się kończy... Nie mamy na to wpływu. Jedyna władną osoba jest tutaj ramicspa.
A co do wtyczek wolnych od zbędnych elementów. Jak już mówiłem ponoć powstały, ponoć jest szturm na nie... Ale jakoś poza zamkniętymi grupami na FB twórców buildów tego nie widać.
