### ISSUE TITLE
eska music

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#588]
jest mozliwosc doklejenia do jakiejs wtyczki,
-eska party tv
-eska best music tv 
mysle ze to dobra opcja,fajnie graja i leci automatycznie przez caly czas,

**Comment by abrus7** [comment]
http://www.eskago.pl/radio
Ja bym dał wszystko z tego :)

**Comment by wisiann** [comment]
jak bu byla mozliwosc to by bylo fajnie, 
ale dla mnie chodzi szczegolnie o programy tv
