### ISSUE TITLE
Polsatsport.pl

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#59]
Jak tak świetnie idzie udoskonalanie wtyczki Ekstraklasa, to może warto dodać materiały wideo z http://www.polsatsport.pl/wideo/ Bardzo dużo ciekawych materiałów o piłce i nie tylko.

**Comment by ramicspa** [comment]
Nie powinno byz wiekszych problemow z wyciagnieciem czegos z polsatsport. Update pojawi sie niebwem

**Comment by rafciu27** [comment]
Wow. Wielkie dzięki. Aż sam nie wiedziałem, że to takie rozległe ;)

**Comment by kashkash18** [comment]
To może jeszcze z 
www.laczynaspilka.pl

**Comment by rafciu27** [comment]
Albo www.footroll.pl

**Comment by kashkash18** [comment]
Wejdzie coś z proponowanych serwisów ??

**Comment by ramicspa** [comment]
powinno cos wyjsc ... a co konretnie interesuje z laczynaspilka.pl?

**Comment by kashkash18** [comment]
Najlepiej wszystko ci związane z Piłką nożna , jest tam sporo materiałów o narodowej i innych polskich ligach rozrgrywkowych

**Comment by kashkash18** [comment]
A coś z tego 

www.vipleague.me

**Comment by ramicspa** [comment]
a vipleague nie ma potrzeby robic dodatku bo juz takie sa.

**Comment by kashkash18** [comment]
A jesteś w stanie podać namiar ??

**Comment by ramicspa** [comment]
wielki brat 'google' mowi np to:
https://forums.tvaddons.ag/live-sports-on-kodi/49600-vipleague-kodi.html

**Comment by kashkash18** [comment]
Po kilku zapytaniach wujka "Google" stwierdzam iż żadna z wtyczek nie działa :/ Ale chyba coś jest nie tak bo kiedyś był dostęp do Vipleague z Castaway ale już go nie ma :) Szkoda bo dużo tam sportu a Sport365Live ma jakiś problem bi po ok 2 minutach wywala strema
