### ISSUE TITLE
TBN Polska VOD

### ISSUE THREAD

**Issue by Jeremishal** [ramicspa/kodi#590]
Dzień dobry.
Czy istnieje możliwość stworzenia wtyczki do materiałów zawartych na tej stronie https://www.tbnpolska.tv/on-demand ? Już tak się przyzwyczaiłem do Kodi, że oglądanie materiałów w przeglądarkach stało się toporne i uciążliwe. 

Dziękuję za odpowiedź.

**Comment by ramicspa** [comment]
witam, wtyczki wylacznie do darmowych stron.
