### ISSUE TITLE
yoy tv OUT

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#594]
Policjanci z KWP w Lublinie zatrzymali trzech mężczyzn, którym przedstawiono zarzuty nielegalnego rozpowszechniania sygnału płatnych telewizji cyfrowych. W ofercie platformy Yoy.tv było ponad 160 kanałów telewizyjnych.
http://www.dziennikwschodni.pl/lublin/telewizja-przez-internet-w-ofercie-bylo-160-kanalow-teraz-sa-zatrzymania,n,1000211827.html

Hmm, i co teraz :D

**Comment by frijerz** [comment]
Nic, kolejne "firmy" ich zastapią
