### ISSUE TITLE
Alletube.tv

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#60]
Brak możliwosci przejscia na następną stronę z filmami na Alletube.tv - wyświetla się tylko pierwsza strona z filmami po kliknięciu na następną stronę wywala błąd

**Comment by ramicspa** [comment]
dzieki za info, naprawione

**Comment by Seico** [comment]
Teraz przechodzi na następną stronę ale za każdym razem wyskakuje okienko z pytaniem czy  chcę przejść i dopiero przechodzi , można to poprawić :) ?

**Comment by ramicspa** [comment]
faktycznie to okienko jest zbedne ... juz poprawione

**Comment by Seico** [comment]
ok , dzieki bardzo :)
