### ISSUE TITLE
Filmwebboster sortowanie w bazie filmów nie działa

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#605]
Wtyczka Filmwebboster -> Baza filmów/Seriali/Programów -> ustawiamy "gatunek" np. Komedia i "kraj" Czechy -> Filmy - i pokazuje top topów a nie wybrany zakres
W logach nic nie widać.

**Comment by ramicspa** [comment]
nowy template strony pojawil sie na poczatku roku i pare rzeczy wymaga poprawki

**Comment by xxcriticxx** [comment]
for the future

http://filmwebbooster.pl/viewtopic.php?f=11&t=16

**Comment by xxcriticxx** [comment]
Aktualizacja 1.7
Cytuj
Post  autor: admin » wt sty 23, 2018 4:23 pm

Aktualizacja 1.7 wprowadza sporo zmian. Przede wszystkim modyfikuje większość odtwarzaczy tak aby te nie wyświetlały reklam i innych niechcianych skryptów. W związku z tym wtyczka potrzebuje nowych uprawnień. Mówiąc wprost - musi mieć uprawnienia do uruchamiania na domenach, które hostują pliki, tj Openload, Vidoza, Streamango itp. 

Lista zmian:

- Możliwość oglądania bez reklam (w serwisie filmdb.pl + bonusowo w serwisie seriale.co)
- Łatwe pobieranie bezpośrednio z playera. (w serwisie filmdb.pl)
- Rozpoznawanie większości niedziałających linków i oznaczanie ich (w serwisie filmdb.pl)
- Rezygnacja z prezentowania informacji na temat obejrzanych odcinków w serwisie Filmweb.
- Po kliknięciu lewym przyciskiem myszy na ikonę FilmwebBooster (w prawym górnym rogu przeglądarki) otwiera się okienko z informacjami.

**Comment by tomasiek** [comment]
@xxcriticxx miejmy nadzieję że współpraca z ramicspa dalej będzie... bo dla mnie to najlepsza wtyczka na świecie...
