### ISSUE TITLE
Prośba

### ISSUE THREAD

**Issue by portobenn** [ramicspa/kodi#608]
Dzień dobry
Czy można prosić o dodanie https://wrealu24.tv/

**Comment by Harrako** [comment]
Przecież ta telewizja to rosyjska tuba propagandowa. Celem tej "tv" jest wzbudzanie nienawiści do innych narodów.  A konsekwencja jest jedna: Polak za żadną granicą nie znajdzie przyjaciół. Lepiej nie szerzyć za darmo takiej propagandy (za wynagrodzeniem też nie :). TV jest sponsorowana przez "anonimowych" darczyńców, a w praktyce z Moskwy. Bo o Moskwie nikt tam źle nie powie.

**Comment by Janasek** [comment]
Amen

**Comment by ramicspa** [comment]
kazda stacja jest przez kogos kontrolowana. Jak nie z Torunia to z nowogrodzkiej, albo Rosja albo Niemcy.

**Comment by portobenn** [comment]
@ramicspa czyli jest szansa?
Koledzy czy obowiazkowe jest instalowanie każdego dodatku?
Czy jesteście zmuszani do ogladania?
Czy jest jak pisze @Harrako nie wiem i malo mnie to obchodzi.

**Comment by tomasiek** [comment]
To ja tylko przypomnę że @ramicspa stwierdził że dla telewizji z Torunia nie ma miejsca...

**Comment by ramicspa** [comment]
@portobenn zapomialem wspomiec ze jest dostepna w livepolishtv. @Harrako jak taka propagadana to nie zasluguje na wlasna wtyczke.
mysle ze na tym mozemy zakonczyc ten temat.
