### ISSUE TITLE
Zalukaj

### ISSUE THREAD

**Issue by Cinek77** [ramicspa/kodi#61]
Witaj Ramicspa.
Mam do Ciebie ogromna prosbe.
Mogłbyś dodać do swojej wtyczki plugin https://zalukaj.com z możliwością logowania?
W dwóch wtyczkach w ktorych jest ten dodatek niestety nie dziala poprawnie.

Oraz czy da sie z tej strony zrobic dodatek ?
http://filmy.to/

Pozdrawiam.

Ps. Znajomy prosil by Cie poinformowac ze Yoy Tv od kilku dni nie chodzi dobrze.

**Comment by ramicspa** [comment]
Witaj, z obu serwisow da sie cos zrobic.
poprawie najpierw polishtv a potem kolejne wytczky sie pojawia

**Comment by Cinek77** [comment]
Super i dziekuje :+1: )

**Comment by ramicspa** [comment]
zalukaj do logowania wymaga protokolu ktory nie jest wspierany przez pytona w K16. to jest glownym powodem dlaczego inne wtyczki nie dzialaja poprawnie. trzeba poczekac jak wyjdzie K17
mozna to obejsc ale z tego co ostatnio widzialem serwery zalukaj sa bardzo przeciazone i nie idzie nic z tym zrobic

**Comment by Cinek77** [comment]
Rozumie Ramicspa i dzieki bardzo za sprawdzenie. Poczekam az wyjdzie K17.
Pozdro
