### ISSUE TITLE
Livepolishtv

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#62]
Przy aktualizacji do wersji 2.0 nieudana aktualizacja.

**Comment by ramicspa** [comment]
Powinno działać.  Testowane na różnych systemach. Załącz log aktualizacji

**Comment by ramicspa** [comment]
Wszysko działa jak trzeba. Testowane na różnych systemach. Załącz log aktualizacji jak jest problem.

**Comment by adaski8** [comment]
Kodi 16.1 instalowane na swiezo i z repo instalacja nieudana

**Comment by ramicspa** [comment]
Sprawdz log w czym problem

**Comment by adaski8** [comment]
2 T:1775726256   ERROR: CAddonInstallJob[plugin.video.LivePolishTV]: could not read addon description of special://home/addons/plugin.video.LivePolishTV
21:47:27 T:1719962968   ERROR: Previous line repeats 1 times.
21:47:27 T:1719962968   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting zip://special%3a%2f%2fhome%2faddons%2fpackages%2fplugin.video.seansik.nl-1.0.zip/
21:47:27 T:1719962968   ERROR: CAddonInstallJob[plugin.video.seansik.nl]: invalid package special://home/addons/packages/plugin.video.seansik.nl-1.0.zip
21:50:53 T:1631777888  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 960x540 @ 58.12 - Full Screen
21:50:53 T:1631777888  NOTICE: GL_VENDOR = ARM
21:50:53 T:1631777888  NOTICE: GL_RENDERER = Mali-400 MP
21:50:53 T:1631777888  NOTICE: GL_VERSION = OpenGL ES 2.0
21:50:53 T:1631777888  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
21:50:53 T:1631777888  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
21:51:02 T:2069514720   ERROR: CAddonInstallJob[plugin.video.LivePolishTV]: could not read addon description of special://home/addons/plugin.video.LivePolishTV
21:52:48 T:2068403224 WARNING: Attempt to use invalid handle -1
21:52:51 T:1779233160 WARNING: Previous line repeats 2 times.
21:52:51 T:1779233160   ERROR: Unable to find plugin
21:52:51 T:1631777888   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://
21:52:51 T:1631777888   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
21:54:04 T:2078537296 WARNING: Attempt to use invalid handle -1
21:54:31 T:1631777888 WARNING: Previous line repeats 5 times.
21:54:31 T:1631777888  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 960x540 @ 58.12 - Full Screen
21:54:31 T:1631777888  NOTICE: GL_VENDOR = ARM
21:54:31 T:1631777888  NOTICE: GL_RENDERER = Mali-400 MP
21:54:31 T:1631777888  NOTICE: GL_VERSION = OpenGL ES 2.0
21:54:31 T:1631777888  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
21:54:31 T:1631777888  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
21:55:36 T:1631777888  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 960x540 @ 58.12 - Full Screen
21:55:36 T:1631777888  NOTICE: GL_VENDOR = ARM
21:55:36 T:1631777888  NOTICE: GL_RENDERER = Mali-400 MP
21:55:36 T:1631777888  NOTICE: GL_VERSION = OpenGL ES 2.0
21:55:36 T:1631777888  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
21:55:36 T:1631777888  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
Download as text

**Comment by ramicspa** [comment]
ten fragment nie jest zawiera informacji z instalacji. Wydaje mi sie ze plik zip sie sciagnal z bledem i to jest problemem. z loga widze ze nietylko z tym pluginem jest problem ale rowniez z seansik
> 21:47:27 T:1719962968 ERROR: CAddonInstallJob[plugin.video.seansik.nl]: invalid package special://home/addons/packages/plugin.video.seansik.nl-1.0.zip

nowa instalacja na androidzie nie zawsze usuwa poprzednie ustawienia.

Jak to nie pomoze sciagnij plugin recznie https://github.com/ramicspa/kodi/raw/master/zips/plugin.video.LivePolishTV/plugin.video.LivePolishTV-2.0.0.zip
i wybierz opcje "zainstaluj z zip"

**Comment by adaski8** [comment]
Ok. Dzieki pomoglo
