### ISSUE TITLE
serial polski blondynka,

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#621]
wiem ,wiem glupi topic,
ale zona nie daje mi zyc,
oglądneła gdzies jeden odcinek Blondyki i chce teraz caly serial ogladnac,
poszperalem troche we wtyczkach Ramica ale nie moge go znalesc?
jakas pomoc by mi sie przydala,

dzieki!!

**Comment by ramicspa** [comment]
W tvp VOD jest w serialach obyczajowych

**Comment by wisiann** [comment]
no tak,
ale ja mieszkam w usa i wyskakuje komunikat, 
ze licencja....... ect ,
i nie moge oddtwazac,
jakas pomoc?

**Comment by edgar73** [comment]
Proxy

**Comment by wisiann** [comment]
no tak ,latwo powiedziec,trudniej wykonac,dla swiezaka, jestem na wtyczce sd-xbmc -telewizja polska,
help needed!

**Comment by edgar73** [comment]
Tak jak Ci ramic napisał jego wtyczka ma wbudowane proxy lub możesz sam ustawić używam działa

**Comment by wisiann** [comment]
Jizzz ..ale ze mnie gapa,
dzieki @Ramic,
dzieki @edgar73

**Comment by wisiann** [comment]
niestety musze wrocic,

mowi ze wyszukuje serery proxy ,
potem kreci i kreci ...i na koniec wyskakuje ze ..one or more items failed to play

**Comment by edgar73** [comment]
Pewnie będzie  update a do tego czasu możesz w ustawieniach wpisać polskie proxy

**Comment by wisiann** [comment]
thx

**Comment by wisiann** [comment]
wpisalem polske proxy na telefonie i zadzialalo,
ale wpisalem te same  na android box i nie chce dzialac,
troche.dziwne?

**Comment by edgar73** [comment]
Możesz też przez vpn jak masz

**Comment by edgar73** [comment]
Lub odpal kilka razy dany materiał darmowe proxy czasem działa po kilku próbach

**Comment by wisiann** [comment]
ok,sprubuje,
dzieki

**Comment by wisiann** [comment]
caly czas pokazuje ograniczenia licencyje i sprobuj uzyc serwera proxy w opcjach,
nawet.po wpisaniu pl proxy dalej nie odtwarza ?
help?
