### ISSUE TITLE
Ipla tvn

### ISSUE THREAD

**Issue by edgar73** [ramicspa/kodi#622]
Tylko w was nadzieja że  będą poprawnie działające wtyczki do tych serwisów . Jest chociaż cień szansy ?

**Comment by MDIV666** [comment]
tvn player jest działający od sd-xbmc (wtyczka telewizja polska) a jeśli chodzi o ipla to w innym issue pytałem i raczej najwcześniej się ktoś za to weźmie dopiero jak 18 Leia będzie w jakiejś wersji RC przynajmniej ze względu że mogą być duże zmiany w api i nie ma sensu nad tym wcześniej siedzieć.
