### ISSUE TITLE
Sport

### ISSUE THREAD

**Issue by edgar73** [ramicspa/kodi#624]
A może by tak sporty walki https://www.allthebestfights.com

**Comment by edgar73** [comment]
Widzę że nikogo sport nie interesuje szkoda :(

**Comment by wisiann** [comment]
po pudzianie i popku sporty walki przeszly na inny wymiar

**Comment by edgar73** [comment]
To raczej nie ten poziom . To poważna strona

**Comment by rafciu27** [comment]
weź sobie zainstaluj planet MMA

**Comment by edgar73** [comment]
Na tej stronie jest też boks a to dla mnie najważniejsze ale dzięki sprawdzę
