### ISSUE TITLE
Propozycję stron 

### ISSUE THREAD

**Issue by edgar73** [ramicspa/kodi#626]
https://www.allthebestfights.com
http://dekoder.ws/telewizja-online

**Comment by abrus7** [comment]
Telewizja skopiowana z tele-wizja.js i nie działa

**Comment by xxcriticxx** [comment]
@tomasiek prosimy o review 

http://kinonet.pl/
http://filmdom.pl/

**Comment by zm1c4l** [comment]
Te proponowane strony to jakiś żart. Filmdom wygląda bardziej obiecująco ale ilość źródeł jest bardzo uboga. W mojej opinii nie warto robić do nich wtyczek.

**Comment by nowyczesio** [comment]
a co myślicie o 
https://allbox.tv/
http://filmosy.tv/
https://movieneo.com/

**Comment by edgar73** [comment]
https://www.allthebestfights.com/ wcale nie taka zła strona oczywiście wielbiciele Trybsona będą zawiedzeni

**Comment by edgar73** [comment]
Pewnie było polsky.tv jest gdzieś dzialajaca wtyczka ?

**Comment by tomasiek** [comment]
> https://www.allthebestfights.com
http://dekoder.ws/telewizja-online

Nie moja działka - nie się inni zajmą oceną.

A teraz na szybko bo nie mam czasu:
filmosy.tv już były https://github.com/ramicspa/kodi/issues/483 - nie wiele się zmieniło - praktycznie nic - chyba 1 film więcej znalazło - nie warto.
allbox.tv - krótki test - nie pokazuje jakości źródeł, zmiana źródeł jedynie po zalogowaniu... Ten brak jakości w wynikach kompletnie dyskwalifikuje wg mnie stronę - mam zgadywać czy będę oglądał piksele?
kinonet.pl - tu już ciut lepiej - widoczna jest jakość źródeł (ale większość to 720 px), dużo filmów, ale dostęp tylko do 2 źródełek - logować się nie zamierzam...
movieneo.com - odpowiednik cda - czyli jak dla mnie fajna sprawa - można czasem znaleźć coś niszowego - natomiast cda ma filtrowanie po długości i jakości - i tu już dla mnie odpada - nie lubię 480p... a tu ich skutecznie nie odfiltruję (chyba że się jakoś da o czym nie wiem)

I to tyle. Tych stronek powstaje wiele. Poleciało ostatnio filmy.to. Jak się znajdzie odpowiednik to z chęcią przetestuję - do tego czasu testy będą tylko wytykały wady - jak będzie coś co mnie zainteresuje to pójdzie pełny, jeszcze bardziej rozbudowany test.... ale wtedy strzeżcie się... na razie mam 35 punktów opracowanych...

**Comment by nowyczesio** [comment]
dekoderws bym dodał bo telewizja padła

**Comment by nowyczesio** [comment]
Mam jeszcze prośbę by dodać możliwość logowania do konta na wizjatv

**Comment by nowyczesio** [comment]
Myślałem również czy by nie dodać Goldvod

**Comment by edgar73** [comment]
Do wizji i gold są wtyczki

**Comment by edgar73** [comment]
http://tele-wizja.ru

**Comment by xxcriticxx** [comment]
@edgar73 same krypto koparki na tej stronie
