### ISSUE TITLE
HORIZON GO - ZAMKNĄĆ usunąć 

### ISSUE THREAD

**Issue by plumers** [ramicspa/kodi#629]
Witam , ramic jesteś w stanie zrobić coś takiego jako wtyczka do KODI?? 
Jest  na androida i IOS apk horizonGO (wymaga login hasło jak ktoś ma UPC) ale lepiej by się odpalało z KODI :) pozdro

**Comment by ramicspa** [comment]
a jak ktos nie ma UPC to co wtedy?

**Comment by tomasiek** [comment]
Dostęp wymaga logowania za pomocą danych z serwisu "moje upc". A moje UPC pozwala na:
- najszybsze rozwiązanie problemu, dzięki Asystentowi Pomocy 
- wygodny dostęp do rachunków i płatności
- promocyjne oferty i zarządzanie usługami online

Dawaj hasła, chętnie będę zarządzał online twoimi usługami... będę miał adres, telefon, pewnie też i pesel... 
Także oferta ograniczona do użytkowników UPC.

**Comment by plumers** [comment]
tomsiek -widocznie nie dorosłeś do tego aby uszanować czyjąś prywatną sprawę - mam to co chcę (hasło login) po co mi dane - pewnie jak będziesz miał kiedyś żonę , itp to w tajemnicy nic Tobie nie będzie można powiedzieć , bo będziesz ZARZĄDZAŁ nawet OFLINE hehe ... ale dzięki za chęci już znalazłem alternatywę - powodzenia.

**Comment by tomasiek** [comment]
Nie zrozumiałeś mnie - powiedziałem to ironicznie  - tu chodzi o bezpieczeństwo twoich danych. To że twoja żona będzie znała te dane nie ma najmniejszego znaczenia, bo i pewnie sam jej to wszystko ustawisz... tak jak ja ustawiłem wszystko swojej :)
Ale znajomemu nie podawałbym mimo wszystko takich haseł. Bo ja szanuję swoją prywatność, twoją też, ale nie wiem czy ten nasz "mityczny" znajomy ją uszanuje. A takie dane jak adres/pesel + możliwość zmiany ustawień... to już chyba troszkę za dużo..

**Comment by Tning08** [comment]
Witam, czy mógłbyś Ramic rozważyć stworzenie wtyczki fo Horizon go?robi sie to coraz bardziej popularne, a bez niej nie ma mozliwosci ogladania tych programow na tv

**Comment by ramicspa** [comment]
nie mam upc oraz horizon wiec nie bede robil wtyczki do tego.
