### ISSUE TITLE
Wtyczka segos

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#63]
Są wrzucane też filmy z rapidvideo , na stronie wrzystko jest ok , w kodi filmy z rapidvideo są interpretowane jako cda.pl i już sie nie odtwarzają , możesz tom poprawić , tu masz przykładowy link : 
http://segos.es/filmy/view.php?id=1612

**Comment by ramicspa** [comment]
hej, sprawdzilem i wyglada na to ze "odnosnik" na tej stronie jest zly. mimo ze jest tam kilka linkow zrodlo filmu jest tylko jedno. popraw linki do zrodla a wszytko bedzie dzialac. tu przykladowy link gdzie faktyczne sa 2 zrodla i "odnosnik" jest poprawny: http://segos.es/filmy/view.php?id=2166
