### ISSUE TITLE
vod.tvp

### ISSUE THREAD

**Issue by wisiann** [ramicspa/kodi#638]
Ramic,
nie oddtwarza za granica,nawet po wpisaniu polskiego proxy,
zuc okiem jak bedziesz mial chwile,

dzieki

**Comment by edgar73** [comment]
Znajdź sobie wtyczka TVP od smuto wpisz swoje proxy mam działa jest tylko mniej materiałów niż w tej od ramica

**Comment by edgar73** [comment]
Używam w USA

**Comment by ramicspa** [comment]
@wisiann w opcjach wtyczki aktywuj 'uzyj alternatwnego proxy' - to powinno wystarczyc

**Comment by edgar73** [comment]
Potwierdzam obie możliwości wyszukiwanie proxy i alternatywne nie działają

**Comment by ramicspa** [comment]
a na czym konkretnie nie dziala bo nie widze zadnego problemu

**Comment by wisiann** [comment]
@edgar73,

smuto jeszcze dziala?
mi pokazuje ze repo jedt puste 
jak mozesz podrzucic link do tej wtyczki bede wdzieczny,

thanks

**Comment by edgar73** [comment]
Ja mam działające wtyczki nie zaktualizował 11 miesięcy ale działa

**Comment by edgar73** [comment]
https://github.com/pkontek/xbmc-pl-tv

**Comment by wisiann** [comment]
ten adres jest pusty,
nie pokazuje  .zip files po wpisaniu do kodi?

**Comment by edgar73** [comment]
Bo widzę że trochę Cię przerasta temat https://github.com/pkontek/xbmc-pl-tv/tree/master/repo/plugin.video.pl-tv.vod.tvp.pl TVP vod 1.0.17 na pena i instalujesz

**Comment by wisiann** [comment]
kodi mam na telefonie, 
i jak wpisuje ten adres w file manager i potem chcem otwozyc z .zip file to jest pusto,
co robie zle?

**Comment by wisiann** [comment]
tak samo robie na android box

**Comment by edgar73** [comment]
Otwórz link normalnie w przeglądarce tam masz zip 1.0.17 skopiuj na pendrive do boxa i dajesz zainstaluj z zip wskazujesz plik i oglądasz działa sprawdzałem minutę temu oczywiście proxy działające musisz wpisać

**Comment by wisiann** [comment]
ok,
teraz rozumiem,
dzieki wielkie!!

**Comment by edgar73** [comment]
@ramicspa wyszukiwanie proxy do poprawki jak możesz wyszukuje odpalasz coś i proszę czekać

**Comment by ramicspa** [comment]
proxy dziala dobrze, ale niestety nie kazdy material mozna odworzyc - niektore sa platne a wtyczka o tym nie informuje inne uzywaja streamu ktorego kodi17 nie jest w stanie odgrac. Nie zawsze problemem jest PROXY - dlatego tez wczesniej sie pytalem by podac konkretna pozycje. warto tez sprawdzic czy przez strone dziala a jak nie to dlaczego.

**Comment by ramicspa** [comment]
dziwne bo akurat te nie potrzebuja proxy (przynajmniej w tym momencie)
a czy gra przez strone (bez proxy/vpn?): np: https://vod.tvp.pl/video/blondynka,odc-72,35892432

**Comment by edgar73** [comment]
Przez www bez proxy / vpn nie działa ale ten konkretny co podałeś pod kodi wyszukuje proxy i działa normalnie . Klan , korona królów nie działają (na smuto tak) dziewczyny że Lwowa tylko ostatnie dwa retro działa Teleexpress nie te co sprawdzałem TVP info nie materiały z olimpiady tak . I przy okazji prośba można by poprawić zagadka hotelu grand  pierwsze odcinki bo nigdy nie działały

**Comment by wisiann** [comment]
tak ten dziala,
zaczalem sprawdzac random,
blondynka odc.
58,
59,
60,
61,
i zaden nie odpala ,
troche dziwne,ze na tym samym proxy jedne chodza a drugie nie?

**Comment by wisiann** [comment]
sprawdzilem kilkanascie nastepnych i to samo,
chyba tylko dziala ten co podales #72

**Comment by edgar73** [comment]
@wisiann zrobiłeś sobie te wtyczkę działa ok ?

**Comment by wisiann** [comment]
tak ,

dzieki!

**Comment by wisiann** [comment]
@ramicspa,
znalazles rozwiazanie tego problemu?
