### ISSUE TITLE
Vectra tv

### ISSUE THREAD

**Issue by abrus7** [ramicspa/kodi#639]
Witam,możesz dodać do kodi z logowaniem Vectra tv. Niestety ich aplikacja jest tak słaba,że nie działa na tv box a oni nie wiedzą kiedy to naprawia.. jest do mobilna darmowa telewizja operatora Vectry. Pozdrawiam

**Comment by kopernik1983** [comment]
NIE JEST DARMOWA. Dostajesz ja w prezencie od hojnej vectry za to ze korzystasz z jej uslug. i logujesz sie swoimi danymi klienta. tyle w tym temacie.

**Comment by abrus7** [comment]
Jezeli ramicspa nie będzie widział przeszkód aby dodać,to nie wiem czemu miałby nie dodać tego. Jeżeli będzie miał problemy,to nie zrobi. Od niego tylko zależy i tyle. Ja tylko zapytałem,czy zrobi to jego decyzja będzie.

**Comment by ramicspa** [comment]
nie posiadam vectry wiec nie pomoge tutaj

**Comment by tomasiek** [comment]
Ta darmowość też jest ograniczona do posiadania odpowiedniego pakietu TV u nich - samo posiadanie internetu nie powoduje że masz ten pakiet.

**Comment by kopernik1983** [comment]
była kiedyś wtyczka do tego ale jak i gdzie to ogarnąc i czy to działa wogóle to kto to wie.

**Comment by kopernik1983** [comment]
https://github.com/rafakob/plugin.video.vectra.tvonline sprawdzaj a nóz może.

**Comment by abrus7** [comment]
Kiedyś nie trzeba było się logować a tam nie zaktualizowane jest,teraz zrobili blokadę iż tylko da się na telefonie oglądać a na tv box wywala błąd;/
