### ISSUE TITLE
problem ze skryptem main.py

### ISSUE THREAD

**Issue by richard74** [ramicspa/kodi#64]
witam

po ostatnich zmianach po wprowadzeniu zmian w serwisie livepolishjak i teraz po wprowadzeniu nowej wtyczki filmy.to przy systemie windows xp i xbmc frodo 12.3 przy tych wtyczkach wyskakuje błąd skryptu main.py oraz w pozostałych wtyczkach wczesniej wszystko działało ok skrót błędu filmy.to
plugin.video.filmyto\main.py", line 165, in <module>
                                                addLinkItem("[COLOR blue]Sortowanie:[/COLOR] [B]"+sortN+"[/B]",'',mode='filtr:sort',iconimage='',IsPlayable=False)
                                              File "plugin.video.filmyto\main.py", line 42, in addLinkItem
                                                liz.setArt(art)
                                            AttributeError: 'xbmcgui.ListItem' object has no attribute 'setArt'
                                            -->End of Python script error report<--
12:18:04 T:2684   ERROR: XFILE:

moze coś trzeba zmienić lub cos dograć żeby wtyczki ponownie chodziły na poccziwym windowsie i frodo 12.3

**Comment by ramicspa** [comment]
wtyczki traca wsteczna kompatybilnosc. polecam uaktualnienie kodiego. Na winXP kodi 16 bedzie dzialal rownie dobrze jak 12.

**Comment by gumball1** [comment]
raczej uaktualnienie systemu
na xp powyzej frodo nic nie pojdzie.

**Comment by ramicspa** [comment]
Faktycznie od wersji 13 nie ma wsparcia dla xp. to nowyszy win lub linux pozostaje
