### ISSUE TITLE
Filmbuster

### ISSUE THREAD

**Issue by leffu33** [ramicspa/kodi#640]
Cześć, zainstalowałem kodi 17.6 Krypton(czyste na win 10) Pierwsze co zrobiłem to ustawiłem sobie wszystko by działała apka Yatse następnie dodałem sobie repo, dodałem wtyczkę FilmBuster z myślą że leżąc w łóżku za pomoc fona będę sobie puszczał filmy i seriale. Wszystko śmiga super do momentu gdy znajduje odcinek klikam w niego i wyskakuje info że brak źródeł. Sprawdzałem przez przeglądarkę źródła są. Czy problemem są ustawienia które zmieniałem by Yatse działało czy coś innego np nie włączyłem jakiejś opcji w kodi ?

**Comment by xxcriticxx** [comment]
inne yatse to pilot do kodiego

@leffu33 log please?

**Comment by leffu33** [comment]
[kodi.old.log](https://github.com/ramicspa/kodi/files/1725299/kodi.old.log)

**Comment by leffu33** [comment]
@ramicspa Mógłbyś rzucić okiem na logi i stwierdzić co jest problemem(w sensie nakierowania na rozwiązanie)

**Comment by leffu33** [comment]
Zaktualizowałem URLresolve najpierw do wersji z dodatków Kodi nic, następnie do wersji z repo ramica i też nic. Zegar jeśli chodzi o strefy czasowe i godzinę poprawny. W kodi ustawione by brał zegar systemowy. Jakieś jeszcze pomysły ?

**Comment by xxcriticxx** [comment]
@leffu33 to jest swieza instalacja kodi czy starsza?

**Comment by leffu33** [comment]
Pobrana "świeża" z https://www.dobreprogramy.pl/Kodi,Program,Windows,22117.html. Chyba że błędem jest pobieranie tego z dobrych programów?

**Comment by tomasiek** [comment]
No nie jest to najlepsze źródło - lepiej pobrać z kodi.tv/download
Jakiego masz antywirusa? Może to on blokuje? Kiedyś kaspersky i avast blokowały jakieś certyfikaty.

**Comment by xxcriticxx** [comment]
Zamontuj z Kodi strony i podaj nowy log zobaczymy co nowego piszczy

Ja miałem problem z certyfikatem to os formatowałem nie myśle ze zmiana Kodi pomoże

**Comment by xxcriticxx** [comment]
dobreprogramy to @tomasiek ulubiona strona

**Comment by tomasiek** [comment]
@xxcriticxx eh... ty kąśliwy jesteś... 
Wydaje mi się że lepiej podawać do źródeł niż do pośrednika. Zresztą - za długo w tym obydwoje siedzimy żeby o tym dyskutować. A dobreprogramy to dobra strona - z niej się dowiedziałem o ramicspa....

**Comment by xxcriticxx** [comment]
@tomasiek a myslelem ze sie dowiedziales z kodi w pigulce :+1:

**Comment by leffu33** [comment]
widows defender(nie oceniajcie), próbowałem z leilą(kodi 18)z kodi.tv bo kumplowi poszło na win10, jednak dalej miałem ten problem, pobieram teraz kryptona z kodi.tv zobaczymy moze faktycznie bezpośrednio u źródła zadziała.

**Comment by xxcriticxx** [comment]
@leffu33 problem masz w os musisz na nowo postawic system

**Comment by leffu33** [comment]
dzięki @xxcriticxx, takie pytanie jeszcze odnosnie tego systemu, jeżeli uparłbym się dalej na winde zamiast Ubuntu to jest problem ze klucz do niej mam z odzysku? Komp po-lizingowy kupiłem za 1pln własnie pod kodi itp. Czy licencja "for refurb pc" może to powodować ?

**Comment by xxcriticxx** [comment]
komputer is oem(hp, dell) czy skladak?

sa programy co odzyskaja klucz znajdziesz pelna filmikow na yt

**Comment by leffu33** [comment]
klucz mam na naklejce takze to luz, komp oem dokładnie dell. zreszta chyba itak postawie ubuntu 16.04 tam nie powinny si dziać cuda ;)

**Comment by xxcriticxx** [comment]
@leffu33 jak oem to moze ma partycje recovery

**Comment by tomasiek** [comment]
@leffu33 gdzie ty kupiłeś kompa za 1 zł? Bo szukam właśnie a budżet mam ograniczony (3 zł) ...

**Comment by xxcriticxx** [comment]
@tomasiek nice budzet 3zl

**Comment by tomasiek** [comment]
To 3x więcej niż wydał leffu33... Za dużo wydałem na dostęp VIP do wtyczek ramica i tyle mi zostało 😉

**Comment by xxcriticxx** [comment]
@tomasiek konto VIP kasuje twardy dysk trzy razy szybciej?

**Comment by tomasiek** [comment]
Nie, daje dostęp do nowszych lepszych i szybszych filmów. Nawet tych co jeszcze nie nakręcili
