### ISSUE TITLE
Ramic nie działa na Kodi 17 Android

### ISSUE THREAD

**Issue by Rafix095** [ramicspa/kodi#65]
Byłem zmuszony do reinstalacji kodi na moim android boxie, po wszystkim zainstalowałem repo razmic z fusion.tvaddons.ag ale nie da się zainstalować żadnej wtyczki z tego repo... Wyskakuje komunikat "Instalacja nie udana", okazało się, że na telefonie również występuje ten sam błąd. Na kodi 16 wszystko działa. Wersja Ramic 1.2.2

**Comment by ramicspa** [comment]
repozytorium z http://fusion.tvaddons.ag/xbmc-repos/international/ jest w starej wersji 1.1.0 ... ale to nie problem powinno sie samo zaktualizowac do 1.2.2. Na kodim17 instalowalem i repo chodzi dobrze. Jakbys przez pastebin.com przeslal log - bylby bardzo pomocny by uniknac tego typu problemow na przyszlosc

**Comment by Rafix095** [comment]
Gdzie na androidzie i kodi 17 znajdę ten log?

**Comment by ramicspa** [comment]
[sdcard or internal memmory] /Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
.kodi jest ukrytym folderm ... w file manager na androidzie trzeba ustawic 'show hidden' albo cos podobnego.

**Comment by Rafix095** [comment]
http://pastebin.com/raw/Qs2eTguw

**Comment by ramicspa** [comment]
thx, wyglada jakby kodi nie mogl go rozpakowac. Czy aktywowales 'unknown sources'?

**Comment by Rafix095** [comment]
Tak, z innych repo można instalować wtyczki. Po za boxem próbowałem na 2 telefonach (moto g1 i moto g2) i nie działa. Na komputerze problem nie występuje.

**Comment by ramicspa** [comment]
Sprawdze ten wątek i jakie repo jest w tvaddons. Tymczsem jak pobierzesz
repo z githuba wszystko bedzie działać

**Comment by Rafix095** [comment]
Już wcześniej próbowałem zainstalować repo bezposrednio stąd ale nic to nie dało, zarówno najnowsza wersja jak i starsza nie działa. Nie da się nawet zainstalować samego dodatku livepolishtv. Pastebin.com/iqsf9bsx

**Comment by gumball1** [comment]
Potwierdzam problem z instalacja wtyczek z repo na kodi 17 beta (4/5)
Tak jak napisal Rafix095 wchodza tylko 3 lub 4 wtyczki z repo.
Reczna instalacja z zipa rowniez nie dziala, problem z rozpakowaniem.
Wrzucilem recznie wtyczki do folderu addons i dzialaja.

**Comment by Rafix095** [comment]
W takim razie zrobię tak jak przedmówca. Ciekawi mnie tylko czy automatyczne aktualizację będą działać...

**Comment by ramicspa** [comment]
z wersjami beta jest czesto sporo problemow, pisane wtyczek kompatybilnych z nimi tez nie latwe to wiele fukcji ulega zmianie lub modyfikacji. lepiej pozostac przy 16.x do pojawienia sie wersji release

**Comment by gumball1** [comment]
Ramic zgadza sie.
dzis polecial fix dla kodi 17 -  https://github.com/xbmc/xbmc/pull/10794
bedzie dostepny w wersjach nightly - beta 5
