### ISSUE TITLE
Problem z internetem

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#657]
Witam. Temat może nie na miejscu, bo nie dotyczy żadnej wtyczki lecz to tak naprawdę jedyna społeczność na polskiej scenie kodi która mogłaby mi pomóc w tym problemie. Na moim android boxie gdy tylko włączę KODI tracę połączenie z internetem. Nie chodzi tu tylko o boxa lecz o wszystkie urządzenia. Router po prostu przy włączonym KODI na boxie zaczyna sprawdzać połączenie z internetem przez co jest nieaktywny. Nie mam się gdzie z tym problem zgłosić bo na innych forach nie dostałem od dawna żadnej odpowiedzi. Jeśli uznanie temat za spam to skasujcie. Z góry dzięki za pomoc.

**Comment by tomasiek** [comment]
Miejsce nie to - pytałeś na kodiwpigulce? Coś masz schrzanione w ustawieniach sieci w samym kodi.

**Comment by sky0002** [comment]
Ja Ci proponuję odinstalować to Kodi i zainstalować ze sklepu play lub ze .strony. Nikt tak naprawdę nie wie co Chińczycy wciskają w to oprogramowanie boksów.

**Comment by rafciu27** [comment]
Dzięki już tam się skierowałem. Wiesz może jak skonfigurować ustawienia sieci bo normalnie w systemie nie ma za wiele opcji ustawień, głównie zmiana proxy. 

Box był formatowany po zakupie i wszystko było instalowane że sklepu play.

**Comment by xxcriticxx** [comment]
@rafciu27 internet przez wifi? chinskie boxy gobija mac address czesto

**Comment by rafciu27** [comment]
2 lata z niego korzystam i pierwszy raz takie coś mam. Rozumiem gdyby gubiły adresy, i tylko nie łączyły się z boxem, ale to wpływa na cały router przez co nie mam połączenia w całym domu z żadnym urządzeniem.

**Comment by rafciu27** [comment]
no pech chciał, że router również dosyć nowy :D

**Comment by tomasiek** [comment]
hm... coś mi to przypomina - nie masz czasem jakiegoś mostu wifi? repeatera?
A sprawdź w kodi:
Ustawienia -system - sieć
i porównaj to z androidem i z tym co masz na routerze.

U mnie kiedyś był troszkę podobny problem - 2 routery (A i B), na obu tomato, ustawiony most między nimi, do B podłączone kabelkiem kilka rzeczy. Działało 10 minut, potem rozsypka sieci i blokada routera i internetu... Problemem było przydzielenie IP do urządzeń podpiętych do B - mieszało się wszystko... Co pomogło? Likwidacja trybu bridge, router B wymieniony na zwykłą tendę i zrobiony zwykły AP... 
https://openlinksys.info/forum/viewthread.php?thread_id=20981&pid=160663#post_160663

**Comment by xxcriticxx** [comment]
Nowy sprzęt tesz się psuje a nie powinien 

Napisz więcej o setupie bo narazie to zgadujemy

**Comment by rafciu27** [comment]
Do zamknięcia, problem naprawiony przez konsultanta netii. Powiedział mi tylko, że skomplikowana sprawa była.
