### ISSUE TITLE
opcje do lepszego szukania

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#66]
@ramicspa da rade cos zrobic zeby robilo serach przez wszystkie serwicy we plugin?

**Comment by ramicspa** [comment]
a o jakim pluginie mowisz?

**Comment by xxcriticxx** [comment]
o wszystkich 

jak szukasz cos na przyklad ABC zeby szukalo przez kazdy service co jest wtej wtyczce

**Comment by ramicspa** [comment]
chyba wiem o co ci chodzi ... zeby przeszukiwalo wszystkie(zainstalowane) pluginy. problem w tym ze plugin moze nie obslugiwac opcji szukania, poza tym, komendy do szukania sa rozne dla kazdego pluginu.  nie bardzo widze jakby to zaimplementowac

**Comment by Seico** [comment]
A może pokusisz sie zrobić jedna wtyczkę która by miała w sobie dostęp do wszystkich twoich wtyczek coś na zasadzie specto lub genesis

**Comment by xxcriticxx** [comment]
@ramicspa dokladnie tak jak napisales jak nie obsluguje szukania to przeskoczysz dalej 

@Seico shhh :)
