### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by gosiaiunia1** [ramicspa/kodi#67]
Witam. Czy jest mozliwosc stworzenia wtyczki z logowaniem fo Netlixa. Pozdrawiam

**Comment by xxcriticxx** [comment]
nope

**Comment by ramicspa** [comment]
jest kilka pluginow do netflixa ale wiem jak one dzialaja
np: https://www.tvaddons.ag/kodi-addons/show/script.program.androidnetflix/
Jak sprawdzisz daj znac

**Comment by gosiaiunia1** [comment]
Czesc. To co wyslales juz znalem. To przekierowuje na app na andr. A mi
chodzi o plugin tylko na kodi. Mam decoder sat z xbmc( 13.2) na ktorym nie
moge miec app typu netflix youtube. I dlatego szukam pluginu NETFLIX tylko
na xbmc z logowaniem.sporo filmow i seriali z netflixa jest na exodus i 123
ale lepsza jakos jest na orginalnym netflixie. Pozdrawiam Chris

27 paź 2016 22:23 "ramicspa" <notifications@github.com> napisał(a):
