### ISSUE TITLE
Cześć

### ISSUE THREAD

**Issue by wacekrnyna** [ramicspa/kodi#7]
Masz super wtyczki. Szczególnie LivePolishTV. Dzisiejszy update jest extra. Dobra robota. Mam do Ciebie pytanie. Jak będziesz miał trochę czasu to się odezwij.

**Comment by ramicspa** [comment]
Witam, dzieki, wal smialo z pytaniem

2016-06-01 18:22 GMT+02:00 wacekrnyna <notifications@github.com>:

**Comment by wacekrnyna** [comment]
Widzę że jesteś dobry w tym co robisz. Ja miałbym do Ciebie prośbę. Rok temu do jednej z wtyczek był dołączony serwis Mmtv.pl. Jest dużo ludzi którzy mają wykupiony serwis w multimediach i chciałbym ją reaktywować. Prosiłem autora ale jest chyba tym niezainteresowany. Posiadam jego starą wtyczkę, ale niestety już nie działa. Czy byłbyś wstanie ją odnowić i dołączyć do twojej wtyczki. Oczywiście jeśli nie jesteś zainteresowany o nie ma sprawy.

**Comment by ramicspa** [comment]
Zwykle staram sie robic sracpery to darmowych serwisow by kazdy mogl z nich
korzystac.
Z tego co widzialem mmtv.pl uzywa MS silverlight technologi i prawdopodbnie
potrzeba bedzie wykorzystanie zewnetrznego odtwarzacza zrodel - kodi
(chyba) natywnie nie radzi sobie jeszcze z tym - trzeba by poprobowac.
Jesli zewnetrzy odtwarzacz bedzie potrzebny - problem moze pojawic sie z
kompatybilnoscia pomiedzy platforamimi (android/linux/windows/osx).
Podeslij linka do tej wtyczki - zobacze co da sie zrobic.

W dniu 1 czerwca 2016 18:52 użytkownik wacekrnyna <notifications@github.com>
napisał:

**Comment by wacekrnyna** [comment]
http://przeklej.org/file/x6SbkT/plugin.video.mrknow-1.7.52.zip
Ta wersja jest jeszcze z tym serwisem. Trzeba wyłączyć aktualizację bo po niej tej wtyczki już nie ma.

**Comment by ramicspa** [comment]
ok dzieki, mam ta wtyczke, zobacze zrodelko do tego serwisu. Dam znac za
pare dni.

W dniu 1 czerwca 2016 19:47 użytkownik wacekrnyna <notifications@github.com>
napisał:

**Comment by wacekrnyna** [comment]
Super dzięki

**Comment by wacekrnyna** [comment]
Widzę że się rozkręcasz z tą wtyczką :) SUPER

**Comment by ramicspa** [comment]
Witam, patrzylem na ten serwis i raczej nie mam dobrych wiadomosci. Poza
logowaniem wymaga podatani identifikatora urzadzenia na ktorym ma dzialac -
a mi sie na zadnym nie udalo zainstalowac (ograniczenia regionalne). Ale
skoro serwis oferuje swoje aplikacje na androida/osx, moze lepiej jak
skorzystasz z uslug w ten sposob.
Pozdrawiam

2016-06-02 17:20 GMT+02:00 wacekrnyna <notifications@github.com>:

**Comment by wacekrnyna** [comment]
Cześć.Dzięki za wiadomość. Wiesz ja wiem jak użyć identyfikatora w tej wtyczce. Mam wykupioną telewizję w multimediach, więc mam u nich konto. Ograniczenia regionalne omijam VPNem. Ja chciałbym z tej wtyczki wywalić wszystko tak żeby zostało tylko Mmtv i żeby dała się zainstalować na androidzie i Windowsie. No i oczywiście nie może się aktualizować do aktualnej wtyczki właściciela. Resztę powinienem ogarnąć.

**Comment by ramicspa** [comment]
OK w takim razie zmontuje wtyczke tylko z mmtv ... reszte juz sam bedziesz
musial poprawic jak cos biegac nie bedzie

W dniu 6 czerwca 2016 18:00 użytkownik wacekrnyna <notifications@github.com>
napisał:

**Comment by wacekrnyna** [comment]
Ok super. Mam do Ciebie pytanie, ale nie tutaj . Daj meila.

**Comment by ramicspa** [comment]
wrzucilem na githuba: plugin.video.mmtv.zip
Sciagnij, zainstaluj z zip. Po zalogowaniu wyswietla liste kanalow ...
reszte juz sam bedziesz musial poprawic jak cos nie bedzie biegac.
info znajdziesz w addon.xml


2016-06-06 22:01 GMT+02:00 wacekrnyna <notifications@github.com>:

**Comment by wacekrnyna** [comment]
Ok . Na Win 10 się zainstalowało ,ale jak klikam na ikonę wtyczki wyskakuje błąd. Na Androidzie 5.1 w ogóle się nie chce zainstalować. Nie mam pojęcia o co chodzi. Na czym ty ją instalowałeś, że się mogłeś zalogować i widziałeś kanały tv?

**Comment by ramicspa** [comment]
Mi biega na win10 i kodi 16.1
Zanim uruchomisz wtyczke wejdz w jej ustawienia i wpisz login/haslo.
Na androidzie nie testowalem.
Musisz zobaczyc logfile gdzie jest problem. Moze jakies zaleznosci sa
niespełnione.
On 6 Jun 2016 23:33, "wacekrnyna" <notifications@github.com> wrote:

Ok . Na Win 10 się zainstalowało ,ale jak klikam na ikonę wtyczki wyskakuje
błąd. Na Androidzie 5.1 w ogóle się nie chce zainstalować. Nie mam pojęcia
o co chodzi. Na czym ty ją instalowałeś, że się mogłeś zalogować i
widziałeś kanały tv?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/7#issuecomment-224095235>, or mute
the thread
<https://github.com/notifications/unsubscribe/AL9q4QDYb8ZEeSegqCNUEAqCvgZDH4gNks5qJJITgaJpZM4IrusQ>
.

**Comment by wacekrnyna** [comment]
Nie instaluje się na androidzie. Nie wiesz co może być przyczyną?

**Comment by ramicspa** [comment]
hej, I jak ... dziala ci mmtv?

**Comment by wacekrnyna** [comment]
Nie działa bo wtyczka nie daje się zainstalować na androidzie. Nie mam pojęcia dlaczego :(

**Comment by wacekrnyna** [comment]
Jesteś WIELKI , po update wtyczka działa jak malina. Poza tym ostatni update twojej wtyczki LIVE i dodanie sport365 wymiata wszystkie wtyczki. Jeszcze raz dzięki za pomoc przy wtyczce.

**Comment by ramicspa** [comment]
no problem, enjoy!
