### ISSUE TITLE
Sport 365 i Ekstralasa

### ISSUE THREAD

**Issue by kashkash18** [ramicspa/kodi#70]
Oba serwisy padły na weekend

**Comment by ramicspa** [comment]
sport naprawiony w wersji 2.03 ... a co nie tak z ekstraklasa? nie wiedze tam problemu

**Comment by jakubbrach** [comment]
brak meczu live o 20:45 przynajmniej u mnie

**Comment by rafciu27** [comment]
nie było fakt, ale to chyba wina serwisu dailymotion
