### ISSUE TITLE
Serialosy.pl i filmy.to problem

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#71]
Obydwie wtyczki podpinaja sie pod mrknow url resolver i nie mozna ich uruchomic po aktualizacji mrknow url

**Comment by ramicspa** [comment]
dzieki za info ... blad copy-past. Jak nie masz mrknow resolvera to zaleznosci nie sa spelnione i blad instalcji wtyczki, zrobie update i poprawie to.

**Comment by adaski8** [comment]
Jak wiekszosc uzytkownikow mam i korzystam rowniez z mrknow .  Ok. Czekam na update . Pozdrawiam. Dobra robota

**Comment by ramicspa** [comment]
ok poszedl update. Udalos sie tak zrobic ze jak glowny resolver nic nie znajdzie to uzyje mrknow resolvera jesli jest zainstalowany. nie wplywa to na zaleznosci pluginu

**Comment by adaski8** [comment]
Ok. Dzieki . Pozdro
