### ISSUE TITLE
Zalukaj niespelnione zaleznosci.

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#72]
Widze nowa wtyczke do zalukaj ale przy prubie instalacji wywala blad xbmc.phython 2.25.0 niespelnione zaleznosci.  Kodi 16.1 jarvis. Doinstalowalem pythona 2.25.0 wtyczka sie zainstalowala ale przy probie otwarcia kategori filmow albo listy ostatnio ogladanych wywala blad.

**Comment by ramicspa** [comment]
wtyczka jest kompatybilna tylko z K17

**Comment by adaski8** [comment]
A  sa szanse na  to zeby ruszyla pod K16

**Comment by ramicspa** [comment]
nie, bo wymaga kodi 17
