### ISSUE TITLE
Sport365

### ISSUE THREAD

**Issue by rafciu27** [ramicspa/kodi#73]
Witam. Od 2 tygodni mam problem ze streamami z tej strony. Po 2-3 minutach się wyłączają. Nie ma to raczej związku z prędkością internetu bo sprawdzałem działanie na 10mb jak i 50mb. Na telefonie, komputerze i smart boxie to samo. Dało by się to jakoś naprawić?

**Comment by ramicspa** [comment]
na razie nie mam pomyslu na ten problem

**Comment by ramicspa** [comment]
dobra wiadomosc ... chyba udalo mi sie znalesc rozwiazanie problemu ... testowalem przez kilka minut i nie wywalo streamu - potestuj i daj znac.
wersja pluginu: 2.0.5

**Comment by kashkash18** [comment]
Teraz streme odpalaja się normalnie , ale nadal po niecałych dwóch minutch wywala strema. Sprawdzane teraz

**Comment by ramicspa** [comment]
faktycznie, nie dziala jeszcze jak trzeba - zmylil mnie fakt ze jak odpali sie dowolny stream przez www, (przez pare minut) to przestaje wywalac na kodim. Teraz to jakos trzeba obejsc ....

**Comment by kashkash18** [comment]
W repo ZEM też jest ten sam problem , mam nadzieję że uda Ci się to obejść :)

**Comment by rafciu27** [comment]
Cały czas to samo. Nie znam się zbytnio, ale doszedłem do wniosku, że nie masz chyba na to żadnego wpływu jeśli ZEM również to samo się dzieję. Dzięki za chęci! ;)

**Comment by ramicspa** [comment]
zobacze co ZEM zrobilo ... ale jak tam jest ten sam problem to wiele to nie pomoze.
Zauwazylem ciekawa rzecz, jak otworzy sie przez www jakis stream to potem na kodim streamow nie wywala. Szukam teraz linka ktory to robi - bo ze strony otwiera sie tego mnostwo - moze z jakas reklama ... 
Zobaczcie czy u was tez tak jest: przestanie wywalac steram po otwarciu streamu przez stronke sport365.live

**Comment by kashkash18** [comment]
Faktycznie jest jak mówisz , coś tu jest powiązane z reklamami bo mi przy włączonym uBlocku na kompie wywalilo strema dokładnie po 1,17. Gdy go włączyłem to zobaczyłem milion reklam ale strem udzie i na kompie i na Kodim

**Comment by ramicspa** [comment]
dobrze ze tylko jedno otwarcie przez www jest potrzebne przynajmniej na 12h. taka tymczasowa opcja jak jest jakis fajny event do zobaczenia
Bede dalej sprawdzal ktora to rekalma ma byc otwarta ... by jakos ominac to ograniczenie. jak cos znajde to bedzie info i update.

**Comment by kashkash18** [comment]
Nie wiem czy to nie ta reklama która pojawia się na dole w oknie strema. Ale to tylko moja sugestia . Trzymam kciuki

**Comment by ramicspa** [comment]
poszedl update - powinno teraz chodzic bez wywalania streamow i koniecznosci otwierania strumieni przez na przegladarce

**Comment by kashkash18** [comment]
Teraz działa jak należy :) Bardzo Ci dziękuję mistrzu ;)

**Comment by ramicspa** [comment]
:) przyda sie szczegolnie teraz - kolejna runda kwalifikacji juz jutro

**Comment by kashkash18** [comment]
Dokładne , w zasadzie to przydaje się co weekend :) A nie ma dla niej alternatywy , i przy jej braku działania odczuwam spory ból . Żona znów będzie niepocieszona heheh

**Comment by kashkash18** [comment]
Czy w Sport365 jesteś w stanie przestawic godziny stremow o godzinę wcześniej ?? Strem z 13 już działa a wg godziny ma działać od 14

**Comment by rafciu27** [comment]
Niestety u mnie nie działa. Przy próbie połączenia wywala błąd B na każdej platformie.

**Comment by kashkash18** [comment]
Potwierdzam , po aktualizacji wtyczki coś hej dolega

**Comment by kashkash18** [comment]
Po aktualizacji działa lecz streme nie odpalaja się same. Potrzeba wciśnięcia Play. Czy jesteś w stanie przestawic te godzinę rozpoczęcia stremu o jedną godzinę do tyłu ??

**Comment by rafciu27** [comment]
Wszystko pięknie śmiga! Wielkie dzięki.

**Comment by kashkash18** [comment]
Sport 365 padł
