### ISSUE TITLE
zalukaj

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#74]
nie widze zalukaj mam repo ver 1.2.2 i niema updatetow 

kodi 16.1 na win7 systemie

**Comment by ramicspa** [comment]
i dobrze ze sie nie pokazuje w repozytorium bo wymaga kodi17

**Comment by xxcriticxx** [comment]
rozumiem

**Comment by Cinek77** [comment]
Dziekuje za dodanie serwisu do repo :)

**Comment by ebot2007** [comment]
Witam a nie da rady zrobic na 16.1 , dzieki

**Comment by ramicspa** [comment]
Witam, da rade zrobic na 16.1
problem w tym, ze bedzie wyskakiwal ERROR

**Comment by xxcriticxx** [comment]
ale bendzie dzialac z error czy w ogole nie odpala?

**Comment by ramicspa** [comment]
serio?
bedzie dziala dopoki error nie wywali wtyczki

**Comment by ebot2007** [comment]
hmmm, szkoda . sprawdzilem wtyczki na kodi 17 beta 5 wiekszosc nie chce sie zainstalowac czy bedzie mozna to zrobic w przyszlosci jak bedzie juz finalna wersja 17 , dzieki

**Comment by ramicspa** [comment]
oczywiscie ze bedzie mozna. jak tylko wyjdzie oficjana wersja K17 wszystkie moje wtyczki bede z nia kompatybilne

**Comment by ebot2007** [comment]
sprawdzilem jeszcze raz co dziwne na win dziala wszystko ale na androidze nie bardzo , takie male info :)

**Comment by ramicspa** [comment]
hmm skoro juz tak dokladnie testujesz otworz nowy watek i wylistuj wtyczki z ich problemami - bedzie mi duzo latwiej poprawic te bledy przy kolejnych aktualizacjach

**Comment by ebot2007** [comment]
ok , dzieki

**Comment by ebot2007** [comment]
Witam . Zalukaj dziala lecz po wybraniu filmu pokazuje sie pusta ramka bez mozliwosci wybrania .

**Comment by ramicspa** [comment]
hmm dawno tam nie zagladalem ... zobacze co da sie zrobic.

**Comment by ebot2007** [comment]
:)

**Comment by ramicspa** [comment]
poszedl update ... dodalem logowanie, powinno wszystko smigac
