### ISSUE TITLE
Nieinstalujący się urlresolver.

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#75]
Przy próbie instalacji dodatku segos bądź e-kabarety z repozytorium wyskakuje błąd że nie może zainstalować bo nie udała się instalacja zależnego dodatku "urlresolver". Po instalacji ręcznej (ściągnięcie zip z twojej strony) instaluje się bez problemu. W repozytorium nie widzi w ogóle dodatku urlresolver.

**Comment by ramicspa** [comment]
dzieki za info, sprawdze to

**Comment by tomasiek** [comment]
Hm... spróbowałem na oryginalnym kodi dla mojego tvboxa... i na nim działa... (wcześniej używałem spmc - i tu był problem). Nie wiem czy to wina zaśmieconego spmc czy jego jakiś "właściwości" - ale na normalnym kodi działa już bezbłędnie. 
Ps - świetna robota z tymi dodatkami - dodatek do cda.pl jest chyba najlepszym jaki widziałem (inne serwisy IMO się chowają... na cda zawsze znajduję to co chcę..). Do tego vider, freedisc, LivePolishTV - i więcej nie potrzeba. Inne równie popularne repozytorium ("wiecie" które) wg. mnie się nie umywa...
