### ISSUE TITLE
e-kabarety - część video nie działa

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#76]
e-kabarey - działają tylko filmy które na stronie są osadzone w youtube, nie działają zaś te, które osadzone są w jakimś flashowym koszmarku
http://www.ekabaret.pl/tv-7339.html - działa
http://www.ekabaret.pl/tv-7094.html - nie działa
logi mogę później podać.

**Comment by ramicspa** [comment]
thx za dobre info, sprawdze w czym problem i bedzie update

**Comment by ramicspa** [comment]
podzedl update, zrodelka z tvp powinny byc dostepne

**Comment by tomasiek** [comment]
**Wszystko działa.** Niestety znowu nie chciało się zaktualizować samo, musiałem ręcznie. Możliwe że nie do końca rozumiem mechanizm automatycznej aktualizacji (wiem że przy uruchomieniu kodi powinno się samo zaktualizować, jednakże korzystam z tvboxa którego tylko usypiam, więc aktualizuję przez "dodatek" - dostosuj - aktualizuj... i to nie działa...).

**Comment by ramicspa** [comment]
pluginow nie trzeba aktualizowac recznie, to co trzeba zrobic to albo uruchomic ponownie kodi, albo lepie uaktualnic repozytorium - wtedy wszystkie pluginy sie same uaktualnia.
instrukcja np tutaj: https://www.youtube.com/watch?v=MnAzKAdVGNk
