### ISSUE TITLE
Małe błędy, literówki

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#78]
Zauważyłem kilka małych literówek... niby nic, ale zawsze:
Dodatek tvp.pl:
- _Teleexperss_ zamiast Teleexpress

Dodatek livepolishTV - przy tworzeniu listy programów w popupie:
- _Tworzę listę programóow_ - zamiast Tworzę listę programów

Jeszcze coś mi gdzieś mignęło - jak znajdę dopiszę...

**Comment by ramicspa** [comment]
thx, poprawione
