### ISSUE TITLE
Witam!! Mam mały problem

### ISSUE THREAD

**Issue by ericg625** [ramicspa/kodi#8]
Cześć! Chciałem się dowiedzieć dlaczego nie mogę założyć ADDON w KODI "RAMIC" mówi mi ze jest nie aktywny.. Działa na laptopie ale chce założyć na Apple TV! Dziękuje!!

**Comment by ericg625** [comment]
*probuje addon z tvfusion

**Comment by ramicspa** [comment]
Witam, dzieki za info. tvaddons.ag albo superrepo maja nieaktualne
repozytorium wiec z tamtad nic nie da sie zainstalowac. Sciagnij wlasciwe
repo dla kodi z githuba:
https://github.com/ramicspa/kodi/raw/master/repository.ramic.zip
Daj znac czy dziala na AppleTV - nigdy tam nie testowalem

2016-06-05 5:04 GMT+02:00 ericg625 <notifications@github.com>:

**Comment by ericg625** [comment]
Nie mogłem założyć na Apple TV ale wszystko działa na iPad i iPhone. Przepraszam za długą odpowiedz!
