### ISSUE TITLE
Bajki dla dzieci.

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#80]
Czy jest możliwość zrobienia wtyczki do http://bajkionline.com/ bądź/i http://bajkipopolsku.com/
"Wiem" że istnieją w innym repozytorium - ale tamto jest dla mnie jakoś mocno ociężałe i nieczytelne. Poza tym - ładuje kupę serwisów które mnie nie interesują - jakoś wolę Twoje rozwiązanie - konkretny serwis = konkretna wtyczka.

**Comment by ramicspa** [comment]
z bajek cos moze wyjsc ... lubie Lucky Luke

**Comment by xxcriticxx** [comment]
sąsiedzi pat i mat :+1:

**Comment by tomasiek** [comment]
Moje dzieci akceptują nawet 480p - byle by było to co chcą...

12.11.2016 1:11 AM "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by xxcriticxx** [comment]
http://www.kreskowkazone.pl/

http://www.kreskowki.tv/
