### ISSUE TITLE
alltube i cda-online brak widocznych streamów filmów

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#81]
Tak jak w tytule , brak widocznych streamów filmów na tych dwóch pluginach

**Comment by ramicspa** [comment]
thx sprawdze co tam sie dzieje

**Comment by tomasiek** [comment]
Na alltube przed chwilą miałem to samo - pomogło wyłączenie i włączenie wtyczki.

**Comment by ramicspa** [comment]
mi alltube dziala ... czasem pomaga otwarcie strony 
cda-online jest ma chwilowo problemy techniczne ... ciekawe jakie nowe zabezpieczenia wkladaja na strone

**Comment by ramicspa** [comment]
powinno wszystko dzialac jak trzeba, zamykam temat
