### ISSUE TITLE
cda.pl - tylko jedna strona przy wyszukiwaniu

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#82]
Przy wyszukiwaniu (czy to za pomocą predefiniowanych katalogów) czy też ręcznie dostępna jest tylko jedna strona - wybranie "następna" nie pokazuje listy plików. W logach:
21:43:56 T:140084684510976  NOTICE:  xbmc.log cdaSearch
21:43:56 T:140084684510976  NOTICE:  N_items 0

**Comment by ramicspa** [comment]
thx, naprawione
