### ISSUE TITLE
Rapidvideo.com - jakość wideo

### ISSUE THREAD

**Issue by Seico** [ramicspa/kodi#83]
Ponawiam prośbę jeżeli to będzie mozliwe aby dodać w kodi przy wyborze filmu wybór jakości wideo , mimo że w ustawieniach na stronie rapidvideo.com mam zaznaczone aby nie konwertował wrzucanych filmów to dosć często jednak to robi i jak oglądam w przeglądarce to mogę zaznaczyć jakość HD , ale w kodi już odtwarza tylko film w jakości SD , mimo że są dwie do wyboru .
Bardzo proszę :)
Link z dwiema jakościami wideo : https://www.rapidvideo.com/?v=H2bfLedo

**Comment by ramicspa** [comment]
podaj przykladowego co ma kilka jakosci

**Comment by Seico** [comment]
No podałem

**Comment by ramicspa** [comment]
gdzie?

**Comment by Seico** [comment]
https://www.rapidvideo.com/?v=H2bfLedo

**Comment by ramicspa** [comment]
ok :)

**Comment by ramicspa** [comment]
a jaki film we wtycze moge otowrzyc bo w segos bonda nie moge znalesc?

**Comment by Seico** [comment]
na alltube film np. "Za horyzontem" - źródło rapidvideo

**Comment by ramicspa** [comment]
trzeba to poprawic w urlresolver bo tak zmina bedzie tylko widoczna w alltube.tv.
polecam otworzyc issiue w https://github.com/tknorris/script.module.urlresolver

**Comment by Seico** [comment]
A możesz to zrobić aby było widoczne na alltube i segos , bo ja tylko tam wrzucam filmy, ja za bardzo nie kumam co zmienić aby było widoczne wszędzie

**Comment by xxcriticxx** [comment]
script.module.urlresolver juz zostal poprawiony

**Comment by Seico** [comment]
**"xxcriticxx"** to nie script.module.urlresolver został poprawiony tylko **"ramicspa"** dodał funkcje wyboru jakości na alltube i segos , z góry bardzo dziękuje :) , dla sprawdzenia wejdz na alltube we wtyczce mrknow i zobaczysz różnicę

**Comment by ramicspa** [comment]
Faktycznie w segosie bylo cos nie tak z rapidvideo ... juz naprawione: wersja 1.7
