### ISSUE TITLE
Problem z LivePolishTV

### ISSUE THREAD

**Issue by krriss** [ramicspa/kodi#84]
Witam! Od 3 dni nie mogę otworzyć żadnego streamu.klikamt w addon: LivePolishTV, poczym wyświetla sie lista: 
LiveTV: tv-online,
LiveTV: Telewizjada
LiveTV: TVP stream
Itd...
Klikam na każdy z nich i otrzymuje tylko komunikat: "LivePolishTV error, check the log for more information
Co sie stało?
Dodam ze kodi mam na amazon fire sticku

Dzięki i pozdrawiam

**Comment by ramicspa** [comment]
hmm ... sugerowalbym zastosowanie sie do komunikatu jaki sie pojawia i zdobyciu wiecej informacji z loga w czym jest problem

**Comment by krriss** [comment]
Właśnie nie wiem gdzie jest "log" :( nie chce wyglądać na kogoś kto nie ma pojęcia o kodi. Ale po prostu kupiłem juz urządzenie z wgranym kodi. 
A tak na marginesie chciałbym podziękować za udostępnianie polskiej telewizji. Naprawdę super robota.

**Comment by ramicspa** [comment]
http://kodi.wiki/view/Log_file/Advanced 
tu sie dowiesz gdzie szukac loga w zaleznosci od systemu jaki masz

**Comment by krriss** [comment]
Dzięki zrobione! Super!
Jeszcźe raz chciałbym podziękować za ta ogromna robotę jaka w to wkładasz! 
Ratujesz życie rodakom na emigracji :)

**Comment by ramicspa** [comment]
:) to w czym byl problem, tak z ciekawosci?

**Comment by krriss** [comment]
Wszedłem w "tego" log'a i Pokazało mi ze mam "update" do zrobienia, mimo iż miałem cały czas włączony "autoupdate" i to właśnie po jeden z aktualizacji sie wszystko zawiesiło. Wiec ręcznie go z aktualizowanem. I zaczęło znów działać. 
A właśnie odnośnie aktualizacji. Po jednej około tygodnia za każdym razem kiedy chciałem otworzyć LivePolishTV aplikacja sie wyzwalała i musiałem ja na nowo instalować zeby moc ja otworzyć. I tak codziennie po włączeniu kodi. Co nie było jakoś bardzo nie wygodne bo ściągnięcie i zainstalowanie aplikacji trwa mniej niż minutę ale jednak codziennie raz musiałem to robić. 
Zobaczymy jak teraz to wszystko będzie wyglądać :)
Nawet myślałem zeby wyłączyć autoupdate tylko nie wiem czy to zalecane?

**Comment by ramicspa** [comment]
aktualizacje sa bardzo wazne - jak masz caly czas wlaczonego kodi to trzeba czasem recznie wymusic odsiwerzenie repozytoriow w poszukiwaniu aktualizacji - domyslnie kodi to powinien robic raz na 24h.
