### ISSUE TITLE
Kinoiseriale kodi17

### ISSUE THREAD

**Issue by adaski8** [ramicspa/kodi#85]
W kodi 17 po otwarciu wtyczki lista pusta brak kategorii

**Comment by ramicspa** [comment]
nie wszystkie pluginy sa zgodne z K17 ... przy ich kolenych aktualizacjach to powinno sie poprawic

**Comment by adaski8** [comment]
Ok. Dzieki

**Comment by adaski8** [comment]
Aktualizacja poszla ale na k17 dalej brak listy filmow.
