### ISSUE TITLE
nowe serwisy 

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#86]
prosze potestowac i wyrazic wlasna opinie 

`www.zobacz.online`

`http://ogladajto.pl/`

`http://von.tv/home?lang=pl`

`www.tvseriesonline.pl`

`http://www.serialeonline.pl/`

**Comment by ramicspa** [comment]
:) nowe serwisy, fajnie, a czy ktos to oglada?
ktos chcial anime ... dodalem ... pozniej zmienili stronke i przez 2 tygodnie nic nie dzialalo i nawet nikt nie zauwazyl.
Moze teraz przy nowych serwisach jakas motywacja by sie przydala typu: duzo fimow HD, jest cos czego nigdzie inndziej nie mozna znalesc ...

**Comment by xxcriticxx** [comment]
moze jakies glosowanie zrobimy?

**Comment by xxcriticxx** [comment]
kazdy niema internetu na HD

**Comment by tomasiek** [comment]
Z tego co zauważyłem to te serwisy które podałeś nie mają nic nowego od tych które już są. Co więcej - część z nich nie działa - ogladaj.to, zobacz.online, część z nich to kopie samych siebie. Głosowanie IMO nie ma sensu. Lepiej chyba żeby ramicspa rozwijał te wtyczki z których korzystają użytkownicy, niż tracił swoją energię na serwisy które pojawiają się i znikają a nic nowego nie wnoszą. ps. na żadnym z tych serwisów nie znalazłem b. rzadkiego filmu Przygody Picassa - który jest na zalukaj.com i np na **http://www.ekinko.pl/** - i tą stronę proponuję - nie ma może i hd ale kilka "dziwnych filmów" jest na niej - może będzie łatwiej niż z zalukaj.com (bo baza filmów dość podobna)

**Comment by Cinek77** [comment]
Ja poprosilbym o dodanie do repo pluginu ze stronki http://www.kinoman.tv/
Jak rowniez wersja mobilna https://m.kinoman.tv/
Korzystam i jestem zadowolony
Pozdrawiam

**Comment by ebot2007** [comment]
http://cyberms.pl/
moze cos z tego wyjdzie 
pozdrawiam

**Comment by xxcriticxx** [comment]
http://dekoder.ml/?p=channels

**Comment by xxcriticxx** [comment]
lista jest od @xgrzegorz1990x thank you!



Filmy Online:
http://www.kinoman.tv/
http://alltube.tv/
http://ekino-tv.pl/
http://www.efilmy.tv/
http://filiser.pl/
http://kinostar.tv/
http://zalukaj.com/
http://nasze-kino.online/
http://stop-limitom.pl
http://zobaczmyto.tv/
http://obczaj.tv/
http://zalukaj-online.com/
http://zalukaj-filmy-cda.pl/
http://kinoman-online.pl/
http://tvon.pl/
http://filmy.to/
http://kinuj.pl/
http://www.seansuj.pl/
http://lobu.pl/
http://www.cda.pl/
http://www.ekinko.pl/
http://kino123.pl/
http://cda-hd.pl/
http://seansik.eu/
http://wkinie.tv/
http://filmik.tv/

TV Online:
https://darmowetv.pl/tv.php
http://dekoder.ml/?p=channels
http://tele-wizja.com/
http://iklub.net/
http://liga-tv.net/
http://youall.tv/
http://sitemtv.cloudaccess.host/sitemtv3.html

**Comment by Cinek77** [comment]
xxcriticxx wiekszosc z tych stron byla juz tutaj przedstawiana. Z wielu sa zrobione pluginy w repo Ramica :)

**Comment by Cinek77** [comment]
Test

**Comment by tomasiek** [comment]
http://kinoman-online.pl/ http://lobu.pl/ http://sitemtv.cloudaccess.host/sitemtv3.html - nie działają - może warto sprawdzić zanim poprosisz o kolejne? Poza tym, ramicspa prosił żeby motywować swoje prośby...

**Comment by xxcriticxx** [comment]
@tomasiek ramicspa niech doda co chce jak nie doda tez bendzie super  :)

**Comment by ebot2007** [comment]
Witam
znalazlem taka stronke , kanaly dzialaja moze cos da sie z tego wyjac , pozdrawiam
