### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by gzenio22** [ramicspa/kodi#88]
Witam

Jak można by było się z panem prywatnie z kontaktować? miał bym do pana sprawę :)

**Comment by xxcriticxx** [comment]
ramicspa jest pania i mieszka w malym bialym domku

**Comment by ramicspa** [comment]
... tak porcelanowy bialy domek.
@gzenio22 pisz na maila ramicspa at gmail dot com

**Comment by gzenio22** [comment]
Z tego co rozmawiałem z kolegą już się z tobą z kontaktował dziękuję za odpowiedź i za prace jaką w to wszystko wkładasz Pozdrawiam :)
