### ISSUE TITLE
Komunikat z niemal kazdej wtyczki

### ISSUE THREAD

**Issue by gzenio22** [ramicspa/kodi#89]
Taki komunikat pojawia się po aktualizacji wtyczek o co chodzi?
![screenshot 2016-11-11 10-48-37](https://cloud.githubusercontent.com/assets/21177361/20210999/a2fbf2f0-a7fc-11e6-94ea-d8c091832935.jpg)

U mnie po wejściu w LivePolishTV

**Comment by Seico** [comment]
Po aktualizacji w "segos" nieodtwarza filmów z rapidvideo.com , na stronie segos jest ok - wywala błąd wtyczki , z innych hostów jest ok

**Comment by Cinek77** [comment]
U mnie pojawia sie taki sam komunikat.
http://screenshot.sh/m7SsSmbc9FQCD
