### ISSUE TITLE
organizacja wtyczki

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#9]
da sie zrobic zeby bylo jeden plugin i serwicy byly jako sub kategorie?

**Comment by ramicspa** [comment]
nie planowalem takiego rozwiazania ale zobacze co da sie zrobic

**Comment by xxcriticxx** [comment]
jak masz kilka plugins zamontowanych to twoje wyskakuja alfabetycznie zamiast razem. tak by hyba bylo prosciej. to jest tylko pomysl

**Comment by ramicspa** [comment]
Dodałem wtyczne o nazwie 'folder' do której można wrzucić wybrane plugginy. W ten sposób mozna pogrupować addonsy tak jak sie chce. Najlepiej bedzie działac jak sie utworzy skrót na glównym ekranie. Daj znać czy to rozwiązanie pomaga.

**Comment by xxcriticxx** [comment]
przetestuje dam znac

**Comment by xxcriticxx** [comment]
cos nie moge znales tych ustawien folder w plugin setting.

**Comment by ramicspa** [comment]
otworz plugin folder -> wejdz do 'Dodaj Plugins' -> wylistuje wszystkie pluginy video. klikajac na jeden z listy zostanie on dodany do skrotow. Po wyjsciu katalog wyrzej tylko dodane beda widoczne.
'Dodaj Plugins' mozna schowac w opcjach a dodane pluginy usunac z listy przez context menu

**Comment by xxcriticxx** [comment]
nie zabardzo rozumiem mam byc w addons pod vid czy w addons pod system potem settings

**Comment by xxcriticxx** [comment]
chodzi mi zeby bylo ramica plugin a jak tam wejde wszystkie serwisy co wtyczka posiada

**Comment by ramicspa** [comment]
wiem o co ci chodzi ale moje wytczki dzialaja niezaleznie dlatego zrobilem 'folder' by mozne te i inne wtyczki tam pogrupowac.
Dzialanie jest bardzo proste: po instalacji odpasz wtyczke jak kazda inna typu video: http://pasteboard.co/8EV9AEkl6.png
wchodzisz do 'Dodaj Plugins': i pojawia sie lista zainstalowaych video dodatkow. Klikajac na nie dodajesz je do listy - tyle ile chesz i jakie chcesz.
jak wyjdziesz z 'Dodaj Plugins': dodane sa dostepne i moze je uruchomic http://pasteboard.co/8F0uLqH2m.png

Pluginy z listy mozna usuwac, oraz schowac 'Dodaj Plugins' z opcji lub context menu

Wtyczke najlepiej dodac sobie do skrotow przy video: http://pasteboard.co/8F4gXpcyJ.png

**Comment by xxcriticxx** [comment]
ale wszystkie wtyczki sa twoje i uzytkownik sobie wybiera co instaluje jedna albo wszystkie. teraz sa alfabetycznie i musze ich szukac

![capture](https://cloud.githubusercontent.com/assets/15007183/17651815/fa89fa6e-623b-11e6-8b74-873d453e2544.PNG)
