### ISSUE TITLE
kinoiseriale - błąd przy wyborze wersji językowej 

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi#93]
W dodatki kinoiseriale po wybraniu opcji wersja językowa pokazuje opcję wyboru jakości filmu sd hd 3d a nie wersje językowe.

ps. po kolei sprawdzam wtyczki które mnie interesują... więc pewnie będzie jeszcze więcej zgłoszeń...

**Comment by ramicspa** [comment]
faktycznie, naprawione.
jak znajdziesz wicej bugow to pisz
