### ISSUE TITLE
serialosy.pl plugin 

### ISSUE THREAD

**Issue by xxcriticxx** [ramicspa/kodi#95]
sortowanie alfabetyczne zaczyna sie od litery Z

**Comment by ramicspa** [comment]
ale jest alfabetycznie, prawda?

**Comment by xxcriticxx** [comment]
A B C... by sie przydalo szukanie czegos po litera D zajmuje z 2 godz

**Comment by tomasiek** [comment]
No ale te na T czy na W są bliżej...
