### ISSUE TITLE
błąd pluginu efilmy

### ISSUE THREAD

**Issue by noyva85** [ramicspa/kodi#98]
od kilku dni plugin efilmy w kodi nieaktualizuje bazy danych.
czyli na stronie efilmy jest dany odcinek np LONGMIRE S05E9 i 10
ale po włączeniu kodi i pluginu pokazuje tylko od 1 do 7 odcinka. jakby od jakiegoś czasu nieaktualizawał bazy danych ze strony. tak samo niedziała, nieaktualizuje się ostatnio dodane filmy i seriale.
następna sprawa. wyszukiwarka filmów i seriali niedziała w tym pluginie efilmy.
i prosba o to by lista filmów i seriali była pod alfabetem.
np A - wszysstkie filmy zaczynające się na A
B - itd. 
ułatwiło by to wyszukiwanie.

**Comment by ramicspa** [comment]
problemy z efilmy wtyczka powinny byc juz rozwiazane.
co do grupowania alfabetycznego to wtyczka moze zrobic tylko to co jest dostepne na stronie a ten serwis nie umozliwia grupowania filmow/seriali po literach alfabetu.
