### ISSUE TITLE
streaming TV

### ISSUE THREAD

**Issue by noyva85** [ramicspa/kodi#99]
wiem ze teraz jest nagonka na blokowanie strinimgów telewizji. bo chcą sprzedawać swoje strimingi (ERA, ORANGE, itp.)
da się coś z tym zrobić?
wiem ze teleizjada.net przeszła na abonament. i szkoda. 30 zł to duzo. za podstawową kablówkę jest 10zł.

**Comment by noyva85** [comment]
p.s.
mógłby ktoś wstawić działającą wtyczkę z ipla TV?

**Comment by rafciu27** [comment]
Masz wtyczke LivePolish TV a ipla jest w telewizji polskiej.

**Comment by noyva85** [comment]
na mr kno tv jest ipla ale niedziała. niechce się włączyć. mam Linuxa. moze działa na MS :/ niewiem
a na LivePolishTV niema iplatv. przeszukiwałem wiele wtyczek. i na kazdej u mnie iplatv niedziała . mniejsza z tą ipląTV ( i tak tam nic niema ciekawego :P ). bardziej mi zalerzy na DOMO+ ( dla mojej mamy :D )

**Comment by ramicspa** [comment]
ipla wymaga platnego konta - ja natomiast staram sie wykorzystywac tylko darmowe zrodla. Jak znajdziesz na takim kanal to cie interesuje np domo+ to daj linka bedzie mozna dorzucic do wtyczki
